In [39]:
import pandas as pd
from thefuzz import process
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# For imputation
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, clone
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from typing import Dict

from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

In [40]:
train_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/train.csv")

In [41]:
train_df.set_index("carID")

,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,,
69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,NaN,11.417268,2.0,63.0,4.000000,0.0
53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,145.0,47.900000,1.5,50.0,1.000000,0.0
6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,145.0,40.900000,1.5,56.0,4.000000,0.0
29021,Ford,FIESTA,2018.0,12500,anual,9102.0,Petrol,145.0,65.700000,1.0,50.0,-2.340306,0.0
10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,145.0,42.800000,1.5,97.0,3.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37194,Mercedes,C Class,2015.0,13498,Manual,14480.0,etrol,125.0,53.300000,2.0,78.0,0.000000,0.0
6265,Audi,Q3,2013.0,12495,Semi-Auto,52134.0,Diesel,200.0,47.900000,2.0,38.0,2.000000,0.0
54886,Toyota,Aygo,2017.0,8399,Automatic,11304.0,Petrol,145.0,67.000000,1.0,57.0,3.000000,0.0
860,Audi,Q3,2015.0,12990,Manual,69072.0,iesel,125.0,60.100000,2.0,74.0,2.000000,0.0
15795,Ford,Fiesta,2018.0,10495,Manual,16709.0,Petro,145.0,64.200000,1.1,38.0,1.000000,0.0

# Data cleaning

In [42]:
# String cleaning and Small numbers changes

def simple_processing(df):
    """
    Apply string cleaning, brand/model corrections, and fuzzy matching.
    These operations don"t require fitting on training data.
    """

    df = df.copy()
    # ============================================================================
    # SECTION 1: REFERENCE DATA SETUP
    # ============================================================================
    
    # Reference list of correct model names
    models = ["golf", "veloste", "caddy", "yaris", "q2", "fiesta", "2 series", "3 series", "a3", "octavia", 
              "passat", "focus", "insignia", "a class", "q3", "fabia", "ka+", "glc class", "i30", "c class", 
              "polo", "e class", "q5", "up", "c-hr", "mokka x", "corsa", "astra", "tt", "5 series", "aygo", 
              "4 series", "slk", "viva", "t-roc", "ecosport", "tucson", "x-class", "cl class", "ix20", "i20", 
              "rapid", "a1", "auris", "sharan", "adam", "x3", "a8", "gls class", "b-max", "a4", "kona", "i10", 
              "mokka", "s-max", "x2", "crossland x", "tiguan", "a5", "gle class", "zafira", "ioniq", "a6", 
              "mondeo", "yeti outdoor", "x1", "scala", "s class", "1 series", "kamiq", "kuga", "tourneo connect", 
              "q7", "gla class", "arteon", "sl class", "santa fe", "grandland x", "i800", "rav4", "touran", 
              "citigo", "roomster", "prius", "corolla", "b class", "kodiaq", "v class", "caddy maxi life", 
              "superb", "getz", "combo life", "beetle", "galaxy", "m3", "gtc", "x4", "ka", "ix35", 
              "grand tourneo connect", "m4", "tourneo custom", "z4", "x5", "meriva", "rs6", "verso", "touareg", 
              "shuttle", "cls class", "c-max", "puma", "cla class", "i40", "tiguan allspace", "6 series", 
              "caravelle", "karoq", "i3", "grand c-max", "t-cross", "a7", "golf sv", "agila", "gt86", "yeti", 
              "california", "land cruiser", "edge", "x6", "caddy life", "8 series", "fusion", "gl class", 
              "scirocco", "z3", "proace verso", "hilux", "amarok", "cc", "7 series", "avensis", "eos", "m class", 
              "grandland", "zafira tourer", "rs5", "r8", "mustang", "antara", "q8", "camry", "clk", "rs3", 
              "jetta", "kadjar", "sq5", "rs4", "supra", "i8", "x7", "sq7", "g class", "s3", "crossland", 
              "tigra", "escort", "glb class", "vivaro", "verso-s", "m5", "s4", "iq", "a2", "caddy maxi", 
              "streetka", "cascada", "accent", "s8", "rs", "golf s", "ranger", "vectra", "ampera", "fox", 
              "urban cruiser", "m2", "clc class", "m6", "s5", "terracan", "200", "220", "230", "NaN"]
    
    # Get unique short model names (2 characters) for separate handling
    short_models = [models[i] for i in range(len(models)) if len(models[i]) == 2]
    short_models = list(set(short_models))
    
    transmission_types = ["semi-auto", "manual", "automatic", "unkown", "NaN", "other"]
    fuel_types = ["petrol", "diesel", "hybrid", "electric", "other", "NaN"]
    
    # Brand name corrections mapping
    brand_mapping = {
        "vw": "vw",
        "v": "vw",
        "w": "vw",
        
        "toyota": "toyota",
        "toyot": "toyota",
        "oyota": "toyota",
        
        "audi": "audi",
        "aud": "audi",
        "udi": "audi",
        "ud": "audi",
        
        "ford": "ford",
        "for": "ford",
        "ord": "ford",
        "or": "ford",
        
        "bmw": "bmw",
        "bm": "bmw",
        "mw": "bmw",
        
        "skoda": "skoda",
        "skod": "skoda",
        "koda": "skoda",
        "kod": "skoda",
        
        "opel": "opel",
        "ope": "opel",
        "pel": "opel",
        "pe": "opel",
        
        "mercedes": "mercedes",
        "mercede": "mercedes",
        "ercedes": "mercedes",
        "ercede": "mercedes",
        
        "hyundai": "hyundai",
        "hyunda": "hyundai",
        "yundai": "hyundai",
        "yunda": "hyundai"
    }
    
    # ============================================================================
    # SECTION 2: INITIAL CLEANING (NO FITTING REQUIRED) -> no risk of data leakage
    # ============================================================================
        
    # Convert brand names to lowercase and removes all beginning and trailing whitespace (e.g. space) from the column
    df["Brand"] = df["Brand"].str.lower().str.strip()
    df["model"] = df["model"].str.lower().str.strip()
    df["transmission"] = df["transmission"].str.lower().str.strip()
    df["fuelType"] = df["fuelType"].str.lower().str.strip()
    
    # Replace NaN with string NaN to avoid errors in the fuzzy algorithm (cant match NaNs)
    df[["model", "transmission", "fuelType"]] = df[["model", "transmission", "fuelType"]].fillna("NaN")
    
    # 1.1 Fixing brands
    df["Brand"] = df["Brand"].map(brand_mapping)
    
    # 1.2 Fixing models
    # Similarity matching for Models, Transmission and fuel columns (Fuzzy Match)
    # Source for process.extractOne (fuzzy): https://github.com/seatgeek/thefuzz
    
    # VECTORIZED APPROACH: Only perform fuzzy matching once per unique value instead of per row
    
    # Models - handle different lengths separately
    unique_models = df["model"].unique()
    model_lookup = {}
    for val in unique_models:
        if pd.isna(val) or val == "NaN":
            model_lookup[val] = "NaN"
        elif len(val) > 2:  # Only perform fuzzy matching for models that have a name longer than 2 letters -> fuzzy will become fuzzy (unreliable) if names are to short
            model_lookup[val] = process.extractOne(val, models)[0]  # [0] because we get the name and score as a return -> score used for debugging
        elif len(val) == 2:  # Use the short names list for comparisons if the model names are 2 letters
            model_lookup[val] = process.extractOne(val, short_models)[0]
        else:  # We can define models with only one letter
            model_lookup[val] = "NaN"
    df["model"] = df["model"].map(model_lookup)
    
    # Transmission
    unique_trans = df["transmission"].unique()
    trans_lookup = {val: process.extractOne(val, transmission_types)[0] for val in unique_trans}
    df["transmission"] = df["transmission"].map(trans_lookup)
    
    # FuelType
    unique_fuel = df["fuelType"].unique()
    fuel_lookup = {val: process.extractOne(val, fuel_types)[0] for val in unique_fuel}
    df["fuelType"] = df["fuelType"].map(fuel_lookup)
    
    # Convert the str NaN values back to pd.NA for easier further processing and readability
    df["model"] = df["model"].replace("NaN", pd.NA)
    df["transmission"] = df["transmission"].replace(["unkown", "NaN", "other"], pd.NA)
    df["fuelType"] = df["fuelType"].replace(["other", "NaN"], pd.NA)
    
    # Get the most frequent brand for each model -> returns df with model and brand
    brand_models = df.groupby("model")["Brand"].agg(lambda x: x.mode()[0] if len(x.mode()) > 0 else pd.NA)
    df = pd.merge(df, brand_models, on="model", how="left", suffixes=("", "_mode"))  # add the model and brand df to our main df (onyl add the brand columns, join on model)
    
    df["Brand"] = df["Brand"].fillna(df["Brand_mode"])  # rename new column
    df.drop("Brand_mode", axis=1, inplace=True)  # remove the old brand column
    
    ################################################################################
    # Simple Number Cleaning
    ################################################################################

    # Cleaning numeric columns
    df["year"] = df["year"].round(0)
    
    # Create the new column
    df["stated_no_damage"] = ~df["hasDamage"].astype(bool)
    df = df.drop(["hasDamage"], axis=1)

    # Round year to integer (no fractional years)
    df["year"] = df["year"].round()
    
    # Mileage: take absolute value and round
    # Some imputation might produce small negative values
    df["mileage"] = abs(df["mileage"].round())
    
    # Tax: take absolute value and round
    df["tax"] = abs(df["tax"].round())
    
    # MPG: round to 1 decimal place 
    df["mpg"] = abs(df["mpg"].round(1))
    
    # Engine size: round to 1 decimal place
    df["engineSize"] = abs(df["engineSize"].round(1))
    
    # Paint quality correction (domain-specific business logic)
    # Assumption based on data exploration:
    # - Values < 4 likely had decimal point in wrong place (e.g., 3.5 -> 35%)
    # - Values > 100 likely have erroneous leading 1 (e.g., 185 -> 85%)
    def fix_paint_quality(x):
        if x < 4:
            return x * 10
        elif x > 100:
            return x - 100
        else:
            return x
    
    df["paintQuality%"] = df["paintQuality%"].apply(fix_paint_quality).round()
    
    # Previous owners: take absolute value and round to integer
    df["previousOwners"] = abs(df["previousOwners"].round())
    
    return df

In [43]:
# Categorical featue Encoding
def fit_transform_encoding(df):
    """
    Fit label encoders for categorical columns on training data.
    """
    
    encoders = {
        "Brand": LabelEncoder(),
        "model": LabelEncoder(),
        "transmission": LabelEncoder(),
        "fuelType": LabelEncoder()
    }
    
    # Fit each encoder on the corresponding column
    """encoders["brand"].fit(df["Brand"])
    encoders["model"].fit(df["model"])
    encoders["transmission"].fit(df["transmission"])
    encoders["fuelType"].fit(df["fuelType"])"""

    columns = ["Brand", "model", "transmission", "fuelType"]

    # Code adapted from: https://stackoverflow.com/questions/36808434/label-encoder-encoding-missing-values

    for column in columns:
        # Get non-null string values
        mask = df[column].notna() & (df[column].apply(type) == str)
        
        # Fit encoder on unique non-null values
        fit_by = df.loc[mask, column].unique()
        encoders[column].fit(fit_by)
        
        # Transform only non-null values (vectorized)
        new_col_name = column + "_transformed"
        df[new_col_name] = pd.NA  # Initialize with NA
        df.loc[mask, new_col_name] = encoders[column].transform(df.loc[mask, column])
        
        # Convert to nullable integer
        df[new_col_name] = df[new_col_name].astype("Int64")

    df = df.drop(columns, axis=1)
    return df, encoders

In [44]:
# Train imputer on train

def fit_imputer(df, fast=True): 
    # Select estimator based on speed/accuracy tradeoff
    if fast:
        # Use default BayesianRidge (fast, ~1 second)
        estimator = None
    else:
        # Use Random Forest for better accuracy with complex relationships (~2 minutes)
        estimator = RandomForestRegressor(
            n_estimators=20,      # Limited trees for speed
            max_depth=10,         # Prevent overfitting
            random_state=12       # Reproducibility
        )

    # TODO: for later
    # Test if we perform better if we use numerical and categorical imputers separately
    
    # Initialize imputer
    imputer = IterativeImputer(
        estimator=estimator,
        max_iter=10,                    # Number of imputation rounds
        random_state=12,                # For reproducibility
        initial_strategy="mean"         # Initial fill before iterative process
    )
    
    # TODO: Test other categorical imputers like: missForest, datawig
    """imputer = IterativeImputer(
        estimator=RandomForestClassifier(),
        max_iter=10,                    # Number of imputation rounds
        random_state=12,                # For reproducibility
        initial_strategy="most_frequent"         # Initial fill before iterative process
        )"""

    # FIT on training data
    # CRITICAL: We fit on data that still has missing values!
    # The imputer learns patterns of missingness and relationships

    imputer.fit(df)
    
    return imputer

In [45]:
def apply_imputer(df, imputer):
    """
        Apply the pretrained imputer to the dataframe
    """

    imputed_values = imputer.transform(df)

    df[df.columns] = imputed_values

    # TODO: rounding is not the best approach as the imputers prediction are continues thus 1.2 doesnt mean the value is closer to 1 than 2
    # However, rounding is the quickest way to fix this for now
    df[["mpg", "engineSize"]] = abs(df[["mpg", "engineSize"]]).round(1)
    try: 
        df[["year", "price", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]] = abs(df[["year", "price", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]]).round(0).astype(int)
    except KeyError: # will raise keyError if we run it on testing data as it has no price column
        df[["year", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]] = abs(df[["year", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]]).round(0).astype(int)
    
    return df

In [46]:
def decode(df, encoders):
    # Iterative imputer produces ~20-30 values that are outside of the range of the encoder
    # The simplest fix is to clip does values back into the range of the encoder
 

    df["Brand_transformed"] = df["Brand_transformed"].clip(lower=0, upper=encoders["Brand"].classes_.shape[0]-1).astype(int)
    df["Brand"] = encoders["Brand"].inverse_transform(df["Brand_transformed"])

    df["transmission_transformed"] = df["transmission_transformed"].clip(lower=0, upper=encoders["transmission"].classes_.shape[0]-1).astype(int)
    df["transmission"] = encoders["transmission"].inverse_transform(df["transmission_transformed"])
        
    # Use clip with the information of the fitted encoder, .classes_.shape gives us the dimension of the labels the encoder uses [0] is the rows - 1 because we start clipping at 0
    df["model_transformed"] = df["model_transformed"].clip(lower=0, upper=encoders["model"].classes_.shape[0]-1).astype(int)
    df["model"] = encoders["model"].inverse_transform(df["model_transformed"])
    
    df["fuelType_transformed"] = df["fuelType_transformed"].clip(lower=0, upper=encoders["fuelType"].classes_.shape[0]-1).astype(int)
    df["fuelType"] = encoders["fuelType"].inverse_transform(df["fuelType_transformed"])
    

    df.drop(columns=["Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"], inplace=True)

    return df

## Workflow for Train and Validation Sets

In [47]:
# Fix typos and small numeric cleanup
df = simple_processing(train_df)
# Encode cateogrical columns and replace the str with int columns. Return fitted encoders for decoding at the end
df_encoded, encoders = fit_transform_encoding(df)

In [64]:
stratify_col = df_encoded["Brand_transformed"].fillna(-999) # Fill the ~40 missing values with -999
# Train validation split
train_split, validation_split = train_test_split(df_encoded, test_size=0.2, random_state=42, stratify=stratify_col)

In [65]:
share_train = train_split["Brand_transformed"].value_counts() / train_split.shape[0]
share_validation= validation_split["Brand_transformed"].value_counts() / validation_split.shape[0]

In [53]:

# Train imputer on train (data leakage risk thus only train on train_split)
imputer = fit_imputer(train_split)

# Apply trained imputer to both datasplits
imputed_train = apply_imputer(train_split, imputer)
imputer_test = apply_imputer(validation_split, imputer)

# Decode encoded columns using the fitted encoders
train_processed = decode(imputed_train, encoders)
validation_processed = decode(imputer_test, encoders)

## Workflow for Seperated Testing Dataset

In [54]:
test_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/test.csv")

In [55]:
test_df.set_index("carID")

,Brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,
89856,Hyundai,I30,2022.878006,Automatic,30700.000000,petrol,205.0,41.5,1.6,61.0,3.0,0.0
106581,VW,Tiguan,2017.000000,Semi-Auto,-48190.655673,Petrol,150.0,38.2,2.0,60.0,2.0,0.0
80886,BMW,2 Series,2016.000000,Automatic,36792.000000,Petrol,125.0,51.4,1.5,94.0,2.0,0.0
100174,Opel,Grandland X,2019.000000,Manual,5533.000000,Petrol,145.0,44.1,1.2,77.0,1.0,0.0
81376,BMW,1 Series,2019.000000,Semi-Auto,9058.000000,Diesel,150.0,51.4,2.0,45.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
105775,VW,Tiguan,2017.000000,Manual,27575.000000,Petrol,145.0,46.3,1.4,94.0,1.0,0.0
81363,BMW,X2,2020.000000,Automatic,1980.000000,Petrol,145.0,34.0,2.0,39.0,3.0,0.0
76833,Audi,Q5,2019.000000,Semi-Auto,8297.000000,Diesel,145.0,38.2,2.0,88.0,4.0,0.0
91768,Mercedes,A Class,2019.000000,Manual,-50755.210230,Petrol,145.0,28.5,1.3,81.0,1.0,0.0
99627,Toyota,Yaris,2017.000000,Automatic,11071.000000,Petrol,30.0,58.0,1.3,98.0,4.0,0.0

In [56]:
test = simple_processing(test_df)
test_df_encoded, test_encoders = fit_transform_encoding(test)


df_encoded_no_price = df_encoded.drop(["price"], axis=1)
test_imputers = fit_imputer(df_encoded_no_price) # we use the full encoded training dataframe to train the imputers

# Apply trained imputer to both datasplits
test_df_imputed = apply_imputer(test_df_encoded, test_imputers)

test_processed = decode(test_df_imputed, test_encoders)

# Test of the models on the full dataset

In [57]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.base import clone
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

class BrandModelTrainer:
    def __init__(self, estimator):
        self.estimator = estimator
        self.brand_models = {}
        self.feature_cols = None

    def fit(self, X_train, y_train):
        self.feature_cols = [c for c in X_train.columns if c != "Brand"]
        print(f"Training models for {len(X_train['Brand'].unique())} brands...\n")

        for brand in X_train["Brand"].unique():
            mask = X_train["Brand"] == brand
            Xb = X_train.loc[mask, self.feature_cols]
            yb = y_train[mask]

            numeric_cols = Xb.select_dtypes(include=["int64", "float64"]).columns.tolist()
            categorical_cols = Xb.select_dtypes(include=["object", "category"]).columns.tolist()

            preprocessor = ColumnTransformer([
                ("num", RobustScaler(), numeric_cols),
                ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
            ])

            model = Pipeline([
                ("preprocess", preprocessor),
                ("estimator", clone(self.estimator))
            ])

            model.fit(Xb, yb)
            self.brand_models[brand] = model
            print(f"  ✓ {brand} done.")

        return self

    def predict(self, X):
        preds = np.zeros(len(X))
        for brand, model in self.brand_models.items():
            mask = X["Brand"] == brand
            if mask.sum() == 0:
                continue
            Xb = X.loc[mask, self.feature_cols]
            preds[mask] = model.predict(Xb)
        return preds

    # --- metriche overall ---
    def evaluate_train(self, X_train, y_train):
        y_pred = self.predict(X_train)
        rmse = np.sqrt(mean_squared_error(y_train, y_pred))
        mae = mean_absolute_error(y_train, y_pred)
        r2 = r2_score(y_train, y_pred)
        print("\nTraining Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    def evaluate(self, X_val, y_val):
        y_pred = self.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, y_pred))
        mae = mean_absolute_error(y_val, y_pred)
        r2 = r2_score(y_val, y_pred)
        print("\nValidation Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    # --- metriche per brand ---
    def evaluate_by_brand(self, X, y, split_name="Validation"):
        y_pred = self.predict(X)
        results = []
        for brand in X["Brand"].unique():
            mask = X["Brand"] == brand
            y_true_b = y[mask]
            y_pred_b = y_pred[mask]
            rmse = np.sqrt(mean_squared_error(y_true_b, y_pred_b))
            mae = mean_absolute_error(y_true_b, y_pred_b)
            r2 = r2_score(y_true_b, y_pred_b)
            results.append({"Brand": brand, "N": len(y_true_b), "RMSE": rmse, "MAE": mae, "R²": r2})
        df = pd.DataFrame(results).sort_values("RMSE")
        print(f"\n{split_name} Performance per Brand:")
        print(df.to_string(index=False))
        return df

    def evaluate_train_by_brand(self, X_train, y_train):
        return self.evaluate_by_brand(X_train, y_train, split_name="Training")

In [58]:
X_train = train_processed.drop(columns=['price'])
y_train = train_processed['price']
X_val = validation_processed.drop(columns=['price'])
y_val = validation_processed['price']

### Linear Regression

In [59]:
# istanza del modello
LR = LinearRegression()
trainer = BrandModelTrainer(LR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ toyota done.
  ✓ audi done.
  ✓ skoda done.
  ✓ opel done.
  ✓ vw done.
  ✓ bmw done.
  ✓ ford done.
  ✓ hyundai done.

Training Set Performance (Overall):
  RMSE: 3572.08
  MAE:  2149.96
  R²:   0.8651

Validation Set Performance (Overall):
  RMSE: 3599.91
  MAE:  2199.98
  R²:   0.8644

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7635 1569.254729 1092.444043 0.804812
  toyota  3774 1871.556076 1171.804225 0.909472
    ford 13114 2160.033966 1537.315802 0.797238
 hyundai  2723 2202.855432 1564.511104 0.860865
   skoda  3510 2433.683000 1543.361495 0.848094
      vw  8485 2945.533988 2073.737045 0.853896
    audi  5973 4544.218407 2915.449391 0.848650
     bmw  6037 4568.821648 3040.240855 0.840769
mercedes  9527 5843.617510 3642.866951 0.727802

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1909 1647.476974 1142.267382 0.791766
   skoda  876 2167.738101 1532.707068 0.878963
    ford 3278 2184.559128 1558.582527 0.787289
  toyota  944 2245.417319 1249.254934 0.895143
 hyundai  681 2376.967381 1649.454501 0.850023
      vw 2121 3086.568078 2186.019099 0.845029
    audi 1495 4289.597886 2825.460520 0.863752
     bmw 1509 4324.461584 3041.687432 0.856351
mercedes 2382 6058.546019 3796.546605 0.704706

      Brand     N         RMSE          MAE        R²
6      opel  1909  1647.476974  1142.267382  0.791766
0     skoda   876  2167.738101  1532.707068  0.878963
5      ford  3278  2184.559128  1558.582527  0.787289
4    toyota   944  2245.417319  1249.254934  0.895143
8   hyundai   681  2376.967381  1649.454501  0.850023
7        vw  2121  3086.568078  2186.019099  0.845029
1      audi  1495  4289.597886  2825.460520  0.863752
3       bmw  1509  4324.461584  3041.687432  0.856351
2  mercedes  2382  6058.546019  3796.546605  0.704706

### SGD

In [60]:
# istanza del modello
SGD = SGDRegressor()
trainer = BrandModelTrainer(SGD)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)        # Performance VALID

Training models for 9 brands...

  ✓ mercedes done.
  ✓ toyota done.
  ✓ audi done.
  ✓ skoda done.
  ✓ opel done.
  ✓ vw done.
  ✓ bmw done.
  ✓ ford done.
  ✓ hyundai done.

Training Set Performance (Overall):
  RMSE: 3711.00
  MAE:  2200.54
  R²:   0.8544

Validation Set Performance (Overall):
  RMSE: 3612.77
  MAE:  2225.63
  R²:   0.8635

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7635 1613.678206 1115.091860 0.793605
  toyota  3774 2019.331256 1257.568266 0.894612
    ford 13114 2179.324272 1538.376797 0.793601
 hyundai  2723 2260.389983 1604.357461 0.853502
   skoda  3510 2482.110676 1578.267061 0.841988
      vw  8485 2996.414874 2094.878687 0.848804
     bmw  6037 4764.950747 3174.147112 0.826805
    audi  5973 4774.960143 3016.224185 0.832890
mercedes  9527 6099.778987 3720.886038 0.703415

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1909 1675.457420 1160.873481 0.784633
   skoda  876 2172.548364 1537.606103 0.878426
    ford 3278 2192.821497 1554.287603 0.785677
  toyota  944 2204.720848 1280.801133 0.898909
 hyundai  681 2382.447667 1656.754084 0.849330
      vw 2121 3125.296992 2195.014511 0.841115
    audi 1495 4432.477740 2874.694753 0.854524
     bmw 1509 4465.377653 3150.927449 0.846837
mercedes 2382 5953.918450 3826.639911 0.714817

      Brand     N         RMSE          MAE        R²
6      opel  1909  1675.457420  1160.873481  0.784633
0     skoda   876  2172.548364  1537.606103  0.878426
5      ford  3278  2192.821497  1554.287603  0.785677
4    toyota   944  2204.720848  1280.801133  0.898909
8   hyundai   681  2382.447667  1656.754084  0.849330
7        vw  2121  3125.296992  2195.014511  0.841115
1      audi  1495  4432.477740  2874.694753  0.854524
3       bmw  1509  4465.377653  3150.927449  0.846837
2  mercedes  2382  5953.918450  3826.639911  0.714817

### KNR

In [61]:
# istanza del modello
KNR = KNeighborsRegressor()
trainer = BrandModelTrainer(KNR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ toyota done.
  ✓ audi done.
  ✓ skoda done.
  ✓ opel done.
  ✓ vw done.
  ✓ bmw done.
  ✓ ford done.
  ✓ hyundai done.

Training Set Performance (Overall):
  RMSE: 2471.16
  MAE:  1424.75
  R²:   0.9355

Validation Set Performance (Overall):
  RMSE: 2916.47
  MAE:  1765.39
  R²:   0.9110

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7635 1120.548739  767.666562 0.900476
    ford 13114 1402.858334  931.752631 0.914475
  toyota  3774 1412.800663  866.810175 0.948413
 hyundai  2723 1558.521836 1034.436430 0.930355
   skoda  3510 1896.163132 1151.640513 0.907786
      vw  8485 2051.824622 1402.532092 0.929105
    audi  5973 3170.729673 2033.356337 0.926315
     bmw  6037 3615.665535 2197.962034 0.900277
mercedes  9527 3754.460985 2211.389566 0.887639

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1909 1412.418295  988.307491 0.846948
    ford 3278 1743.493306 1167.524649 0.864511
  toyota  944 1936.602529 1101.756568 0.922002
   skoda  876 2018.034629 1414.439041 0.895104
 hyundai  681 2116.531245 1372.547724 0.881087
      vw 2121 2609.887144 1800.129844 0.889199
    audi 1495 3625.923517 2386.992776 0.902650
     bmw 1509 4129.083167 2671.563950 0.869038
mercedes 2382 4369.803245 2720.157347 0.846382

      Brand     N         RMSE          MAE        R²
6      opel  1909  1412.418295   988.307491  0.846948
5      ford  3278  1743.493306  1167.524649  0.864511
4    toyota   944  1936.602529  1101.756568  0.922002
0     skoda   876  2018.034629  1414.439041  0.895104
8   hyundai   681  2116.531245  1372.547724  0.881087
7        vw  2121  2609.887144  1800.129844  0.889199
1      audi  1495  3625.923517  2386.992776  0.902650
3       bmw  1509  4129.083167  2671.563950  0.869038
2  mercedes  2382  4369.803245  2720.157347  0.846382

### Random Forest

In [62]:
# istanza del modello
RF = RandomForestRegressor()
trainer = BrandModelTrainer(RF)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

KeyboardInterrupt:

### Neural Network

In [ ]:
from sklearn.neural_network import MLPRegressor

mlp_deep = MLPRegressor(
    hidden_layer_sizes=(512, 256, 128, 64),  
    activation='relu',
    solver='adam',
    alpha=0.0001,  
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=1000,
    batch_size=32,
    random_state=42,
    early_stopping=True,
    n_iter_no_change=30,  # Più pazienza
    validation_fraction=0.15,
    verbose=True
)

trainer = BrandModelTrainer(mlp_deep)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

Iteration 1, loss = 22043472.82945213
Validation score: 0.357357
Iteration 2, loss = 6860957.21686987
Validation score: 0.405066
Iteration 3, loss = 6575254.95262054
Validation score: 0.413837
Iteration 4, loss = 6442960.41884249
Validation score: 0.431650
Iteration 5, loss = 6376301.56310276
Validation score: 0.435515
Iteration 6, loss = 6232869.86717771
Validation score: 0.452481
Iteration 7, loss = 6105867.75164786
Validation score: 0.459479
Iteration 8, loss = 6000949.02302772
Validation score: 0.464047
Iteration 9, loss = 5878128.99980298
Validation score: 0.472874
Iteration 10, loss = 5793846.50678740
Validation score: 0.436217
Iteration 11, loss = 5699604.26011444
Validation score: 0.495438
Iteration 12, loss = 5646879.62600422
Validation score: 0.502912
Iteration 13, loss = 5550968.33816704
Validation score: 0.501755
Iteration 14, loss = 5492381.99910342
Validation score: 0.488008
Iteration 15, loss = 5499446.70140327
Validation score: 0.518157
Iteration 16, loss = 5381078.24112618
Validation score: 0.514730
Iteration 17, loss = 5359128.66867792
Validation score: 0.510077
Iteration 18, loss = 5309948.80113440
Validation score: 0.524426
Iteration 19, loss = 5300316.62966988
Validation score: 0.526267
Iteration 20, loss = 5220296.96092235
Validation score: 0.523278
Iteration 21, loss = 5189372.39113087
Validation score: 0.530482
Iteration 22, loss = 5128346.71028284
Validation score: 0.533046
Iteration 23, loss = 5106119.98419611
Validation score: 0.527199
Iteration 24, loss = 5050939.65861250
Validation score: 0.531321
Iteration 25, loss = 4987424.38608675
Validation score: 0.535791
Iteration 26, loss = 4966393.14598092
Validation score: 0.537159
Iteration 27, loss = 4886038.19403948
Validation score: 0.552124
Iteration 28, loss = 4793466.59765744
Validation score: 0.561103
Iteration 29, loss = 4706073.04810054
Validation score: 0.570735
Iteration 30, loss = 4637432.12251274
Validation score: 0.568033
Iteration 31, loss = 4598758.67684242
Validation score: 0.581982
Iteration 32, loss = 4473995.76271450
Validation score: 0.585732
Iteration 33, loss = 4426143.86129715
Validation score: 0.597102
Iteration 34, loss = 4371726.73089633
Validation score: 0.599705
Iteration 35, loss = 4286916.80913741
Validation score: 0.603713
Iteration 36, loss = 4238007.30523623
Validation score: 0.602805
Iteration 37, loss = 4167541.53562162
Validation score: 0.612342
Iteration 38, loss = 4148398.57117682
Validation score: 0.607197
Iteration 39, loss = 4074384.86051840
Validation score: 0.610688
Iteration 40, loss = 4021033.97896679
Validation score: 0.614584
Iteration 41, loss = 4007172.54814300
Validation score: 0.607979
Iteration 42, loss = 3967203.26589874
Validation score: 0.586793
Iteration 43, loss = 3917711.90131791
Validation score: 0.629649
Iteration 44, loss = 3874608.60621056
Validation score: 0.630172
Iteration 45, loss = 3846224.86303106
Validation score: 0.626414
Iteration 46, loss = 3799518.07505933
Validation score: 0.630456
Iteration 47, loss = 3824672.44357363
Validation score: 0.635911
Iteration 48, loss = 3781719.80741947
Validation score: 0.622517
Iteration 49, loss = 3788874.48352288
Validation score: 0.631461
Iteration 50, loss = 3726364.40334006
Validation score: 0.634983
Iteration 51, loss = 3682053.69855852
Validation score: 0.630922
Iteration 52, loss = 3651258.44158664
Validation score: 0.626315
Iteration 53, loss = 3607595.52793561
Validation score: 0.613470
Iteration 54, loss = 3585468.39714496
Validation score: 0.624703
Iteration 55, loss = 3582580.61311128
Validation score: 0.642335
Iteration 56, loss = 3579872.21313119
Validation score: 0.623761
Iteration 57, loss = 3572619.96448071
Validation score: 0.628313
Iteration 58, loss = 3520337.75234858
Validation score: 0.645828
Iteration 59, loss = 3580207.59428760
Validation score: 0.638923
Iteration 60, loss = 3483401.74206969
Validation score: 0.585395
Iteration 61, loss = 3494908.46707760
Validation score: 0.644639
Iteration 62, loss = 3492438.63336724
Validation score: 0.649232
Iteration 63, loss = 3420740.39175107
Validation score: 0.648336
Iteration 64, loss = 3428095.39649680
Validation score: 0.648898
Iteration 65, loss = 3386271.84297674
Validation score: 0.643308
Iteration 66, loss = 3403687.81562884
Validation score: 0.650811
Iteration 67, loss = 3356484.39988531
Validation score: 0.631990
Iteration 68, loss = 3407031.71655890
Validation score: 0.650671
Iteration 69, loss = 3315240.47878076
Validation score: 0.639354
Iteration 70, loss = 3354393.28044613
Validation score: 0.630064
Iteration 71, loss = 3329280.10691383
Validation score: 0.642274
Iteration 72, loss = 3359367.84311942
Validation score: 0.653220
Iteration 73, loss = 3302526.82444241
Validation score: 0.636063
Iteration 74, loss = 3341728.95405126
Validation score: 0.643952
Iteration 75, loss = 3353371.54253070
Validation score: 0.623835
Iteration 76, loss = 3285091.20012224
Validation score: 0.646374
Iteration 77, loss = 3262904.18838366
Validation score: 0.631694
Iteration 78, loss = 3241324.95535486
Validation score: 0.620596
Iteration 79, loss = 3230281.57669910
Validation score: 0.653922
Iteration 80, loss = 3233470.20478834
Validation score: 0.643686
Iteration 81, loss = 3223683.67011998
Validation score: 0.647204
Iteration 82, loss = 3197902.78240444
Validation score: 0.648780
Iteration 83, loss = 3193867.33584897
Validation score: 0.632107
Iteration 84, loss = 3179284.72836812
Validation score: 0.665605
Iteration 85, loss = 3216105.71672827
Validation score: 0.660813
Iteration 86, loss = 3203159.39464859
Validation score: 0.645177
Iteration 87, loss = 3163984.40737071
Validation score: 0.651479
Iteration 88, loss = 3178187.26576284
Validation score: 0.653443
Iteration 89, loss = 3122721.35436495
Validation score: 0.663053
Iteration 90, loss = 3141695.61893592
Validation score: 0.624970
Iteration 91, loss = 3151206.54592242
Validation score: 0.645222
Iteration 92, loss = 3169635.23364058
Validation score: 0.651275
Iteration 93, loss = 3131725.47618347
Validation score: 0.645715
Iteration 94, loss = 3139993.08490454
Validation score: 0.627729
Iteration 95, loss = 3133718.02842225
Validation score: 0.658974
Iteration 96, loss = 3080665.12000174
Validation score: 0.652922
Iteration 97, loss = 3160608.58347792
Validation score: 0.630481
Iteration 98, loss = 3115912.81409929
Validation score: 0.645640
Iteration 99, loss = 3083225.03384550
Validation score: 0.652669
Iteration 100, loss = 3119449.73152238
Validation score: 0.644866
Iteration 101, loss = 3051083.38118826
Validation score: 0.657511
Iteration 102, loss = 3117057.89134991
Validation score: 0.658458
Iteration 103, loss = 3055837.86392347
Validation score: 0.660103
Iteration 104, loss = 3078455.30081317
Validation score: 0.661597
Iteration 105, loss = 3046390.86209569
Validation score: 0.656616
Iteration 106, loss = 3042526.97967242
Validation score: 0.651859
Iteration 107, loss = 3069355.06710809
Validation score: 0.655718
Iteration 108, loss = 3027965.52847299
Validation score: 0.655893
Iteration 109, loss = 3005995.05864121
Validation score: 0.657212
Iteration 110, loss = 3010064.39123540
Validation score: 0.648976
Iteration 111, loss = 3088237.58916796
Validation score: 0.620598
Iteration 112, loss = 2987631.03341911
Validation score: 0.659552
Iteration 113, loss = 3015551.90705737
Validation score: 0.659549
Iteration 114, loss = 3004547.44018580
Validation score: 0.643643
Iteration 115, loss = 3004302.46082789
Validation score: 0.653157
Validation score did not improve more than tol=0.000100 for 30 consecutive epochs. Stopping.
  ✓ ford done.
Iteration 1, loss = 19464628.09279659
Validation score: 0.407811
Iteration 2, loss = 3510965.63684235
Validation score: 0.457155
Iteration 3, loss = 3317581.65555992
Validation score: 0.489734
Iteration 4, loss = 3246438.13745841
Validation score: 0.495319
Iteration 5, loss = 3195722.79212260
Validation score: 0.501192
Iteration 6, loss = 3158406.32860468
Validation score: 0.512900
Iteration 7, loss = 3098723.74293340
Validation score: 0.521569
Iteration 8, loss = 3069571.71694540
Validation score: 0.526898
Iteration 9, loss = 3011518.14651810
Validation score: 0.490336
Iteration 10, loss = 2967151.42651210
Validation score: 0.536742
Iteration 11, loss = 2899437.16100397
Validation score: 0.550427
Iteration 12, loss = 2872567.94891452
Validation score: 0.565905
Iteration 13, loss = 2834739.74423838
Validation score: 0.528395
Iteration 14, loss = 2798828.49218758
Validation score: 0.578697
Iteration 15, loss = 2777656.96633417
Validation score: 0.564145
Iteration 16, loss = 2747997.95818769
Validation score: 0.562628
Iteration 17, loss = 2700601.26970721
Validation score: 0.588884
Iteration 18, loss = 2652096.65067954
Validation score: 0.588782
Iteration 19, loss = 2642608.81349301
Validation score: 0.580181
Iteration 20, loss = 2653425.87301027
Validation score: 0.560723
Iteration 21, loss = 2579528.66172684
Validation score: 0.596803
Iteration 22, loss = 2580564.42483005
Validation score: 0.601245
Iteration 23, loss = 2557653.26862480
Validation score: 0.534820
Iteration 24, loss = 2562867.62914133
Validation score: 0.591404
Iteration 25, loss = 2522673.19735212
Validation score: 0.603908
Iteration 26, loss = 2483444.16592847
Validation score: 0.599773
Iteration 27, loss = 2489655.81772300
Validation score: 0.610541
Iteration 28, loss = 2460054.50454824
Validation score: 0.583324
Iteration 29, loss = 2449491.33113434
Validation score: 0.594049
Iteration 30, loss = 2453573.35755690
Validation score: 0.608614
Iteration 31, loss = 2422065.86838181
Validation score: 0.590075
Iteration 32, loss = 2424099.79359946
Validation score: 0.606524
Iteration 33, loss = 2404803.79124886
Validation score: 0.582184
Iteration 34, loss = 2369936.26509235
Validation score: 0.619453
Iteration 35, loss = 2377658.62390428
Validation score: 0.624277
Iteration 36, loss = 2366950.37321787
Validation score: 0.621087
Iteration 37, loss = 2364847.91138299
Validation score: 0.615700
Iteration 38, loss = 2376683.02535900
Validation score: 0.629425
Iteration 39, loss = 2319716.76035177
Validation score: 0.609771
Iteration 40, loss = 2358601.86202292
Validation score: 0.615848
Iteration 41, loss = 2326466.05569171
Validation score: 0.626911
Iteration 42, loss = 2308107.17178133
Validation score: 0.629821
Iteration 43, loss = 2301836.75543749
Validation score: 0.614713
Iteration 44, loss = 2305739.80658975
Validation score: 0.625526
Iteration 45, loss = 2280949.26767039
Validation score: 0.632252
Iteration 46, loss = 2255641.53503398
Validation score: 0.620268
Iteration 47, loss = 2242844.74474490
Validation score: 0.635286
Iteration 48, loss = 2239188.61119687
Validation score: 0.609516
Iteration 49, loss = 2245596.01026610
Validation score: 0.636768
Iteration 50, loss = 2246243.35901309
Validation score: 0.626091
Iteration 51, loss = 2216898.73443481
Validation score: 0.607706
Iteration 52, loss = 2233188.45016971
Validation score: 0.622530
Iteration 53, loss = 2189434.78492742
Validation score: 0.632097
Iteration 54, loss = 2198219.25111711
Validation score: 0.625191
Iteration 55, loss = 2197529.82690754
Validation score: 0.639997
Iteration 56, loss = 2226899.17001637
Validation score: 0.637859
Iteration 57, loss = 2206869.28692307
Validation score: 0.642256
Iteration 58, loss = 2181648.94296356
Validation score: 0.636834
Iteration 59, loss = 2152677.09888641
Validation score: 0.644735
Iteration 60, loss = 2183676.91636341
Validation score: 0.615680
Iteration 61, loss = 2175928.63614719
Validation score: 0.648040
Iteration 62, loss = 2136829.63518151
Validation score: 0.635899
Iteration 63, loss = 2148368.12654297
Validation score: 0.634671
Iteration 64, loss = 2111172.91924309
Validation score: 0.627556
Iteration 65, loss = 2177260.71817603
Validation score: 0.647422
Iteration 66, loss = 2120848.94592941
Validation score: 0.637977
Iteration 67, loss = 2130352.03171766
Validation score: 0.630308
Iteration 68, loss = 2125290.25426301
Validation score: 0.623525
Iteration 69, loss = 2106629.19944219
Validation score: 0.651267
Iteration 70, loss = 2092272.01117376
Validation score: 0.644833
Iteration 71, loss = 2107580.95458137
Validation score: 0.647120
Iteration 72, loss = 2088301.20606467
Validation score: 0.636139
Iteration 73, loss = 2078210.15690035
Validation score: 0.645436
Iteration 74, loss = 2103585.21405908
Validation score: 0.641019
Iteration 75, loss = 2082682.21078291
Validation score: 0.645992
Iteration 76, loss = 2067971.10001890
Validation score: 0.639662
Iteration 77, loss = 2094966.51495005
Validation score: 0.635537
Iteration 78, loss = 2081032.42825367
Validation score: 0.654285
Iteration 79, loss = 2061358.08857709
Validation score: 0.651688
Iteration 80, loss = 2068136.20319351
Validation score: 0.644056
Iteration 81, loss = 2060029.63353015
Validation score: 0.649743
Iteration 82, loss = 2054758.54752248
Validation score: 0.651890
Iteration 83, loss = 2025146.35424890
Validation score: 0.648149
Iteration 84, loss = 2029058.28896962
Validation score: 0.650625
Iteration 85, loss = 2023163.22901628
Validation score: 0.632148
Iteration 86, loss = 2024243.50320453
Validation score: 0.604873
Iteration 87, loss = 2053750.63869590
Validation score: 0.649109
Iteration 88, loss = 2029734.60700323
Validation score: 0.655502
Iteration 89, loss = 2037630.23872454
Validation score: 0.657799
Iteration 90, loss = 2015306.71305274
Validation score: 0.653938
Iteration 91, loss = 2047302.57835220
Validation score: 0.658921
Iteration 92, loss = 2000372.57584968
Validation score: 0.653054
Iteration 93, loss = 1998878.71464528
Validation score: 0.655421
Iteration 94, loss = 1985120.92650504
Validation score: 0.656209
Iteration 95, loss = 2003439.69185685
Validation score: 0.654207
Iteration 96, loss = 2003674.50053366
Validation score: 0.648922
Iteration 97, loss = 1988141.33460564
Validation score: 0.626585
Iteration 98, loss = 1987115.45588839
Validation score: 0.661508
Iteration 99, loss = 1969318.88175012
Validation score: 0.651774
Iteration 100, loss = 1977000.45118641
Validation score: 0.655702
Iteration 101, loss = 1972770.17676514
Validation score: 0.652261
Iteration 102, loss = 1976674.51141491
Validation score: 0.615818
Iteration 103, loss = 1970306.98981364
Validation score: 0.638910
Iteration 104, loss = 1958615.61747270
Validation score: 0.657483
Iteration 105, loss = 1974254.72686327
Validation score: 0.659856
Iteration 106, loss = 1928333.10164567
Validation score: 0.653569
Iteration 107, loss = 1972253.06746946
Validation score: 0.667924
Iteration 108, loss = 1936537.28844830
Validation score: 0.656872
Iteration 109, loss = 1951931.82294185
Validation score: 0.663935
Iteration 110, loss = 1922968.12975009
Validation score: 0.666250
Iteration 111, loss = 1951136.94495178
Validation score: 0.666241
Iteration 112, loss = 1936890.97939001
Validation score: 0.645972
Iteration 113, loss = 1924053.76397586
Validation score: 0.666576
Iteration 114, loss = 1919119.49879705
Validation score: 0.648007
Iteration 115, loss = 1925863.40995485
Validation score: 0.661334
Iteration 116, loss = 1920986.97056909
Validation score: 0.647810
Iteration 117, loss = 1935629.55798577
Validation score: 0.650088
Iteration 118, loss = 1934564.14637675
Validation score: 0.661445
Iteration 119, loss = 1963105.14091795
Validation score: 0.670547
Iteration 120, loss = 1905323.92306383
Validation score: 0.659839
Iteration 121, loss = 1910311.25947133
Validation score: 0.643118
Iteration 122, loss = 1915292.14157184
Validation score: 0.651973
Iteration 123, loss = 1914098.90983400
Validation score: 0.652136
Iteration 124, loss = 1903818.68189336
Validation score: 0.671547
Iteration 125, loss = 1881555.97516844
Validation score: 0.665820
Iteration 126, loss = 1904679.50043159
Validation score: 0.667716
Iteration 127, loss = 1881502.50754795
Validation score: 0.655188
Iteration 128, loss = 1892188.28458322
Validation score: 0.665287
Iteration 129, loss = 1882040.52670406
Validation score: 0.648899
Iteration 130, loss = 1877598.11219212
Validation score: 0.654900
Iteration 131, loss = 1868086.35195087
Validation score: 0.622352
Iteration 132, loss = 1891187.19944380
Validation score: 0.662710
Iteration 133, loss = 1862679.44652778
Validation score: 0.672328
Iteration 134, loss = 1858992.66839835
Validation score: 0.663175
Iteration 135, loss = 1902396.81293352
Validation score: 0.669464
Iteration 136, loss = 1843011.38214288
Validation score: 0.667793
Iteration 137, loss = 1874027.74544718
Validation score: 0.669028
Iteration 138, loss = 1876250.07079305
Validation score: 0.675827
Iteration 139, loss = 1863392.92409602
Validation score: 0.669142
Iteration 140, loss = 1854737.31140889
Validation score: 0.666254
Iteration 141, loss = 1850118.43077506
Validation score: 0.668160
Iteration 142, loss = 1853063.36452528
Validation score: 0.672627
Iteration 143, loss = 1832079.33829632
Validation score: 0.669800
Iteration 144, loss = 1835201.64836109
Validation score: 0.665996
Iteration 145, loss = 1858296.84361339
Validation score: 0.600208
Iteration 146, loss = 1875937.07223703
Validation score: 0.672193
Iteration 147, loss = 1823456.39101905
Validation score: 0.669298
Iteration 148, loss = 1848902.58877726
Validation score: 0.633002
Iteration 149, loss = 1813207.51942959
Validation score: 0.673511
Iteration 150, loss = 1822282.88885716
Validation score: 0.681413
Iteration 151, loss = 1843321.45317806
Validation score: 0.673233
Iteration 152, loss = 1801548.10458742
Validation score: 0.654676
Iteration 153, loss = 1823683.65698897
Validation score: 0.673553
Iteration 154, loss = 1814780.89317216
Validation score: 0.651890
Iteration 155, loss = 1823770.51436596
Validation score: 0.672282
Iteration 156, loss = 1835039.16552914
Validation score: 0.656859
Iteration 157, loss = 1854855.64605526
Validation score: 0.680583
Iteration 158, loss = 1808795.29719717
Validation score: 0.670209
Iteration 159, loss = 1807334.99499835
Validation score: 0.675536
Iteration 160, loss = 1802738.14771546
Validation score: 0.663302
Iteration 161, loss = 1826915.73177514
Validation score: 0.663248
Iteration 162, loss = 1816134.44062505
Validation score: 0.673083
Iteration 163, loss = 1800456.12683417
Validation score: 0.673614
Iteration 164, loss = 1798637.67411435
Validation score: 0.679298
Iteration 165, loss = 1802178.62474884
Validation score: 0.680204
Iteration 166, loss = 1799631.27828655
Validation score: 0.659536
Iteration 167, loss = 1790868.53495847
Validation score: 0.674490
Iteration 168, loss = 1802073.60587501
Validation score: 0.678384
Iteration 169, loss = 1818888.56256972
Validation score: 0.630597
Iteration 170, loss = 1810417.39860283
Validation score: 0.676403
Iteration 171, loss = 1776015.62215841
Validation score: 0.674138
Iteration 172, loss = 1806817.34213283
Validation score: 0.674661
Iteration 173, loss = 1781399.19879372
Validation score: 0.665121
Iteration 174, loss = 1778573.18730107
Validation score: 0.676804
Iteration 175, loss = 1769542.87674348
Validation score: 0.671385
Iteration 176, loss = 1813971.77223419
Validation score: 0.661508
Iteration 177, loss = 1771891.01287603
Validation score: 0.643742
Iteration 178, loss = 1780673.16794399
Validation score: 0.668165
Iteration 179, loss = 1782879.08901934
Validation score: 0.669915
Iteration 180, loss = 1804495.76523973
Validation score: 0.672580
Iteration 181, loss = 1800006.67137094
Validation score: 0.674708
Validation score did not improve more than tol=0.000100 for 30 consecutive epochs. Stopping.
  ✓ opel done.
Iteration 1, loss = 64353009.82988959
Validation score: 0.499438
Iteration 2, loss = 7390194.04914626
Validation score: 0.740526
Iteration 3, loss = 6166430.81135705
Validation score: 0.769845
Iteration 4, loss = 5737163.55864727
Validation score: 0.791286
Iteration 5, loss = 5482267.99513521
Validation score: 0.802855
Iteration 6, loss = 5302088.68385725
Validation score: 0.811919
Iteration 7, loss = 5139919.08559685

      Brand     N         RMSE          MAE        R²
6      opel  1912  2241.580303  1472.888628  0.615157
1     skoda   914  2518.628206  1770.621197  0.817930
3      ford  3182  2711.415578  1905.984929  0.678478
7   hyundai   716  2834.978895  1875.300153  0.766054
8    toyota   939  3004.968333  1921.578237  0.767996
2        vw  2117  3552.523174  2254.535563  0.772561
4      audi  1527  5363.637946  3347.892006  0.758011
0  mercedes  2368  5466.803931  3363.666451  0.745159
5       bmw  1520  6703.984231  4663.633818  0.680939

In [ ]:
from sklearn.neural_network import MLPRegressor

mlp_wide = MLPRegressor(
    hidden_layer_sizes=(1024,),  # Un solo layer MOLTO largo
    activation='relu',
    solver='adam',
    alpha=0.0001,
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=1000,
    batch_size=64,
    random_state=42,
    early_stopping=True,
    n_iter_no_change=30,
    validation_fraction=0.15,
    verbose=True
)

trainer = BrandModelTrainer(mlp_wide)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

Iteration 1, loss = 89867252.42027950
Validation score: -7.095258
Iteration 2, loss = 84132912.70672533
Validation score: -6.277111
Iteration 3, loss = 72674494.71837711
Validation score: -5.025910
Iteration 4, loss = 57853238.06019688
Validation score: -3.606339
Iteration 5, loss = 42654326.40868299
Validation score: -2.276832
Iteration 6, loss = 29521201.43998935
Validation score: -1.220340
Iteration 7, loss = 19920235.85627457
Validation score: -0.518546
Iteration 8, loss = 14024697.01665131
Validation score: -0.127958
Iteration 9, loss = 11017590.03150420
Validation score: 0.053325
Iteration 10, loss = 9714728.71073372
Validation score: 0.126798
Iteration 11, loss = 9184441.24807563
Validation score: 0.158700
Iteration 12, loss = 8938955.33418435
Validation score: 0.177088
Iteration 13, loss = 8780513.20324910
Validation score: 0.191510
Iteration 14, loss = 8651905.80398754
Validation score: 0.204433
Iteration 15, loss = 8536816.31807630
Validation score: 0.215728
Iteration 16, loss = 8434405.77526902
Validation score: 0.225995
Iteration 17, loss = 8341709.91176259
Validation score: 0.235378
Iteration 18, loss = 8258379.98230564
Validation score: 0.244039
Iteration 19, loss = 8183070.11235654
Validation score: 0.251678
Iteration 20, loss = 8115087.83505543
Validation score: 0.258692
Iteration 21, loss = 8054840.44629136
Validation score: 0.264933
Iteration 22, loss = 8000530.06451471
Validation score: 0.270531
Iteration 23, loss = 7951978.46976070
Validation score: 0.275882
Iteration 24, loss = 7907006.44421288
Validation score: 0.280604
Iteration 25, loss = 7866711.98816920
Validation score: 0.284868
Iteration 26, loss = 7831307.38112469
Validation score: 0.288873
Iteration 27, loss = 7796362.32500943
Validation score: 0.292184
Iteration 28, loss = 7764905.28883823
Validation score: 0.295588
Iteration 29, loss = 7736901.55622916
Validation score: 0.298687
Iteration 30, loss = 7708585.41473959
Validation score: 0.301869
Iteration 31, loss = 7682497.30006111
Validation score: 0.304788
Iteration 32, loss = 7657199.33679531
Validation score: 0.307366
Iteration 33, loss = 7634417.59680358
Validation score: 0.309815
Iteration 34, loss = 7611752.05442626
Validation score: 0.312369
Iteration 35, loss = 7590910.89006191
Validation score: 0.314403
Iteration 36, loss = 7569640.57348930
Validation score: 0.316254
Iteration 37, loss = 7549282.89603416
Validation score: 0.318598
Iteration 38, loss = 7531364.99210841
Validation score: 0.320526
Iteration 39, loss = 7511473.24575813
Validation score: 0.321375
Iteration 40, loss = 7496080.24122958
Validation score: 0.324139
Iteration 41, loss = 7480546.64067939
Validation score: 0.325660
Iteration 42, loss = 7462695.24263955
Validation score: 0.327550
Iteration 43, loss = 7445131.07913928
Validation score: 0.328658
Iteration 44, loss = 7433312.10222126
Validation score: 0.330722
Iteration 45, loss = 7418602.98861006
Validation score: 0.332223
Iteration 46, loss = 7402911.83039550
Validation score: 0.333673
Iteration 47, loss = 7391409.61389991
Validation score: 0.335099
Iteration 48, loss = 7375857.94117190
Validation score: 0.336159
Iteration 49, loss = 7362034.97656167
Validation score: 0.337450
Iteration 50, loss = 7351034.20171006
Validation score: 0.339005
Iteration 51, loss = 7338354.04574214
Validation score: 0.339726
Iteration 52, loss = 7325354.97623874
Validation score: 0.341137
Iteration 53, loss = 7313315.76022775
Validation score: 0.342398
Iteration 54, loss = 7301328.95168310
Validation score: 0.342752
Iteration 55, loss = 7294067.87656538
Validation score: 0.344270
Iteration 56, loss = 7280116.99170995
Validation score: 0.345637
Iteration 57, loss = 7270486.67450078
Validation score: 0.346460
Iteration 58, loss = 7259035.92311590
Validation score: 0.347572
Iteration 59, loss = 7249943.46787024
Validation score: 0.348655
Iteration 60, loss = 7237715.57304166
Validation score: 0.349245
Iteration 61, loss = 7226678.78575597
Validation score: 0.350457
Iteration 62, loss = 7220525.25271533
Validation score: 0.351264
Iteration 63, loss = 7210998.24937620
Validation score: 0.352082
Iteration 64, loss = 7201952.25667516
Validation score: 0.353054
Iteration 65, loss = 7190477.35194258
Validation score: 0.353253
Iteration 66, loss = 7183068.28088641
Validation score: 0.354684
Iteration 67, loss = 7175766.46588775
Validation score: 0.355520
Iteration 68, loss = 7166416.60476530
Validation score: 0.356352
Iteration 69, loss = 7157205.94593432
Validation score: 0.357133
Iteration 70, loss = 7148874.21326421
Validation score: 0.357934
Iteration 71, loss = 7140824.88428010
Validation score: 0.358825
Iteration 72, loss = 7134131.41944607
Validation score: 0.359492
Iteration 73, loss = 7123859.78026141
Validation score: 0.360346
Iteration 74, loss = 7116939.79751121
Validation score: 0.360935
Iteration 75, loss = 7108496.08410781
Validation score: 0.361613
Iteration 76, loss = 7102595.44453979
Validation score: 0.362250
Iteration 77, loss = 7093265.85644437
Validation score: 0.363114
Iteration 78, loss = 7085165.73195840
Validation score: 0.363471
Iteration 79, loss = 7078358.23907200
Validation score: 0.364280
Iteration 80, loss = 7069781.40768565
Validation score: 0.364880
Iteration 81, loss = 7062346.45950040
Validation score: 0.365682
Iteration 82, loss = 7056288.13856673
Validation score: 0.366300
Iteration 83, loss = 7048706.41775030
Validation score: 0.367154
Iteration 84, loss = 7042057.72633404
Validation score: 0.367714
Iteration 85, loss = 7034752.63913327
Validation score: 0.368363
Iteration 86, loss = 7027199.37746555
Validation score: 0.368624
Iteration 87, loss = 7021877.48197912
Validation score: 0.369655
Iteration 88, loss = 7014872.06071419
Validation score: 0.370410
Iteration 89, loss = 7007830.34522863
Validation score: 0.370705
Iteration 90, loss = 7000006.81864340
Validation score: 0.371314
Iteration 91, loss = 6993922.83860134
Validation score: 0.372267
Iteration 92, loss = 6987217.45416374
Validation score: 0.372886
Iteration 93, loss = 6981502.72594695
Validation score: 0.373466
Iteration 94, loss = 6974795.96128198
Validation score: 0.373804
Iteration 95, loss = 6968750.23480654
Validation score: 0.374391
Iteration 96, loss = 6963395.12740227
Validation score: 0.374996
Iteration 97, loss = 6955812.05637384
Validation score: 0.375532
Iteration 98, loss = 6950370.46347773
Validation score: 0.376062
Iteration 99, loss = 6942882.04674823
Validation score: 0.376379
Iteration 100, loss = 6936644.49855181
Validation score: 0.377121
Iteration 101, loss = 6930446.76450001
Validation score: 0.377704
Iteration 102, loss = 6927462.34311137
Validation score: 0.378079
Iteration 103, loss = 6917955.01781682
Validation score: 0.378778
Iteration 104, loss = 6914834.69681657
Validation score: 0.379508
Iteration 105, loss = 6907338.29121880
Validation score: 0.379897
Iteration 106, loss = 6901995.77418261
Validation score: 0.380433
Iteration 107, loss = 6895306.99727482
Validation score: 0.380941
Iteration 108, loss = 6890196.10241140
Validation score: 0.381089
Iteration 109, loss = 6883386.57598047
Validation score: 0.382155
Iteration 110, loss = 6877892.09414042
Validation score: 0.382479
Iteration 111, loss = 6873861.56903110
Validation score: 0.383134
Iteration 112, loss = 6866532.07478328
Validation score: 0.383547
Iteration 113, loss = 6860832.81692039
Validation score: 0.383923
Iteration 114, loss = 6856321.32050429
Validation score: 0.384289
Iteration 115, loss = 6849886.36898953
Validation score: 0.385161
Iteration 116, loss = 6844054.18713212
Validation score: 0.385624
Iteration 117, loss = 6839094.36775448
Validation score: 0.386377
Iteration 118, loss = 6833394.78175427
Validation score: 0.386646
Iteration 119, loss = 6826167.37659454
Validation score: 0.387198
Iteration 120, loss = 6820367.92849522
Validation score: 0.387902
Iteration 121, loss = 6815456.07331119
Validation score: 0.388220
Iteration 122, loss = 6808055.28337209
Validation score: 0.388518
Iteration 123, loss = 6803731.57029610
Validation score: 0.389192
Iteration 124, loss = 6798895.80464850
Validation score: 0.389571
Iteration 125, loss = 6792435.78564954
Validation score: 0.390250
Iteration 126, loss = 6785610.16219482
Validation score: 0.390798
Iteration 127, loss = 6780405.64876460
Validation score: 0.390820
Iteration 128, loss = 6776118.02890601
Validation score: 0.391701
Iteration 129, loss = 6770273.91995781
Validation score: 0.392342
Iteration 130, loss = 6763799.98309438
Validation score: 0.392612
Iteration 131, loss = 6758799.33345295
Validation score: 0.393176
Iteration 132, loss = 6753140.75050825
Validation score: 0.393904
Iteration 133, loss = 6746297.48377054
Validation score: 0.394365
Iteration 134, loss = 6741236.60642325
Validation score: 0.394814
Iteration 135, loss = 6735039.55126543
Validation score: 0.395093
Iteration 136, loss = 6729926.36875704
Validation score: 0.395660
Iteration 137, loss = 6724435.10839669
Validation score: 0.396057
Iteration 138, loss = 6718430.24703295
Validation score: 0.397056
Iteration 139, loss = 6711853.88980584
Validation score: 0.397250
Iteration 140, loss = 6706309.91792869
Validation score: 0.398039
Iteration 141, loss = 6700562.82817363
Validation score: 0.398640
Iteration 142, loss = 6693199.07723811
Validation score: 0.398778
Iteration 143, loss = 6688296.86384922
Validation score: 0.399721
Iteration 144, loss = 6682968.83851934
Validation score: 0.400030
Iteration 145, loss = 6677846.02327159
Validation score: 0.400770
Iteration 146, loss = 6671020.54191722
Validation score: 0.401390
Iteration 147, loss = 6665124.41634065
Validation score: 0.401716
Iteration 148, loss = 6659111.48217646
Validation score: 0.402272
Iteration 149, loss = 6653810.89991342
Validation score: 0.403072
Iteration 150, loss = 6647328.56188746
Validation score: 0.403416
Iteration 151, loss = 6642360.09236906
Validation score: 0.403820
Iteration 152, loss = 6637252.84245395
Validation score: 0.404521
Iteration 153, loss = 6630586.82359402
Validation score: 0.405150
Iteration 154, loss = 6624243.91747178
Validation score: 0.405544
Iteration 155, loss = 6620414.84462552
Validation score: 0.405734
Iteration 156, loss = 6612439.32764415
Validation score: 0.406475
Iteration 157, loss = 6607976.20636683
Validation score: 0.407152
Iteration 158, loss = 6601046.61017576
Validation score: 0.407674
Iteration 159, loss = 6595402.78176547
Validation score: 0.408270
Iteration 160, loss = 6590181.74542073
Validation score: 0.408725
Iteration 161, loss = 6584244.90286173
Validation score: 0.408894
Iteration 162, loss = 6578475.76755672
Validation score: 0.409929
Iteration 163, loss = 6572396.60941872
Validation score: 0.410194
Iteration 164, loss = 6566020.30029190
Validation score: 0.410459
Iteration 165, loss = 6560646.34077922
Validation score: 0.411475
Iteration 166, loss = 6553429.94841846
Validation score: 0.411580
Iteration 167, loss = 6548095.99941727
Validation score: 0.412145
Iteration 168, loss = 6541676.68306591
Validation score: 0.412810
Iteration 169, loss = 6537238.73419377
Validation score: 0.413598
Iteration 170, loss = 6530185.53311369
Validation score: 0.414009
Iteration 171, loss = 6526656.46520475
Validation score: 0.414585
Iteration 172, loss = 6519438.97040904
Validation score: 0.415152
Iteration 173, loss = 6514119.66481455
Validation score: 0.415903
Iteration 174, loss = 6507204.23571968
Validation score: 0.415973
Iteration 175, loss = 6502536.96896017
Validation score: 0.416735
Iteration 176, loss = 6496167.66953465
Validation score: 0.417208
Iteration 177, loss = 6491457.09022350
Validation score: 0.417557
Iteration 178, loss = 6483766.38430581
Validation score: 0.417964
Iteration 179, loss = 6478589.56197212
Validation score: 0.418418
Iteration 180, loss = 6473959.09321017
Validation score: 0.419343
Iteration 181, loss = 6466801.95062377
Validation score: 0.419830
Iteration 182, loss = 6461610.09440172
Validation score: 0.420448
Iteration 183, loss = 6456129.20090635
Validation score: 0.420880
Iteration 184, loss = 6450302.82124713
Validation score: 0.420989
Iteration 185, loss = 6446008.92287053
Validation score: 0.421809
Iteration 186, loss = 6440678.00319296
Validation score: 0.421883
Iteration 187, loss = 6434518.26478775
Validation score: 0.422692
Iteration 188, loss = 6428696.83747413
Validation score: 0.423261
Iteration 189, loss = 6425019.85158189
Validation score: 0.423500
Iteration 190, loss = 6416839.58029594
Validation score: 0.424089
Iteration 191, loss = 6412952.32814077
Validation score: 0.424625
Iteration 192, loss = 6406866.00070668
Validation score: 0.425527
Iteration 193, loss = 6402332.01893417
Validation score: 0.425319
Iteration 194, loss = 6396629.15722331
Validation score: 0.425839
Iteration 195, loss = 6390762.97042319
Validation score: 0.426521
Iteration 196, loss = 6385437.10004863
Validation score: 0.427075
Iteration 197, loss = 6380459.09980223
Validation score: 0.427423
Iteration 198, loss = 6375457.00583146
Validation score: 0.427900
Iteration 199, loss = 6370317.25657674
Validation score: 0.428489
Iteration 200, loss = 6364630.81835700
Validation score: 0.428486
Iteration 201, loss = 6359934.18512090
Validation score: 0.429242
Iteration 202, loss = 6353004.22292159
Validation score: 0.429828
Iteration 203, loss = 6349695.96004068
Validation score: 0.430178
Iteration 204, loss = 6343115.62119317
Validation score: 0.430819
Iteration 205, loss = 6338142.87279496
Validation score: 0.431186
Iteration 206, loss = 6332442.64818353
Validation score: 0.431808
Iteration 207, loss = 6327442.13203503
Validation score: 0.432217
Iteration 208, loss = 6323596.91472232
Validation score: 0.432692
Iteration 209, loss = 6318105.79316511
Validation score: 0.432475
Iteration 210, loss = 6313225.63863450
Validation score: 0.433344
Iteration 211, loss = 6307832.83988609
Validation score: 0.433905
Iteration 212, loss = 6304013.48437282
Validation score: 0.434287
Iteration 213, loss = 6298193.90749055
Validation score: 0.434961
Iteration 214, loss = 6294447.80244506
Validation score: 0.434948
Iteration 215, loss = 6288709.56366987
Validation score: 0.435667
Iteration 216, loss = 6285031.44831980
Validation score: 0.436032
Iteration 217, loss = 6279321.12866412
Validation score: 0.436290
Iteration 218, loss = 6276794.83984948
Validation score: 0.436515
Iteration 219, loss = 6268915.91818423
Validation score: 0.437155
Iteration 220, loss = 6264781.85190069
Validation score: 0.437099
Iteration 221, loss = 6260996.39256107
Validation score: 0.437969
Iteration 222, loss = 6255462.29545342
Validation score: 0.438583
Iteration 223, loss = 6251552.07953103
Validation score: 0.438699
Iteration 224, loss = 6248481.15995402
Validation score: 0.439134
Iteration 225, loss = 6242773.69013477
Validation score: 0.439576
Iteration 226, loss = 6239390.71349337
Validation score: 0.440004
Iteration 227, loss = 6233696.76736468
Validation score: 0.440628
Iteration 228, loss = 6228949.63859134
Validation score: 0.441187
Iteration 229, loss = 6224100.38715464
Validation score: 0.441467
Iteration 230, loss = 6220506.55913268
Validation score: 0.442056
Iteration 231, loss = 6215673.44865813
Validation score: 0.442406
Iteration 232, loss = 6209758.78332833
Validation score: 0.442510
Iteration 233, loss = 6205821.87497312
Validation score: 0.442761
Iteration 234, loss = 6202334.15188351
Validation score: 0.443211
Iteration 235, loss = 6197454.09177288
Validation score: 0.443676
Iteration 236, loss = 6194944.23791175
Validation score: 0.443348
Iteration 237, loss = 6190397.86540124
Validation score: 0.444275
Iteration 238, loss = 6186654.98275852
Validation score: 0.444705
Iteration 239, loss = 6181957.14528211
Validation score: 0.444961
Iteration 240, loss = 6177949.28715952
Validation score: 0.445631
Iteration 241, loss = 6172257.37409525
Validation score: 0.445627
Iteration 242, loss = 6166630.40582989
Validation score: 0.446081
Iteration 243, loss = 6165510.46239067
Validation score: 0.446642
Iteration 244, loss = 6159741.88811162
Validation score: 0.447026
Iteration 245, loss = 6155072.16538035
Validation score: 0.446965
Iteration 246, loss = 6153694.09389428
Validation score: 0.447439
Iteration 247, loss = 6148146.76891357
Validation score: 0.448103
Iteration 248, loss = 6145045.71109828
Validation score: 0.448269
Iteration 249, loss = 6139914.80335973
Validation score: 0.448428
Iteration 250, loss = 6135137.49958165
Validation score: 0.448903
Iteration 251, loss = 6132817.51412890
Validation score: 0.449444
Iteration 252, loss = 6128542.42291306
Validation score: 0.449893
Iteration 253, loss = 6123972.69820178
Validation score: 0.449972
Iteration 254, loss = 6121556.44270904
Validation score: 0.450053
Iteration 255, loss = 6117888.86582672
Validation score: 0.450623
Iteration 256, loss = 6113755.42158409
Validation score: 0.450793
Iteration 257, loss = 6110310.91902793
Validation score: 0.451011
Iteration 258, loss = 6105890.51459226
Validation score: 0.451604
Iteration 259, loss = 6100773.22217530
Validation score: 0.451870
Iteration 260, loss = 6098875.72685680
Validation score: 0.452271
Iteration 261, loss = 6094246.10418064
Validation score: 0.452571
Iteration 262, loss = 6089512.36481558
Validation score: 0.452903
Iteration 263, loss = 6087181.09025011
Validation score: 0.453023
Iteration 264, loss = 6083337.95854874
Validation score: 0.453561
Iteration 265, loss = 6080526.41570707
Validation score: 0.454110
Iteration 266, loss = 6075330.18909508
Validation score: 0.454457
Iteration 267, loss = 6071954.41852543
Validation score: 0.454399
Iteration 268, loss = 6069271.25433377
Validation score: 0.454772
Iteration 269, loss = 6065243.62957739
Validation score: 0.455106
Iteration 270, loss = 6060436.27894061
Validation score: 0.455559
Iteration 271, loss = 6056449.71235604
Validation score: 0.455769
Iteration 272, loss = 6054379.75622130
Validation score: 0.455892
Iteration 273, loss = 6051106.01061323
Validation score: 0.456297
Iteration 274, loss = 6047147.61154780
Validation score: 0.456494
Iteration 275, loss = 6043597.09885625
Validation score: 0.457039
Iteration 276, loss = 6040418.87700824
Validation score: 0.457379
Iteration 277, loss = 6036567.62687549
Validation score: 0.457639
Iteration 278, loss = 6032793.64226640
Validation score: 0.457731
Iteration 279, loss = 6029340.49400710
Validation score: 0.458066
Iteration 280, loss = 6026414.45271609
Validation score: 0.458485
Iteration 281, loss = 6022488.55095969
Validation score: 0.458696
Iteration 282, loss = 6019447.47330432
Validation score: 0.458928
Iteration 283, loss = 6015687.47334751
Validation score: 0.459257
Iteration 284, loss = 6011455.40258894
Validation score: 0.459484
Iteration 285, loss = 6009105.63736498
Validation score: 0.459793
Iteration 286, loss = 6008055.69823712
Validation score: 0.459988
Iteration 287, loss = 6000138.20751978
Validation score: 0.460131
Iteration 288, loss = 5998402.24475620
Validation score: 0.460942
Iteration 289, loss = 5994673.96193210
Validation score: 0.460788
Iteration 290, loss = 5991330.01959496
Validation score: 0.461051
Iteration 291, loss = 5986971.81889468
Validation score: 0.461317
Iteration 292, loss = 5984137.13031785
Validation score: 0.461917
Iteration 293, loss = 5980711.48037141
Validation score: 0.461987
Iteration 294, loss = 5976788.70154717
Validation score: 0.462464
Iteration 295, loss = 5973897.87832189
Validation score: 0.462596
Iteration 296, loss = 5971398.87062056
Validation score: 0.462939
Iteration 297, loss = 5967482.03453906
Validation score: 0.463419
Iteration 298, loss = 5963192.12557458
Validation score: 0.463406
Iteration 299, loss = 5959765.15352387
Validation score: 0.463811
Iteration 300, loss = 5955355.53091164
Validation score: 0.463948
Iteration 301, loss = 5953449.02821578
Validation score: 0.464598
Iteration 302, loss = 5948476.99413987
Validation score: 0.464674
Iteration 303, loss = 5946203.53462147
Validation score: 0.465098
Iteration 304, loss = 5941625.33311040

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 59720094.82837289
Validation score: -8.057110
Iteration 2, loss = 58426097.38610099
Validation score: -7.729972
Iteration 3, loss = 55440195.69688635
Validation score: -7.151093
Iteration 4, loss = 50972918.47013802
Validation score: -6.375271
Iteration 5, loss = 45424540.01031194
Validation score: -5.472425
Iteration 6, loss = 39257595.58113284
Validation score: -4.512306
Iteration 7, loss = 32968906.05869914
Validation score: -3.573501
Iteration 8, loss = 26967338.60440079
Validation score: -2.697114
Iteration 9, loss = 21572994.59291694
Validation score: -1.938556
Iteration 10, loss = 17003720.97395921
Validation score: -1.314438
Iteration 11, loss = 13334310.24512372
Validation score: -0.827652
Iteration 12, loss = 10566137.65220692
Validation score: -0.473100
Iteration 13, loss = 8607174.75095417
Validation score: -0.231696
Iteration 14, loss = 7297682.06690289
Validation score: -0.072901
Iteration 15, loss = 6452162.58494377
Validation score: 0.027376
Iteration 16, loss = 5912741.17640844
Validation score: 0.093229
Iteration 17, loss = 5550540.11009599
Validation score: 0.139885
Iteration 18, loss = 5278586.65749983
Validation score: 0.177058
Iteration 19, loss = 5050364.76361808
Validation score: 0.209251
Iteration 20, loss = 4849640.87416952
Validation score: 0.238133
Iteration 21, loss = 4668116.22201628
Validation score: 0.264776
Iteration 22, loss = 4503813.68265792
Validation score: 0.288884
Iteration 23, loss = 4355898.75802144
Validation score: 0.310441
Iteration 24, loss = 4222568.39263135
Validation score: 0.330246
Iteration 25, loss = 4103045.49925609
Validation score: 0.347401
Iteration 26, loss = 3996088.40453860
Validation score: 0.363059
Iteration 27, loss = 3901593.36435988
Validation score: 0.376873
Iteration 28, loss = 3818569.16972894
Validation score: 0.388869
Iteration 29, loss = 3746508.45980228
Validation score: 0.399725
Iteration 30, loss = 3680967.16419264
Validation score: 0.409077
Iteration 31, loss = 3625277.20582268
Validation score: 0.417303
Iteration 32, loss = 3574250.61272467
Validation score: 0.424712
Iteration 33, loss = 3529193.59048500
Validation score: 0.431256
Iteration 34, loss = 3490177.66542640
Validation score: 0.437201
Iteration 35, loss = 3456001.03092081
Validation score: 0.442266
Iteration 36, loss = 3424062.73522869
Validation score: 0.446856
Iteration 37, loss = 3395915.89101353
Validation score: 0.450911
Iteration 38, loss = 3371947.03705823
Validation score: 0.454628
Iteration 39, loss = 3348738.45808081
Validation score: 0.457967
Iteration 40, loss = 3327184.80641066
Validation score: 0.460768
Iteration 41, loss = 3309131.00088877
Validation score: 0.463548
Iteration 42, loss = 3291987.48994075
Validation score: 0.466481
Iteration 43, loss = 3276796.94412170
Validation score: 0.468476
Iteration 44, loss = 3263020.70483270
Validation score: 0.470801
Iteration 45, loss = 3250521.57004415
Validation score: 0.472672
Iteration 46, loss = 3239090.44344580
Validation score: 0.474429
Iteration 47, loss = 3227684.42303155
Validation score: 0.476283
Iteration 48, loss = 3219264.23432554
Validation score: 0.477457
Iteration 49, loss = 3208528.94891992
Validation score: 0.479279
Iteration 50, loss = 3201123.40483031
Validation score: 0.480668
Iteration 51, loss = 3192407.85983079
Validation score: 0.481733
Iteration 52, loss = 3186244.91149518
Validation score: 0.482613
Iteration 53, loss = 3179015.44946108
Validation score: 0.484199
Iteration 54, loss = 3172694.94109183
Validation score: 0.484836
Iteration 55, loss = 3167304.30753740
Validation score: 0.485765
Iteration 56, loss = 3161763.72269437
Validation score: 0.486756
Iteration 57, loss = 3156180.80796778
Validation score: 0.487660
Iteration 58, loss = 3151077.38813760
Validation score: 0.488677
Iteration 59, loss = 3146957.55632213
Validation score: 0.488858
Iteration 60, loss = 3143666.02795397
Validation score: 0.490051
Iteration 61, loss = 3138428.69276108
Validation score: 0.490937
Iteration 62, loss = 3133632.84288813
Validation score: 0.491376
Iteration 63, loss = 3130133.21864528
Validation score: 0.492409
Iteration 64, loss = 3126122.14355385
Validation score: 0.493126
Iteration 65, loss = 3121663.11051790
Validation score: 0.493490
Iteration 66, loss = 3119052.03550745
Validation score: 0.493808
Iteration 67, loss = 3114570.34936391
Validation score: 0.494884
Iteration 68, loss = 3111648.38685983
Validation score: 0.495368
Iteration 69, loss = 3108611.09687434
Validation score: 0.496032
Iteration 70, loss = 3104713.48052139
Validation score: 0.496593
Iteration 71, loss = 3102255.38721845
Validation score: 0.496722
Iteration 72, loss = 3098242.00848806
Validation score: 0.497819
Iteration 73, loss = 3096127.33793099
Validation score: 0.498374
Iteration 74, loss = 3092940.62318405
Validation score: 0.498854
Iteration 75, loss = 3089747.42898558
Validation score: 0.499190
Iteration 76, loss = 3086347.40990828
Validation score: 0.499767
Iteration 77, loss = 3083713.09439580
Validation score: 0.500404
Iteration 78, loss = 3082214.83580398
Validation score: 0.500983
Iteration 79, loss = 3079816.85675391
Validation score: 0.501151
Iteration 80, loss = 3075572.21731354
Validation score: 0.501724
Iteration 81, loss = 3072932.64454780
Validation score: 0.502321
Iteration 82, loss = 3071523.13119813
Validation score: 0.502736
Iteration 83, loss = 3068129.44635567
Validation score: 0.503252
Iteration 84, loss = 3065141.28926068
Validation score: 0.503254
Iteration 85, loss = 3063414.49884316
Validation score: 0.503935
Iteration 86, loss = 3059707.23608428
Validation score: 0.504316
Iteration 87, loss = 3057009.30780679
Validation score: 0.505082
Iteration 88, loss = 3054902.03617425
Validation score: 0.505240
Iteration 89, loss = 3052942.87291830
Validation score: 0.506057
Iteration 90, loss = 3049571.53755933
Validation score: 0.506345
Iteration 91, loss = 3047701.58397259
Validation score: 0.506567
Iteration 92, loss = 3046146.09515502
Validation score: 0.507093
Iteration 93, loss = 3043782.34310854
Validation score: 0.507524
Iteration 94, loss = 3041771.78678980
Validation score: 0.508092
Iteration 95, loss = 3038527.51476781
Validation score: 0.508465
Iteration 96, loss = 3036781.20865074
Validation score: 0.508814
Iteration 97, loss = 3033597.29839883
Validation score: 0.509298
Iteration 98, loss = 3032265.38829595
Validation score: 0.509301
Iteration 99, loss = 3029466.23723790
Validation score: 0.509944
Iteration 100, loss = 3027669.93896139
Validation score: 0.510551
Iteration 101, loss = 3025194.34562934
Validation score: 0.510728
Iteration 102, loss = 3022935.97989614
Validation score: 0.511255
Iteration 103, loss = 3019518.85431465
Validation score: 0.511165
Iteration 104, loss = 3017915.58291155
Validation score: 0.511691
Iteration 105, loss = 3016265.85857749
Validation score: 0.512274
Iteration 106, loss = 3014320.95961400
Validation score: 0.512319
Iteration 107, loss = 3010754.71987425
Validation score: 0.512858
Iteration 108, loss = 3009661.49321745
Validation score: 0.513202
Iteration 109, loss = 3007242.95399766
Validation score: 0.513446
Iteration 110, loss = 3004660.52604881
Validation score: 0.513776
Iteration 111, loss = 3002548.55180794
Validation score: 0.514135
Iteration 112, loss = 3000558.77706498
Validation score: 0.514132
Iteration 113, loss = 2998535.16348800
Validation score: 0.514490
Iteration 114, loss = 2997498.96007485
Validation score: 0.515176
Iteration 115, loss = 2995442.59629041
Validation score: 0.515334
Iteration 116, loss = 2992497.24759945
Validation score: 0.515987
Iteration 117, loss = 2991270.22147423
Validation score: 0.516237
Iteration 118, loss = 2988177.68831713
Validation score: 0.516537
Iteration 119, loss = 2987239.82883789
Validation score: 0.516707
Iteration 120, loss = 2984895.18800535
Validation score: 0.516974
Iteration 121, loss = 2982034.26845736
Validation score: 0.517434
Iteration 122, loss = 2981000.46142213
Validation score: 0.517717
Iteration 123, loss = 2980240.97698028
Validation score: 0.517717
Iteration 124, loss = 2977286.76509315
Validation score: 0.518356
Iteration 125, loss = 2975875.72260742
Validation score: 0.518381
Iteration 126, loss = 2972356.33814319
Validation score: 0.518856
Iteration 127, loss = 2970656.36831255
Validation score: 0.519215
Iteration 128, loss = 2968672.56206479
Validation score: 0.519343
Iteration 129, loss = 2967771.05131694
Validation score: 0.519670
Iteration 130, loss = 2965804.27852686
Validation score: 0.519935
Iteration 131, loss = 2963837.32936442
Validation score: 0.519958
Iteration 132, loss = 2961292.56886351
Validation score: 0.520706
Iteration 133, loss = 2960392.51842515
Validation score: 0.520866
Iteration 134, loss = 2957204.13168219
Validation score: 0.521170
Iteration 135, loss = 2956841.93280178
Validation score: 0.521508
Iteration 136, loss = 2952986.25141143
Validation score: 0.521656
Iteration 137, loss = 2952047.98240728
Validation score: 0.521878
Iteration 138, loss = 2951743.28432500
Validation score: 0.522266
Iteration 139, loss = 2948200.83576721
Validation score: 0.522586
Iteration 140, loss = 2946317.54762227
Validation score: 0.522479
Iteration 141, loss = 2946441.85064972
Validation score: 0.523133
Iteration 142, loss = 2943048.43278499
Validation score: 0.523318
Iteration 143, loss = 2940495.17478117
Validation score: 0.523352
Iteration 144, loss = 2939863.13133297
Validation score: 0.523615
Iteration 145, loss = 2937085.97918935
Validation score: 0.524182
Iteration 146, loss = 2936211.98933277
Validation score: 0.523993
Iteration 147, loss = 2934462.05745918
Validation score: 0.524622
Iteration 148, loss = 2931403.37546378
Validation score: 0.524714
Iteration 149, loss = 2931077.82285434
Validation score: 0.525060
Iteration 150, loss = 2928708.57381044
Validation score: 0.525319
Iteration 151, loss = 2926586.35984529
Validation score: 0.525414
Iteration 152, loss = 2925016.40168774
Validation score: 0.526129
Iteration 153, loss = 2923296.75032297
Validation score: 0.526327
Iteration 154, loss = 2923047.39979522
Validation score: 0.526400
Iteration 155, loss = 2920525.68322679
Validation score: 0.526859
Iteration 156, loss = 2919578.80220207
Validation score: 0.527046
Iteration 157, loss = 2917054.06959605
Validation score: 0.527375
Iteration 158, loss = 2914020.86006388
Validation score: 0.527413
Iteration 159, loss = 2914601.47008751
Validation score: 0.527915
Iteration 160, loss = 2911346.58650902
Validation score: 0.527958
Iteration 161, loss = 2908885.67642808
Validation score: 0.528345
Iteration 162, loss = 2908327.79687221
Validation score: 0.528508
Iteration 163, loss = 2906903.27625198
Validation score: 0.528793
Iteration 164, loss = 2904334.77810940
Validation score: 0.528765
Iteration 165, loss = 2903778.87567786
Validation score: 0.529125
Iteration 166, loss = 2901239.17794236
Validation score: 0.528846
Iteration 167, loss = 2901066.25373043
Validation score: 0.529508
Iteration 168, loss = 2898093.11701625
Validation score: 0.530047
Iteration 169, loss = 2897349.31967137
Validation score: 0.530260
Iteration 170, loss = 2895217.76162442
Validation score: 0.530318
Iteration 171, loss = 2892914.98899755
Validation score: 0.530800
Iteration 172, loss = 2890377.03571417
Validation score: 0.530924
Iteration 173, loss = 2889784.04641046
Validation score: 0.531074
Iteration 174, loss = 2888493.41726262
Validation score: 0.531030
Iteration 175, loss = 2887093.16101925
Validation score: 0.531686
Iteration 176, loss = 2884866.54177508
Validation score: 0.531606
Iteration 177, loss = 2883766.22773310
Validation score: 0.532013
Iteration 178, loss = 2882325.53671720
Validation score: 0.532301
Iteration 179, loss = 2879146.55840349
Validation score: 0.532585
Iteration 180, loss = 2878218.66932407
Validation score: 0.532870
Iteration 181, loss = 2877871.56381009
Validation score: 0.532995
Iteration 182, loss = 2875574.83360028
Validation score: 0.533063
Iteration 183, loss = 2875530.04373523
Validation score: 0.533013
Iteration 184, loss = 2872995.68345202
Validation score: 0.533678
Iteration 185, loss = 2870633.17191161
Validation score: 0.533982
Iteration 186, loss = 2868438.11857476
Validation score: 0.533493
Iteration 187, loss = 2867907.56495329
Validation score: 0.534552
Iteration 188, loss = 2868030.06402878
Validation score: 0.534557
Iteration 189, loss = 2863186.95875775
Validation score: 0.534937
Iteration 190, loss = 2863767.33934451
Validation score: 0.534955
Iteration 191, loss = 2862809.36204945
Validation score: 0.535312
Iteration 192, loss = 2860592.20683495
Validation score: 0.535604
Iteration 193, loss = 2859054.15409465
Validation score: 0.535839
Iteration 194, loss = 2856080.18224545
Validation score: 0.535978
Iteration 195, loss = 2855881.48650176
Validation score: 0.536150
Iteration 196, loss = 2853012.19631398
Validation score: 0.536210
Iteration 197, loss = 2852068.19015773
Validation score: 0.536659
Iteration 198, loss = 2851040.43921435
Validation score: 0.536803
Iteration 199, loss = 2849217.42260371
Validation score: 0.536719
Iteration 200, loss = 2848160.36898585
Validation score: 0.537168
Iteration 201, loss = 2845806.56495425
Validation score: 0.537482
Iteration 202, loss = 2845112.81589366
Validation score: 0.537767
Iteration 203, loss = 2843689.36470095
Validation score: 0.538051
Iteration 204, loss = 2842598.13733774
Validation score: 0.538186
Iteration 205, loss = 2839783.24314576
Validation score: 0.538465
Iteration 206, loss = 2838634.84360519
Validation score: 0.538539
Iteration 207, loss = 2836943.55113245
Validation score: 0.538825
Iteration 208, loss = 2835241.40382350
Validation score: 0.539068
Iteration 209, loss = 2834728.26524481
Validation score: 0.539347
Iteration 210, loss = 2832686.05868959
Validation score: 0.539489
Iteration 211, loss = 2831471.75890199
Validation score: 0.539488
Iteration 212, loss = 2829518.27756376
Validation score: 0.539614
Iteration 213, loss = 2828120.23238160
Validation score: 0.539931
Iteration 214, loss = 2827389.45113012
Validation score: 0.540438
Iteration 215, loss = 2826165.48781282
Validation score: 0.540620
Iteration 216, loss = 2823666.08860172
Validation score: 0.540881
Iteration 217, loss = 2823375.56407606
Validation score: 0.541108
Iteration 218, loss = 2820424.15427253
Validation score: 0.541123
Iteration 219, loss = 2820311.91715813
Validation score: 0.541583
Iteration 220, loss = 2817610.22348649
Validation score: 0.541659
Iteration 221, loss = 2815938.05755312
Validation score: 0.542173
Iteration 222, loss = 2814567.19773243
Validation score: 0.542395
Iteration 223, loss = 2813362.70129015
Validation score: 0.542351
Iteration 224, loss = 2812401.02352245
Validation score: 0.542596
Iteration 225, loss = 2810877.12318200
Validation score: 0.542902
Iteration 226, loss = 2809083.01038498
Validation score: 0.543139
Iteration 227, loss = 2808192.68368362
Validation score: 0.543294
Iteration 228, loss = 2806179.31749550
Validation score: 0.543403
Iteration 229, loss = 2803977.16779392
Validation score: 0.543712
Iteration 230, loss = 2803028.12622711
Validation score: 0.543924
Iteration 231, loss = 2800878.76622410
Validation score: 0.544319
Iteration 232, loss = 2799291.81833145
Validation score: 0.544217
Iteration 233, loss = 2797575.57031337
Validation score: 0.544666
Iteration 234, loss = 2797156.34414671
Validation score: 0.544865
Iteration 235, loss = 2794063.31685529
Validation score: 0.545163
Iteration 236, loss = 2792739.01777189
Validation score: 0.545528
Iteration 237, loss = 2791128.93978191
Validation score: 0.545660
Iteration 238, loss = 2789847.99498868
Validation score: 0.545870
Iteration 239, loss = 2788666.62324692
Validation score: 0.546162
Iteration 240, loss = 2787192.00509390
Validation score: 0.545860
Iteration 241, loss = 2786523.43126405
Validation score: 0.546475
Iteration 242, loss = 2783365.56689353
Validation score: 0.546657
Iteration 243, loss = 2781739.64357726
Validation score: 0.546994
Iteration 244, loss = 2780313.17768905
Validation score: 0.547414
Iteration 245, loss = 2779226.22566390
Validation score: 0.547499
Iteration 246, loss = 2778409.05444146
Validation score: 0.547945
Iteration 247, loss = 2776229.70109509
Validation score: 0.548174
Iteration 248, loss = 2775563.09581541
Validation score: 0.548273
Iteration 249, loss = 2772199.71741327
Validation score: 0.548800
Iteration 250, loss = 2771357.96323302
Validation score: 0.548713
Iteration 251, loss = 2769547.10341787
Validation score: 0.548542
Iteration 252, loss = 2768534.95629086
Validation score: 0.549240
Iteration 253, loss = 2766227.95430678
Validation score: 0.549212
Iteration 254, loss = 2764299.42804072
Validation score: 0.549899
Iteration 255, loss = 2763525.71440246
Validation score: 0.549940
Iteration 256, loss = 2761617.63314681
Validation score: 0.550105
Iteration 257, loss = 2759542.61521594
Validation score: 0.550268
Iteration 258, loss = 2758705.55668567
Validation score: 0.550795
Iteration 259, loss = 2756423.97425407
Validation score: 0.551075
Iteration 260, loss = 2754453.59277024
Validation score: 0.550976
Iteration 261, loss = 2754053.64093713
Validation score: 0.551445
Iteration 262, loss = 2754024.68379557
Validation score: 0.551571
Iteration 263, loss = 2750646.45730429
Validation score: 0.551826
Iteration 264, loss = 2749398.94739120
Validation score: 0.552084
Iteration 265, loss = 2747675.30842474
Validation score: 0.552449
Iteration 266, loss = 2745676.63161311
Validation score: 0.552820
Iteration 267, loss = 2743890.56310870
Validation score: 0.552741
Iteration 268, loss = 2742108.29630359
Validation score: 0.553118
Iteration 269, loss = 2742796.96549109
Validation score: 0.553424
Iteration 270, loss = 2738314.07258396
Validation score: 0.553689
Iteration 271, loss = 2737133.58639195
Validation score: 0.553950
Iteration 272, loss = 2735577.10462104
Validation score: 0.554101
Iteration 273, loss = 2733997.73234191
Validation score: 0.554453
Iteration 274, loss = 2733860.50915213
Validation score: 0.554479
Iteration 275, loss = 2731349.04008512
Validation score: 0.554935
Iteration 276, loss = 2730148.15669027
Validation score: 0.555199
Iteration 277, loss = 2728049.88571162
Validation score: 0.555330
Iteration 278, loss = 2728444.13753730
Validation score: 0.555644
Iteration 279, loss = 2725255.91411621
Validation score: 0.555877
Iteration 280, loss = 2723410.65185491
Validation score: 0.556172
Iteration 281, loss = 2722845.45973513
Validation score: 0.556134
Iteration 282, loss = 2720179.88896055
Validation score: 0.556210
Iteration 283, loss = 2718567.90713514
Validation score: 0.556848
Iteration 284, loss = 2715733.74488556
Validation score: 0.556607
Iteration 285, loss = 2715229.66333566
Validation score: 0.557287
Iteration 286, loss = 2713787.55824523
Validation score: 0.557197
Iteration 287, loss = 2712081.93036908
Validation score: 0.557540
Iteration 288, loss = 2711847.26740006
Validation score: 0.557760
Iteration 289, loss = 2710076.57017623
Validation score: 0.558193
Iteration 290, loss = 2708745.67960001
Validation score: 0.558494
Iteration 291, loss = 2706233.50782457
Validation score: 0.558265
Iteration 292, loss = 2705386.53759500
Validation score: 0.558741
Iteration 293, loss = 2702738.51597550
Validation score: 0.558844
Iteration 294, loss = 2701948.25551708
Validation score: 0.559124
Iteration 295, loss = 2700497.97702518
Validation score: 0.559534
Iteration 296, loss = 2698886.72290647
Validation score: 0.559676
Iteration 297, loss = 2698522.70942020
Validation score: 0.559898
Iteration 298, loss = 2695718.40085988
Validation score: 0.559988
Iteration 299, loss = 2694439.11620665
Validation score: 0.560305
Iteration 300, loss = 2692970.20995685
Validation score: 0.560487
Iteration 301, loss = 2692111.59698160
Validation score: 0.560649
Iteration 302, loss = 2690902.40352290
Validation score: 0.560827
Iteration 303, loss = 2688714.80093104
Validation score: 0.561033
Iteration 304, loss = 2687331.14200847
Validation score: 0.561471

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 2, loss = 97873698.51812124
Validation score: -3.894874
Iteration 3, loss = 97105746.90017499
Validation score: -3.842506
Iteration 4, loss = 95787015.43038695
Validation score: -3.762135
Iteration 5, loss = 93925014.03206630
Validation score: -3.655446
Iteration 6, loss = 91548253.67033295
Validation score: -3.524547
Iteration 7, loss = 88724563.22997545
Validation score: -3.372256
Iteration 8, loss = 85511248.92939383
Validation score: -3.201420
Iteration 9, loss = 81955918.27040510
Validation score: -3.017714
Iteration 10, loss = 78111701.37506971
Validation score: -2.817980
Iteration 11, loss = 74068317.34784649
Validation score: -2.610834
Iteration 12, loss = 69872678.08748966
Validation score: -2.396828
Iteration 13, loss = 65583971.71248122
Validation score: -2.181732
Iteration 14, loss = 61279753.13650904
Validation score: -1.965018
Iteration 15, loss = 56995178.30916391
Validation score: -1.750470
Iteration 16, loss = 52810998.50304195
Validation score: -1.543042
Iteration 17, loss = 48721059.97752895
Validation score: -1.340949
Iteration 18, loss = 44819932.78199624
Validation score: -1.148650
Iteration 19, loss = 41138658.18528792
Validation score: -0.969044
Iteration 20, loss = 37694046.33145434
Validation score: -0.801008
Iteration 21, loss = 34484357.04196218
Validation score: -0.646084
Iteration 22, loss = 31504288.51170722
Validation score: -0.498500
Iteration 23, loss = 28791407.67546291
Validation score: -0.369173
Iteration 24, loss = 26410578.05080181
Validation score: -0.253866
Iteration 25, loss = 24272209.69456805
Validation score: -0.151398
Iteration 26, loss = 22394027.47823346
Validation score: -0.060536
Iteration 27, loss = 20738359.16505906
Validation score: 0.019467
Iteration 28, loss = 19286856.75231505
Validation score: 0.089555
Iteration 29, loss = 18013723.45254544
Validation score: 0.151512
Iteration 30, loss = 16911857.85005185
Validation score: 0.204942
Iteration 31, loss = 15947287.14258514
Validation score: 0.251715
Iteration 32, loss = 15103565.25365798
Validation score: 0.293895
Iteration 33, loss = 14365285.53288667
Validation score: 0.330554
Iteration 34, loss = 13713230.35539521
Validation score: 0.363843
Iteration 35, loss = 13130027.28395154
Validation score: 0.391987
Iteration 36, loss = 12612033.17736739
Validation score: 0.419566
Iteration 37, loss = 12148297.31906906
Validation score: 0.442485
Iteration 38, loss = 11735104.88772412
Validation score: 0.463249
Iteration 39, loss = 11359688.17683903
Validation score: 0.483100
Iteration 40, loss = 11008355.84918586
Validation score: 0.501774
Iteration 41, loss = 10696629.16042082
Validation score: 0.517295
Iteration 42, loss = 10422136.86253924
Validation score: 0.532415
Iteration 43, loss = 10156848.43690450
Validation score: 0.545531
Iteration 44, loss = 9922006.46304339
Validation score: 0.558399
Iteration 45, loss = 9701021.17074540
Validation score: 0.569897
Iteration 46, loss = 9497936.37325632
Validation score: 0.580565
Iteration 47, loss = 9310408.87699303
Validation score: 0.590809
Iteration 48, loss = 9134541.08265695
Validation score: 0.599817
Iteration 49, loss = 8976862.77779215
Validation score: 0.608337
Iteration 50, loss = 8831794.42032602
Validation score: 0.616152
Iteration 51, loss = 8694913.50543903
Validation score: 0.623059
Iteration 52, loss = 8560941.25578982
Validation score: 0.630356
Iteration 53, loss = 8442430.74435031
Validation score: 0.637007
Iteration 54, loss = 8329329.32265431
Validation score: 0.642846
Iteration 55, loss = 8226753.33323119
Validation score: 0.648658
Iteration 56, loss = 8126928.19258445
Validation score: 0.653712
Iteration 57, loss = 8035510.61290372
Validation score: 0.658379
Iteration 58, loss = 7951241.58773669
Validation score: 0.663159
Iteration 59, loss = 7868712.73218864
Validation score: 0.667451
Iteration 60, loss = 7792066.72618181
Validation score: 0.671318
Iteration 61, loss = 7719494.35369309
Validation score: 0.675466
Iteration 62, loss = 7649125.40790290
Validation score: 0.679047
Iteration 63, loss = 7580982.92918099
Validation score: 0.682938
Iteration 64, loss = 7515645.72865811
Validation score: 0.686279
Iteration 65, loss = 7453975.90353776
Validation score: 0.689717
Iteration 66, loss = 7396268.48968048
Validation score: 0.692402
Iteration 67, loss = 7341467.46941392
Validation score: 0.695231
Iteration 68, loss = 7284833.04786332
Validation score: 0.698459
Iteration 69, loss = 7236004.26558466
Validation score: 0.701258
Iteration 70, loss = 7186252.84540410
Validation score: 0.703743
Iteration 71, loss = 7141016.92712153
Validation score: 0.706218
Iteration 72, loss = 7096018.05559099
Validation score: 0.708244
Iteration 73, loss = 7053418.69306130
Validation score: 0.710198
Iteration 74, loss = 7015708.53805735
Validation score: 0.712596
Iteration 75, loss = 6974396.06277439
Validation score: 0.714290
Iteration 76, loss = 6936976.46777571
Validation score: 0.716155
Iteration 77, loss = 6898531.04213375
Validation score: 0.718004
Iteration 78, loss = 6864948.68448054
Validation score: 0.719843
Iteration 79, loss = 6832330.62317003
Validation score: 0.721579
Iteration 80, loss = 6798731.29912236
Validation score: 0.723063
Iteration 81, loss = 6769631.65922192
Validation score: 0.724735
Iteration 82, loss = 6739669.25565912
Validation score: 0.725735
Iteration 83, loss = 6715186.52559788
Validation score: 0.727109
Iteration 84, loss = 6687285.99692027
Validation score: 0.728503
Iteration 85, loss = 6660088.54633820
Validation score: 0.729885
Iteration 86, loss = 6633136.70264241
Validation score: 0.731218
Iteration 87, loss = 6610783.53553297
Validation score: 0.732299
Iteration 88, loss = 6585595.88247780
Validation score: 0.733500
Iteration 89, loss = 6561825.09762046
Validation score: 0.734538
Iteration 90, loss = 6539462.88701071
Validation score: 0.735534
Iteration 91, loss = 6517192.21263909
Validation score: 0.736835
Iteration 92, loss = 6497371.62355354
Validation score: 0.737909
Iteration 93, loss = 6477953.34129865
Validation score: 0.738502
Iteration 94, loss = 6459639.68203793
Validation score: 0.739325
Iteration 95, loss = 6441733.29166075
Validation score: 0.740254
Iteration 96, loss = 6423786.63857105
Validation score: 0.741009
Iteration 97, loss = 6408546.32418435
Validation score: 0.741993
Iteration 98, loss = 6391656.47641765
Validation score: 0.742550
Iteration 99, loss = 6375022.62690969
Validation score: 0.743231
Iteration 100, loss = 6359982.86364669
Validation score: 0.744093
Iteration 101, loss = 6347823.68502468
Validation score: 0.744832
Iteration 102, loss = 6332565.92375082
Validation score: 0.745276
Iteration 103, loss = 6315637.04391827
Validation score: 0.745983
Iteration 104, loss = 6302953.64602223
Validation score: 0.746441
Iteration 105, loss = 6287769.98361647
Validation score: 0.747162
Iteration 106, loss = 6275572.01520963
Validation score: 0.748046
Iteration 107, loss = 6263111.32892195
Validation score: 0.748548
Iteration 108, loss = 6250487.63575522
Validation score: 0.749057
Iteration 109, loss = 6238743.79569798
Validation score: 0.749477
Iteration 110, loss = 6227928.19998009
Validation score: 0.750019
Iteration 111, loss = 6213833.04815771
Validation score: 0.750657
Iteration 112, loss = 6202653.59335800
Validation score: 0.751305
Iteration 113, loss = 6191678.51620888
Validation score: 0.751789
Iteration 114, loss = 6180601.99303519
Validation score: 0.752481
Iteration 115, loss = 6169923.28204585
Validation score: 0.752859
Iteration 116, loss = 6159487.97469280
Validation score: 0.753273
Iteration 117, loss = 6149989.75104274
Validation score: 0.753768
Iteration 118, loss = 6138864.66018473
Validation score: 0.754389
Iteration 119, loss = 6131034.24924773
Validation score: 0.754805
Iteration 120, loss = 6120177.26594054
Validation score: 0.755038
Iteration 121, loss = 6110696.92233510
Validation score: 0.755591
Iteration 122, loss = 6103419.71228490
Validation score: 0.755939
Iteration 123, loss = 6093515.60109404
Validation score: 0.756211
Iteration 124, loss = 6085100.07924238
Validation score: 0.756662
Iteration 125, loss = 6075175.89024847
Validation score: 0.757064
Iteration 126, loss = 6067908.91233176
Validation score: 0.757300
Iteration 127, loss = 6059745.56708092
Validation score: 0.757900
Iteration 128, loss = 6049799.60740788
Validation score: 0.758251
Iteration 129, loss = 6044543.44214086
Validation score: 0.758451
Iteration 130, loss = 6033772.31215225
Validation score: 0.758721
Iteration 131, loss = 6025553.75680077
Validation score: 0.759062
Iteration 132, loss = 6019244.04590170
Validation score: 0.759320
Iteration 133, loss = 6012015.54927887
Validation score: 0.759624
Iteration 134, loss = 6003241.94512003
Validation score: 0.760087
Iteration 135, loss = 5995350.50316251
Validation score: 0.760396
Iteration 136, loss = 5988381.31292446
Validation score: 0.760787
Iteration 137, loss = 5979488.13581555
Validation score: 0.761038
Iteration 138, loss = 5973910.21804743
Validation score: 0.761445
Iteration 139, loss = 5967909.97600287
Validation score: 0.761737
Iteration 140, loss = 5957937.89176424
Validation score: 0.762234
Iteration 141, loss = 5951112.51474244
Validation score: 0.762471
Iteration 142, loss = 5945175.95305633
Validation score: 0.762622
Iteration 143, loss = 5937116.70630269
Validation score: 0.763100
Iteration 144, loss = 5930891.48643681
Validation score: 0.763305
Iteration 145, loss = 5921009.42027965
Validation score: 0.763606
Iteration 146, loss = 5915283.70794881
Validation score: 0.763951
Iteration 147, loss = 5908466.53813715
Validation score: 0.764312
Iteration 148, loss = 5900905.32446777
Validation score: 0.764550
Iteration 149, loss = 5894433.18490798
Validation score: 0.764980
Iteration 150, loss = 5890835.68166275
Validation score: 0.765229
Iteration 151, loss = 5881414.16195647
Validation score: 0.765630
Iteration 152, loss = 5875360.22495666
Validation score: 0.765902
Iteration 153, loss = 5867708.19873164
Validation score: 0.766169
Iteration 154, loss = 5860977.82515997
Validation score: 0.766387
Iteration 155, loss = 5858043.49214206
Validation score: 0.766627
Iteration 156, loss = 5849876.59511077
Validation score: 0.767158
Iteration 157, loss = 5843644.57831220
Validation score: 0.767232
Iteration 158, loss = 5836536.70110243
Validation score: 0.767609
Iteration 159, loss = 5831174.50335038
Validation score: 0.767862
Iteration 160, loss = 5823163.20780103
Validation score: 0.768117
Iteration 161, loss = 5819041.62364494
Validation score: 0.768155
Iteration 162, loss = 5810878.99277805
Validation score: 0.768393
Iteration 163, loss = 5805443.85269996
Validation score: 0.768903
Iteration 164, loss = 5797741.72003292
Validation score: 0.769093
Iteration 165, loss = 5792094.99051657
Validation score: 0.769369
Iteration 166, loss = 5787277.79426389
Validation score: 0.769395
Iteration 167, loss = 5781378.69773854
Validation score: 0.769734
Iteration 168, loss = 5779886.27408668
Validation score: 0.770271
Iteration 169, loss = 5767163.76064986
Validation score: 0.770540
Iteration 170, loss = 5764484.58007791
Validation score: 0.770726
Iteration 171, loss = 5757376.36417867
Validation score: 0.770853
Iteration 172, loss = 5751121.70774758
Validation score: 0.771228
Iteration 173, loss = 5746996.51859550
Validation score: 0.771598
Iteration 174, loss = 5738339.00099915
Validation score: 0.771826
Iteration 175, loss = 5732261.43266423
Validation score: 0.772204
Iteration 176, loss = 5725898.28752746
Validation score: 0.772569
Iteration 177, loss = 5721566.99137464
Validation score: 0.772692
Iteration 178, loss = 5716120.59222169
Validation score: 0.772935
Iteration 179, loss = 5709866.04197426
Validation score: 0.773241
Iteration 180, loss = 5703931.09211025
Validation score: 0.773433
Iteration 181, loss = 5696685.24665524
Validation score: 0.773762
Iteration 182, loss = 5692866.99637399
Validation score: 0.774134
Iteration 183, loss = 5685362.02771244
Validation score: 0.774394
Iteration 184, loss = 5683789.69945054
Validation score: 0.774655
Iteration 185, loss = 5679868.11826579
Validation score: 0.774658
Iteration 186, loss = 5666783.04136266
Validation score: 0.775021
Iteration 187, loss = 5663144.93899886
Validation score: 0.775229
Iteration 188, loss = 5658434.31430554
Validation score: 0.775398
Iteration 189, loss = 5654791.52086208
Validation score: 0.775937
Iteration 190, loss = 5646199.50021254
Validation score: 0.775977
Iteration 191, loss = 5640329.35788869
Validation score: 0.776238
Iteration 192, loss = 5635242.70401723
Validation score: 0.776472
Iteration 193, loss = 5629954.82728517
Validation score: 0.776884
Iteration 194, loss = 5622823.68853553
Validation score: 0.777058
Iteration 195, loss = 5619851.68369250
Validation score: 0.777208
Iteration 196, loss = 5614025.68062593
Validation score: 0.777442
Iteration 197, loss = 5606785.05817046
Validation score: 0.777716
Iteration 198, loss = 5605510.15703869
Validation score: 0.777875
Iteration 199, loss = 5601072.04154792
Validation score: 0.778214
Iteration 200, loss = 5592847.15371152
Validation score: 0.777934
Iteration 201, loss = 5587522.26664692
Validation score: 0.778241
Iteration 202, loss = 5583432.98367792
Validation score: 0.778464
Iteration 203, loss = 5579365.45727047
Validation score: 0.778537
Iteration 204, loss = 5569998.65048940
Validation score: 0.779088
Iteration 205, loss = 5565219.53155586
Validation score: 0.779205
Iteration 206, loss = 5560280.38584886
Validation score: 0.779539
Iteration 207, loss = 5554909.49777220
Validation score: 0.779652
Iteration 208, loss = 5550180.08461326
Validation score: 0.780031
Iteration 209, loss = 5550514.80213329
Validation score: 0.780072
Iteration 210, loss = 5540382.53814824
Validation score: 0.780427
Iteration 211, loss = 5533601.35695884
Validation score: 0.780728
Iteration 212, loss = 5529716.08771010
Validation score: 0.781107
Iteration 213, loss = 5524503.16959735
Validation score: 0.781300
Iteration 214, loss = 5518471.74727334
Validation score: 0.781169
Iteration 215, loss = 5515465.01176631
Validation score: 0.781524
Iteration 216, loss = 5508902.48699060
Validation score: 0.781760
Iteration 217, loss = 5503575.98017120
Validation score: 0.781984
Iteration 218, loss = 5499845.42463675
Validation score: 0.782060
Iteration 219, loss = 5497107.21718518
Validation score: 0.782370
Iteration 220, loss = 5490560.13475891
Validation score: 0.782705
Iteration 221, loss = 5484201.42466861
Validation score: 0.782953
Iteration 222, loss = 5480732.02697364
Validation score: 0.783155
Iteration 223, loss = 5474986.74161178
Validation score: 0.783326
Iteration 224, loss = 5466792.35011146
Validation score: 0.783527
Iteration 225, loss = 5463377.35134589
Validation score: 0.783886
Iteration 226, loss = 5458455.92608161
Validation score: 0.784114
Iteration 227, loss = 5454320.66855339
Validation score: 0.784164
Iteration 228, loss = 5448655.74604721
Validation score: 0.784465
Iteration 229, loss = 5444247.24868762
Validation score: 0.784524
Iteration 230, loss = 5440451.28380827
Validation score: 0.784815
Iteration 231, loss = 5435385.73601244
Validation score: 0.784911
Iteration 232, loss = 5430327.26788825
Validation score: 0.785260
Iteration 233, loss = 5424100.42124103
Validation score: 0.785479
Iteration 234, loss = 5424318.31827416
Validation score: 0.785626
Iteration 235, loss = 5415192.25744147
Validation score: 0.785954
Iteration 236, loss = 5411147.39859712
Validation score: 0.785931
Iteration 237, loss = 5408093.41559876
Validation score: 0.786213
Iteration 238, loss = 5400184.24573047
Validation score: 0.786396
Iteration 239, loss = 5395353.14490803
Validation score: 0.786661
Iteration 240, loss = 5393128.30345479
Validation score: 0.786899
Iteration 241, loss = 5384108.72046044
Validation score: 0.787287
Iteration 242, loss = 5380490.11753709
Validation score: 0.787405
Iteration 243, loss = 5379715.25863494
Validation score: 0.787682
Iteration 244, loss = 5371675.53950272
Validation score: 0.787812
Iteration 245, loss = 5367085.51817310
Validation score: 0.788055
Iteration 246, loss = 5364504.83818707
Validation score: 0.788283
Iteration 247, loss = 5360272.79378252
Validation score: 0.788498
Iteration 248, loss = 5353674.01264157
Validation score: 0.788398
Iteration 249, loss = 5349072.94511178
Validation score: 0.788751
Iteration 250, loss = 5347050.12169469
Validation score: 0.788829
Iteration 251, loss = 5339560.60967577
Validation score: 0.789186
Iteration 252, loss = 5337455.67404611
Validation score: 0.789235
Iteration 253, loss = 5334187.11343198
Validation score: 0.789558
Iteration 254, loss = 5326555.33278949
Validation score: 0.789448
Iteration 255, loss = 5321942.55480094
Validation score: 0.789823
Iteration 256, loss = 5319319.68249261
Validation score: 0.789709
Iteration 257, loss = 5313662.28743256
Validation score: 0.790195
Iteration 258, loss = 5308802.00590400
Validation score: 0.790454
Iteration 259, loss = 5304689.38380165
Validation score: 0.790736
Iteration 260, loss = 5301057.67242672
Validation score: 0.790697
Iteration 261, loss = 5297349.70325754
Validation score: 0.791174
Iteration 262, loss = 5292643.43282237
Validation score: 0.791300
Iteration 263, loss = 5287682.44001754
Validation score: 0.791482
Iteration 264, loss = 5285513.00600287
Validation score: 0.791719
Iteration 265, loss = 5284552.64821267
Validation score: 0.792304
Iteration 266, loss = 5275427.03356144
Validation score: 0.792370
Iteration 267, loss = 5270007.54973721
Validation score: 0.792438
Iteration 268, loss = 5266571.73090973
Validation score: 0.792848
Iteration 269, loss = 5262755.66097417
Validation score: 0.793037
Iteration 270, loss = 5259452.07117350
Validation score: 0.792673
Iteration 271, loss = 5253413.29830455
Validation score: 0.792874
Iteration 272, loss = 5249023.00449554
Validation score: 0.792951
Iteration 273, loss = 5245866.23922041
Validation score: 0.793162
Iteration 274, loss = 5243091.83524287
Validation score: 0.793412
Iteration 275, loss = 5238262.60155025
Validation score: 0.793571
Iteration 276, loss = 5232730.73348164
Validation score: 0.793881
Iteration 277, loss = 5229110.87838503
Validation score: 0.794022
Iteration 278, loss = 5225274.70492437
Validation score: 0.794096
Iteration 279, loss = 5220738.42309218
Validation score: 0.794183
Iteration 280, loss = 5216523.91332714
Validation score: 0.794293
Iteration 281, loss = 5212220.22243530
Validation score: 0.794515
Iteration 282, loss = 5211769.08008486
Validation score: 0.794621
Iteration 283, loss = 5205161.10093958
Validation score: 0.794708
Iteration 284, loss = 5200545.56792556
Validation score: 0.794882
Iteration 285, loss = 5197942.84085786
Validation score: 0.794848
Iteration 286, loss = 5192918.54863231
Validation score: 0.795134
Iteration 287, loss = 5187949.69178265
Validation score: 0.795377
Iteration 288, loss = 5185378.97733477
Validation score: 0.795500
Iteration 289, loss = 5180783.64123222
Validation score: 0.795741
Iteration 290, loss = 5177561.26209351
Validation score: 0.795865
Iteration 291, loss = 5172593.52297908
Validation score: 0.796029
Iteration 292, loss = 5169444.90092181
Validation score: 0.796115
Iteration 293, loss = 5165251.86923731
Validation score: 0.796358
Iteration 294, loss = 5160382.31826047
Validation score: 0.796606
Iteration 295, loss = 5156320.75600216
Validation score: 0.796621
Iteration 296, loss = 5152737.50413000
Validation score: 0.796745
Iteration 297, loss = 5149660.50379429
Validation score: 0.796865
Iteration 298, loss = 5146136.44859467
Validation score: 0.797087
Iteration 299, loss = 5142403.16672259
Validation score: 0.797135
Iteration 300, loss = 5137381.06585819
Validation score: 0.797392
Iteration 301, loss = 5134936.05035155
Validation score: 0.797454
Iteration 302, loss = 5129635.90049860
Validation score: 0.797826
Iteration 303, loss = 5125321.86248546
Validation score: 0.797996
Iteration 304, loss = 5121591.29612465
Validation score: 0.798143
Iteration 305, loss = 5120956.79423285

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 173428814.82611260
Validation score: -4.451983
Iteration 2, loss = 170616899.35338387
Validation score: -4.303123
Iteration 3, loss = 164104047.89936674
Validation score: -4.036510
Iteration 4, loss = 154155225.03212586
Validation score: -3.672886
Iteration 5, loss = 141557917.51372415
Validation score: -3.237519
Iteration 6, loss = 127104051.05374634
Validation score: -2.757403
Iteration 7, loss = 111682080.18607700
Validation score: -2.258252
Iteration 8, loss = 96050065.35727897
Validation score: -1.768985
Iteration 9, loss = 80961176.91699961
Validation score: -1.304053
Iteration 10, loss = 66975248.61818644
Validation score: -0.886175
Iteration 11, loss = 54573666.56771883
Validation score: -0.523726
Iteration 12, loss = 44048688.53140019
Validation score: -0.225309
Iteration 13, loss = 35492124.41078849
Validation score: 0.012516
Iteration 14, loss = 28843355.12629608
Validation score: 0.189531
Iteration 15, loss = 23908069.55452400
Validation score: 0.317610
Iteration 16, loss = 20397479.02470142
Validation score: 0.405167
Iteration 17, loss = 18000365.02230291
Validation score: 0.462955
Iteration 18, loss = 16407435.23297000
Validation score: 0.500351
Iteration 19, loss = 15365561.83972741
Validation score: 0.524192
Iteration 20, loss = 14683898.30262354
Validation score: 0.539872
Iteration 21, loss = 14221349.29538607
Validation score: 0.550428
Iteration 22, loss = 13893707.89923436
Validation score: 0.558054
Iteration 23, loss = 13644867.95323230
Validation score: 0.564250
Iteration 24, loss = 13446264.81676974
Validation score: 0.569338
Iteration 25, loss = 13282909.44449542
Validation score: 0.573676
Iteration 26, loss = 13142726.75291401
Validation score: 0.577487
Iteration 27, loss = 13020788.64424405
Validation score: 0.580963
Iteration 28, loss = 12908893.18799948
Validation score: 0.584080
Iteration 29, loss = 12806771.76393123
Validation score: 0.587069
Iteration 30, loss = 12712777.06811347
Validation score: 0.589903
Iteration 31, loss = 12625813.17762917
Validation score: 0.592409
Iteration 32, loss = 12544008.99612966
Validation score: 0.594948
Iteration 33, loss = 12465252.35866463
Validation score: 0.597100
Iteration 34, loss = 12389065.94666710
Validation score: 0.599344
Iteration 35, loss = 12319221.09386443
Validation score: 0.601368
Iteration 36, loss = 12251195.42311088
Validation score: 0.603498
Iteration 37, loss = 12188798.14030773
Validation score: 0.605399
Iteration 38, loss = 12129084.25796186
Validation score: 0.607203
Iteration 39, loss = 12073352.58971829
Validation score: 0.608839
Iteration 40, loss = 12020238.53318867
Validation score: 0.610416
Iteration 41, loss = 11969189.94071580
Validation score: 0.611712
Iteration 42, loss = 11924325.88772513
Validation score: 0.612955
Iteration 43, loss = 11876913.92984790
Validation score: 0.614741
Iteration 44, loss = 11834374.38749284
Validation score: 0.615626
Iteration 45, loss = 11792870.75039902
Validation score: 0.617184
Iteration 46, loss = 11754504.04209425
Validation score: 0.618356
Iteration 47, loss = 11716917.58494348
Validation score: 0.619363
Iteration 48, loss = 11681074.45884858
Validation score: 0.620367
Iteration 49, loss = 11648181.47640940
Validation score: 0.621252
Iteration 50, loss = 11617073.78469518
Validation score: 0.622164
Iteration 51, loss = 11584958.82358577
Validation score: 0.622990
Iteration 52, loss = 11557281.84705617
Validation score: 0.623701
Iteration 53, loss = 11529413.26516957
Validation score: 0.624514
Iteration 54, loss = 11504419.45899684
Validation score: 0.625728
Iteration 55, loss = 11476623.04990344
Validation score: 0.625990
Iteration 56, loss = 11450571.06602372
Validation score: 0.626183
Iteration 57, loss = 11426240.09996255
Validation score: 0.627375
Iteration 58, loss = 11398593.15923659
Validation score: 0.628082
Iteration 59, loss = 11377392.22668443
Validation score: 0.628635
Iteration 60, loss = 11354007.31002620
Validation score: 0.629198
Iteration 61, loss = 11329440.09146325
Validation score: 0.630419
Iteration 62, loss = 11308465.46849481
Validation score: 0.630965
Iteration 63, loss = 11285792.03090997
Validation score: 0.631340
Iteration 64, loss = 11263964.56540563
Validation score: 0.632284
Iteration 65, loss = 11246355.16120846
Validation score: 0.632968
Iteration 66, loss = 11222359.30172173
Validation score: 0.633252
Iteration 67, loss = 11203066.63096817
Validation score: 0.633588
Iteration 68, loss = 11183441.28817404
Validation score: 0.634105
Iteration 69, loss = 11161155.32234540
Validation score: 0.634830
Iteration 70, loss = 11144882.91435826
Validation score: 0.635156
Iteration 71, loss = 11123213.31332650
Validation score: 0.635551
Iteration 72, loss = 11104448.58623919
Validation score: 0.636395
Iteration 73, loss = 11085374.67299828
Validation score: 0.636767
Iteration 74, loss = 11067311.09052393
Validation score: 0.637316
Iteration 75, loss = 11050532.59833804
Validation score: 0.637203
Iteration 76, loss = 11032141.70425234
Validation score: 0.638237
Iteration 77, loss = 11015906.65272508
Validation score: 0.638773
Iteration 78, loss = 10995680.84188626
Validation score: 0.639419
Iteration 79, loss = 10976089.36664569
Validation score: 0.639606
Iteration 80, loss = 10960378.82880322
Validation score: 0.640254
Iteration 81, loss = 10941905.79041723
Validation score: 0.640933
Iteration 82, loss = 10925653.35567493
Validation score: 0.641290
Iteration 83, loss = 10908842.73419823
Validation score: 0.641720
Iteration 84, loss = 10891894.10230075
Validation score: 0.642262
Iteration 85, loss = 10873532.65431199
Validation score: 0.642352
Iteration 86, loss = 10859500.40435886
Validation score: 0.643152
Iteration 87, loss = 10841884.78527724
Validation score: 0.643279
Iteration 88, loss = 10822817.36278269
Validation score: 0.643697
Iteration 89, loss = 10806626.51587493
Validation score: 0.644086
Iteration 90, loss = 10791164.86513613
Validation score: 0.644938
Iteration 91, loss = 10775384.26461532
Validation score: 0.645186
Iteration 92, loss = 10757368.26239119
Validation score: 0.645637
Iteration 93, loss = 10738870.21867164
Validation score: 0.646362
Iteration 94, loss = 10720225.54244640
Validation score: 0.646433
Iteration 95, loss = 10700229.42409072
Validation score: 0.647026
Iteration 96, loss = 10681680.86035295
Validation score: 0.647136
Iteration 97, loss = 10659834.92104701
Validation score: 0.647847
Iteration 98, loss = 10640682.85651465
Validation score: 0.648186
Iteration 99, loss = 10618300.39918217
Validation score: 0.648674
Iteration 100, loss = 10598127.09135889
Validation score: 0.649100
Iteration 101, loss = 10577433.07284033
Validation score: 0.650002
Iteration 102, loss = 10560959.25951485
Validation score: 0.649961
Iteration 103, loss = 10538437.47155140
Validation score: 0.651201
Iteration 104, loss = 10510277.37886630
Validation score: 0.651148
Iteration 105, loss = 10487468.54593427
Validation score: 0.651756
Iteration 106, loss = 10464376.74699825
Validation score: 0.652199
Iteration 107, loss = 10442649.45388177
Validation score: 0.652952
Iteration 108, loss = 10413707.08236196
Validation score: 0.653371
Iteration 109, loss = 10389053.66080082
Validation score: 0.654003
Iteration 110, loss = 10363098.34412199
Validation score: 0.654628
Iteration 111, loss = 10337039.87827682
Validation score: 0.655131
Iteration 112, loss = 10312513.31398633
Validation score: 0.655889
Iteration 113, loss = 10283365.05829600
Validation score: 0.656548
Iteration 114, loss = 10262304.70169442
Validation score: 0.657024
Iteration 115, loss = 10231713.12179338
Validation score: 0.658024
Iteration 116, loss = 10205524.49032376
Validation score: 0.658467
Iteration 117, loss = 10176392.98843369
Validation score: 0.658798
Iteration 118, loss = 10147408.52323928
Validation score: 0.659693
Iteration 119, loss = 10122662.72694898
Validation score: 0.659997
Iteration 120, loss = 10090989.18526561
Validation score: 0.660338
Iteration 121, loss = 10063259.29659925
Validation score: 0.661399
Iteration 122, loss = 10035733.42236706
Validation score: 0.662261
Iteration 123, loss = 10005808.36817088
Validation score: 0.662735
Iteration 124, loss = 9975007.04652166
Validation score: 0.662931
Iteration 125, loss = 9945847.04160007
Validation score: 0.663461
Iteration 126, loss = 9916754.23572070
Validation score: 0.664289
Iteration 127, loss = 9887590.94260000
Validation score: 0.664652
Iteration 128, loss = 9859167.64515514
Validation score: 0.665146
Iteration 129, loss = 9828708.46336797
Validation score: 0.666314
Iteration 130, loss = 9802776.69897668
Validation score: 0.667049
Iteration 131, loss = 9770869.31436686
Validation score: 0.667369
Iteration 132, loss = 9740469.67058619
Validation score: 0.668272
Iteration 133, loss = 9713656.89022366
Validation score: 0.668687
Iteration 134, loss = 9682720.74808158
Validation score: 0.669190
Iteration 135, loss = 9653185.52783527
Validation score: 0.669986
Iteration 136, loss = 9623778.11918295
Validation score: 0.670150
Iteration 137, loss = 9596873.30398266
Validation score: 0.670898
Iteration 138, loss = 9564952.79791413
Validation score: 0.671488
Iteration 139, loss = 9539715.73656242
Validation score: 0.672095
Iteration 140, loss = 9511334.12977994
Validation score: 0.672475
Iteration 141, loss = 9483178.04449097
Validation score: 0.672843
Iteration 142, loss = 9455475.40199411
Validation score: 0.673774
Iteration 143, loss = 9427463.27619250
Validation score: 0.673939
Iteration 144, loss = 9402221.21182352
Validation score: 0.674357
Iteration 145, loss = 9375606.09711044
Validation score: 0.675051
Iteration 146, loss = 9349548.15484068
Validation score: 0.675530
Iteration 147, loss = 9326762.51533830
Validation score: 0.675932
Iteration 148, loss = 9303218.54398941
Validation score: 0.676476
Iteration 149, loss = 9278807.81755152
Validation score: 0.676367
Iteration 150, loss = 9256975.21210769
Validation score: 0.676706
Iteration 151, loss = 9233357.78986022
Validation score: 0.677228
Iteration 152, loss = 9211307.28111171
Validation score: 0.677733
Iteration 153, loss = 9189186.60390257
Validation score: 0.678203
Iteration 154, loss = 9168412.91664461
Validation score: 0.678677
Iteration 155, loss = 9150207.01927662
Validation score: 0.678902
Iteration 156, loss = 9131549.31237304
Validation score: 0.679034
Iteration 157, loss = 9113705.60212069
Validation score: 0.679341
Iteration 158, loss = 9091810.07953582
Validation score: 0.679478
Iteration 159, loss = 9074079.90547177
Validation score: 0.679850
Iteration 160, loss = 9056084.28565697
Validation score: 0.680583
Iteration 161, loss = 9040624.65361025
Validation score: 0.680145
Iteration 162, loss = 9023424.59219527
Validation score: 0.680901
Iteration 163, loss = 9006497.41663240
Validation score: 0.681274
Iteration 164, loss = 8993066.50509726
Validation score: 0.681344
Iteration 165, loss = 8977741.87542407
Validation score: 0.681550
Iteration 166, loss = 8959497.20730912
Validation score: 0.682065
Iteration 167, loss = 8947171.46013689
Validation score: 0.682014
Iteration 168, loss = 8935068.88180481
Validation score: 0.682172
Iteration 169, loss = 8918851.40191565
Validation score: 0.682582
Iteration 170, loss = 8908775.41813618
Validation score: 0.682740
Iteration 171, loss = 8895086.56697044
Validation score: 0.682828
Iteration 172, loss = 8884430.45584721
Validation score: 0.682556
Iteration 173, loss = 8869982.70588933
Validation score: 0.683112
Iteration 174, loss = 8856817.25555856
Validation score: 0.683198
Iteration 175, loss = 8846073.16950755
Validation score: 0.683185
Iteration 176, loss = 8834656.41542599
Validation score: 0.683459
Iteration 177, loss = 8822997.49480091
Validation score: 0.683242
Iteration 178, loss = 8814478.35035787
Validation score: 0.683369
Iteration 179, loss = 8803459.46915677
Validation score: 0.683452
Iteration 180, loss = 8793084.01510826
Validation score: 0.683770
Iteration 181, loss = 8782178.60216268
Validation score: 0.683971
Iteration 182, loss = 8773585.46071997
Validation score: 0.684319
Iteration 183, loss = 8766635.68090499
Validation score: 0.683984
Iteration 184, loss = 8754334.94425046
Validation score: 0.684340
Iteration 185, loss = 8744640.78457274
Validation score: 0.684556
Iteration 186, loss = 8734421.61114266
Validation score: 0.684590
Iteration 187, loss = 8728454.19022495
Validation score: 0.685110
Iteration 188, loss = 8720382.73195699
Validation score: 0.684572
Iteration 189, loss = 8711164.38364973
Validation score: 0.684682
Iteration 190, loss = 8700453.37839315
Validation score: 0.685287
Iteration 191, loss = 8696952.97611917
Validation score: 0.685292
Iteration 192, loss = 8687458.99063465
Validation score: 0.685342
Iteration 193, loss = 8680426.57525996
Validation score: 0.685544
Iteration 194, loss = 8668932.63379510
Validation score: 0.685235
Iteration 195, loss = 8663519.99886277
Validation score: 0.685601
Iteration 196, loss = 8657263.40177134
Validation score: 0.685597
Iteration 197, loss = 8649284.20094728
Validation score: 0.685710
Iteration 198, loss = 8640909.05317183
Validation score: 0.685886
Iteration 199, loss = 8632316.05873193
Validation score: 0.686006
Iteration 200, loss = 8625997.92849579
Validation score: 0.685861
Iteration 201, loss = 8618474.53424859
Validation score: 0.686153
Iteration 202, loss = 8614217.89413964
Validation score: 0.686508
Iteration 203, loss = 8606266.84138847
Validation score: 0.686096
Iteration 204, loss = 8598554.13310043
Validation score: 0.686144
Iteration 205, loss = 8593167.83614914
Validation score: 0.686193
Iteration 206, loss = 8586275.18146857
Validation score: 0.686193
Iteration 207, loss = 8580453.23027692
Validation score: 0.686555
Iteration 208, loss = 8575913.05394358
Validation score: 0.686707
Iteration 209, loss = 8565846.14843934
Validation score: 0.686439
Iteration 210, loss = 8561483.13097770
Validation score: 0.686837
Iteration 211, loss = 8557059.46068374
Validation score: 0.686907
Iteration 212, loss = 8547828.19144152
Validation score: 0.687007
Iteration 213, loss = 8540818.28313486
Validation score: 0.687313
Iteration 214, loss = 8539606.81361758
Validation score: 0.687222
Iteration 215, loss = 8531124.34072834
Validation score: 0.687217
Iteration 216, loss = 8525965.90901577
Validation score: 0.687316
Iteration 217, loss = 8517187.76893582
Validation score: 0.687239
Iteration 218, loss = 8515656.92950343
Validation score: 0.687317
Iteration 219, loss = 8507327.50974778
Validation score: 0.687484
Iteration 220, loss = 8499687.48975314
Validation score: 0.687738
Iteration 221, loss = 8494484.73831856
Validation score: 0.687689
Iteration 222, loss = 8488448.54324006
Validation score: 0.687578
Iteration 223, loss = 8484889.02497555
Validation score: 0.687595
Iteration 224, loss = 8475732.48102815
Validation score: 0.687779
Iteration 225, loss = 8472488.80522313
Validation score: 0.688036
Iteration 226, loss = 8464229.97512974
Validation score: 0.687957
Iteration 227, loss = 8458115.23505067
Validation score: 0.687611
Iteration 228, loss = 8455984.22966515
Validation score: 0.687960
Iteration 229, loss = 8449218.56269654
Validation score: 0.688529
Iteration 230, loss = 8441391.62626698
Validation score: 0.688390
Iteration 231, loss = 8435069.88670173
Validation score: 0.688798
Iteration 232, loss = 8433061.19518029
Validation score: 0.688371
Iteration 233, loss = 8425757.17576750
Validation score: 0.688583
Iteration 234, loss = 8420750.02803335
Validation score: 0.689034
Iteration 235, loss = 8412970.36567282
Validation score: 0.688580
Iteration 236, loss = 8407687.75184518
Validation score: 0.689140
Iteration 237, loss = 8402358.66685340
Validation score: 0.688821
Iteration 238, loss = 8399340.30921065
Validation score: 0.689110
Iteration 239, loss = 8394964.70875856
Validation score: 0.689396
Iteration 240, loss = 8386784.80014229
Validation score: 0.689380
Iteration 241, loss = 8382635.98510243
Validation score: 0.689229
Iteration 242, loss = 8376106.05222321
Validation score: 0.689420
Iteration 243, loss = 8369093.14429160
Validation score: 0.689512
Iteration 244, loss = 8367212.88776236
Validation score: 0.689447
Iteration 245, loss = 8359122.75508375
Validation score: 0.689607
Iteration 246, loss = 8353674.45857053
Validation score: 0.689957
Iteration 247, loss = 8348292.52954905
Validation score: 0.690016
Iteration 248, loss = 8343834.81714812
Validation score: 0.689991
Iteration 249, loss = 8337670.92824706
Validation score: 0.690082
Iteration 250, loss = 8331940.57564273
Validation score: 0.690361
Iteration 251, loss = 8326861.30215829
Validation score: 0.690426
Iteration 252, loss = 8324649.76074079
Validation score: 0.690396
Iteration 253, loss = 8317709.73383060
Validation score: 0.690857
Iteration 254, loss = 8316047.04407279
Validation score: 0.690523
Iteration 255, loss = 8305893.89136274
Validation score: 0.690750
Iteration 256, loss = 8301121.19951510
Validation score: 0.690724
Iteration 257, loss = 8295854.63241140
Validation score: 0.691179
Iteration 258, loss = 8292190.99413243
Validation score: 0.691358
Iteration 259, loss = 8287196.19627768
Validation score: 0.691349
Iteration 260, loss = 8279602.75109096
Validation score: 0.691223
Iteration 261, loss = 8276214.96985495
Validation score: 0.691337
Iteration 262, loss = 8267520.40047787
Validation score: 0.691228
Iteration 263, loss = 8263854.94175759
Validation score: 0.691521
Iteration 264, loss = 8258683.77557991
Validation score: 0.691772
Iteration 265, loss = 8253492.44761722
Validation score: 0.691377
Iteration 266, loss = 8251660.37359606
Validation score: 0.691770
Iteration 267, loss = 8242036.26600590
Validation score: 0.692008
Iteration 268, loss = 8236896.07113290
Validation score: 0.692030
Iteration 269, loss = 8236122.16739210
Validation score: 0.692184
Iteration 270, loss = 8227440.00011648
Validation score: 0.692341
Iteration 271, loss = 8223812.54120522
Validation score: 0.692556
Iteration 272, loss = 8218143.81208155
Validation score: 0.692521
Iteration 273, loss = 8210707.46639388
Validation score: 0.692612
Iteration 274, loss = 8207043.17916109
Validation score: 0.692985
Iteration 275, loss = 8202074.88150624
Validation score: 0.692745
Iteration 276, loss = 8196245.62368007
Validation score: 0.692692
Iteration 277, loss = 8190872.26343543
Validation score: 0.693030
Iteration 278, loss = 8188026.96390709
Validation score: 0.693255
Iteration 279, loss = 8181146.31265136
Validation score: 0.693315
Iteration 280, loss = 8176395.08759984
Validation score: 0.693400
Iteration 281, loss = 8171515.94592498
Validation score: 0.693264
Iteration 282, loss = 8167049.07774179
Validation score: 0.693825
Iteration 283, loss = 8161128.00406108
Validation score: 0.693651
Iteration 284, loss = 8156949.87392817
Validation score: 0.694042
Iteration 285, loss = 8150822.50268999
Validation score: 0.693863
Iteration 286, loss = 8146526.44230021
Validation score: 0.694166
Iteration 287, loss = 8143208.54969985
Validation score: 0.694071
Iteration 288, loss = 8137735.14423687
Validation score: 0.694404
Iteration 289, loss = 8132264.47751778
Validation score: 0.694392
Iteration 290, loss = 8127137.07633844
Validation score: 0.694609
Iteration 291, loss = 8123170.77609217
Validation score: 0.694616
Iteration 292, loss = 8117301.05799534
Validation score: 0.694758
Iteration 293, loss = 8110515.11912426
Validation score: 0.694868
Iteration 294, loss = 8104636.35004734
Validation score: 0.694836
Iteration 295, loss = 8102565.51647947
Validation score: 0.695275
Iteration 296, loss = 8094636.62125157
Validation score: 0.695251
Iteration 297, loss = 8089741.24134841
Validation score: 0.695721
Iteration 298, loss = 8084951.20689042
Validation score: 0.695421
Iteration 299, loss = 8081360.97544299
Validation score: 0.695823
Iteration 300, loss = 8075627.48726607
Validation score: 0.695806
Iteration 301, loss = 8071889.03728116
Validation score: 0.695906
Iteration 302, loss = 8065192.04580451
Validation score: 0.696148

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 323404578.69381815
Validation score: -4.679187
Iteration 2, loss = 321701060.63232774
Validation score: -4.627275
Iteration 3, loss = 317593948.93104124
Validation score: -4.528725
Iteration 4, loss = 310893668.32878190
Validation score: -4.385552
Iteration 5, loss = 301808875.62631792
Validation score: -4.203815
Iteration 6, loss = 290785854.53235489
Validation score: -3.989094
Iteration 7, loss = 278017192.59630466
Validation score: -3.745479
Iteration 8, loss = 263811943.96788689
Validation score: -3.481178
Iteration 9, loss = 248583621.89671952
Validation score: -3.199383
Iteration 10, loss = 232584545.09392166
Validation score: -2.907221
Iteration 11, loss = 215865027.27861309
Validation score: -2.608873
Iteration 12, loss = 199397255.47008249
Validation score: -2.314155
Iteration 13, loss = 183166812.57034630
Validation score: -2.026424
Iteration 14, loss = 167253702.62749612
Validation score: -1.747320
Iteration 15, loss = 151843704.03453928
Validation score: -1.481503
Iteration 16, loss = 137668248.68767357
Validation score: -1.238276
Iteration 17, loss = 124636401.73720238
Validation score: -1.015659
Iteration 18, loss = 112784449.94328062
Validation score: -0.814332
Iteration 19, loss = 102084722.25723366
Validation score: -0.635632
Iteration 20, loss = 92545324.04256310
Validation score: -0.477436
Iteration 21, loss = 84078890.26626472
Validation score: -0.337373
Iteration 22, loss = 76808506.83877814
Validation score: -0.218782
Iteration 23, loss = 70749201.41812362
Validation score: -0.121964
Iteration 24, loss = 65819077.60487363
Validation score: -0.043947
Iteration 25, loss = 61636786.24833459
Validation score: 0.021945
Iteration 26, loss = 58274248.89762589
Validation score: 0.074092
Iteration 27, loss = 55557919.25745499
Validation score: 0.116415
Iteration 28, loss = 53327430.54592267
Validation score: 0.150886
Iteration 29, loss = 51514402.84155755
Validation score: 0.178917
Iteration 30, loss = 49940591.80566464
Validation score: 0.202824
Iteration 31, loss = 48700377.44529335
Validation score: 0.222622
Iteration 32, loss = 47565780.82081065
Validation score: 0.239249
Iteration 33, loss = 46705113.64871020
Validation score: 0.252376
Iteration 34, loss = 45952732.50450384
Validation score: 0.263768
Iteration 35, loss = 45258918.26014058
Validation score: 0.275029
Iteration 36, loss = 44622695.89627648
Validation score: 0.285136
Iteration 37, loss = 44036128.70212448
Validation score: 0.294519
Iteration 38, loss = 43518785.13378083
Validation score: 0.302844
Iteration 39, loss = 43021170.45510203
Validation score: 0.310568
Iteration 40, loss = 42547093.38559682
Validation score: 0.318310
Iteration 41, loss = 42092804.47692706
Validation score: 0.325745
Iteration 42, loss = 41682615.72021007
Validation score: 0.332351
Iteration 43, loss = 41294881.57251542
Validation score: 0.338970
Iteration 44, loss = 40900852.61196734
Validation score: 0.345416
Iteration 45, loss = 40543443.33395636
Validation score: 0.351179
Iteration 46, loss = 40200165.78716100
Validation score: 0.357136
Iteration 47, loss = 39873458.31604424
Validation score: 0.362671
Iteration 48, loss = 39566792.15678296
Validation score: 0.367564
Iteration 49, loss = 39260121.35185366
Validation score: 0.372668
Iteration 50, loss = 38955075.08730962
Validation score: 0.377265
Iteration 51, loss = 38680757.42236625
Validation score: 0.381998
Iteration 52, loss = 38422549.51379425
Validation score: 0.386370
Iteration 53, loss = 38177904.33056967
Validation score: 0.390773
Iteration 54, loss = 37934562.76022264
Validation score: 0.394947
Iteration 55, loss = 37696707.08731771
Validation score: 0.399022
Iteration 56, loss = 37469587.90367068
Validation score: 0.402743
Iteration 57, loss = 37243037.47137237
Validation score: 0.406585
Iteration 58, loss = 37034509.10453228
Validation score: 0.410083
Iteration 59, loss = 36826441.67888129
Validation score: 0.413442
Iteration 60, loss = 36632075.23889066
Validation score: 0.417105
Iteration 61, loss = 36432998.72488710
Validation score: 0.420238
Iteration 62, loss = 36243457.38686508
Validation score: 0.423409
Iteration 63, loss = 36048653.10534869
Validation score: 0.426773
Iteration 64, loss = 35868667.47526743
Validation score: 0.429658
Iteration 65, loss = 35689169.29544774
Validation score: 0.432654
Iteration 66, loss = 35517079.73967149
Validation score: 0.435504
Iteration 67, loss = 35352628.12960531
Validation score: 0.438466
Iteration 68, loss = 35183910.95265160
Validation score: 0.441134
Iteration 69, loss = 35012114.04542898
Validation score: 0.443844
Iteration 70, loss = 34850419.65395591
Validation score: 0.446161
Iteration 71, loss = 34691177.95480086
Validation score: 0.448921
Iteration 72, loss = 34538517.23707280
Validation score: 0.451250
Iteration 73, loss = 34382171.88904424
Validation score: 0.453540
Iteration 74, loss = 34234788.43437620
Validation score: 0.455723
Iteration 75, loss = 34088924.38962567
Validation score: 0.457918
Iteration 76, loss = 33943246.53799616
Validation score: 0.460189
Iteration 77, loss = 33794095.05246609
Validation score: 0.462103
Iteration 78, loss = 33655723.12436786
Validation score: 0.464458
Iteration 79, loss = 33514410.71522834
Validation score: 0.466514
Iteration 80, loss = 33381729.25661733
Validation score: 0.468376
Iteration 81, loss = 33246162.05167698
Validation score: 0.470082
Iteration 82, loss = 33116604.45205872
Validation score: 0.471771
Iteration 83, loss = 32982788.94893054
Validation score: 0.473494
Iteration 84, loss = 32859134.79300877
Validation score: 0.475306
Iteration 85, loss = 32742535.48271336
Validation score: 0.477180
Iteration 86, loss = 32624730.49786133
Validation score: 0.478499
Iteration 87, loss = 32503650.54388292
Validation score: 0.479821
Iteration 88, loss = 32398826.08888483
Validation score: 0.481295
Iteration 89, loss = 32297733.95027440
Validation score: 0.482692
Iteration 90, loss = 32183499.74369169
Validation score: 0.484284
Iteration 91, loss = 32079759.45201427
Validation score: 0.485796
Iteration 92, loss = 31970833.34660995
Validation score: 0.487442
Iteration 93, loss = 31882037.08262869
Validation score: 0.488936
Iteration 94, loss = 31777576.51977543
Validation score: 0.490416
Iteration 95, loss = 31683701.58572086
Validation score: 0.491682
Iteration 96, loss = 31583267.52808471
Validation score: 0.492913
Iteration 97, loss = 31488657.79766032
Validation score: 0.493937
Iteration 98, loss = 31396939.57091205
Validation score: 0.495113
Iteration 99, loss = 31306284.90054667
Validation score: 0.496484
Iteration 100, loss = 31199999.56182187
Validation score: 0.497354
Iteration 101, loss = 31115623.25375184
Validation score: 0.498412
Iteration 102, loss = 31053617.32955065
Validation score: 0.499015
Iteration 103, loss = 30949323.73713004
Validation score: 0.500737
Iteration 104, loss = 30882794.32357002
Validation score: 0.501641
Iteration 105, loss = 30807260.78741717
Validation score: 0.502480
Iteration 106, loss = 30734409.91380568
Validation score: 0.503386
Iteration 107, loss = 30662057.12574105
Validation score: 0.504327
Iteration 108, loss = 30593244.24261861
Validation score: 0.505189
Iteration 109, loss = 30518686.60422089
Validation score: 0.505881
Iteration 110, loss = 30446327.12955649
Validation score: 0.506806
Iteration 111, loss = 30376999.96327773
Validation score: 0.507903
Iteration 112, loss = 30299187.96723820
Validation score: 0.508894
Iteration 113, loss = 30232871.88482310
Validation score: 0.510014
Iteration 114, loss = 30164003.76972885
Validation score: 0.510669
Iteration 115, loss = 30096042.63478520
Validation score: 0.511474
Iteration 116, loss = 30029567.35473147
Validation score: 0.512075
Iteration 117, loss = 29965215.18531505
Validation score: 0.512939
Iteration 118, loss = 29895327.41537936
Validation score: 0.513939
Iteration 119, loss = 29831401.95050918
Validation score: 0.514702
Iteration 120, loss = 29764599.40600495
Validation score: 0.515459
Iteration 121, loss = 29701081.00729689
Validation score: 0.516365
Iteration 122, loss = 29635593.15406496
Validation score: 0.517081
Iteration 123, loss = 29570697.20284196
Validation score: 0.517925
Iteration 124, loss = 29512101.14904716
Validation score: 0.518505
Iteration 125, loss = 29442455.19932323
Validation score: 0.519564
Iteration 126, loss = 29390832.52822705
Validation score: 0.520355
Iteration 127, loss = 29329801.07134721
Validation score: 0.521117
Iteration 128, loss = 29272717.91375316
Validation score: 0.521561
Iteration 129, loss = 29215519.78085216
Validation score: 0.522055
Iteration 130, loss = 29164071.94838978
Validation score: 0.522640
Iteration 131, loss = 29097247.99361711
Validation score: 0.523507
Iteration 132, loss = 29043372.30585174
Validation score: 0.524048
Iteration 133, loss = 28986476.37192457
Validation score: 0.524937
Iteration 134, loss = 28929781.00581810
Validation score: 0.525556
Iteration 135, loss = 28874992.78386404
Validation score: 0.526443
Iteration 136, loss = 28819420.98333012
Validation score: 0.527045
Iteration 137, loss = 28766312.64872159
Validation score: 0.527674
Iteration 138, loss = 28715126.00077853
Validation score: 0.528578
Iteration 139, loss = 28665307.74129664
Validation score: 0.529166
Iteration 140, loss = 28606887.31023145
Validation score: 0.529642
Iteration 141, loss = 28552166.37458382
Validation score: 0.530195
Iteration 142, loss = 28507494.48032226
Validation score: 0.530774
Iteration 143, loss = 28460135.55973416
Validation score: 0.531028
Iteration 144, loss = 28404882.96843781
Validation score: 0.531359
Iteration 145, loss = 28360944.71244064
Validation score: 0.531467
Iteration 146, loss = 28312521.74326932
Validation score: 0.532510
Iteration 147, loss = 28257891.30732752
Validation score: 0.533144
Iteration 148, loss = 28209563.33503081
Validation score: 0.533772
Iteration 149, loss = 28175372.64068824
Validation score: 0.534427
Iteration 150, loss = 28122342.17642349
Validation score: 0.535195
Iteration 151, loss = 28076383.98672577
Validation score: 0.535572
Iteration 152, loss = 28026988.85874648
Validation score: 0.536054
Iteration 153, loss = 27984917.06680547
Validation score: 0.536459
Iteration 154, loss = 27935199.84953655
Validation score: 0.536841
Iteration 155, loss = 27895804.46052256
Validation score: 0.537393
Iteration 156, loss = 27853715.44684112
Validation score: 0.537775
Iteration 157, loss = 27807979.14446573
Validation score: 0.538225
Iteration 158, loss = 27768563.19855352
Validation score: 0.538652
Iteration 159, loss = 27724664.05060489
Validation score: 0.538949
Iteration 160, loss = 27683229.88234882
Validation score: 0.539257
Iteration 161, loss = 27642775.30747017
Validation score: 0.540047
Iteration 162, loss = 27601080.90387736
Validation score: 0.540399
Iteration 163, loss = 27563047.92975791
Validation score: 0.540919
Iteration 164, loss = 27524358.84580994
Validation score: 0.541097
Iteration 165, loss = 27482586.43718198
Validation score: 0.541420
Iteration 166, loss = 27444857.87862745
Validation score: 0.541807
Iteration 167, loss = 27404884.28373633
Validation score: 0.542302
Iteration 168, loss = 27362254.55027004
Validation score: 0.542458
Iteration 169, loss = 27327037.59492057
Validation score: 0.542562
Iteration 170, loss = 27292359.37392774
Validation score: 0.543212
Iteration 171, loss = 27261865.73036100
Validation score: 0.543569
Iteration 172, loss = 27223421.38878892
Validation score: 0.543646
Iteration 173, loss = 27186149.04003659
Validation score: 0.544242
Iteration 174, loss = 27146534.31958682
Validation score: 0.544550
Iteration 175, loss = 27101600.69010458
Validation score: 0.545085
Iteration 176, loss = 27072003.93617336
Validation score: 0.545163
Iteration 177, loss = 27037414.98095400
Validation score: 0.545501
Iteration 178, loss = 27011514.92812777
Validation score: 0.545575
Iteration 179, loss = 26973654.84117243
Validation score: 0.545862
Iteration 180, loss = 26937770.22236634
Validation score: 0.546052
Iteration 181, loss = 26902901.02435683
Validation score: 0.546518
Iteration 182, loss = 26872972.77949036
Validation score: 0.546829
Iteration 183, loss = 26840853.15574380
Validation score: 0.547123
Iteration 184, loss = 26807793.24210294
Validation score: 0.547574
Iteration 185, loss = 26773430.49306615
Validation score: 0.547464
Iteration 186, loss = 26745988.83451786
Validation score: 0.547747
Iteration 187, loss = 26706499.69581448
Validation score: 0.548595
Iteration 188, loss = 26683451.05993887
Validation score: 0.548795
Iteration 189, loss = 26654825.39155048
Validation score: 0.549278
Iteration 190, loss = 26622586.83123760
Validation score: 0.549581
Iteration 191, loss = 26596694.66278365
Validation score: 0.549828
Iteration 192, loss = 26567309.82978716
Validation score: 0.550262
Iteration 193, loss = 26532407.71297395
Validation score: 0.550092
Iteration 194, loss = 26504669.00480760
Validation score: 0.550300
Iteration 195, loss = 26476861.81326479
Validation score: 0.550564
Iteration 196, loss = 26449374.68689839
Validation score: 0.551110
Iteration 197, loss = 26420436.35613425
Validation score: 0.551129
Iteration 198, loss = 26393303.50551610
Validation score: 0.551535
Iteration 199, loss = 26361701.42461349
Validation score: 0.551710
Iteration 200, loss = 26333746.54898017
Validation score: 0.551962
Iteration 201, loss = 26303584.26415348
Validation score: 0.552035
Iteration 202, loss = 26278527.14329821
Validation score: 0.552044
Iteration 203, loss = 26254853.23786667
Validation score: 0.552782
Iteration 204, loss = 26223504.63805515
Validation score: 0.552805
Iteration 205, loss = 26198779.32603316
Validation score: 0.553021
Iteration 206, loss = 26170603.78655174
Validation score: 0.553153
Iteration 207, loss = 26147873.53057709
Validation score: 0.553301
Iteration 208, loss = 26119544.94515778
Validation score: 0.553555
Iteration 209, loss = 26094282.02424745
Validation score: 0.554124
Iteration 210, loss = 26070620.26082182
Validation score: 0.554087
Iteration 211, loss = 26057805.57805032
Validation score: 0.554006
Iteration 212, loss = 26020783.91443717
Validation score: 0.554565
Iteration 213, loss = 26009251.25653068
Validation score: 0.554609
Iteration 214, loss = 25970699.93721575
Validation score: 0.555119
Iteration 215, loss = 25947656.80340858
Validation score: 0.555130
Iteration 216, loss = 25925939.44307448
Validation score: 0.555240
Iteration 217, loss = 25903644.60852692
Validation score: 0.555445
Iteration 218, loss = 25880104.48001127
Validation score: 0.555777
Iteration 219, loss = 25854651.51726411
Validation score: 0.556193
Iteration 220, loss = 25831832.21798019
Validation score: 0.556628
Iteration 221, loss = 25810707.53597987
Validation score: 0.556717
Iteration 222, loss = 25785515.72768060
Validation score: 0.556677
Iteration 223, loss = 25768427.24339302
Validation score: 0.556939
Iteration 224, loss = 25739197.76935594
Validation score: 0.556927
Iteration 225, loss = 25719826.87621513
Validation score: 0.556912
Iteration 226, loss = 25690049.58346264
Validation score: 0.556606
Iteration 227, loss = 25667308.11121607
Validation score: 0.556845
Iteration 228, loss = 25649132.11663835
Validation score: 0.556960
Iteration 229, loss = 25636026.03605998
Validation score: 0.556855
Iteration 230, loss = 25615684.81304673
Validation score: 0.557180
Iteration 231, loss = 25600954.08686691
Validation score: 0.557512
Iteration 232, loss = 25576487.38514967
Validation score: 0.557742
Iteration 233, loss = 25563809.94597816
Validation score: 0.557773
Iteration 234, loss = 25536579.01530746
Validation score: 0.558139
Iteration 235, loss = 25525152.74751537
Validation score: 0.558006
Iteration 236, loss = 25504233.54877691
Validation score: 0.558318
Iteration 237, loss = 25488198.83786209
Validation score: 0.558146
Iteration 238, loss = 25470351.49122968
Validation score: 0.558094
Iteration 239, loss = 25456474.34035914
Validation score: 0.558628
Iteration 240, loss = 25432425.97532152
Validation score: 0.558581
Iteration 241, loss = 25419921.12085895
Validation score: 0.559016
Iteration 242, loss = 25398071.64508412
Validation score: 0.559246
Iteration 243, loss = 25378859.49906857
Validation score: 0.559418
Iteration 244, loss = 25370880.15885089
Validation score: 0.559654
Iteration 245, loss = 25355120.55809475
Validation score: 0.559802
Iteration 246, loss = 25331368.21151793
Validation score: 0.560075
Iteration 247, loss = 25322161.44614556
Validation score: 0.560194
Iteration 248, loss = 25296213.59838552
Validation score: 0.560225
Iteration 249, loss = 25279708.79471667
Validation score: 0.560418
Iteration 250, loss = 25265711.68044692
Validation score: 0.560101
Iteration 251, loss = 25247318.92825507
Validation score: 0.560483
Iteration 252, loss = 25233832.47270635
Validation score: 0.560509
Iteration 253, loss = 25222040.72101300
Validation score: 0.560726
Iteration 254, loss = 25196030.28049743
Validation score: 0.560702
Iteration 255, loss = 25195160.30335185
Validation score: 0.560347
Iteration 256, loss = 25176658.41942326
Validation score: 0.560654
Iteration 257, loss = 25151195.12827970
Validation score: 0.560736
Iteration 258, loss = 25136373.29757672
Validation score: 0.561012
Iteration 259, loss = 25121530.94644578
Validation score: 0.561144
Iteration 260, loss = 25108247.26954879
Validation score: 0.561051
Iteration 261, loss = 25090659.55086077
Validation score: 0.561267
Iteration 262, loss = 25079348.49810547
Validation score: 0.561424
Iteration 263, loss = 25058052.02287627
Validation score: 0.561486
Iteration 264, loss = 25050902.33191886
Validation score: 0.561453
Iteration 265, loss = 25031192.61913218
Validation score: 0.561379
Iteration 266, loss = 25017011.75472784
Validation score: 0.561527
Iteration 267, loss = 25002601.89499075
Validation score: 0.561750
Iteration 268, loss = 24986033.15538657
Validation score: 0.561786
Iteration 269, loss = 24975997.56985839
Validation score: 0.561917
Iteration 270, loss = 24956898.56023182
Validation score: 0.562350
Iteration 271, loss = 24946081.66408568
Validation score: 0.562402
Iteration 272, loss = 24935758.78472156
Validation score: 0.562766
Iteration 273, loss = 24913836.53550988
Validation score: 0.562643
Iteration 274, loss = 24903477.72880450
Validation score: 0.562740
Iteration 275, loss = 24888372.34527666
Validation score: 0.562684
Iteration 276, loss = 24883935.30990251
Validation score: 0.562055
Iteration 277, loss = 24865559.89538753
Validation score: 0.562437
Iteration 278, loss = 24846434.38377773
Validation score: 0.562512
Iteration 279, loss = 24836572.79829460
Validation score: 0.562578
Iteration 280, loss = 24826562.74474311
Validation score: 0.562744
Iteration 281, loss = 24809984.25009265
Validation score: 0.562806
Iteration 282, loss = 24800592.46036294
Validation score: 0.562499
Iteration 283, loss = 24790847.37025401
Validation score: 0.562603
Iteration 284, loss = 24776933.41224092
Validation score: 0.562952
Iteration 285, loss = 24760270.79713861
Validation score: 0.563138
Iteration 286, loss = 24746111.23969335
Validation score: 0.563362
Iteration 287, loss = 24733118.03322291
Validation score: 0.563318
Iteration 288, loss = 24719457.92544205
Validation score: 0.563350
Iteration 289, loss = 24712396.31823002
Validation score: 0.563679
Iteration 290, loss = 24699330.34795859
Validation score: 0.563718
Iteration 291, loss = 24687218.38875268
Validation score: 0.563880
Iteration 292, loss = 24674086.11265740
Validation score: 0.563852
Iteration 293, loss = 24660633.48833593
Validation score: 0.563743
Iteration 294, loss = 24647266.73228219
Validation score: 0.563862
Iteration 295, loss = 24635613.02311944
Validation score: 0.564115
Iteration 296, loss = 24622824.37482305
Validation score: 0.564073
Iteration 297, loss = 24615169.20189269
Validation score: 0.564167
Iteration 298, loss = 24610598.77586221
Validation score: 0.564331
Iteration 299, loss = 24588097.54976593
Validation score: 0.564442

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 2, loss = 122662869.24254480
Validation score: -5.059346
Iteration 3, loss = 121900487.30952179
Validation score: -5.007468
Iteration 4, loss = 120591743.24031620
Validation score: -4.927402
Iteration 5, loss = 118714741.13129856
Validation score: -4.818681
Iteration 6, loss = 116263000.63994326
Validation score: -4.681652
Iteration 7, loss = 113270982.92340769
Validation score: -4.520301
Iteration 8, loss = 109814887.92469084
Validation score: -4.335471
Iteration 9, loss = 105937724.79004365
Validation score: -4.131881
Iteration 10, loss = 101682728.24760488
Validation score: -3.912035
Iteration 11, loss = 97132528.82737383
Validation score: -3.677765
Iteration 12, loss = 92343504.59626296
Validation score: -3.435676
Iteration 13, loss = 87371356.44530767
Validation score: -3.182654
Iteration 14, loss = 82267524.24835202
Validation score: -2.928100
Iteration 15, loss = 77128801.63169600
Validation score: -2.670382
Iteration 16, loss = 71930955.28362030
Validation score: -2.413929
Iteration 17, loss = 66814905.72611426
Validation score: -2.161371
Iteration 18, loss = 61800787.35498244
Validation score: -1.916426
Iteration 19, loss = 56898926.78959084
Validation score: -1.681152
Iteration 20, loss = 52165349.70939534
Validation score: -1.450669
Iteration 21, loss = 47667247.81147112
Validation score: -1.235513
Iteration 22, loss = 43401182.19431131
Validation score: -1.031815
Iteration 23, loss = 39384617.02826890
Validation score: -0.842482
Iteration 24, loss = 35686932.00492469
Validation score: -0.671082
Iteration 25, loss = 32311613.55047311
Validation score: -0.513185
Iteration 26, loss = 29242091.03556251
Validation score: -0.371808
Iteration 27, loss = 26469331.38429051
Validation score: -0.244727
Iteration 28, loss = 23971785.16684025
Validation score: -0.131252
Iteration 29, loss = 21767382.13614608
Validation score: -0.032854
Iteration 30, loss = 19823140.93213403
Validation score: 0.054838
Iteration 31, loss = 18097678.57843558
Validation score: 0.130024
Iteration 32, loss = 16628502.15641245
Validation score: 0.193778
Iteration 33, loss = 15383366.49331487
Validation score: 0.247455
Iteration 34, loss = 14327994.37608848
Validation score: 0.292678
Iteration 35, loss = 13433978.38064478
Validation score: 0.330517
Iteration 36, loss = 12683571.86065069
Validation score: 0.362445
Iteration 37, loss = 12048714.35674152
Validation score: 0.388907
Iteration 38, loss = 11510534.69193121
Validation score: 0.411985
Iteration 39, loss = 11049528.76995853
Validation score: 0.430769
Iteration 40, loss = 10664142.41181096
Validation score: 0.446778
Iteration 41, loss = 10343408.82906798
Validation score: 0.460485
Iteration 42, loss = 10060187.21119290
Validation score: 0.472332
Iteration 43, loss = 9814073.96827155
Validation score: 0.482398
Iteration 44, loss = 9608870.41157593
Validation score: 0.491375
Iteration 45, loss = 9428514.79796496
Validation score: 0.499450
Iteration 46, loss = 9266160.58697927
Validation score: 0.506483
Iteration 47, loss = 9123380.45623764
Validation score: 0.512972
Iteration 48, loss = 8993573.32329285
Validation score: 0.518756
Iteration 49, loss = 8878465.84793851
Validation score: 0.524318
Iteration 50, loss = 8771920.35431617
Validation score: 0.529352
Iteration 51, loss = 8671443.85823936
Validation score: 0.534221
Iteration 52, loss = 8580376.78320717
Validation score: 0.538425
Iteration 53, loss = 8497813.62018988
Validation score: 0.542647
Iteration 54, loss = 8419337.41701795
Validation score: 0.546447
Iteration 55, loss = 8347433.37090641
Validation score: 0.550180
Iteration 56, loss = 8276706.82557899
Validation score: 0.553592
Iteration 57, loss = 8213376.74492693
Validation score: 0.557028
Iteration 58, loss = 8150074.40403558
Validation score: 0.560246
Iteration 59, loss = 8091192.36381625
Validation score: 0.563411
Iteration 60, loss = 8036198.01866672
Validation score: 0.566286
Iteration 61, loss = 7982344.31240018
Validation score: 0.569310
Iteration 62, loss = 7932886.23509993
Validation score: 0.571940
Iteration 63, loss = 7886160.58346925
Validation score: 0.574487
Iteration 64, loss = 7841089.74878403
Validation score: 0.577074
Iteration 65, loss = 7797457.17076341
Validation score: 0.579663
Iteration 66, loss = 7754830.93431232
Validation score: 0.581999
Iteration 67, loss = 7713530.20472116
Validation score: 0.584498
Iteration 68, loss = 7674886.21291465
Validation score: 0.586714
Iteration 69, loss = 7636152.64212036
Validation score: 0.588946
Iteration 70, loss = 7600874.10975800
Validation score: 0.591080
Iteration 71, loss = 7562434.75509763
Validation score: 0.593363
Iteration 72, loss = 7527701.62941817
Validation score: 0.595355
Iteration 73, loss = 7494646.09856013
Validation score: 0.597418
Iteration 74, loss = 7458981.45824603
Validation score: 0.599663
Iteration 75, loss = 7426236.63077782
Validation score: 0.601545
Iteration 76, loss = 7395181.42047897
Validation score: 0.603479
Iteration 77, loss = 7364514.76761934
Validation score: 0.605365
Iteration 78, loss = 7334057.70715691
Validation score: 0.607140
Iteration 79, loss = 7304540.84013173
Validation score: 0.608856
Iteration 80, loss = 7276211.72144562
Validation score: 0.610795
Iteration 81, loss = 7246762.99383733
Validation score: 0.612554
Iteration 82, loss = 7218902.26050164
Validation score: 0.614225
Iteration 83, loss = 7191941.71501481
Validation score: 0.615801
Iteration 84, loss = 7166750.05531934
Validation score: 0.617383
Iteration 85, loss = 7141546.66419011
Validation score: 0.618962
Iteration 86, loss = 7115790.52424564
Validation score: 0.620575
Iteration 87, loss = 7092074.87902599
Validation score: 0.622202
Iteration 88, loss = 7068855.55778284
Validation score: 0.623760
Iteration 89, loss = 7046190.19715161
Validation score: 0.625242
Iteration 90, loss = 7023760.94852716
Validation score: 0.626670
Iteration 91, loss = 7002371.42296794
Validation score: 0.627984
Iteration 92, loss = 6981077.25595950
Validation score: 0.629501
Iteration 93, loss = 6960998.72001684
Validation score: 0.630727
Iteration 94, loss = 6942210.70220918
Validation score: 0.631979
Iteration 95, loss = 6920570.06654896
Validation score: 0.633312
Iteration 96, loss = 6902127.38114524
Validation score: 0.634557
Iteration 97, loss = 6882543.12935164
Validation score: 0.636073
Iteration 98, loss = 6864784.84933965
Validation score: 0.637189
Iteration 99, loss = 6847209.52800840
Validation score: 0.638233
Iteration 100, loss = 6831000.70439922
Validation score: 0.639384
Iteration 101, loss = 6814835.52000384
Validation score: 0.640567
Iteration 102, loss = 6797669.26661219
Validation score: 0.641640
Iteration 103, loss = 6780654.66297788
Validation score: 0.642574
Iteration 104, loss = 6765955.96642392
Validation score: 0.643603
Iteration 105, loss = 6751612.54051742
Validation score: 0.644619
Iteration 106, loss = 6737820.53060253
Validation score: 0.645597
Iteration 107, loss = 6721413.01800377
Validation score: 0.646575
Iteration 108, loss = 6707897.69123201
Validation score: 0.647472
Iteration 109, loss = 6695112.51338918
Validation score: 0.648458
Iteration 110, loss = 6682970.32908385
Validation score: 0.649112
Iteration 111, loss = 6669888.13991886
Validation score: 0.650133
Iteration 112, loss = 6654874.37192089
Validation score: 0.650912
Iteration 113, loss = 6644524.20785634
Validation score: 0.651868
Iteration 114, loss = 6630632.04276367
Validation score: 0.652644
Iteration 115, loss = 6619860.67298413
Validation score: 0.653339
Iteration 116, loss = 6608186.39894920
Validation score: 0.653952
Iteration 117, loss = 6596414.94562689
Validation score: 0.654819
Iteration 118, loss = 6584771.11429214
Validation score: 0.655319
Iteration 119, loss = 6575009.27392013
Validation score: 0.656161
Iteration 120, loss = 6565157.53175682
Validation score: 0.656846
Iteration 121, loss = 6552780.43551387
Validation score: 0.657522
Iteration 122, loss = 6542966.61963760
Validation score: 0.658265
Iteration 123, loss = 6533738.22082424
Validation score: 0.658742
Iteration 124, loss = 6525402.56777819
Validation score: 0.659422
Iteration 125, loss = 6515695.36502808
Validation score: 0.659997
Iteration 126, loss = 6504349.00516319
Validation score: 0.660711
Iteration 127, loss = 6496602.02833635
Validation score: 0.661409
Iteration 128, loss = 6488009.20247198
Validation score: 0.661877
Iteration 129, loss = 6480979.67316524
Validation score: 0.662538
Iteration 130, loss = 6471082.04566190
Validation score: 0.662895
Iteration 131, loss = 6463372.68251698
Validation score: 0.663456
Iteration 132, loss = 6456200.83630556
Validation score: 0.664016
Iteration 133, loss = 6450077.27944873
Validation score: 0.664573
Iteration 134, loss = 6441321.60254805
Validation score: 0.664938
Iteration 135, loss = 6436091.94672170
Validation score: 0.665532
Iteration 136, loss = 6428373.93338108
Validation score: 0.665722
Iteration 137, loss = 6420235.97261626
Validation score: 0.666073
Iteration 138, loss = 6413780.37500528
Validation score: 0.666555
Iteration 139, loss = 6407043.63926011
Validation score: 0.667206
Iteration 140, loss = 6401316.97712843
Validation score: 0.667610
Iteration 141, loss = 6393925.85299662
Validation score: 0.667957
Iteration 142, loss = 6388224.64922320
Validation score: 0.668264
Iteration 143, loss = 6383318.00819063
Validation score: 0.668507
Iteration 144, loss = 6378745.56531328
Validation score: 0.668737
Iteration 145, loss = 6373499.39495507
Validation score: 0.669132
Iteration 146, loss = 6367960.44525071
Validation score: 0.669367
Iteration 147, loss = 6363633.92387086
Validation score: 0.669585
Iteration 148, loss = 6358603.92443008
Validation score: 0.670026
Iteration 149, loss = 6353795.48097171
Validation score: 0.670268
Iteration 150, loss = 6349596.43458380
Validation score: 0.670701
Iteration 151, loss = 6346306.53838433
Validation score: 0.670927
Iteration 152, loss = 6339278.08593323
Validation score: 0.671058
Iteration 153, loss = 6336197.48857483
Validation score: 0.671473
Iteration 154, loss = 6332994.83711972
Validation score: 0.671700
Iteration 155, loss = 6327849.08905864
Validation score: 0.671892
Iteration 156, loss = 6322376.54152029
Validation score: 0.671970
Iteration 157, loss = 6319313.75650959
Validation score: 0.672193
Iteration 158, loss = 6314694.47777018
Validation score: 0.672484
Iteration 159, loss = 6310712.63978652
Validation score: 0.672814
Iteration 160, loss = 6308313.28706790
Validation score: 0.672785
Iteration 161, loss = 6303795.91048016
Validation score: 0.673066
Iteration 162, loss = 6302582.52297227
Validation score: 0.673228
Iteration 163, loss = 6296746.17506113
Validation score: 0.673474
Iteration 164, loss = 6295114.68872395
Validation score: 0.673445
Iteration 165, loss = 6293440.90145104
Validation score: 0.673761
Iteration 166, loss = 6287750.45804624
Validation score: 0.673908
Iteration 167, loss = 6284150.23041640
Validation score: 0.674163
Iteration 168, loss = 6291689.64340991
Validation score: 0.673626
Iteration 169, loss = 6282573.05648008
Validation score: 0.673939
Iteration 170, loss = 6277261.76506821
Validation score: 0.674155
Iteration 171, loss = 6272606.49732833
Validation score: 0.674332
Iteration 172, loss = 6270083.48258656
Validation score: 0.674572
Iteration 173, loss = 6267975.78881767
Validation score: 0.674866
Iteration 174, loss = 6264167.72560409
Validation score: 0.675008
Iteration 175, loss = 6262711.15493894
Validation score: 0.675188
Iteration 176, loss = 6259013.72356136
Validation score: 0.675302
Iteration 177, loss = 6260392.44495720
Validation score: 0.675528
Iteration 178, loss = 6254113.65623526
Validation score: 0.675657
Iteration 179, loss = 6252209.47762880
Validation score: 0.675761
Iteration 180, loss = 6249499.58160776
Validation score: 0.675878
Iteration 181, loss = 6246338.70059995
Validation score: 0.676070
Iteration 182, loss = 6244766.03926166
Validation score: 0.676247
Iteration 183, loss = 6244626.97089992
Validation score: 0.676200
Iteration 184, loss = 6240054.83416921
Validation score: 0.676387
Iteration 185, loss = 6238260.98041386
Validation score: 0.676641
Iteration 186, loss = 6235881.63552041
Validation score: 0.676718
Iteration 187, loss = 6232969.94372667
Validation score: 0.676739
Iteration 188, loss = 6232101.90199897
Validation score: 0.677334
Iteration 189, loss = 6227618.04771371
Validation score: 0.677168
Iteration 190, loss = 6226283.62159533
Validation score: 0.677145
Iteration 191, loss = 6224332.73091285
Validation score: 0.677239
Iteration 192, loss = 6221936.41519583
Validation score: 0.677307
Iteration 193, loss = 6221306.66409047
Validation score: 0.677198
Iteration 194, loss = 6219932.36461450
Validation score: 0.677157
Iteration 195, loss = 6216849.70473599
Validation score: 0.677220
Iteration 196, loss = 6214549.87136571
Validation score: 0.677706
Iteration 197, loss = 6212065.35185241
Validation score: 0.677506
Iteration 198, loss = 6211068.64285037
Validation score: 0.677823
Iteration 199, loss = 6208933.53381391
Validation score: 0.678022
Iteration 200, loss = 6205691.39165602
Validation score: 0.678020
Iteration 201, loss = 6204593.61687549
Validation score: 0.678212
Iteration 202, loss = 6203084.56414560
Validation score: 0.678426
Iteration 203, loss = 6200424.81498506
Validation score: 0.678299
Iteration 204, loss = 6199244.32797511
Validation score: 0.678444
Iteration 205, loss = 6196603.82477225
Validation score: 0.678654
Iteration 206, loss = 6194151.24945999
Validation score: 0.678670
Iteration 207, loss = 6192103.11104081
Validation score: 0.678835
Iteration 208, loss = 6191430.68459337
Validation score: 0.679109
Iteration 209, loss = 6191609.75693058
Validation score: 0.679088
Iteration 210, loss = 6186951.34820400
Validation score: 0.679190
Iteration 211, loss = 6187010.13202558
Validation score: 0.679148
Iteration 212, loss = 6184687.19204923
Validation score: 0.679317
Iteration 213, loss = 6181896.54382841
Validation score: 0.679396
Iteration 214, loss = 6180921.31751557
Validation score: 0.679326
Iteration 215, loss = 6179414.93945449
Validation score: 0.679472
Iteration 216, loss = 6177365.82892429
Validation score: 0.679648
Iteration 217, loss = 6176587.83575793
Validation score: 0.679632
Iteration 218, loss = 6173102.46720285
Validation score: 0.679824
Iteration 219, loss = 6172415.40065177
Validation score: 0.679673
Iteration 220, loss = 6170000.12843777
Validation score: 0.679804
Iteration 221, loss = 6168513.90992231
Validation score: 0.679976
Iteration 222, loss = 6167216.98565458
Validation score: 0.680162
Iteration 223, loss = 6163479.54305220
Validation score: 0.680161
Iteration 224, loss = 6162564.48816973
Validation score: 0.679996
Iteration 225, loss = 6160543.59791734
Validation score: 0.680134
Iteration 226, loss = 6160207.33221539
Validation score: 0.680048
Iteration 227, loss = 6155487.38561349
Validation score: 0.680151
Iteration 228, loss = 6155707.43273087
Validation score: 0.680406
Iteration 229, loss = 6153519.14308879
Validation score: 0.680560
Iteration 230, loss = 6151744.82583870
Validation score: 0.680545
Iteration 231, loss = 6150565.94827970
Validation score: 0.680578
Iteration 232, loss = 6149266.90321809
Validation score: 0.680835
Iteration 233, loss = 6145777.29306555
Validation score: 0.680915
Iteration 234, loss = 6144083.23612563
Validation score: 0.680795
Iteration 235, loss = 6143366.71770120
Validation score: 0.680889
Iteration 236, loss = 6141448.24719460
Validation score: 0.680994
Iteration 237, loss = 6138090.92041172
Validation score: 0.680989
Iteration 238, loss = 6136841.21020891
Validation score: 0.681298
Iteration 239, loss = 6135328.91490081
Validation score: 0.681243
Iteration 240, loss = 6133470.66597130
Validation score: 0.681320
Iteration 241, loss = 6131746.04720368
Validation score: 0.681450
Iteration 242, loss = 6130539.44262976
Validation score: 0.681468
Iteration 243, loss = 6128027.80282380
Validation score: 0.681661
Iteration 244, loss = 6130811.72423465
Validation score: 0.681639
Iteration 245, loss = 6125514.06152072
Validation score: 0.681749
Iteration 246, loss = 6122641.61278386
Validation score: 0.681848
Iteration 247, loss = 6120873.43963131
Validation score: 0.681904
Iteration 248, loss = 6122441.65756606
Validation score: 0.682088
Iteration 249, loss = 6118608.22478311
Validation score: 0.682211
Iteration 250, loss = 6118824.70647732
Validation score: 0.682297
Iteration 251, loss = 6113933.82560718
Validation score: 0.682398
Iteration 252, loss = 6113318.07233651
Validation score: 0.682478
Iteration 253, loss = 6111206.25318101
Validation score: 0.682474
Iteration 254, loss = 6108951.24963322
Validation score: 0.682537
Iteration 255, loss = 6108024.03321777
Validation score: 0.682686
Iteration 256, loss = 6107572.68379134
Validation score: 0.683022
Iteration 257, loss = 6104170.63663403
Validation score: 0.683043
Iteration 258, loss = 6102216.55598638
Validation score: 0.683149
Iteration 259, loss = 6101163.91452210
Validation score: 0.683390
Iteration 260, loss = 6101262.30354919
Validation score: 0.683555
Iteration 261, loss = 6097999.99848977
Validation score: 0.683711
Iteration 262, loss = 6096112.73619868
Validation score: 0.683625
Iteration 263, loss = 6094258.16915935
Validation score: 0.683566
Iteration 264, loss = 6092003.09418756
Validation score: 0.683792
Iteration 265, loss = 6090125.32161957
Validation score: 0.683971
Iteration 266, loss = 6088357.53321949
Validation score: 0.683953
Iteration 267, loss = 6086023.87031929
Validation score: 0.683827
Iteration 268, loss = 6085383.56875230
Validation score: 0.683950
Iteration 269, loss = 6083108.13434427
Validation score: 0.683853
Iteration 270, loss = 6081999.37907293
Validation score: 0.684000
Iteration 271, loss = 6079592.28770770
Validation score: 0.684137
Iteration 272, loss = 6077609.30963710
Validation score: 0.684229
Iteration 273, loss = 6077257.83330946
Validation score: 0.684169
Iteration 274, loss = 6074902.56255328
Validation score: 0.684287
Iteration 275, loss = 6074421.80696606
Validation score: 0.684485
Iteration 276, loss = 6071133.49373363
Validation score: 0.684513
Iteration 277, loss = 6071033.30501913
Validation score: 0.684655
Iteration 278, loss = 6067271.81995004
Validation score: 0.684827
Iteration 279, loss = 6065104.82535639
Validation score: 0.684935
Iteration 280, loss = 6063546.10548659
Validation score: 0.685010
Iteration 281, loss = 6061650.03998837
Validation score: 0.685026
Iteration 282, loss = 6060693.52957325
Validation score: 0.684999
Iteration 283, loss = 6058662.24203101
Validation score: 0.685080
Iteration 284, loss = 6058507.98028613
Validation score: 0.685163
Iteration 285, loss = 6056191.95515394
Validation score: 0.685342
Iteration 286, loss = 6052437.03150329
Validation score: 0.685537
Iteration 287, loss = 6052627.37056168
Validation score: 0.685525
Iteration 288, loss = 6051229.78635727
Validation score: 0.685630
Iteration 289, loss = 6050262.27670191
Validation score: 0.685524
Iteration 290, loss = 6047480.14281536
Validation score: 0.685839
Iteration 291, loss = 6043517.35652875
Validation score: 0.685986
Iteration 292, loss = 6040967.65481307
Validation score: 0.685934
Iteration 293, loss = 6043408.07498180
Validation score: 0.685899
Iteration 294, loss = 6037669.13076825
Validation score: 0.686179
Iteration 295, loss = 6036893.74766664
Validation score: 0.686477
Iteration 296, loss = 6035802.73759702
Validation score: 0.686570
Iteration 297, loss = 6034605.64148105
Validation score: 0.686444
Iteration 298, loss = 6030958.97692234
Validation score: 0.686570
Iteration 299, loss = 6028673.53092828
Validation score: 0.686792
Iteration 300, loss = 6026916.52472927
Validation score: 0.687013
Iteration 301, loss = 6024944.41055433
Validation score: 0.687065
Iteration 302, loss = 6024406.07425003
Validation score: 0.687238
Iteration 303, loss = 6020649.72473800
Validation score: 0.687071
Iteration 304, loss = 6018759.08755313
Validation score: 0.687366

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 365572318.90708107
Validation score: -4.614965
Iteration 2, loss = 359675746.38158017
Validation score: -4.461755
Iteration 3, loss = 346016414.28979415
Validation score: -4.187957
Iteration 4, loss = 325349008.50613379
Validation score: -3.818758
Iteration 5, loss = 299563726.34777141
Validation score: -3.384756
Iteration 6, loss = 270281923.30856311
Validation score: -2.907686
Iteration 7, loss = 239101596.41135418
Validation score: -2.420996
Iteration 8, loss = 207698879.51257604
Validation score: -1.941634
Iteration 9, loss = 177470339.09430611
Validation score: -1.491688
Iteration 10, loss = 149615703.45261839
Validation score: -1.093316
Iteration 11, loss = 124963977.84584825
Validation score: -0.746004
Iteration 12, loss = 103993876.90128081
Validation score: -0.462173
Iteration 13, loss = 86906725.85225058
Validation score: -0.238486
Iteration 14, loss = 73561967.21477240
Validation score: -0.070928
Iteration 15, loss = 63530055.80235954
Validation score: 0.051105
Iteration 16, loss = 56293879.14502227
Validation score: 0.134741
Iteration 17, loss = 51221644.78125959
Validation score: 0.191492
Iteration 18, loss = 47765230.97159015
Validation score: 0.228727
Iteration 19, loss = 45449603.16410257
Validation score: 0.252903
Iteration 20, loss = 43913590.16778751
Validation score: 0.268905
Iteration 21, loss = 42862112.71079372
Validation score: 0.280571
Iteration 22, loss = 42107225.04801080
Validation score: 0.289064
Iteration 23, loss = 41533075.11105287
Validation score: 0.296912
Iteration 24, loss = 41075057.03135474
Validation score: 0.302828
Iteration 25, loss = 40681825.09794866
Validation score: 0.308136
Iteration 26, loss = 40348529.14512429
Validation score: 0.313537
Iteration 27, loss = 40038539.57828565
Validation score: 0.318491
Iteration 28, loss = 39765635.36339756
Validation score: 0.322227
Iteration 29, loss = 39505616.72470389
Validation score: 0.326702
Iteration 30, loss = 39275373.48117198
Validation score: 0.330601
Iteration 31, loss = 39053866.92669642
Validation score: 0.333813
Iteration 32, loss = 38857845.52938382
Validation score: 0.336785
Iteration 33, loss = 38674364.86225289
Validation score: 0.339534
Iteration 34, loss = 38501477.07601793
Validation score: 0.342580
Iteration 35, loss = 38335786.18603110
Validation score: 0.344979
Iteration 36, loss = 38187824.43635211
Validation score: 0.347216
Iteration 37, loss = 38046004.30454777
Validation score: 0.349540
Iteration 38, loss = 37919411.76829059
Validation score: 0.351289
Iteration 39, loss = 37795064.93337251
Validation score: 0.352937
Iteration 40, loss = 37674145.48169964
Validation score: 0.354434
Iteration 41, loss = 37573530.13239633
Validation score: 0.356152
Iteration 42, loss = 37461896.86715077
Validation score: 0.358003
Iteration 43, loss = 37362018.27483619
Validation score: 0.359749
Iteration 44, loss = 37273079.03172001
Validation score: 0.361747
Iteration 45, loss = 37185118.85655869
Validation score: 0.362396
Iteration 46, loss = 37085824.76266304
Validation score: 0.363664
Iteration 47, loss = 36997771.85395522
Validation score: 0.364843
Iteration 48, loss = 36914770.12891466
Validation score: 0.366294
Iteration 49, loss = 36822372.11752656
Validation score: 0.367688
Iteration 50, loss = 36745581.49589872
Validation score: 0.367753
Iteration 51, loss = 36658708.92732967
Validation score: 0.368929
Iteration 52, loss = 36556845.22484925
Validation score: 0.370783
Iteration 53, loss = 36482829.27034455
Validation score: 0.371769
Iteration 54, loss = 36394813.21842073
Validation score: 0.373413
Iteration 55, loss = 36317176.64511111
Validation score: 0.373545
Iteration 56, loss = 36242457.73469852
Validation score: 0.375356
Iteration 57, loss = 36159670.16266587
Validation score: 0.376272
Iteration 58, loss = 36089415.57185965
Validation score: 0.377499
Iteration 59, loss = 36008109.83120275
Validation score: 0.377857
Iteration 60, loss = 35944120.19519810
Validation score: 0.377977
Iteration 61, loss = 35875071.93948486
Validation score: 0.379658
Iteration 62, loss = 35801313.51895554
Validation score: 0.380841
Iteration 63, loss = 35727682.99480798
Validation score: 0.381043
Iteration 64, loss = 35657570.88194270
Validation score: 0.382266
Iteration 65, loss = 35595887.01649503
Validation score: 0.382936
Iteration 66, loss = 35528446.35087034
Validation score: 0.384262
Iteration 67, loss = 35464065.57604256
Validation score: 0.384295
Iteration 68, loss = 35405372.61643820
Validation score: 0.385482
Iteration 69, loss = 35336887.96939498
Validation score: 0.386350
Iteration 70, loss = 35285866.99204207
Validation score: 0.386293
Iteration 71, loss = 35216235.31992536
Validation score: 0.387618
Iteration 72, loss = 35156247.39294609
Validation score: 0.388852
Iteration 73, loss = 35094983.60193618
Validation score: 0.388585
Iteration 74, loss = 35032634.01376183
Validation score: 0.390605
Iteration 75, loss = 34979957.61997936
Validation score: 0.390774
Iteration 76, loss = 34918519.25692640
Validation score: 0.390678
Iteration 77, loss = 34857462.04557583
Validation score: 0.392253
Iteration 78, loss = 34806321.12848233
Validation score: 0.393472
Iteration 79, loss = 34748283.07694670
Validation score: 0.393942
Iteration 80, loss = 34696494.90808457
Validation score: 0.393839
Iteration 81, loss = 34640801.45084333
Validation score: 0.395239
Iteration 82, loss = 34587362.72105940
Validation score: 0.396252
Iteration 83, loss = 34531045.24542345
Validation score: 0.396811
Iteration 84, loss = 34477372.46504059
Validation score: 0.397402
Iteration 85, loss = 34423161.99870396
Validation score: 0.397823
Iteration 86, loss = 34372050.56967068
Validation score: 0.398933
Iteration 87, loss = 34329947.68371606
Validation score: 0.399554
Iteration 88, loss = 34280128.18510589
Validation score: 0.399440
Iteration 89, loss = 34220752.51258353
Validation score: 0.400621
Iteration 90, loss = 34170185.63881939
Validation score: 0.400601
Iteration 91, loss = 34121979.39267050
Validation score: 0.400850
Iteration 92, loss = 34085105.05568457
Validation score: 0.401128
Iteration 93, loss = 34032499.27267175
Validation score: 0.402734
Iteration 94, loss = 33979327.86345546
Validation score: 0.402877
Iteration 95, loss = 33932587.58463284
Validation score: 0.403861
Iteration 96, loss = 33889354.13950597
Validation score: 0.404462
Iteration 97, loss = 33836576.19738814
Validation score: 0.404349
Iteration 98, loss = 33792937.29166999
Validation score: 0.405720
Iteration 99, loss = 33759860.67471170
Validation score: 0.407060
Iteration 100, loss = 33702119.06245736
Validation score: 0.405965
Iteration 101, loss = 33658189.70945574
Validation score: 0.406579
Iteration 102, loss = 33621947.39384839
Validation score: 0.407519
Iteration 103, loss = 33570674.92644510
Validation score: 0.407214
Iteration 104, loss = 33538636.25171232
Validation score: 0.408080
Iteration 105, loss = 33493858.51040834
Validation score: 0.409565
Iteration 106, loss = 33457068.85864309
Validation score: 0.409871
Iteration 107, loss = 33414354.10253822
Validation score: 0.409366
Iteration 108, loss = 33376859.59590011
Validation score: 0.409864
Iteration 109, loss = 33325222.04563561
Validation score: 0.411212
Iteration 110, loss = 33287873.65662108
Validation score: 0.411051
Iteration 111, loss = 33247371.82095325
Validation score: 0.412010
Iteration 112, loss = 33213188.25847309
Validation score: 0.412708
Iteration 113, loss = 33186763.04118514
Validation score: 0.413824
Iteration 114, loss = 33136119.32058794
Validation score: 0.413081
Iteration 115, loss = 33096565.24847185
Validation score: 0.413357
Iteration 116, loss = 33072937.92403375
Validation score: 0.414113
Iteration 117, loss = 33024960.29592283
Validation score: 0.414771
Iteration 118, loss = 32984516.20999883
Validation score: 0.415087
Iteration 119, loss = 32954482.19013619
Validation score: 0.415568
Iteration 120, loss = 32918435.78206274
Validation score: 0.415435
Iteration 121, loss = 32885000.46461734
Validation score: 0.415685
Iteration 122, loss = 32847094.53276046
Validation score: 0.416643
Iteration 123, loss = 32819121.89572836
Validation score: 0.415992
Iteration 124, loss = 32778355.72203931
Validation score: 0.417131
Iteration 125, loss = 32744908.72274921
Validation score: 0.417667
Iteration 126, loss = 32721772.56394498
Validation score: 0.418417
Iteration 127, loss = 32684626.23099610
Validation score: 0.418686
Iteration 128, loss = 32658200.71317447
Validation score: 0.419539
Iteration 129, loss = 32623171.23708227
Validation score: 0.419584
Iteration 130, loss = 32590272.20274793
Validation score: 0.420184
Iteration 131, loss = 32559192.14584347
Validation score: 0.420194
Iteration 132, loss = 32526800.60945515
Validation score: 0.420236
Iteration 133, loss = 32501257.08404700
Validation score: 0.421313
Iteration 134, loss = 32472519.67064904
Validation score: 0.421425
Iteration 135, loss = 32436417.01629462
Validation score: 0.421081
Iteration 136, loss = 32399427.01588922
Validation score: 0.422520
Iteration 137, loss = 32376906.99205774
Validation score: 0.422074
Iteration 138, loss = 32338292.94570062
Validation score: 0.422410
Iteration 139, loss = 32320956.54315686
Validation score: 0.423127
Iteration 140, loss = 32288448.17003950
Validation score: 0.423184
Iteration 141, loss = 32264502.35967335
Validation score: 0.423562
Iteration 142, loss = 32230828.30806508
Validation score: 0.424747
Iteration 143, loss = 32207414.62197875
Validation score: 0.425038
Iteration 144, loss = 32170667.45963438
Validation score: 0.424755
Iteration 145, loss = 32144996.27933933
Validation score: 0.425016
Iteration 146, loss = 32119863.13854891
Validation score: 0.424972
Iteration 147, loss = 32095285.72423112
Validation score: 0.425827
Iteration 148, loss = 32062231.14819599
Validation score: 0.425863
Iteration 149, loss = 32033097.14545098
Validation score: 0.426701
Iteration 150, loss = 32013737.17662783
Validation score: 0.426441
Iteration 151, loss = 31981153.65318675
Validation score: 0.427165
Iteration 152, loss = 31953916.76434752
Validation score: 0.427560
Iteration 153, loss = 31933893.46371875
Validation score: 0.428414
Iteration 154, loss = 31902743.20984118
Validation score: 0.427776
Iteration 155, loss = 31875989.06551531
Validation score: 0.427927
Iteration 156, loss = 31852161.50218306
Validation score: 0.429661
Iteration 157, loss = 31834652.30666859
Validation score: 0.429593
Iteration 158, loss = 31801673.40491815
Validation score: 0.429177
Iteration 159, loss = 31780683.35226848
Validation score: 0.429921
Iteration 160, loss = 31762821.95636581
Validation score: 0.430962
Iteration 161, loss = 31723292.04316757
Validation score: 0.430686
Iteration 162, loss = 31717112.54508810
Validation score: 0.431249
Iteration 163, loss = 31676528.14473285
Validation score: 0.431366
Iteration 164, loss = 31656129.93448583
Validation score: 0.432209
Iteration 165, loss = 31639779.05953096
Validation score: 0.432693
Iteration 166, loss = 31601985.34085799
Validation score: 0.432757
Iteration 167, loss = 31580549.28949441
Validation score: 0.432803
Iteration 168, loss = 31554128.87428487
Validation score: 0.433500
Iteration 169, loss = 31534343.96112113
Validation score: 0.434249
Iteration 170, loss = 31520545.46921127
Validation score: 0.433257
Iteration 171, loss = 31485893.18670756
Validation score: 0.434395
Iteration 172, loss = 31463875.16061192
Validation score: 0.434726
Iteration 173, loss = 31439990.24677660
Validation score: 0.435565
Iteration 174, loss = 31412296.37406202
Validation score: 0.435493
Iteration 175, loss = 31399281.25250181
Validation score: 0.435837
Iteration 176, loss = 31368261.75599427
Validation score: 0.436091
Iteration 177, loss = 31349530.22918545
Validation score: 0.436721
Iteration 178, loss = 31339216.37826778
Validation score: 0.437275
Iteration 179, loss = 31293592.45161507
Validation score: 0.436614
Iteration 180, loss = 31288745.55186892
Validation score: 0.436598
Iteration 181, loss = 31256441.00458455
Validation score: 0.437491
Iteration 182, loss = 31229272.37756196
Validation score: 0.438355
Iteration 183, loss = 31220756.03238712
Validation score: 0.437711
Iteration 184, loss = 31187848.40806909
Validation score: 0.438359
Iteration 185, loss = 31181652.04110305
Validation score: 0.439537
Iteration 186, loss = 31152683.64798484
Validation score: 0.439694
Iteration 187, loss = 31127580.26218285
Validation score: 0.439784
Iteration 188, loss = 31099697.22392294
Validation score: 0.439690
Iteration 189, loss = 31083197.28297729
Validation score: 0.440629
Iteration 190, loss = 31055273.50485412
Validation score: 0.440401
Iteration 191, loss = 31037804.17958672
Validation score: 0.440559
Iteration 192, loss = 31016996.99467707
Validation score: 0.442074
Iteration 193, loss = 30998423.54676327
Validation score: 0.440753
Iteration 194, loss = 30974502.91139056
Validation score: 0.441809
Iteration 195, loss = 30948292.80627568
Validation score: 0.441965
Iteration 196, loss = 30925897.25059763
Validation score: 0.443163
Iteration 197, loss = 30916429.16658315
Validation score: 0.442213
Iteration 198, loss = 30881964.43575072
Validation score: 0.443184
Iteration 199, loss = 30861705.51046041
Validation score: 0.443154
Iteration 200, loss = 30848906.88823261
Validation score: 0.443407
Iteration 201, loss = 30830612.28441947
Validation score: 0.444357
Iteration 202, loss = 30797941.41859445
Validation score: 0.444026
Iteration 203, loss = 30772018.25062463
Validation score: 0.444372
Iteration 204, loss = 30758543.88387029
Validation score: 0.444751
Iteration 205, loss = 30735050.25527361
Validation score: 0.445704
Iteration 206, loss = 30709757.59840231
Validation score: 0.445472
Iteration 207, loss = 30687642.00831633
Validation score: 0.445650
Iteration 208, loss = 30660040.73882204
Validation score: 0.446573
Iteration 209, loss = 30652029.92578402
Validation score: 0.446948
Iteration 210, loss = 30626586.93849647
Validation score: 0.447745
Iteration 211, loss = 30605404.69746371
Validation score: 0.448100
Iteration 212, loss = 30579447.17107450
Validation score: 0.447369
Iteration 213, loss = 30557272.39184483
Validation score: 0.448066
Iteration 214, loss = 30547807.54261539
Validation score: 0.448822
Iteration 215, loss = 30524621.36567801
Validation score: 0.448653
Iteration 216, loss = 30503725.04076162
Validation score: 0.448474
Iteration 217, loss = 30472818.67288643
Validation score: 0.448758
Iteration 218, loss = 30452105.10868338
Validation score: 0.449808
Iteration 219, loss = 30433082.20496169
Validation score: 0.449185
Iteration 220, loss = 30421280.05117239
Validation score: 0.449941
Iteration 221, loss = 30396374.27583551
Validation score: 0.449785
Iteration 222, loss = 30370429.82455431
Validation score: 0.450164
Iteration 223, loss = 30356638.08526712
Validation score: 0.449733
Iteration 224, loss = 30329846.38193889
Validation score: 0.451481
Iteration 225, loss = 30324177.41502267
Validation score: 0.451752
Iteration 226, loss = 30291854.45511321
Validation score: 0.451516
Iteration 227, loss = 30272059.45564364
Validation score: 0.451328
Iteration 228, loss = 30282029.42661768
Validation score: 0.452950
Iteration 229, loss = 30242655.82671279
Validation score: 0.452803
Iteration 230, loss = 30215024.94672560
Validation score: 0.452859
Iteration 231, loss = 30194856.50467156
Validation score: 0.453509
Iteration 232, loss = 30181689.80891127
Validation score: 0.452799
Iteration 233, loss = 30156988.74838573
Validation score: 0.454146
Iteration 234, loss = 30139338.13588353
Validation score: 0.454153
Iteration 235, loss = 30124028.63615702
Validation score: 0.454488
Iteration 236, loss = 30103436.74461632
Validation score: 0.454795
Iteration 237, loss = 30082911.08445821
Validation score: 0.454869
Iteration 238, loss = 30062314.37641596
Validation score: 0.453965
Iteration 239, loss = 30047961.62509067
Validation score: 0.454732
Iteration 240, loss = 30025070.38045424
Validation score: 0.455272
Iteration 241, loss = 30002343.42011338
Validation score: 0.455640
Iteration 242, loss = 30007517.35368207
Validation score: 0.455615
Iteration 243, loss = 29979318.17251452
Validation score: 0.457279
Iteration 244, loss = 29953690.76890039
Validation score: 0.457257
Iteration 245, loss = 29936888.53748195
Validation score: 0.456972
Iteration 246, loss = 29921098.81613079
Validation score: 0.457876
Iteration 247, loss = 29896117.56823229
Validation score: 0.458117
Iteration 248, loss = 29876534.49572172
Validation score: 0.458249
Iteration 249, loss = 29856820.36840960
Validation score: 0.458075
Iteration 250, loss = 29841516.08320859
Validation score: 0.458460
Iteration 251, loss = 29818955.07294013
Validation score: 0.458939
Iteration 252, loss = 29799083.55950835
Validation score: 0.459357
Iteration 253, loss = 29788548.64918979
Validation score: 0.459019
Iteration 254, loss = 29767039.74867729
Validation score: 0.459105
Iteration 255, loss = 29746179.79002940
Validation score: 0.459641
Iteration 256, loss = 29729071.51151596
Validation score: 0.460337
Iteration 257, loss = 29711688.18108053
Validation score: 0.460548
Iteration 258, loss = 29692623.24500844
Validation score: 0.460521
Iteration 259, loss = 29680414.26768137
Validation score: 0.461430
Iteration 260, loss = 29659304.03272057
Validation score: 0.460893
Iteration 261, loss = 29637863.35615280
Validation score: 0.462110
Iteration 262, loss = 29622288.01457159
Validation score: 0.461969
Iteration 263, loss = 29611460.93298329
Validation score: 0.462268
Iteration 264, loss = 29586655.55041713
Validation score: 0.462606
Iteration 265, loss = 29573543.04935931
Validation score: 0.463628
Iteration 266, loss = 29560207.99205337
Validation score: 0.463322
Iteration 267, loss = 29545344.33768262
Validation score: 0.464218
Iteration 268, loss = 29520851.18675395
Validation score: 0.463898
Iteration 269, loss = 29501471.26714726
Validation score: 0.463617
Iteration 270, loss = 29483189.00014012
Validation score: 0.464341
Iteration 271, loss = 29463336.52757706
Validation score: 0.463898
Iteration 272, loss = 29454797.63162907
Validation score: 0.464781
Iteration 273, loss = 29438258.39989071
Validation score: 0.465369
Iteration 274, loss = 29411579.37769535
Validation score: 0.465427
Iteration 275, loss = 29392656.45796070
Validation score: 0.465199
Iteration 276, loss = 29378003.84946686
Validation score: 0.465599
Iteration 277, loss = 29370032.51721386
Validation score: 0.466297
Iteration 278, loss = 29356190.43250301
Validation score: 0.465645
Iteration 279, loss = 29326364.09588115
Validation score: 0.467005
Iteration 280, loss = 29311369.98200950
Validation score: 0.467312
Iteration 281, loss = 29303434.82942856
Validation score: 0.467780
Iteration 282, loss = 29278274.91179950
Validation score: 0.467400
Iteration 283, loss = 29263543.35443221
Validation score: 0.466929
Iteration 284, loss = 29241188.06564596
Validation score: 0.468239
Iteration 285, loss = 29233878.30082859
Validation score: 0.467764
Iteration 286, loss = 29213700.48651985
Validation score: 0.467239
Iteration 287, loss = 29198076.53935502
Validation score: 0.468911
Iteration 288, loss = 29196735.69575912
Validation score: 0.468722
Iteration 289, loss = 29162094.12315554
Validation score: 0.470400
Iteration 290, loss = 29154942.25159257
Validation score: 0.470024
Iteration 291, loss = 29130042.28873249
Validation score: 0.470250
Iteration 292, loss = 29107870.29037062
Validation score: 0.470100
Iteration 293, loss = 29099441.52403552
Validation score: 0.470430
Iteration 294, loss = 29080823.33595034
Validation score: 0.470237
Iteration 295, loss = 29069511.47318121
Validation score: 0.470384
Iteration 296, loss = 29056741.29883309
Validation score: 0.470494
Iteration 297, loss = 29030130.18719908
Validation score: 0.471867
Iteration 298, loss = 29015960.17370613
Validation score: 0.472517
Iteration 299, loss = 28999528.76893741
Validation score: 0.472351
Iteration 300, loss = 28981218.11236746

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 2, loss = 98324162.98309024
Validation score: -5.011775
Iteration 3, loss = 97972637.62936974
Validation score: -4.983153
Iteration 4, loss = 97363271.55921057
Validation score: -4.938300
Iteration 5, loss = 96477643.53299303
Validation score: -4.876617
Iteration 6, loss = 95307143.40183179
Validation score: -4.798195
Iteration 7, loss = 93866011.98302017
Validation score: -4.703533
Iteration 8, loss = 92159897.10906240
Validation score: -4.594594
Iteration 9, loss = 90222150.80634695
Validation score: -4.470986
Iteration 10, loss = 88054875.40617353
Validation score: -4.335377
Iteration 11, loss = 85694040.01866952
Validation score: -4.187456
Iteration 12, loss = 83146122.81623276
Validation score: -4.029667
Iteration 13, loss = 80435164.12648742
Validation score: -3.864233
Iteration 14, loss = 77604858.99609427
Validation score: -3.690748
Iteration 15, loss = 74670499.91052884
Validation score: -3.511079
Iteration 16, loss = 71650227.40577872
Validation score: -3.328589
Iteration 17, loss = 68588027.28392135
Validation score: -3.142325
Iteration 18, loss = 65483290.35279006
Validation score: -2.956199
Iteration 19, loss = 62371115.18294969
Validation score: -2.768895
Iteration 20, loss = 59261512.45182149
Validation score: -2.581893
Iteration 21, loss = 56172316.50271291
Validation score: -2.397810
Iteration 22, loss = 53128468.95866226
Validation score: -2.216109
Iteration 23, loss = 50146583.17997723
Validation score: -2.038521
Iteration 24, loss = 47254450.07690536
Validation score: -1.864666
Iteration 25, loss = 44445540.02723669
Validation score: -1.699012
Iteration 26, loss = 41758344.56848232
Validation score: -1.539285
Iteration 27, loss = 39174078.87675995
Validation score: -1.388024
Iteration 28, loss = 36737963.22167856
Validation score: -1.240805
Iteration 29, loss = 34397990.63878522
Validation score: -1.105308
Iteration 30, loss = 32217261.74132824
Validation score: -0.974903
Iteration 31, loss = 30157387.38534901
Validation score: -0.854005
Iteration 32, loss = 28244657.23212173
Validation score: -0.739576
Iteration 33, loss = 26459450.92618273
Validation score: -0.632795
Iteration 34, loss = 24803933.71480315
Validation score: -0.534148
Iteration 35, loss = 23274079.82819962
Validation score: -0.444375
Iteration 36, loss = 21876823.52047116
Validation score: -0.359516
Iteration 37, loss = 20585647.58453208
Validation score: -0.282595
Iteration 38, loss = 19409272.25610489
Validation score: -0.212308
Iteration 39, loss = 18337277.60779692
Validation score: -0.146294
Iteration 40, loss = 17352817.03837531
Validation score: -0.087114
Iteration 41, loss = 16463726.44388312
Validation score: -0.033062
Iteration 42, loss = 15655314.76423211
Validation score: 0.016483
Iteration 43, loss = 14923050.96738113
Validation score: 0.062263
Iteration 44, loss = 14253416.89859191
Validation score: 0.103213
Iteration 45, loss = 13644726.92241021
Validation score: 0.140488
Iteration 46, loss = 13096437.72527739
Validation score: 0.175649
Iteration 47, loss = 12589858.21407545
Validation score: 0.206354
Iteration 48, loss = 12139999.21079744
Validation score: 0.236144
Iteration 49, loss = 11718565.99503822
Validation score: 0.262367
Iteration 50, loss = 11339788.38019251
Validation score: 0.286281
Iteration 51, loss = 10995574.97529709
Validation score: 0.308915
Iteration 52, loss = 10676866.71814589
Validation score: 0.329295
Iteration 53, loss = 10387749.96099878
Validation score: 0.348256
Iteration 54, loss = 10122228.48509483
Validation score: 0.366357
Iteration 55, loss = 9869495.07398478
Validation score: 0.381519
Iteration 56, loss = 9646268.99161658
Validation score: 0.397146
Iteration 57, loss = 9430743.00497776
Validation score: 0.410693
Iteration 58, loss = 9236849.82942245
Validation score: 0.423861
Iteration 59, loss = 9054178.21214513
Validation score: 0.435844
Iteration 60, loss = 8883700.55412299
Validation score: 0.447109
Iteration 61, loss = 8724188.94670475
Validation score: 0.457461
Iteration 62, loss = 8574374.51824340
Validation score: 0.467181
Iteration 63, loss = 8433544.96017009
Validation score: 0.476355
Iteration 64, loss = 8299945.68326315
Validation score: 0.484950
Iteration 65, loss = 8176086.49626264
Validation score: 0.493568
Iteration 66, loss = 8056008.91566511
Validation score: 0.501225
Iteration 67, loss = 7942763.71202264
Validation score: 0.508203
Iteration 68, loss = 7837665.00423032
Validation score: 0.515269
Iteration 69, loss = 7734523.65244338
Validation score: 0.521449
Iteration 70, loss = 7639621.87435372
Validation score: 0.527942
Iteration 71, loss = 7545924.22290769
Validation score: 0.533715
Iteration 72, loss = 7458533.77479348
Validation score: 0.539509
Iteration 73, loss = 7372327.01354192
Validation score: 0.544422
Iteration 74, loss = 7292987.41369018
Validation score: 0.549208
Iteration 75, loss = 7215010.46373737
Validation score: 0.554310
Iteration 76, loss = 7142785.65747210
Validation score: 0.558898
Iteration 77, loss = 7070416.53431440
Validation score: 0.563007
Iteration 78, loss = 7002518.26939252
Validation score: 0.567377
Iteration 79, loss = 6937157.85230315
Validation score: 0.571215
Iteration 80, loss = 6876121.37279275
Validation score: 0.574742
Iteration 81, loss = 6814768.07984224
Validation score: 0.578155
Iteration 82, loss = 6758660.58942099
Validation score: 0.582116
Iteration 83, loss = 6702461.51148067
Validation score: 0.585266
Iteration 84, loss = 6651374.45830432
Validation score: 0.587784
Iteration 85, loss = 6601128.63312372
Validation score: 0.591052
Iteration 86, loss = 6551704.75716504
Validation score: 0.593596
Iteration 87, loss = 6505106.48114792
Validation score: 0.596177
Iteration 88, loss = 6461708.94158421
Validation score: 0.598657
Iteration 89, loss = 6419623.44229576
Validation score: 0.601082
Iteration 90, loss = 6378040.43606297
Validation score: 0.603177
Iteration 91, loss = 6339917.27220439
Validation score: 0.605469
Iteration 92, loss = 6301552.82812376
Validation score: 0.607176
Iteration 93, loss = 6266250.16963378
Validation score: 0.608655
Iteration 94, loss = 6232014.07192491
Validation score: 0.610997
Iteration 95, loss = 6198335.30619868
Validation score: 0.612526
Iteration 96, loss = 6167091.47406922
Validation score: 0.613850
Iteration 97, loss = 6136024.38492655
Validation score: 0.615575
Iteration 98, loss = 6108205.28263912
Validation score: 0.616645
Iteration 99, loss = 6079898.17852334
Validation score: 0.618625
Iteration 100, loss = 6052303.15343795
Validation score: 0.619652
Iteration 101, loss = 6026927.83275685
Validation score: 0.620857
Iteration 102, loss = 6002960.19471076
Validation score: 0.621510
Iteration 103, loss = 5979682.71551434
Validation score: 0.622699
Iteration 104, loss = 5956834.51134897
Validation score: 0.623883
Iteration 105, loss = 5935632.21664637
Validation score: 0.624893
Iteration 106, loss = 5916052.92970137
Validation score: 0.625461
Iteration 107, loss = 5895054.76171163
Validation score: 0.626506
Iteration 108, loss = 5876825.61635776
Validation score: 0.627298
Iteration 109, loss = 5857819.68333458
Validation score: 0.628057
Iteration 110, loss = 5840572.58348223
Validation score: 0.628385
Iteration 111, loss = 5824456.19417455
Validation score: 0.629170
Iteration 112, loss = 5807761.23656423
Validation score: 0.630137
Iteration 113, loss = 5791894.42517251
Validation score: 0.630698
Iteration 114, loss = 5776813.15587116
Validation score: 0.631279
Iteration 115, loss = 5762421.15843826
Validation score: 0.631807
Iteration 116, loss = 5750122.05016716
Validation score: 0.632609
Iteration 117, loss = 5735426.30466348
Validation score: 0.632633
Iteration 118, loss = 5722727.18245884
Validation score: 0.633002
Iteration 119, loss = 5711807.67901187
Validation score: 0.633587
Iteration 120, loss = 5699367.56624013
Validation score: 0.633891
Iteration 121, loss = 5687360.95316903
Validation score: 0.634007
Iteration 122, loss = 5677574.92408775
Validation score: 0.634575
Iteration 123, loss = 5664375.19818099
Validation score: 0.635024
Iteration 124, loss = 5654437.66654085
Validation score: 0.635290
Iteration 125, loss = 5645659.69845589
Validation score: 0.635890
Iteration 126, loss = 5634871.20927997
Validation score: 0.635829
Iteration 127, loss = 5624635.54982857
Validation score: 0.636511
Iteration 128, loss = 5615634.76517572
Validation score: 0.636924
Iteration 129, loss = 5606612.35051156
Validation score: 0.636886
Iteration 130, loss = 5597748.75931680
Validation score: 0.637312
Iteration 131, loss = 5590327.51210254
Validation score: 0.637655
Iteration 132, loss = 5581596.27509660
Validation score: 0.638231
Iteration 133, loss = 5572923.51470436
Validation score: 0.638034
Iteration 134, loss = 5566042.08003051
Validation score: 0.638497
Iteration 135, loss = 5557678.88808388
Validation score: 0.638637
Iteration 136, loss = 5552936.75454130
Validation score: 0.639143
Iteration 137, loss = 5544248.97687474
Validation score: 0.638579
Iteration 138, loss = 5536396.83846968
Validation score: 0.639278
Iteration 139, loss = 5529777.34503700
Validation score: 0.638997
Iteration 140, loss = 5522444.82447232
Validation score: 0.639535
Iteration 141, loss = 5518783.69923045
Validation score: 0.640292
Iteration 142, loss = 5510214.90310264
Validation score: 0.640161
Iteration 143, loss = 5503693.23998954
Validation score: 0.640239
Iteration 144, loss = 5498053.01462177
Validation score: 0.640122
Iteration 145, loss = 5492702.15709134
Validation score: 0.640488
Iteration 146, loss = 5489180.35801664
Validation score: 0.640791
Iteration 147, loss = 5480358.96408135
Validation score: 0.640573
Iteration 148, loss = 5475371.26555601
Validation score: 0.641289
Iteration 149, loss = 5469138.95432396
Validation score: 0.641190
Iteration 150, loss = 5464366.28778869
Validation score: 0.641392
Iteration 151, loss = 5459551.46364080
Validation score: 0.641251
Iteration 152, loss = 5455068.55320476
Validation score: 0.641500
Iteration 153, loss = 5449559.57083896
Validation score: 0.641992
Iteration 154, loss = 5445821.05645149
Validation score: 0.642189
Iteration 155, loss = 5439533.01149881
Validation score: 0.642492
Iteration 156, loss = 5436048.63883947
Validation score: 0.642770
Iteration 157, loss = 5433087.09199575
Validation score: 0.642696
Iteration 158, loss = 5428510.47749144
Validation score: 0.643305
Iteration 159, loss = 5423136.12342729
Validation score: 0.642779
Iteration 160, loss = 5419449.85437865
Validation score: 0.642546
Iteration 161, loss = 5415507.61849662
Validation score: 0.643446
Iteration 162, loss = 5411258.73823985
Validation score: 0.643394
Iteration 163, loss = 5407767.02426934
Validation score: 0.643683
Iteration 164, loss = 5402485.60289936
Validation score: 0.643545
Iteration 165, loss = 5400844.66375280
Validation score: 0.644132
Iteration 166, loss = 5395973.13965929
Validation score: 0.643778
Iteration 167, loss = 5392888.09150650
Validation score: 0.643514
Iteration 168, loss = 5389606.40372171
Validation score: 0.644296
Iteration 169, loss = 5386118.98973933
Validation score: 0.644553
Iteration 170, loss = 5383569.70994186
Validation score: 0.644022
Iteration 171, loss = 5379040.15345560
Validation score: 0.644415
Iteration 172, loss = 5375955.05202533
Validation score: 0.645121
Iteration 173, loss = 5372353.46525193
Validation score: 0.645126
Iteration 174, loss = 5369792.55818371
Validation score: 0.644934
Iteration 175, loss = 5366641.74348547
Validation score: 0.645424
Iteration 176, loss = 5364232.44924963
Validation score: 0.645279
Iteration 177, loss = 5361100.45885786
Validation score: 0.644980
Iteration 178, loss = 5359528.80069923
Validation score: 0.645089
Iteration 179, loss = 5355193.79168395
Validation score: 0.645686
Iteration 180, loss = 5357000.76014497
Validation score: 0.646520
Iteration 181, loss = 5349861.38303106
Validation score: 0.645866
Iteration 182, loss = 5348639.33018227
Validation score: 0.645243
Iteration 183, loss = 5345397.60270511
Validation score: 0.646211
Iteration 184, loss = 5341594.44658717
Validation score: 0.646367
Iteration 185, loss = 5339515.85943553
Validation score: 0.646475
Iteration 186, loss = 5338429.08282818
Validation score: 0.646391
Iteration 187, loss = 5337702.76023573
Validation score: 0.646458
Iteration 188, loss = 5332784.09758207
Validation score: 0.647015
Iteration 189, loss = 5330410.34455130
Validation score: 0.646913
Iteration 190, loss = 5328089.71757442
Validation score: 0.646952
Iteration 191, loss = 5326354.26291442
Validation score: 0.647274
Iteration 192, loss = 5324351.38733815
Validation score: 0.647059
Iteration 193, loss = 5322063.99390841
Validation score: 0.647769
Iteration 194, loss = 5321952.09110200
Validation score: 0.647211
Iteration 195, loss = 5318456.06570466
Validation score: 0.647387
Iteration 196, loss = 5316411.35747525
Validation score: 0.647284
Iteration 197, loss = 5314066.03950046
Validation score: 0.647817
Iteration 198, loss = 5313601.26396219
Validation score: 0.647407
Iteration 199, loss = 5313292.60603046
Validation score: 0.648117
Iteration 200, loss = 5309793.54504788
Validation score: 0.648334
Iteration 201, loss = 5305944.41828501
Validation score: 0.647723
Iteration 202, loss = 5304650.26610156
Validation score: 0.648280
Iteration 203, loss = 5304478.29798580
Validation score: 0.648536
Iteration 204, loss = 5301304.32464995
Validation score: 0.648362
Iteration 205, loss = 5301628.52253811
Validation score: 0.648392
Iteration 206, loss = 5298216.30439672
Validation score: 0.648627
Iteration 207, loss = 5295794.98298521
Validation score: 0.648503
Iteration 208, loss = 5296723.72582786
Validation score: 0.648648
Iteration 209, loss = 5292402.92058343
Validation score: 0.648983
Iteration 210, loss = 5290443.18153371
Validation score: 0.649179
Iteration 211, loss = 5291846.13497004
Validation score: 0.648753
Iteration 212, loss = 5287911.95969156
Validation score: 0.649137
Iteration 213, loss = 5291484.41010045
Validation score: 0.649636
Iteration 214, loss = 5284418.90856892
Validation score: 0.649027
Iteration 215, loss = 5286633.31897948
Validation score: 0.649625
Iteration 216, loss = 5281762.29977554
Validation score: 0.649459
Iteration 217, loss = 5282707.42475421
Validation score: 0.648947
Iteration 218, loss = 5279477.00803706
Validation score: 0.649496
Iteration 219, loss = 5278330.66442863
Validation score: 0.650283
Iteration 220, loss = 5277167.59875174
Validation score: 0.650172
Iteration 221, loss = 5275981.03390372
Validation score: 0.649729
Iteration 222, loss = 5273528.94533119
Validation score: 0.649674
Iteration 223, loss = 5275652.78452570
Validation score: 0.650411
Iteration 224, loss = 5270640.19594278
Validation score: 0.649951
Iteration 225, loss = 5269949.58324182
Validation score: 0.650439
Iteration 226, loss = 5270406.80168651
Validation score: 0.650669
Iteration 227, loss = 5269086.49519586
Validation score: 0.650127
Iteration 228, loss = 5267743.28924950
Validation score: 0.650932
Iteration 229, loss = 5265128.01234967
Validation score: 0.650337
Iteration 230, loss = 5264059.89363960
Validation score: 0.650832
Iteration 231, loss = 5264195.76297640
Validation score: 0.651076
Iteration 232, loss = 5261964.93880335
Validation score: 0.650486
Iteration 233, loss = 5260087.89954521
Validation score: 0.650803
Iteration 234, loss = 5259911.51756418
Validation score: 0.650585
Iteration 235, loss = 5258388.49667438
Validation score: 0.651000
Iteration 236, loss = 5256820.29851148
Validation score: 0.651305
Iteration 237, loss = 5256121.58542341
Validation score: 0.651495
Iteration 238, loss = 5255040.45081629
Validation score: 0.651234
Iteration 239, loss = 5254544.44775173
Validation score: 0.651176
Iteration 240, loss = 5253304.10449251
Validation score: 0.651074
Iteration 241, loss = 5251682.67424416
Validation score: 0.651140
Iteration 242, loss = 5250317.49313384
Validation score: 0.651701
Iteration 243, loss = 5254839.50010872
Validation score: 0.652545
Iteration 244, loss = 5249310.23227700
Validation score: 0.651226
Iteration 245, loss = 5251310.70936743
Validation score: 0.651394
Iteration 246, loss = 5247877.92961381
Validation score: 0.651498
Iteration 247, loss = 5245603.75782201
Validation score: 0.651656
Iteration 248, loss = 5244921.97483655
Validation score: 0.651871
Iteration 249, loss = 5244738.99547826
Validation score: 0.652595
Iteration 250, loss = 5244924.96798798
Validation score: 0.652091
Iteration 251, loss = 5247415.62832804
Validation score: 0.651763
Iteration 252, loss = 5245599.04567394
Validation score: 0.652891
Iteration 253, loss = 5243419.20299746
Validation score: 0.651938
Iteration 254, loss = 5239580.62426781
Validation score: 0.652558
Iteration 255, loss = 5239252.09974060
Validation score: 0.652862
Iteration 256, loss = 5238332.62485409
Validation score: 0.652702
Iteration 257, loss = 5237161.96523028
Validation score: 0.652203
Iteration 258, loss = 5237366.34757616
Validation score: 0.652736
Iteration 259, loss = 5236293.88208634
Validation score: 0.653424
Iteration 260, loss = 5234446.89742450
Validation score: 0.652349
Iteration 261, loss = 5232775.83941392
Validation score: 0.653047
Iteration 262, loss = 5234649.22548891
Validation score: 0.653177
Iteration 263, loss = 5232182.83938957
Validation score: 0.653548
Iteration 264, loss = 5230966.31694106
Validation score: 0.652930
Iteration 265, loss = 5230265.05399404
Validation score: 0.652792
Iteration 266, loss = 5230333.14437798
Validation score: 0.653329
Iteration 267, loss = 5230181.12993211
Validation score: 0.653525
Iteration 268, loss = 5227027.23814361
Validation score: 0.653386
Iteration 269, loss = 5227918.11461243
Validation score: 0.653009
Iteration 270, loss = 5225906.45722538
Validation score: 0.653565
Iteration 271, loss = 5225331.01759889
Validation score: 0.653334
Iteration 272, loss = 5224368.57178999
Validation score: 0.653933
Iteration 273, loss = 5225907.65661619
Validation score: 0.654458
Iteration 274, loss = 5224220.04228492
Validation score: 0.653260
Iteration 275, loss = 5222535.12489904
Validation score: 0.653306
Iteration 276, loss = 5222598.30529471
Validation score: 0.654561
Iteration 277, loss = 5220133.99092646
Validation score: 0.653599
Iteration 278, loss = 5219800.68878192
Validation score: 0.654274
Iteration 279, loss = 5220521.43775476
Validation score: 0.654060
Iteration 280, loss = 5217941.32545658
Validation score: 0.653563
Iteration 281, loss = 5218072.45121521
Validation score: 0.653611
Iteration 282, loss = 5216459.38484128
Validation score: 0.653959
Iteration 283, loss = 5216673.26907565
Validation score: 0.654389
Iteration 284, loss = 5214674.13301704
Validation score: 0.654695
Iteration 285, loss = 5214105.19888406
Validation score: 0.654433
Iteration 286, loss = 5214088.30151279
Validation score: 0.653911
Iteration 287, loss = 5213987.00979399
Validation score: 0.654545
Iteration 288, loss = 5213408.64271850
Validation score: 0.653885
Iteration 289, loss = 5211064.86566811
Validation score: 0.654552
Iteration 290, loss = 5210968.44682397
Validation score: 0.655039
Iteration 291, loss = 5211118.20341754
Validation score: 0.654586
Iteration 292, loss = 5210492.19754211
Validation score: 0.655233
Iteration 293, loss = 5211167.46722212
Validation score: 0.655438
Iteration 294, loss = 5208666.61103107
Validation score: 0.654583
Iteration 295, loss = 5207850.46656173
Validation score: 0.655536
Iteration 296, loss = 5207964.73801891
Validation score: 0.655149
Iteration 297, loss = 5206939.08603942
Validation score: 0.655301
Iteration 298, loss = 5206456.68605540
Validation score: 0.654601
Iteration 299, loss = 5204455.96088271
Validation score: 0.655126
Iteration 300, loss = 5204954.53344625
Validation score: 0.655097
Iteration 301, loss = 5203137.57885772
Validation score: 0.655236
Iteration 302, loss = 5203411.65040236
Validation score: 0.655266
Iteration 303, loss = 5202367.96805353
Validation score: 0.655814
Iteration 304, loss = 5204343.03506410
Validation score: 0.655151

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Training Set Performance (Overall):
  RMSE: 4485.39
  MAE:  2823.19
  R²:   0.7899

Validation Set Performance (Overall):
  RMSE: 4599.25
  MAE:  2926.26
  R²:   0.7678

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7632 2126.243572 1438.529052 0.641379
  toyota  3779 2857.126889 1822.559498 0.801018
   skoda  3472 2887.890994 1943.114858 0.791618
 hyundai  2689 3049.805348 2035.654901 0.739752
    ford 13210 3066.919762 2221.973098 0.589381
      vw  8489 3631.962127 2412.343130 0.783283
    audi  5941 5889.799549 3744.032682 0.753213
     bmw  6025 6339.622845 4560.968455 0.687083
mercedes  9541 6626.760580 4396.565865 0.654738

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 2284.511289 1533.146243 0.600274
   skoda  914 2783.239814 1953.674246 0.777663
  toyota  939 3122.637043 1986.951622 0.749471
    ford 3182 3161.118676 2310.536992 0.562981
 hyundai  716 3182.329486 2086.973865 0.705215
      vw 2117 3637.085904 2463.986818 0.761604
    audi 1527 6033.960971 3849.918413 0.693746
mercedes 2368 6659.535932 4533.473969 0.621827
     bmw 1520 6665.818077 4740.085748 0.684562

      Brand     N         RMSE          MAE        R²
6      opel  1912  2284.511289  1533.146243  0.600274
1     skoda   914  2783.239814  1953.674246  0.777663
8    toyota   939  3122.637043  1986.951622  0.749471
3      ford  3182  3161.118676  2310.536992  0.562981
7   hyundai   716  3182.329486  2086.973865  0.705215
2        vw  2117  3637.085904  2463.986818  0.761604
4      audi  1527  6033.960971  3849.918413  0.693746
0  mercedes  2368  6659.535932  4533.473969  0.621827
5       bmw  1520  6665.818077  4740.085748  0.684562