#TODO

- prova multipli nn su 27 modelli
- function documentation
- import all the functions
- hyperparam refined
- train full df
- predictions

# Project

In [1]:
import pandas as pd
from thefuzz import process
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# For imputation
from sklearn.experimental import enable_iterative_imputer  # noqa
from sklearn.impute import IterativeImputer

from scipy import stats
from sklearn.feature_selection import VarianceThreshold, RFE
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier, ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor

import numpy as np
from sklearn.base import BaseEstimator, clone
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from typing import Dict

from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.neighbors import KNeighborsRegressor

from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor

import random
from copy import deepcopy
import time

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.cluster import DBSCAN

In [2]:
train_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/train.csv")

In [3]:
train_df = train_df.set_index("carID")
train_df = train_df.drop(columns=["paintQuality%"])

In [4]:
train_df.head()

,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,previousOwners,hasDamage
carID,,,,,,,,,,,,
69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,NaN,11.417268,2.0,4.000000,0.0
53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,145.0,47.900000,1.5,1.000000,0.0
6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,145.0,40.900000,1.5,4.000000,0.0
29021,Ford,FIESTA,2018.0,12500,anual,9102.0,Petrol,145.0,65.700000,1.0,-2.340306,0.0
10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,145.0,42.800000,1.5,3.000000,0.0

### Making sure that the model prices are not typos

In [5]:
#df_cleaned = simple_processing(train_df)
#df_cleaned = df_cleaned[df_cleaned["model"].notna()]
#df_price_model = df_cleaned[["Brand","model", "price"]].copy()

In [6]:

"""# Get the list of unique models
models = df_price_model['model'].unique()

# Loop through each model and create a boxplot
#for model in models:
sns.catplot(data=df_price_model, y='price', col='model', kind='box', col_wrap=4, height=3, sharey=False)
plt.show()"""

"# Get the list of unique models\nmodels = df_price_model['model'].unique()\n\n# Loop through each model and create a boxplot\n#for model in models:\nsns.catplot(data=df_price_model, y='price', col='model', kind='box', col_wrap=4, height=3, sharey=False)\nplt.show()"

In [7]:

"""def is_outlier(x):
    Q1, Q3 = x.quantile([0.25, 0.75])
    IQR = Q3 - Q1
    return (x < (Q1 - 3 * IQR)) | (x > (Q3 + 3 * IQR))

# Apply the function per model group to get the outlier rows
outliers = df_price_model[df_price_model.groupby('model')['price'].transform(is_outlier)]

# Display sorted results
outliers.sort_values(['model', 'price'])
"""

"def is_outlier(x):\n    Q1, Q3 = x.quantile([0.25, 0.75])\n    IQR = Q3 - Q1\n    return (x < (Q1 - 3 * IQR)) | (x > (Q3 + 3 * IQR))\n\n# Apply the function per model group to get the outlier rows\noutliers = df_price_model[df_price_model.groupby('model')['price'].transform(is_outlier)]\n\n# Display sorted results\noutliers.sort_values(['model', 'price'])\n"

## Data cleaning

In [8]:
# TODO: Move the functions to a separate file

In [9]:
# String cleaning and Small numbers changes

def simple_processing(df):
    """
    Apply string cleaning, brand/model corrections, and fuzzy matching.
    These operations don"t require fitting on training data.
    """

    df = df.copy()
    # ============================================================================
    # SECTION 1: REFERENCE DATA SETUP
    # ============================================================================
    
    # Reference list of correct model names
    models = ["golf", "veloste", "caddy", "yaris", "q2", "fiesta", "2 series", "3 series", "a3", "octavia", 
              "passat", "focus", "insignia", "a class", "q3", "fabia", "ka+", "glc class", "i30", "c class", 
              "polo", "e class", "q5", "up", "c-hr", "mokka x", "corsa", "astra", "tt", "5 series", "aygo", 
              "4 series", "slk", "viva", "t-roc", "ecosport", "tucson", "x-class", "cl class", "ix20", "i20", 
              "rapid", "a1", "auris", "sharan", "adam", "x3", "a8", "gls class", "b-max", "a4", "kona", "i10", 
              "mokka", "s-max", "x2", "crossland x", "tiguan", "a5", "gle class", "zafira", "ioniq", "a6", 
              "mondeo", "yeti outdoor", "x1", "scala", "s class", "1 series", "kamiq", "kuga", "tourneo connect", 
              "q7", "gla class", "arteon", "sl class", "santa fe", "grandland x", "i800", "rav4", "touran", 
              "citigo", "roomster", "prius", "corolla", "b class", "kodiaq", "v class", "caddy maxi life", 
              "superb", "getz", "combo life", "beetle", "galaxy", "m3", "gtc", "x4", "ka", "ix35", 
              "grand tourneo connect", "m4", "tourneo custom", "z4", "x5", "meriva", "rs6", "verso", "touareg", 
              "shuttle", "cls class", "c-max", "puma", "cla class", "i40", "tiguan allspace", "6 series", 
              "caravelle", "karoq", "i3", "grand c-max", "t-cross", "a7", "golf sv", "agila", "gt86", "yeti", 
              "california", "land cruiser", "edge", "x6", "caddy life", "8 series", "fusion", "gl class", 
              "scirocco", "z3", "proace verso", "hilux", "amarok", "cc", "7 series", "avensis", "eos", "m class", 
              "grandland", "zafira tourer", "rs5", "r8", "mustang", "antara", "q8", "camry", "clk", "rs3", 
              "jetta", "kadjar", "sq5", "rs4", "supra", "i8", "x7", "sq7", "g class", "s3", "crossland", 
              "tigra", "escort", "glb class", "vivaro", "verso-s", "m5", "s4", "iq", "a2", "caddy maxi", 
              "streetka", "cascada", "accent", "s8", "rs", "golf s", "ranger", "vectra", "ampera", "fox", 
              "urban cruiser", "m2", "clc class", "m6", "s5", "terracan", "200", "220", "230", "NaN"]
    
    # Get unique short model names (2 characters) for separate handling
    short_models = [models[i] for i in range(len(models)) if len(models[i]) == 2]
    short_models = list(set(short_models))
    
    transmission_types = ["semi-auto", "manual", "automatic", "unkown", "NaN", "other"]
    fuel_types = ["petrol", "diesel", "hybrid", "electric", "other", "NaN"]
    
    # Brand name corrections mapping
    brand_mapping = {
        "vw": "vw",
        "v": "vw",
        "w": "vw",
        
        "toyota": "toyota",
        "toyot": "toyota",
        "oyota": "toyota",
        
        "audi": "audi",
        "aud": "audi",
        "udi": "audi",
        "ud": "audi",
        
        "ford": "ford",
        "for": "ford",
        "ord": "ford",
        "or": "ford",
        
        "bmw": "bmw",
        "bm": "bmw",
        "mw": "bmw",
        
        "skoda": "skoda",
        "skod": "skoda",
        "koda": "skoda",
        "kod": "skoda",
        
        "opel": "opel",
        "ope": "opel",
        "pel": "opel",
        "pe": "opel",
        
        "mercedes": "mercedes",
        "mercede": "mercedes",
        "ercedes": "mercedes",
        "ercede": "mercedes",
        
        "hyundai": "hyundai",
        "hyunda": "hyundai",
        "yundai": "hyundai",
        "yunda": "hyundai"
    }
    
    # ============================================================================
    # SECTION 2: INITIAL CLEANING (NO FITTING REQUIRED) -> no risk of data leakage
    # ============================================================================
        
    # Convert brand names to lowercase and removes all beginning and trailing whitespace (e.g. space) from the column
    df["Brand"] = df["Brand"].str.lower().str.strip()
    df["model"] = df["model"].str.lower().str.strip()
    df["transmission"] = df["transmission"].str.lower().str.strip()
    df["fuelType"] = df["fuelType"].str.lower().str.strip()
    
    # Replace NaN with string NaN to avoid errors in the fuzzy algorithm (cant match NaNs)
    df[["model", "transmission", "fuelType"]] = df[["model", "transmission", "fuelType"]].fillna("NaN")
    
    # 1.1 Fixing brands
    df["Brand"] = df["Brand"].map(brand_mapping)
    
    # 1.2 Fixing models
    # Similarity matching for Models, Transmission and fuel columns (Fuzzy Match)
    # Source for process.extractOne (fuzzy): https://github.com/seatgeek/thefuzz
    
    # VECTORIZED APPROACH: Only perform fuzzy matching once per unique value instead of per row
    
    # Models - handle different lengths separately
    unique_models = df["model"].unique()
    model_lookup = {}
    for val in unique_models:
        if pd.isna(val) or val == "NaN":
            model_lookup[val] = "NaN"
        elif len(val) > 2:  # Only perform fuzzy matching for models that have a name longer than 2 letters -> fuzzy will become fuzzy (unreliable) if names are to short
            model_lookup[val] = process.extractOne(val, models)[0]  # [0] because we get the name and score as a return -> score used for debugging
        elif len(val) == 2:  # Use the short names list for comparisons if the model names are 2 letters
            model_lookup[val] = process.extractOne(val, short_models)[0]
        else:  # We can define models with only one letter
            model_lookup[val] = "NaN"
    df["model"] = df["model"].map(model_lookup)
    
    # Transmission
    unique_trans = df["transmission"].unique()
    trans_lookup = {val: process.extractOne(val, transmission_types)[0] for val in unique_trans}
    df["transmission"] = df["transmission"].map(trans_lookup)
    
    # FuelType
    unique_fuel = df["fuelType"].unique()
    fuel_lookup = {val: process.extractOne(val, fuel_types)[0] for val in unique_fuel}
    df["fuelType"] = df["fuelType"].map(fuel_lookup)
    
    # Convert the str NaN values back to pd.NA for easier further processing and readability
    df["model"] = df["model"].replace("NaN", pd.NA)
    df["transmission"] = df["transmission"].replace(["unkown", "NaN", "other"], pd.NA)
    df["fuelType"] = df["fuelType"].replace(["other", "NaN"], pd.NA)
    
    #df["Brand"] = df["Brand"].fillna(df["Brand_mode"])  # rename new column
    #df.drop("Brand_mode", axis=1, inplace=True)  # remove the old brand column
    
    ################################################################################
    # Simple Number Cleaning
    ################################################################################

    # Cleaning numeric columns
    df["year"] = df["year"].round(0)
    
    # Create the new column
    df["stated_no_damage"] = ~df["hasDamage"].astype(bool)
    df = df.drop(["hasDamage"], axis=1)

    # Round year to integer (no fractional years)
    df["year"] = df["year"].round()

    # Replace the years 2024, 2023 with NA as these values are very likley wrong (dataset is from 2020) and we want to impute them 
    df.loc[df["year"] == 2024, "year"] = pd.NA 
    df.loc[df["year"] == 2023, "year"] = pd.NA

    
    # Mileage: take absolute value and round
    # Some imputation might produce small negative values
    df["mileage"] = abs(df["mileage"].round())
    
    # Tax: take absolute value and round
    df["tax"] = abs(df["tax"].round())
    
    # MPG: round to 1 decimal place 
    df["mpg"] = abs(df["mpg"].round(1))
    
    # Engine size: round to 1 decimal place
    df["engineSize"] = abs(df["engineSize"].round(1))
    
    # Remove paintQuality column as this is information collected by the mechanic and thus not available for pre-assesment of the car
    #df.drop("paintQuality%", axis=1, inplace=True) 
    
    # Previous owners: take absolute value and round to integer
    df["previousOwners"] = abs(df["previousOwners"].round())
    
    return df

In [10]:
def mode_imputation(df):
    """
    Get the most frequent brand for each model -> returns df with model and brand
    """
    brand_models = df.groupby("model_transformed")["Brand_transformed"].agg(lambda x: x.mode()[0] if len(x.mode()) > 0 else pd.NA)
    df = pd.merge(df, brand_models, on="model_transformed", how="left", suffixes=("", "_mode"))  # add the model and brand df to our main df (onyl add the brand columns, join on model)
    
    df["Brand_transformed"] = df["Brand_transformed"].fillna(df["Brand_transformed_mode"])  # rename new column
    df.drop("Brand_transformed_mode", axis=1, inplace=True)  # remove the old brand column
    

    return df

In [11]:
def remove_price_outliers(df, threshold=3):
    """
    Replaces price outliers with NaN for each model group based on the IQR method.
    
    Parameters:
    df: Input dataframe containing 'model' and 'price' columns.
    threshold: The multiplier for the IQR to define outliers. Default is 3 (extreme outliers).
    
    Returns:
    Dataframe with outliers replaced by NaN.
    """
    df_clean = df.copy()
    
    # Calculate Q1, Q3, and IQR per model
    # We use transform to broadcast the group statistics back to the original index size
    groups = df_clean.groupby('model')['price']
    q1 = groups.transform(lambda x: x.quantile(0.25))
    q3 = groups.transform(lambda x: x.quantile(0.75))
    iqr = q3 - q1
    
    # Define bounds
    lower_bound = q1 - (threshold * iqr)
    upper_bound = q3 + (threshold * iqr)
    
    # Identify outliers
    outlier_mask = (df_clean['price'] < lower_bound) | (df_clean['price'] > upper_bound)
    
    # Replace outliers with NaN
    df_clean.loc[outlier_mask, 'price'] = np.nan
    
    return df_clean

In [12]:
# Categorical featue Encoding
def fit_transform_encoding(df):
    """
    Fit label encoders for categorical columns on training data.
    """
    
    encoders = {
        "Brand": LabelEncoder(),
        "model": LabelEncoder(),
        "transmission": LabelEncoder(),
        "fuelType": LabelEncoder()
    }
    
    # Fit each encoder on the corresponding column
    """encoders["brand"].fit(df["Brand"])
    encoders["model"].fit(df["model"])
    encoders["transmission"].fit(df["transmission"])
    encoders["fuelType"].fit(df["fuelType"])"""

    columns = ["Brand", "model", "transmission", "fuelType"]

    # Code adapted from: https://stackoverflow.com/questions/36808434/label-encoder-encoding-missing-values

    for column in columns:
        # Get non-null string values
        mask = df[column].notna() & (df[column].apply(type) == str)
        
        # Fit encoder on unique non-null values
        fit_by = df.loc[mask, column].unique()
        encoders[column].fit(fit_by)
        
        # Transform only non-null values (vectorized)
        new_col_name = column + "_transformed"
        df[new_col_name] = pd.NA  # Initialize with NA
        df.loc[mask, new_col_name] = encoders[column].transform(df.loc[mask, column])
        
        # Convert to nullable integer
        df[new_col_name] = df[new_col_name].astype("Int64")

    df = df.drop(columns, axis=1)
    return df, encoders

In [13]:
# Categorical featue Encoding
def fit_transform_encoding(df):
    """
    Fit label encoders for categorical columns on training data.
    """
    
    encoders = {
        "Brand": LabelEncoder(),
        "model": LabelEncoder(),
        "transmission": LabelEncoder(),
        "fuelType": LabelEncoder()
    }
    
    # Fit each encoder on the corresponding column
    """encoders["brand"].fit(df["Brand"])
    encoders["model"].fit(df["model"])
    encoders["transmission"].fit(df["transmission"])
    encoders["fuelType"].fit(df["fuelType"])"""

    columns = ["Brand", "model", "transmission", "fuelType"]

    # Code adapted from: https://stackoverflow.com/questions/36808434/label-encoder-encoding-missing-values

    for column in columns:
        # Get non-null string values
        mask = df[column].notna() & (df[column].apply(type) == str)
        
        # Fit encoder on unique non-null values
        fit_by = df.loc[mask, column].unique()
        encoders[column].fit(fit_by)
        
        # Transform only non-null values (vectorized)
        new_col_name = column + "_transformed"
        df[new_col_name] = pd.NA  # Initialize with NA
        df.loc[mask, new_col_name] = encoders[column].transform(df.loc[mask, column])
        
        # Convert to nullable integer
        df[new_col_name] = df[new_col_name].astype("Int64")

    df = df.drop(columns, axis=1)
    return df, encoders

In [14]:
# Train imputer on train

def fit_imputer(df): 
    try: 
        df = df.drop(["price"], axis=1) # Remove the price column as it would not be available for imputation and thus should not be used when training the imputer
    except KeyError: # Happens when we use testing data as we previously dropped the price column 
        pass
    
    estimator = ExtraTreesRegressor(n_estimators=50,
                                    n_jobs=-1,
                                    min_samples_leaf=10,
                                    max_depth=20,
                                    random_state=69)

    imputer = IterativeImputer(estimator=estimator,
                                max_iter=20,
                                n_nearest_features=10,
                                random_state=69,
                                initial_strategy="most_frequent")

    imputer.fit(df)
    
    return imputer

In [15]:
def apply_imputer(df, imputer):
    """
    Apply the pretrained imputer to the dataframe features only, preserving the price column.
    """
    df_imputed = df.copy()
    
    # 1. Separate price if it exists
    price_col = None
    if 'price' in df_imputed.columns:
        price_col = df_imputed['price']
        df_for_imputation = df_imputed.drop(columns=['price'])
    else:
        df_for_imputation = df_imputed

    # 2. Apply imputer to features
    imputed_values = imputer.transform(df_for_imputation)
    
    # Create a new dataframe from the imputed values to avoid dtype warnings
    # We use the same index and columns as the input to preserve structure
    df_for_imputation = pd.DataFrame(
        imputed_values, 
        columns=df_for_imputation.columns, 
        index=df_for_imputation.index
    )
    
    # 3. Re-attach price if it existed
    if price_col is not None:
        df_for_imputation['price'] = price_col
        
    # 4. Post-processing (Rounding)
    df_for_imputation[["mpg", "engineSize"]] = abs(df_for_imputation[["mpg", "engineSize"]]).round(1)
    
    int_cols = ["year", "tax", "mileage", "previousOwners", "Brand_transformed", 
                "model_transformed", "transmission_transformed", "fuelType_transformed"]
    
    existing_int_cols = [col for col in int_cols if col in df_for_imputation.columns]
    df_for_imputation[existing_int_cols] = abs(df_for_imputation[existing_int_cols]).round(0).astype(int)
    
    return df_for_imputation

In [16]:
def fit_price_imputer(df, target_col='price'):
    """
    Trains a regressor to impute missing values in the target column (price).
    
    Parameters:
    df: Dataframe containing features and the target column with NaNs.
    target_col: The name of the target column to impute.
    
    Returns:
    model: The trained regression model.
    """
    
    # Separate data into sets with known and unknown target values
    train_known = df[df[target_col].notna()]
    
    # X contains all columns except the target
    X = train_known.drop(columns=[target_col])
    y = train_known[target_col]
    
    # Initialize the estimator (same robust parameters as your previous imputer)
    estimator = ExtraTreesRegressor(n_estimators=100,
                                    n_jobs=-1,
                                    min_samples_leaf=5,
                                    max_depth=20,
                                    random_state=69)
    
    # Fit the model
    estimator.fit(X, y)
    
    return estimator

In [17]:
def apply_price_imputer(df, model, target_col='price'):
    """
    Uses the trained model to fill NaN values in the target column.
    """
    df_imputed = df.copy()
    
    # Identify rows where the target is missing
    missing_mask = df_imputed[target_col].isna()
    
    # If there are missing values, predict and fill them
    if missing_mask.sum() > 0:
        X_missing = df_imputed.loc[missing_mask].drop(columns=[target_col])
        predicted_values = model.predict(X_missing)
        df_imputed.loc[missing_mask, target_col] = predicted_values
        
    return df_imputed

In [18]:
def decode(df, encoders):
    # Iterative imputer produces ~20-30 values that are outside of the range of the encoder
    # The simplest fix is to clip does values back into the range of the encoder
 

    df["Brand_transformed"] = df["Brand_transformed"].clip(lower=0, upper=encoders["Brand"].classes_.shape[0]-1).astype(int)
    df["Brand"] = encoders["Brand"].inverse_transform(df["Brand_transformed"])

    df["transmission_transformed"] = df["transmission_transformed"].clip(lower=0, upper=encoders["transmission"].classes_.shape[0]-1).astype(int)
    df["transmission"] = encoders["transmission"].inverse_transform(df["transmission_transformed"])
        
    # Use clip with the information of the fitted encoder, .classes_.shape gives us the dimension of the labels the encoder uses [0] is the rows - 1 because we start clipping at 0
    df["model_transformed"] = df["model_transformed"].clip(lower=0, upper=encoders["model"].classes_.shape[0]-1).astype(int)
    df["model"] = encoders["model"].inverse_transform(df["model_transformed"])
    
    df["fuelType_transformed"] = df["fuelType_transformed"].clip(lower=0, upper=encoders["fuelType"].classes_.shape[0]-1).astype(int)
    df["fuelType"] = encoders["fuelType"].inverse_transform(df["fuelType_transformed"])
    

    df.drop(columns=["Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"], inplace=True)

    return df

### Workflow for Train and Validation Sets

#### Encoding

In [19]:
# Fix typos and small numeric cleanup
df = simple_processing(train_df)

# Remove extreme price outliers
df = remove_price_outliers(df)

# Encode cateogrical columns and replace the str with int columns. Return fitted encoders for decoding at the end
df_encoded, encoders = fit_transform_encoding(df)

#### Creating the stratification column

In [20]:
# Create Categorical price column with 0 < 1 < 2 for the price
df_encoded["price_cat"] = pd.qcut(df_encoded["price"], 3, labels=False)

# Combine the 10 unique brand values (1-9 & NA) with the 3 unique price category values (0-2)
stratify_col = df_encoded["Brand_transformed"].astype(str) + "_" + df_encoded["price_cat"].astype(str)

#### Imputation and decoding

In [21]:
# Train validation split
train_split, validation_split = train_test_split(df_encoded, test_size=0.2, random_state=69, stratify=stratify_col)
# train_split, validation_split = train_test_split(df_encoded, test_size=0.2, random_state=42)

# Drop price_cat column from both splits as it would introduce data leakage
train_split = train_split.drop("price_cat", axis=1)
validation_split = validation_split.drop("price_cat", axis=1)

train_split = mode_imputation(train_split)
validation_split = mode_imputation(validation_split)

# Train imputer on train (data leakage risk thus only train on train_split)
imputer = fit_imputer(train_split)

# Apply trained imputer to both datasplits
imputed_train = apply_imputer(train_split, imputer)
imputed_validation = apply_imputer(validation_split, imputer)

# Impute the missing price values created by removing extrem outliers
# In our step to remove extrem price outliers we introduced missing values in the price column. However, in our normal imputer, which we also use for imputing the test 
# Dataset we can not fix these values as this would cause the imputer to not work on the test subset, with no price feature. 
# Thus we create a seperate price imputer to fix the missing values in the testing and validation sets. This imputer is trained on train and applied to validation
# Fit price imputer
price_imputer = fit_price_imputer(imputed_train)
# Apply price imputer
imputed_train = apply_price_imputer(imputed_train, price_imputer)
imputed_validation = apply_price_imputer(imputed_validation, price_imputer)

# Decode encoded columns using the fitted encoders
train_processed = decode(imputed_train, encoders)
validation_processed = decode(imputed_validation, encoders)

c:\Users\liber\anaconda3\envs\ML_env\Lib\site-packages\sklearn\impute\_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [22]:
train_processed.isna().sum()

year                0
mileage             0
tax                 0
mpg                 0
engineSize          0
previousOwners      0
stated_no_damage    0
price               0
Brand               0
transmission        0
model               0
fuelType            0
dtype: int64

### Workflow for Seperated Testing Dataset

In [23]:
test_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/test.csv")

In [24]:
test_df = test_df.set_index("carID")
test_df = test_df.drop(columns=["paintQuality%"])

In [25]:
test = simple_processing(test_df)

test_df_encoded, test_encoders = fit_transform_encoding(test)

#test_imputers = fit_imputer(df_encoded_no_price, fast=False) # we use the full encoded training dataframe to train the imputers

#df_encoded_no_price = test_df_imputed.drop(["price", "price_cat"], axis=1)

# Apply imputer trained on testing data
test_df_imputed = apply_imputer(test_df_encoded, imputer)

test_processed = decode(test_df_imputed, test_encoders)

In [26]:
train_val_models = set(pd.concat([train_processed, validation_processed])["model"].unique())
test_models = set(test_processed["model"].unique())

missing_models = train_val_models - test_models

In [27]:
list(missing_models)

['caddy maxi',
 'accent',
 'kadjar',
 '230',
 'verso-s',
 'ranger',
 'urban cruiser',
 '220',
 '200',
 'getz',
 'escort',
 'streetka',
 's8']

## Feature Engineering

In [28]:
train_processed.index = train_processed.index.astype(int)
validation_processed.index = validation_processed.index.astype(int)

In [29]:
X_train = train_processed
X_val = validation_processed

In [30]:
def minimal_features(df):
    df = df.copy()
    df['age'] = 2020 - df['year']
    df = df.drop(columns=["year"])
    df['mileage_per_year'] = df['mileage'] / (df['age'] + 1)
    df['efficiency_ratio'] = df['mpg'] / (df['engineSize'] + 0.1)
    df['age_mileage'] = df['age'] * df['mileage'] / 100000

    return df

In [31]:
X_train = minimal_features(X_train)
X_val = minimal_features(X_val)

In [32]:
model_mean_price = X_train.groupby('model')['price'].mean() 
X_train['model_mean_price'] = X_train['model'].map(model_mean_price) 
X_val['model_mean_price'] = X_val['model'].map(model_mean_price)

In [33]:
X_train = X_train.drop(columns=["model"])
X_val = X_val.drop(columns=["model"])

In [34]:
y_train = X_train['price']
y_val = X_val['price']

In [35]:
X_train = X_train.drop(columns=['price'])

X_val = X_val.drop(columns=['price'])

In [36]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60778 entries, 0 to 60777
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           60778 non-null  int32
 1   tax               60778 non-null  int32
 2   mpg               60778 non-null  float64
 3   engineSize        60778 non-null  float64
 4   previousOwners    60778 non-null  int32
 5   stated_no_damage  60778 non-null  float64
 6   Brand             60778 non-null  object
 7   transmission      60778 non-null  object
 8   fuelType          60778 non-null  object
 9   age               60778 non-null  int32
 10  mileage_per_year  60778 non-null  float64
 11  efficiency_ratio  60778 non-null  float64
 12  age_mileage       60778 non-null  float64
 13  model_mean_price  60778 non-null  float64
dtypes: float64(7), int32(4), object(3)
memory usage: 5.8+ MB

In [37]:
X_val.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15195 entries, 0 to 15194
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           15195 non-null  int32
 1   tax               15195 non-null  int32
 2   mpg               15195 non-null  float64
 3   engineSize        15195 non-null  float64
 4   previousOwners    15195 non-null  int32
 5   stated_no_damage  15195 non-null  float64
 6   Brand             15195 non-null  object
 7   transmission      15195 non-null  object
 8   fuelType          15195 non-null  object
 9   age               15195 non-null  int32
 10  mileage_per_year  15195 non-null  float64
 11  efficiency_ratio  15195 non-null  float64
 12  age_mileage       15195 non-null  float64
 13  model_mean_price  15195 non-null  float64
dtypes: float64(7), int32(4), object(3)
memory usage: 1.4+ MB

In [38]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 60778 entries, 0 to 60777
Series name: price
Non-Null Count  Dtype
--------------  -----
60778 non-null  float64
dtypes: float64(1)
memory usage: 712.2 KB

In [39]:
y_val.info()

<class 'pandas.core.series.Series'>
Index: 15195 entries, 0 to 15194
Series name: price
Non-Null Count  Dtype
--------------  -----
15195 non-null  float64
dtypes: float64(1)
memory usage: 178.1 KB

## Test of the models on the full dataset

In [40]:
class BrandModelTrainer:
    def __init__(self, estimator):
        self.estimator = estimator
        self.brand_models = {}
        self.feature_cols = None

    def fit(self, X_train, y_train):
        self.feature_cols = [c for c in X_train.columns if c != "Brand"]
        print(f"Training models for {len(X_train['Brand'].unique())} brands...\n")

        for brand in X_train["Brand"].unique():
            mask = X_train["Brand"] == brand
            Xb = X_train.loc[mask, self.feature_cols]
            yb = y_train[mask]

            numeric_cols = Xb.select_dtypes(include=["int64", "int32" ,"float64"]).columns.tolist()
            categorical_cols = Xb.select_dtypes(include=["object", "category"]).columns.tolist()

            preprocessor = ColumnTransformer([
                ("num", RobustScaler(), numeric_cols),
                ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
            ])

            model = Pipeline([
                ("preprocess", preprocessor),
                ("estimator", clone(self.estimator))
            ])

            model.fit(Xb, yb)
            self.brand_models[brand] = model
            print(f"  ✓ {brand} done.")

        return self

    def predict(self, X):
        preds = np.zeros(len(X))
        for brand, model in self.brand_models.items():
            mask = X["Brand"] == brand
            if mask.sum() == 0:
                continue
            Xb = X.loc[mask, self.feature_cols]
            preds[mask] = model.predict(Xb)
        return preds

    def evaluate_train(self, X_train, y_train):
        y_pred = self.predict(X_train)
        rmse = np.sqrt(mean_squared_error(y_train, y_pred))
        mae = mean_absolute_error(y_train, y_pred)
        r2 = r2_score(y_train, y_pred)
        print("\nTraining Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    def evaluate(self, X_val, y_val):
        y_pred = self.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, y_pred))
        mae = mean_absolute_error(y_val, y_pred)
        r2 = r2_score(y_val, y_pred)
        print("\nValidation Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    def evaluate_by_brand(self, X, y, split_name="Validation"):
        y_pred = self.predict(X)
        results = []
        for brand in X["Brand"].unique():
            mask = X["Brand"] == brand
            y_true_b = y[mask]
            y_pred_b = y_pred[mask]
            rmse = np.sqrt(mean_squared_error(y_true_b, y_pred_b))
            mae = mean_absolute_error(y_true_b, y_pred_b)
            r2 = r2_score(y_true_b, y_pred_b)
            results.append({"Brand": brand, "N": len(y_true_b), "RMSE": rmse, "MAE": mae, "R²": r2})
        df = pd.DataFrame(results).sort_values("RMSE")
        print(f"\n{split_name} Performance per Brand:")
        print(df.to_string(index=False))
        return df

    def evaluate_train_by_brand(self, X_train, y_train):
        return self.evaluate_by_brand(X_train, y_train, split_name="Training")
    
    def save_predictions(self, X, path):
        preds = self.predict(X)
        df = pd.DataFrame({
            "CarID": X["CarID"].values,
            "price": preds
        })
        df.to_csv(path, index=False)
        print(f"File salvato in: {path}")
        return df

In [41]:
raise SystemExit("Stop before training the models")

SystemExit: Stop before training the models

C:\Users\liber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

### Linear Regression

In [ ]:
LR = LinearRegression()
trainer = BrandModelTrainer(LR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 3442.01
  MAE:  2144.51
  R²:   0.8718

Validation Set Performance (Overall):
  RMSE: 3383.27
  MAE:  2156.67
  R²:   0.8723

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7644 1804.879210 1261.623779 0.740389
    ford 13108 2134.363308 1476.104103 0.800574
   skoda  3507 2189.201631 1541.424664 0.872451
  toyota  3775 2409.171888 1478.395462 0.854670
 hyundai  2724 2420.528081 1671.759526 0.835181
      vw  8479 3141.918645 2112.214045 0.832716
    audi  5971 4470.093313 2919.596232 0.855723
     bmw  6029 4489.217686 3085.250549 0.843073
mercedes  9541 5182.497736 3339.506559 0.763434

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1769.390434 1267.726325 0.753326
    ford 3282 2105.414326 1492.778850 0.801982
 hyundai  683 2363.467323 1595.200160 0.846346
   skoda  875 2510.576724 1588.635694 0.833582
  toyota  941 2517.817091 1549.075444 0.837962
      vw 2125 3337.402398 2147.630425 0.821398
    audi 1489 4260.940846 2882.654055 0.848291
     bmw 1513 4437.867434 3058.617525 0.849100
mercedes 2381 4919.273107 3374.256001 0.769401

      Brand     N         RMSE          MAE        R²
1      opel  1906  1769.390434  1267.726325  0.753326
2      ford  3282  2105.414326  1492.778850  0.801982
5   hyundai   683  2363.467323  1595.200160  0.846346
7     skoda   875  2510.576724  1588.635694  0.833582
3    toyota   941  2517.817091  1549.075444  0.837962
0        vw  2125  3337.402398  2147.630425  0.821398
6      audi  1489  4260.940846  2882.654055  0.848291
8       bmw  1513  4437.867434  3058.617525  0.849100
4  mercedes  2381  4919.273107  3374.256001  0.769401

### Decision Tree

In [ ]:
Tree = DecisionTreeRegressor(criterion="absolute_error")
trainer = BrandModelTrainer(Tree)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)        # Performance VALID

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 112.79
  MAE:  6.37
  R²:   0.9999

Validation Set Performance (Overall):
  RMSE: 2784.00
  MAE:  1663.58
  R²:   0.9135

Training Performance per Brand:
   Brand     N       RMSE       MAE       R²
  toyota  3775  46.897353  2.598411 0.999945
      vw  8479  63.082838  3.946574 0.999933
    ford 13108  63.980359  3.652426 0.999821
   skoda  3507  80.171532  3.627887 0.999829
 hyundai  2724 104.155336  6.392070 0.999695
    audi  5971 118.844654  6.502261 0.999898
     bmw  6029 124.844385  3.790678 0.999879
    opel  7644 131.589032 11.239832 0.998620
mercedes  9541 181.644333 12.369982 0.999709

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1508.156131 1010.035705 0.820788
    ford 3282 1768.188805 1163.698578 0.860335
 hyundai  683 1912.997533 1211.926259 0.899336
  toyota  941 2110.132421 1232.335501 0.886188
   skoda  875 2189.804973 1472.373080 0.873391
      vw 2125 2779.461077 1688.750188 0.876123
     bmw 1513 3565.430794 2273.499693 0.902599
    audi 1489 3731.609089 2353.809217 0.883643
mercedes 2381 3883.268842 2404.395680 0.856302

      Brand     N         RMSE          MAE        R²
1      opel  1906  1508.156131  1010.035705  0.820788
2      ford  3282  1768.188805  1163.698578  0.860335
5   hyundai   683  1912.997533  1211.926259  0.899336
3    toyota   941  2110.132421  1232.335501  0.886188
7     skoda   875  2189.804973  1472.373080  0.873391
0        vw  2125  2779.461077  1688.750188  0.876123
8       bmw  1513  3565.430794  2273.499693  0.902599
6      audi  1489  3731.609089  2353.809217  0.883643
4  mercedes  2381  3883.268842  2404.395680  0.856302

### KNR

In [ ]:
KNR = KNeighborsRegressor()
trainer = BrandModelTrainer(KNR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 2086.84
  MAE:  1283.10
  R²:   0.9529

Validation Set Performance (Overall):
  RMSE: 2623.89
  MAE:  1599.60
  R²:   0.9232

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7644 1060.443151  724.541970 0.910381
    ford 13108 1306.958090  864.458222 0.925223
  toyota  3775 1415.382027  878.545362 0.949839
 hyundai  2724 1533.182629  989.739145 0.933874
   skoda  3507 1560.687760 1113.738857 0.935176
      vw  8479 1924.798390 1318.260710 0.937218
    audi  5971 2830.259754 1827.477616 0.942162
mercedes  9541 2885.203570 1869.137089 0.926679
     bmw  6029 2951.503736 1869.829258 0.932167

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1302.391145  882.899637 0.866353
    ford 3282 1575.199951 1082.577625 0.889159
  toyota  941 1745.839874 1107.878668 0.922093
 hyundai  683 1856.141027 1194.873983 0.905231
   skoda  875 1957.684444 1407.985499 0.898809
      vw 2125 2484.154084 1624.600940 0.901048
     bmw 1513 3484.453688 2329.667173 0.906973
mercedes 2381 3640.606197 2366.027305 0.873700
    audi 1489 3810.683371 2262.526043 0.878660

      Brand     N         RMSE          MAE        R²
1      opel  1906  1302.391145   882.899637  0.866353
2      ford  3282  1575.199951  1082.577625  0.889159
3    toyota   941  1745.839874  1107.878668  0.922093
5   hyundai   683  1856.141027  1194.873983  0.905231
7     skoda   875  1957.684444  1407.985499  0.898809
0        vw  2125  2484.154084  1624.600940  0.901048
8       bmw  1513  3484.453688  2329.667173  0.906973
4  mercedes  2381  3640.606197  2366.027305  0.873700
6      audi  1489  3810.683371  2262.526043  0.878660

### Random Forest

In [ ]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train, y_train)


rf_trainer.evaluate_train(X_train, y_train)
rf_trainer.evaluate(X_val, y_val)

rf_trainer.evaluate_train_by_brand(X_train, y_train)
rf_trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 783.19
  MAE:  470.30
  R²:   0.9934

Validation Set Performance (Overall):
  RMSE: 2032.89
  MAE:  1258.34
  R²:   0.9539

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7644  445.237109 301.775315 0.984202
    ford 13108  530.727184 343.508418 0.987669
  toyota  3775  561.355323 336.224850 0.992110
 hyundai  2724  567.357718 363.538041 0.990945
   skoda  3507  597.478664 404.029184 0.990499
      vw  8479  689.289589 445.810446 0.991949
     bmw  6029 1029.470880 640.502578 0.991748
    audi  5971 1034.713743 641.635071 0.992270
mercedes  9541 1118.873712 694.385848 0.988974

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1149.310525  780.338976 0.895924
    ford 3282 1351.280315  930.478081 0.918432
 hyundai  683 1423.578040  936.074861 0.944255
  toyota  941 1521.813102  934.312362 0.940804
   skoda  875 1562.612019 1074.404938 0.935530
      vw 2125 1895.158361 1228.334302 0.942408
    audi 1489 2599.268918 1666.287440 0.943545
     bmw 1513 2686.359438 1722.229650 0.944707
mercedes 2381 2896.389793 1857.880577 0.920059

      Brand     N         RMSE          MAE        R²
1      opel  1906  1149.310525   780.338976  0.895924
2      ford  3282  1351.280315   930.478081  0.918432
5   hyundai   683  1423.578040   936.074861  0.944255
3    toyota   941  1521.813102   934.312362  0.940804
7     skoda   875  1562.612019  1074.404938  0.935530
0        vw  2125  1895.158361  1228.334302  0.942408
6      audi  1489  2599.268918  1666.287440  0.943545
8       bmw  1513  2686.359438  1722.229650  0.944707
4  mercedes  2381  2896.389793  1857.880577  0.920059

### Neural Network

In [ ]:
from sklearn.neural_network import MLPRegressor

mlp_deep = MLPRegressor(
    hidden_layer_sizes=(256, 128, 64),  
    activation='relu',
    solver='adam',
    alpha=0.0001,  
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=2000,
    batch_size=256,
    random_state=69,
    early_stopping=True,
    n_iter_no_change=30,  
    validation_fraction=0.15,
    verbose=True
)

mlp_trainer = BrandModelTrainer(mlp_deep)


mlp_trainer.fit(X_train, y_train)


mlp_trainer.evaluate_train(X_train, y_train)
mlp_trainer.evaluate(X_val, y_val)


mlp_trainer.evaluate_train_by_brand(X_train, y_train)
mlp_trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

Iteration 1, loss = 59852720.28436311
Validation score: -9.266880
Iteration 2, loss = 59007365.20543310
Validation score: -8.928061
Iteration 3, loss = 54676844.81815294
Validation score: -7.525840
Iteration 4, loss = 41738644.98614478
Validation score: -4.268555
Iteration 5, loss = 21796883.07524724
Validation score: -0.896603
Iteration 6, loss = 8471215.93549464
Validation score: 0.163387
Iteration 7, loss = 5143618.36199932
Validation score: 0.319848
Iteration 8, loss = 4062500.79534993
Validation score: 0.407811
Iteration 9, loss = 3428061.86028418
Validation score: 0.468079
Iteration 10, loss = 3014297.13070471
Validation score: 0.515664
Iteration 11, loss = 2654734.59489821
Validation score: 0.554798
Iteration 12, loss = 2405561.22326486
Validation score: 0.584354
Iteration 13, loss = 2217646.07471571
Validation score: 0.610275
Iteration 14, loss = 2074960.47227245
Validation score: 0.629207
Iteration 15, loss = 1963516.83492540
Validation score: 0.644528
Iteration 16, loss = 1879588.15232065
Validation score: 0.657003
Iteration 17, loss = 1807830.34693152
Validation score: 0.666637
Iteration 18, loss = 1759339.04386037
Validation score: 0.675222
Iteration 19, loss = 1717987.30794932
Validation score: 0.681891
Iteration 20, loss = 1682714.50483477
Validation score: 0.687184
Iteration 21, loss = 1660505.05629215
Validation score: 0.688840
Iteration 22, loss = 1633301.64501990
Validation score: 0.695570
Iteration 23, loss = 1619949.91799729
Validation score: 0.698770
Iteration 24, loss = 1602620.28249965
Validation score: 0.699685
Iteration 25, loss = 1589123.81694120
Validation score: 0.700936
Iteration 26, loss = 1578923.95118775
Validation score: 0.704397
Iteration 27, loss = 1567254.61122752
Validation score: 0.705325
Iteration 28, loss = 1558791.84866370
Validation score: 0.705310
Iteration 29, loss = 1551521.74788047
Validation score: 0.710262
Iteration 30, loss = 1546410.11757271
Validation score: 0.710676
Iteration 31, loss = 1540396.03097506
Validation score: 0.711116
Iteration 32, loss = 1532632.43531557
Validation score: 0.711995
Iteration 33, loss = 1530004.69358561
Validation score: 0.712955
Iteration 34, loss = 1523083.70446733
Validation score: 0.714186
Iteration 35, loss = 1520573.78326819
Validation score: 0.714009
Iteration 36, loss = 1515518.81755387
Validation score: 0.714621
Iteration 37, loss = 1513535.81364200
Validation score: 0.716216
Iteration 38, loss = 1508684.33494873
Validation score: 0.715240
Iteration 39, loss = 1506304.15374088
Validation score: 0.715924
Iteration 40, loss = 1504043.72128647
Validation score: 0.717067
Iteration 41, loss = 1499840.66839862
Validation score: 0.716920
Iteration 42, loss = 1494306.11216953
Validation score: 0.718312
Iteration 43, loss = 1491272.67979647
Validation score: 0.719378
Iteration 44, loss = 1488956.07454749
Validation score: 0.719621
Iteration 45, loss = 1486933.09421084
Validation score: 0.719810
Iteration 46, loss = 1479896.67129046
Validation score: 0.720965
Iteration 47, loss = 1475739.43333500
Validation score: 0.720528
Iteration 48, loss = 1476862.11840686
Validation score: 0.720082
Iteration 49, loss = 1469802.26556535
Validation score: 0.722525
Iteration 50, loss = 1466872.60845431
Validation score: 0.724312
Iteration 51, loss = 1462245.34140982
Validation score: 0.723102
Iteration 52, loss = 1459288.47701994
Validation score: 0.725014
Iteration 53, loss = 1454510.64547179
Validation score: 0.726399
Iteration 54, loss = 1446045.95750265
Validation score: 0.727543
Iteration 55, loss = 1442341.42029005
Validation score: 0.728748
Iteration 56, loss = 1436453.35077471
Validation score: 0.728335
Iteration 57, loss = 1434104.98955376
Validation score: 0.729427
Iteration 58, loss = 1425522.80526619
Validation score: 0.729878
Iteration 59, loss = 1420458.86959646
Validation score: 0.730324
Iteration 60, loss = 1417821.47747799
Validation score: 0.730686
Iteration 61, loss = 1411048.74851161
Validation score: 0.732078
Iteration 62, loss = 1405577.41048722
Validation score: 0.733991
Iteration 63, loss = 1399693.26569133
Validation score: 0.734994
Iteration 64, loss = 1397550.89354852
Validation score: 0.737036
Iteration 65, loss = 1387598.96802388
Validation score: 0.735385
Iteration 66, loss = 1379735.06112341
Validation score: 0.738927
Iteration 67, loss = 1372855.48234930
Validation score: 0.740729
Iteration 68, loss = 1366466.54330162
Validation score: 0.739626
Iteration 69, loss = 1357412.07794330
Validation score: 0.743695
Iteration 70, loss = 1351077.03735052
Validation score: 0.744491
Iteration 71, loss = 1338825.57589013
Validation score: 0.744917
Iteration 72, loss = 1336098.19714365
Validation score: 0.745753
Iteration 73, loss = 1326481.51935381
Validation score: 0.748418
Iteration 74, loss = 1311180.78895777
Validation score: 0.749476
Iteration 75, loss = 1303947.72479078
Validation score: 0.751493
Iteration 76, loss = 1292584.32539241
Validation score: 0.753080
Iteration 77, loss = 1281828.73923313
Validation score: 0.752170
Iteration 78, loss = 1273852.41820889
Validation score: 0.756649
Iteration 79, loss = 1262345.93411431
Validation score: 0.761013
Iteration 80, loss = 1247736.59782360
Validation score: 0.761345
Iteration 81, loss = 1237673.72608863
Validation score: 0.761761
Iteration 82, loss = 1226259.17381245
Validation score: 0.763041
Iteration 83, loss = 1214423.17677036
Validation score: 0.768138
Iteration 84, loss = 1200369.66788432
Validation score: 0.767278
Iteration 85, loss = 1190162.80856616
Validation score: 0.771726
Iteration 86, loss = 1178048.82990520
Validation score: 0.776228
Iteration 87, loss = 1161422.75470627
Validation score: 0.777582
Iteration 88, loss = 1147771.95162802
Validation score: 0.779264
Iteration 89, loss = 1130888.96023571
Validation score: 0.780583
Iteration 90, loss = 1119619.92699053
Validation score: 0.785487
Iteration 91, loss = 1105143.99456748
Validation score: 0.789873
Iteration 92, loss = 1090902.25678381
Validation score: 0.790644
Iteration 93, loss = 1077119.27641335
Validation score: 0.795179
Iteration 94, loss = 1066363.17409693
Validation score: 0.796780
Iteration 95, loss = 1052234.70418720
Validation score: 0.800935
Iteration 96, loss = 1037324.86356870
Validation score: 0.801843
Iteration 97, loss = 1027635.59641550
Validation score: 0.803457
Iteration 98, loss = 1010982.38797409
Validation score: 0.805036
Iteration 99, loss = 1005133.42371782
Validation score: 0.808262
Iteration 100, loss = 992553.52404801
Validation score: 0.810047
Iteration 101, loss = 981478.81402284
Validation score: 0.812051
Iteration 102, loss = 976015.85407010
Validation score: 0.812463
Iteration 103, loss = 963952.31421729
Validation score: 0.813323
Iteration 104, loss = 956037.77241930
Validation score: 0.816987
Iteration 105, loss = 947552.70826936
Validation score: 0.817175
Iteration 106, loss = 942822.82235351
Validation score: 0.818705
Iteration 107, loss = 936360.19630086
Validation score: 0.819170
Iteration 108, loss = 931320.89216305
Validation score: 0.817915
Iteration 109, loss = 928349.29470782
Validation score: 0.820775
Iteration 110, loss = 920043.89027829
Validation score: 0.817734
Iteration 111, loss = 917595.65954647
Validation score: 0.821748
Iteration 112, loss = 913440.08966142
Validation score: 0.820843
Iteration 113, loss = 908669.37460525
Validation score: 0.822643
Iteration 114, loss = 902820.26146561
Validation score: 0.824478
Iteration 115, loss = 897017.03658788
Validation score: 0.822449
Iteration 116, loss = 895158.50312665
Validation score: 0.823160
Iteration 117, loss = 893184.48835862
Validation score: 0.826166
Iteration 118, loss = 887646.94995091
Validation score: 0.827464
Iteration 119, loss = 883296.57095060
Validation score: 0.828376
Iteration 120, loss = 881443.84533518
Validation score: 0.827813
Iteration 121, loss = 874175.08517924
Validation score: 0.826880
Iteration 122, loss = 874273.80709173
Validation score: 0.829408
Iteration 123, loss = 867619.59585912
Validation score: 0.829864
Iteration 124, loss = 865972.73806469
Validation score: 0.829765
Iteration 125, loss = 865278.14330386
Validation score: 0.830930
Iteration 126, loss = 862087.33228575
Validation score: 0.827756
Iteration 127, loss = 857458.56346000
Validation score: 0.832376
Iteration 128, loss = 853717.08445977
Validation score: 0.829284
Iteration 129, loss = 849955.46217467
Validation score: 0.831360
Iteration 130, loss = 849466.37172993
Validation score: 0.832908
Iteration 131, loss = 843109.97617803
Validation score: 0.833526
Iteration 132, loss = 839034.46724105
Validation score: 0.832036
Iteration 133, loss = 841309.90263500
Validation score: 0.829197
Iteration 134, loss = 832633.37456216
Validation score: 0.833573
Iteration 135, loss = 830374.79357852
Validation score: 0.831841
Iteration 136, loss = 829480.29244030
Validation score: 0.833930
Iteration 137, loss = 825463.86368433
Validation score: 0.832172
Iteration 138, loss = 821729.92882944
Validation score: 0.836163
Iteration 139, loss = 821500.19210838
Validation score: 0.834330
Iteration 140, loss = 822546.87618765
Validation score: 0.834673
Iteration 141, loss = 820799.59614324
Validation score: 0.835329
Iteration 142, loss = 821308.72937829
Validation score: 0.833236
Iteration 143, loss = 816181.56221207
Validation score: 0.838484
Iteration 144, loss = 808399.89068928
Validation score: 0.836129
Iteration 145, loss = 800219.26316716
Validation score: 0.838676
Iteration 146, loss = 799569.63153992
Validation score: 0.837722
Iteration 147, loss = 798458.30927400
Validation score: 0.836519
Iteration 148, loss = 798469.83668904
Validation score: 0.837601
Iteration 149, loss = 793887.78595212
Validation score: 0.838102
Iteration 150, loss = 796874.82920776
Validation score: 0.836150
Iteration 151, loss = 785987.84478660
Validation score: 0.836380
Iteration 152, loss = 789638.57011420
Validation score: 0.838307
Iteration 153, loss = 786248.91662280
Validation score: 0.838465
Iteration 154, loss = 783079.10072747
Validation score: 0.838455
Iteration 155, loss = 783816.29839664
Validation score: 0.841648
Iteration 156, loss = 785219.65716592
Validation score: 0.835665
Iteration 157, loss = 783941.71968030
Validation score: 0.842036
Iteration 158, loss = 776274.84272627
Validation score: 0.840639
Iteration 159, loss = 777341.10883950
Validation score: 0.841304
Iteration 160, loss = 773864.36231985
Validation score: 0.842180
Iteration 161, loss = 770055.08846888
Validation score: 0.840465
Iteration 162, loss = 771940.27137336
Validation score: 0.840696
Iteration 163, loss = 769285.31781239
Validation score: 0.841487
Iteration 164, loss = 770531.09358873
Validation score: 0.841508
Iteration 165, loss = 766255.81295541
Validation score: 0.841706
Iteration 166, loss = 765794.50738419
Validation score: 0.844128
Iteration 167, loss = 763574.64637018
Validation score: 0.836580
Iteration 168, loss = 765647.88547696
Validation score: 0.842857
Iteration 169, loss = 757413.90377936
Validation score: 0.842981
Iteration 170, loss = 761745.97688614
Validation score: 0.840771
Iteration 171, loss = 764278.32724192
Validation score: 0.841469
Iteration 172, loss = 756007.46987502
Validation score: 0.842267
Iteration 173, loss = 755670.09718634
Validation score: 0.843533
Iteration 174, loss = 757315.83220217
Validation score: 0.843706
Iteration 175, loss = 759021.37072515
Validation score: 0.844667
Iteration 176, loss = 756259.85968672
Validation score: 0.845065
Iteration 177, loss = 749148.22558843
Validation score: 0.846220
Iteration 178, loss = 749534.09194567
Validation score: 0.842512
Iteration 179, loss = 745965.91031625
Validation score: 0.843557
Iteration 180, loss = 745339.83440027
Validation score: 0.844964
Iteration 181, loss = 745306.11982896
Validation score: 0.846158
Iteration 182, loss = 742544.61628231
Validation score: 0.845690
Iteration 183, loss = 744527.33813967
Validation score: 0.844853
Iteration 184, loss = 745186.85771759
Validation score: 0.846198
Iteration 185, loss = 738641.25185844
Validation score: 0.845570
Iteration 186, loss = 737247.83690448
Validation score: 0.845621
Iteration 187, loss = 736182.15265462
Validation score: 0.847485
Iteration 188, loss = 738033.55695246
Validation score: 0.845289
Iteration 189, loss = 734436.52551427
Validation score: 0.845622
Iteration 190, loss = 738907.76149581
Validation score: 0.847703
Iteration 191, loss = 736576.30890679
Validation score: 0.844884
Iteration 192, loss = 730937.48011666
Validation score: 0.843342
Iteration 193, loss = 733477.83293444
Validation score: 0.845981
Iteration 194, loss = 727158.13986339
Validation score: 0.841813
Iteration 195, loss = 733539.55368819
Validation score: 0.844497
Iteration 196, loss = 726848.39199044
Validation score: 0.845228
Iteration 197, loss = 730502.69259094
Validation score: 0.845259
Iteration 198, loss = 730648.02195025
Validation score: 0.840918
Iteration 199, loss = 732224.33195429
Validation score: 0.847760
Iteration 200, loss = 730436.79581771
Validation score: 0.846165
Iteration 201, loss = 730429.29628704
Validation score: 0.848941
Iteration 202, loss = 727378.34580954
Validation score: 0.845752
Iteration 203, loss = 723672.26451284
Validation score: 0.848822
Iteration 204, loss = 719482.77233407
Validation score: 0.845778
Iteration 205, loss = 721663.46225506
Validation score: 0.843168
Iteration 206, loss = 716702.08005673
Validation score: 0.849488
Iteration 207, loss = 718186.05662475
Validation score: 0.847877
Iteration 208, loss = 721672.08211200
Validation score: 0.849511
Iteration 209, loss = 716382.58272461
Validation score: 0.850024
Iteration 210, loss = 715309.97397986
Validation score: 0.847647
Iteration 211, loss = 712578.45334394
Validation score: 0.849505
Iteration 212, loss = 714551.57707500
Validation score: 0.849157
Iteration 213, loss = 714752.77494866
Validation score: 0.844705
Iteration 214, loss = 712735.48545162
Validation score: 0.845978
Iteration 215, loss = 721502.65212973
Validation score: 0.847213
Iteration 216, loss = 709604.25901699
Validation score: 0.848476
Iteration 217, loss = 712071.98644080
Validation score: 0.848047
Iteration 218, loss = 711641.92998961
Validation score: 0.846878
Iteration 219, loss = 718735.22927996
Validation score: 0.847244
Iteration 220, loss = 710291.58014682
Validation score: 0.849541
Iteration 221, loss = 705660.35694357
Validation score: 0.848130
Iteration 222, loss = 706477.74935252
Validation score: 0.845974
Iteration 223, loss = 704391.14477642
Validation score: 0.849611
Iteration 224, loss = 701907.49715771
Validation score: 0.849482
Iteration 225, loss = 701791.36141390
Validation score: 0.849937
Iteration 226, loss = 705312.19278630
Validation score: 0.847863
Iteration 227, loss = 699544.02862303
Validation score: 0.850334
Iteration 228, loss = 701056.14968283
Validation score: 0.848030
Iteration 229, loss = 699232.29834421
Validation score: 0.851620
Iteration 230, loss = 701014.33573837
Validation score: 0.849408
Iteration 231, loss = 700873.10980957
Validation score: 0.849848
Iteration 232, loss = 701661.84344978
Validation score: 0.846982
Iteration 233, loss = 698225.86724776
Validation score: 0.848283
Iteration 234, loss = 692536.88848056
Validation score: 0.850879
Iteration 235, loss = 699227.23668632
Validation score: 0.846076
Iteration 236, loss = 699966.75359124
Validation score: 0.850135
Iteration 237, loss = 695101.32334748
Validation score: 0.851240
Iteration 238, loss = 697007.66109202
Validation score: 0.848772
Iteration 239, loss = 692893.84404428
Validation score: 0.849930
Iteration 240, loss = 692315.58423595
Validation score: 0.850438
Iteration 241, loss = 692142.87474094
Validation score: 0.850588
Iteration 242, loss = 689309.45899587
Validation score: 0.850835
Iteration 243, loss = 688640.58512267
Validation score: 0.850542
Iteration 244, loss = 689749.90478267
Validation score: 0.850540
Iteration 245, loss = 689243.30191093
Validation score: 0.850364
Iteration 246, loss = 689597.24776895
Validation score: 0.851760
Iteration 247, loss = 692257.59001605
Validation score: 0.851045
Iteration 248, loss = 687175.68883355
Validation score: 0.851425
Iteration 249, loss = 682493.30607450
Validation score: 0.850347
Iteration 250, loss = 684120.36988139
Validation score: 0.849904
Iteration 251, loss = 683836.18889969
Validation score: 0.852282
Iteration 252, loss = 686387.35689358
Validation score: 0.852017
Iteration 253, loss = 682383.51068214
Validation score: 0.848623
Iteration 254, loss = 679734.22969620
Validation score: 0.851629
Iteration 255, loss = 677185.90490426
Validation score: 0.852803
Iteration 256, loss = 679286.68631224
Validation score: 0.851059
Iteration 257, loss = 685358.02254655
Validation score: 0.850626
Iteration 258, loss = 683710.50470861
Validation score: 0.851595
Iteration 259, loss = 688978.46432451
Validation score: 0.851195
Iteration 260, loss = 690341.52269990
Validation score: 0.849264
Iteration 261, loss = 681877.17753766
Validation score: 0.849275
Iteration 262, loss = 686248.23256621
Validation score: 0.853972
Iteration 263, loss = 674680.66287311
Validation score: 0.852536
Iteration 264, loss = 672355.36367292
Validation score: 0.852451
Iteration 265, loss = 670977.89967691
Validation score: 0.853029
Iteration 266, loss = 667780.83295613
Validation score: 0.851941
Iteration 267, loss = 672248.89488371
Validation score: 0.853043
Iteration 268, loss = 675365.99084087
Validation score: 0.845893
Iteration 269, loss = 676475.91710626
Validation score: 0.850946
Iteration 270, loss = 666931.17128744
Validation score: 0.850307
Iteration 271, loss = 669318.90376969
Validation score: 0.853010
Iteration 272, loss = 665128.95943207
Validation score: 0.854401
Iteration 273, loss = 667012.32666977
Validation score: 0.854350
Iteration 274, loss = 667729.98205558
Validation score: 0.851096
Iteration 275, loss = 670522.64842758
Validation score: 0.853028
Iteration 276, loss = 661848.27736419
Validation score: 0.852789
Iteration 277, loss = 663824.52842191
Validation score: 0.848927
Iteration 278, loss = 666690.55984615
Validation score: 0.851745
Iteration 279, loss = 675785.46060431
Validation score: 0.853478
Iteration 280, loss = 675700.88860318
Validation score: 0.851586
Iteration 281, loss = 666481.90506431
Validation score: 0.855066
Iteration 282, loss = 662745.03910987
Validation score: 0.851488
Iteration 283, loss = 657537.07194488
Validation score: 0.854665
Iteration 284, loss = 658152.36291173
Validation score: 0.852354
Iteration 285, loss = 659980.20594837
Validation score: 0.852141
Iteration 286, loss = 660249.05839140
Validation score: 0.855373
Iteration 287, loss = 654773.98542551
Validation score: 0.856801
Iteration 288, loss = 653931.37850219
Validation score: 0.851807
Iteration 289, loss = 656335.67913658
Validation score: 0.855877
Iteration 290, loss = 654490.40605761
Validation score: 0.856380
Iteration 291, loss = 652437.99644512
Validation score: 0.854637
Iteration 292, loss = 652116.60774410
Validation score: 0.852742
Iteration 293, loss = 652756.23081372
Validation score: 0.852873
Iteration 294, loss = 646732.32807389
Validation score: 0.855631
Iteration 295, loss = 649464.96116793
Validation score: 0.852516
Iteration 296, loss = 648892.17537595
Validation score: 0.852914
Iteration 297, loss = 645264.65212658
Validation score: 0.855919
Iteration 298, loss = 643228.79717947
Validation score: 0.855883
Iteration 299, loss = 644051.03204396
Validation score: 0.857347
Iteration 300, loss = 641278.26104187
Validation score: 0.855902
Iteration 301, loss = 647057.16401695
Validation score: 0.856194
Iteration 302, loss = 645330.72362663
Validation score: 0.857036
Iteration 303, loss = 642190.87562323
Validation score: 0.855833
Iteration 304, loss = 640349.90005163
Validation score: 0.858368
Iteration 305, loss = 637576.90117218
Validation score: 0.855682
Iteration 306, loss = 639688.24631507
Validation score: 0.854775
Iteration 307, loss = 638968.41659727
Validation score: 0.857381

      Brand     N         RMSE          MAE        R²
1      opel  1906  1185.958936   825.331619  0.889181
2      ford  3282  1457.492770  1026.689923  0.905105
5   hyundai   683  1498.572902   991.528424  0.938227
3    toyota   941  1584.843834  1000.246157  0.935799
7     skoda   875  1685.425548  1201.032753  0.924998
0        vw  2125  2325.160546  1491.889290  0.913309
6      audi  1489  2968.604285  2011.282473  0.926362
8       bmw  1513  3051.200355  2103.005976  0.928668
4  mercedes  2381  3367.450326  2239.211709  0.891942

### Performance

| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3383.27 | 2156.67 | 0.8723 |
| Tree | 2784.00 | 1663.58 | 0.9135 |
| KNR|2623.89 |1599.60 |0.9232 |
|RF | 2032.89 |1258.34 |0.9539 |
|NN | 2319.24 |1466.96 |0.9400 |

## Feature selection - Filter Methods

In [ ]:
df = X_train.join(y_train)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60778 entries, 0 to 60777
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           60778 non-null  int32
 1   tax               60778 non-null  int32
 2   mpg               60778 non-null  float64
 3   engineSize        60778 non-null  float64
 4   previousOwners    60778 non-null  int32
 5   stated_no_damage  60778 non-null  float64
 6   Brand             60778 non-null  object
 7   transmission      60778 non-null  object
 8   fuelType          60778 non-null  object
 9   age               60778 non-null  int32
 10  mileage_per_year  60778 non-null  float64
 11  efficiency_ratio  60778 non-null  float64
 12  age_mileage       60778 non-null  float64
 13  model_mean_price  60778 non-null  float64
 14  price             60778 non-null  float64
dtypes: float64(8), int32(4), object(3)
memory usage: 6.3+ MB

In [ ]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
y = df['price']

numerical_cols = df.select_dtypes(include=['int64', "int32",'float64']).columns

# Drop 'carID' and 'price'
num_cols = [col for col in numerical_cols 
            if "_transformed" not in col and col not in ['price', 'carID']]

print(num_cols)
print(categorical_cols)

['mileage', 'tax', 'mpg', 'engineSize', 'previousOwners', 'stated_no_damage', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']
['Brand', 'transmission', 'fuelType']

In [ ]:
#FILTER METHOD


#ANOVA FUNCTION

def anova_for_categorical(df, y, categorical_cols):
    # Align indices between df and y
    common_idx = df.index.intersection(y.index)
    df_aligned = df.loc[common_idx]
    y_aligned = y.loc[common_idx]
    
    f_scores, p_values = [], []
    for col in df_aligned.columns:
        if col in categorical_cols:
            groups = [y_aligned[df_aligned[col] == cat] for cat in df_aligned[col].dropna().unique()]
            if len(groups) > 1 and all(len(g) > 1 for g in groups):
                f_stat, p_val = stats.f_oneway(*groups)
            else:
                f_stat, p_val = 0.0, 1.0
        else:
            if df_aligned[col].nunique() > 1:
                # Remove NaN values for correlation calculation
                valid_idx = df_aligned[col].notna() & y_aligned.notna()
                if valid_idx.sum() > 1:
                    corr = np.corrcoef(df_aligned.loc[valid_idx, col], y_aligned[valid_idx])[0, 1]
                    f_stat = corr**2 * valid_idx.sum()
                    p_val = 0.0
                else:
                    f_stat, p_val = 0.0, 1.0
            else:
                f_stat, p_val = 0.0, 1.0
        f_scores.append(f_stat)
        p_values.append(p_val)
    
    return np.array(f_scores), np.array(p_values)


def filter_method_selection(X_train, y_train, categorical_cols, num_cols,
                            top_k=None,
                            var_threshold=0.01,
                            corr_threshold=0.85):
    
    print("FILTER METHOD (Variance + Spearman Correlation + ANOVA)")
    
    # Ensure indices match
    common_idx = X_train.index.intersection(y_train.index)
    X_train = X_train.loc[common_idx]
    y_train = y_train.loc[common_idx]
    
    # Filter numerical columns that exist in X_train
    num_cols_in_X = [col for col in num_cols if col in X_train.columns]
    
    # Variance Threshold
    if num_cols_in_X:
        vt_selector = VarianceThreshold(threshold=var_threshold)
        X_num_vt = pd.DataFrame(
            vt_selector.fit_transform(X_train[num_cols_in_X]),
            columns=np.array(num_cols_in_X)[vt_selector.get_support()],
            index=X_train.index
        )
        print(f"Removed {len(num_cols_in_X) - X_num_vt.shape[1]} low-variance numeric features.")
    else:
        X_num_vt = pd.DataFrame(index=X_train.index)
    
    # Spearman Correlation
    if not X_num_vt.empty and X_num_vt.shape[1] > 1:
        corr_matrix = X_num_vt.corr(method='spearman').abs()
        upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
        to_drop = [col for col in upper.columns if any(upper[col] > corr_threshold)]
        X_num_corr = X_num_vt.drop(columns=to_drop)
        print(f"Removed {len(to_drop)} correlated numeric features (Spearman |corr| > {corr_threshold}).")
    else:
        X_num_corr = X_num_vt
    
    # Filter categorical columns that exist in X_train
    categorical_cols_in_X = [col for col in categorical_cols if col in X_train.columns]
    
    # Combine numeric + categorical
    X_filtered = pd.concat([X_num_corr, X_train[categorical_cols_in_X]], axis=1)
    
    # ANOVA F-test
    f_scores, f_pvalues = anova_for_categorical(X_filtered, y_train, categorical_cols_in_X)
    f_norm = (f_scores - f_scores.min()) / (f_scores.max() - f_scores.min() + 1e-10)
    
    results_df = pd.DataFrame({
        'feature': X_filtered.columns,
        'ANOVA_F': f_scores,
        'ANOVA_p_value': f_pvalues,
        'ANOVA_norm': f_norm,
        'type': ['categorical' if c in categorical_cols_in_X else 'numerical' for c in X_filtered.columns]
    }).sort_values('ANOVA_norm', ascending=False)
    
    if top_k is None:
        selected_features = X_filtered.columns.tolist()
    else:
        selected_features = X_filtered.columns[np.argsort(f_norm)[-top_k:]].tolist()
    
    print(f"\nFilter method selected {len(selected_features)} features")
    
    return selected_features, X_filtered[selected_features], results_df

In [ ]:
y = df["price"]

df = df.drop(columns=["price"])

In [ ]:

#X_train = df[num_cols]
#y_train = df['price']

# Filter method (Variance + Spearman + ANOVA)
# Define categorical and numerical columns first (if not already defined)
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
num_cols = df.select_dtypes(include=['int64',"int32", 'float64']).columns.tolist()

# Filter method with all required parameters
selected_filter, X_train_filtered, filter_df = filter_method_selection(
    df, 
    y,
    categorical_cols=categorical_cols,  # Add this
    num_cols=num_cols,                  # Add this
    top_k=None, 
    var_threshold=0.01, 
    corr_threshold=0.85
)

# Print features selected
print("\nFeatures selected by Filter Method:")
for f in selected_filter:
    print(f)

# Display feature importance scores
print("\nTop 10 Features by ANOVA Score:")
print(filter_df.head(10))

FILTER METHOD (Variance + Spearman Correlation + ANOVA)
Removed 0 low-variance numeric features.
Removed 2 correlated numeric features (Spearman |corr| > 0.85).

Filter method selected 12 features

Features selected by Filter Method:
mileage
tax
mpg
engineSize
previousOwners
stated_no_damage
age
efficiency_ratio
model_mean_price
Brand
transmission
fuelType

Top 10 Features by ANOVA Score:
             feature       ANOVA_F  ANOVA_p_value  ANOVA_norm         type
8   model_mean_price  34427.971184            0.0    1.000000    numerical
3         engineSize  22861.690368            0.0    0.664044    numerical
6                age  14640.658332            0.0    0.425255    numerical
10      transmission  13153.933343            0.0    0.382071  categorical
0            mileage  10714.468578            0.0    0.311214    numerical
1                tax   5713.455939            0.0    0.165954    numerical
2                mpg   5027.571589            0.0    0.146032    numerical
9              Brand   3175.490515            0.0    0.092236  categorical
11          fuelType   1040.499728            0.0    0.030223  categorical
7   efficiency_ratio    559.411994            0.0    0.016249    numerical

In [ ]:
raise SystemExit("Stop before training the models")

SystemExit: Stop before training the models

C:\Users\liber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

## Test models on reduced DF

In [42]:
X_train_filter = X_train[["mileage", "tax", "mpg", "engineSize", "previousOwners", "stated_no_damage", "age", "efficiency_ratio", 
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_train_filter

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model_mean_price,fuelType
0,11899,124,51.4,1.4,2,1.0,4,34.266667,opel,manual,10488.218094,petrol
1,18500,145,48.7,1.4,4,1.0,2,32.466667,audi,semi-auto,22860.502532,petrol
2,10658,145,46.3,1.5,2,1.0,1,28.937500,mercedes,semi-auto,23609.185947,petrol
3,1500,145,43.5,0.0,4,1.0,0,435.000000,audi,manual,22522.319540,petrol
4,18495,98,64.1,2.1,4,1.0,3,29.136364,mercedes,automatic,23609.185947,diesel
...,...,...,...,...,...,...,...,...,...,...,...,...
60773,14867,150,55.4,1.4,3,1.0,2,36.933333,opel,manual,8338.330769,petrol
60774,20100,145,52.3,1.2,3,1.0,2,40.230769,toyota,manual,12456.520101,petrol
60775,10498,145,68.9,1.0,0,1.0,2,62.636364,toyota,manual,8046.197685,petrol
60776,17502,145,40.4,2.0,4,1.0,3,19.238095,audi,semi-auto,30135.793388,petrol
60777,16734,145,54.3,1.4,1,1.0,2,36.200000,opel,manual,8338.330769,petrol

In [43]:
X_val_filter = X_val[["mileage", "tax", "mpg", "engineSize", "previousOwners", "stated_no_damage", "age", "efficiency_ratio", 
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_val_filter

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model_mean_price,fuelType
0,14774,145,53.3,2.0,0,1.0,1,25.380952,vw,manual,16802.884146,diesel
1,16375,150,47.9,1.6,4,1.0,4,28.176471,ford,manual,10252.815470,petrol
2,32746,265,37.2,3.0,3,0.0,4,12.000000,bmw,semi-auto,19665.944282,petrol
3,10164,145,68.9,1.5,3,1.0,1,43.062500,bmw,automatic,15836.032550,diesel
4,11407,145,80.7,1.5,2,1.0,1,50.437500,ford,manual,13400.396964,diesel
...,...,...,...,...,...,...,...,...,...,...,...,...
15190,10766,20,51.4,1.4,2,1.0,1,34.266667,opel,manual,10488.218094,petrol
15191,5000,145,48.7,2.0,1,1.0,0,23.190476,vw,semi-auto,16802.884146,diesel
15192,28056,145,60.1,2.0,0,1.0,3,28.619048,ford,manual,15784.977335,diesel
15193,25169,145,56.5,1.0,4,1.0,2,51.363636,ford,manual,10252.815470,petrol
15194,23389,145,58.9,1.5,2,0.0,3,36.812500,toyota,manual,10500.113958,petrol

### Linear Regression

In [ ]:
LR = LinearRegression()
trainer = BrandModelTrainer(LR)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 3569.83
  MAE:  2224.49
  R²:   0.8621

Validation Set Performance (Overall):
  RMSE: 3501.39
  MAE:  2241.68
  R²:   0.8632

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7644 1847.478671 1275.024377 0.727989
   skoda  3507 2209.115055 1540.806376 0.870120
    ford 13108 2235.318701 1573.277430 0.781262
  toyota  3775 2433.505700 1476.753655 0.851720
 hyundai  2724 2526.620730 1704.753502 0.820417
      vw  8479 3188.715394 2132.994825 0.827696
    audi  5971 4607.100051 2997.744466 0.846743
     bmw  6029 4805.254287 3314.721301 0.820201
mercedes  9541 5358.237831 3483.853978 0.747118

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1812.706179 1280.647362 0.741101
    ford 3282 2207.180214 1599.699316 0.782377
 hyundai  683 2486.132214 1649.172777 0.829983
   skoda  875 2531.178369 1585.820124 0.830839
  toyota  941 2535.753276 1531.276127 0.835645
      vw 2125 3396.538431 2171.385451 0.815013
    audi 1489 4454.373544 3000.955775 0.834204
     bmw 1513 4714.310051 3296.302181 0.829715
mercedes 2381 5039.620621 3505.430332 0.757980

      Brand     N         RMSE          MAE        R²
1      opel  1906  1812.706179  1280.647362  0.741101
2      ford  3282  2207.180214  1599.699316  0.782377
5   hyundai   683  2486.132214  1649.172777  0.829983
7     skoda   875  2531.178369  1585.820124  0.830839
3    toyota   941  2535.753276  1531.276127  0.835645
0        vw  2125  3396.538431  2171.385451  0.815013
6      audi  1489  4454.373544  3000.955775  0.834204
8       bmw  1513  4714.310051  3296.302181  0.829715
4  mercedes  2381  5039.620621  3505.430332  0.757980

### Single tree

In [ ]:
Tree = DecisionTreeRegressor(criterion="absolute_error")
trainer = BrandModelTrainer(Tree)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)        # Performance VALID

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 114.96
  MAE:  6.59
  R²:   0.9999

Validation Set Performance (Overall):
  RMSE: 2759.39
  MAE:  1650.79
  R²:   0.9150

Training Performance per Brand:
   Brand     N       RMSE       MAE       R²
  toyota  3775  46.897353  2.598411 0.999945
      vw  8479  63.082838  3.946574 0.999933
    ford 13108  63.980359  3.652426 0.999821
   skoda  3507  80.171532  3.627887 0.999829
    audi  5971 118.844654  6.502261 0.999898
     bmw  6029 124.844385  3.790678 0.999879
    opel  7644 131.589032 11.239832 0.998620
 hyundai  2724 147.792520 11.420338 0.999386
mercedes  9541 181.644333 12.369982 0.999709

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1489.669080 1003.150186 0.825154
    ford 3282 1814.337280 1190.181697 0.852950
 hyundai  683 1902.116447 1235.952315 0.900478
   skoda  875 2090.996628 1438.788439 0.884559
  toyota  941 2346.387743 1266.682005 0.859276
      vw 2125 2521.645041 1578.123835 0.898039
     bmw 1513 3631.626580 2332.910419 0.898948
    audi 1489 3687.525193 2288.208390 0.886376
mercedes 2381 3859.881075 2385.607905 0.858027

      Brand     N         RMSE          MAE        R²
1      opel  1906  1489.669080  1003.150186  0.825154
2      ford  3282  1814.337280  1190.181697  0.852950
5   hyundai   683  1902.116447  1235.952315  0.900478
7     skoda   875  2090.996628  1438.788439  0.884559
3    toyota   941  2346.387743  1266.682005  0.859276
0        vw  2125  2521.645041  1578.123835  0.898039
8       bmw  1513  3631.626580  2332.910419  0.898948
6      audi  1489  3687.525193  2288.208390  0.886376
4  mercedes  2381  3859.881075  2385.607905  0.858027

In [ ]:
KNR = KNeighborsRegressor()
trainer = BrandModelTrainer(KNR)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 2101.29
  MAE:  1281.10
  R²:   0.9522

Validation Set Performance (Overall):
  RMSE: 2624.75
  MAE:  1598.18
  R²:   0.9231

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7644 1061.803550  726.367342 0.910150
    ford 13108 1298.672984  853.786253 0.926168
  toyota  3775 1305.945217  829.741756 0.957296
   skoda  3507 1546.850965 1097.138994 0.936320
 hyundai  2724 1553.896147  992.036005 0.932075
      vw  8479 1857.952137 1266.352114 0.941503
    audi  5971 2882.967420 1852.861059 0.939987
mercedes  9541 2935.803235 1895.555914 0.924085
     bmw  6029 3023.021640 1915.804820 0.928840

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1340.656131  905.444789 0.858385
    ford 3282 1541.808631 1065.807156 0.893808
  toyota  941 1664.797525 1057.595262 0.929158
 hyundai  683 1765.038156 1171.877665 0.914305
   skoda  875 1916.159213 1375.449742 0.903057
      vw 2125 2395.816536 1559.189324 0.907960
     bmw 1513 3542.433394 2357.861489 0.903851
    audi 1489 3716.919635 2316.399531 0.884557
mercedes 2381 3765.042995 2407.257809 0.864918

      Brand     N         RMSE          MAE        R²
1      opel  1906  1340.656131   905.444789  0.858385
2      ford  3282  1541.808631  1065.807156  0.893808
3    toyota   941  1664.797525  1057.595262  0.929158
5   hyundai   683  1765.038156  1171.877665  0.914305
7     skoda   875  1916.159213  1375.449742  0.903057
0        vw  2125  2395.816536  1559.189324  0.907960
8       bmw  1513  3542.433394  2357.861489  0.903851
6      audi  1489  3716.919635  2316.399531  0.884557
4  mercedes  2381  3765.042995  2407.257809  0.864918

In [ ]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train_filter, y_train)


rf_trainer.evaluate_train(X_train_filter, y_train)
rf_trainer.evaluate(X_val_filter, y_val)

rf_trainer.evaluate_train_by_brand(X_train_filter, y_train)
rf_trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 787.09
  MAE:  470.69
  R²:   0.9933

Validation Set Performance (Overall):
  RMSE: 2036.38
  MAE:  1254.22
  R²:   0.9537

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7644  445.583387 300.987988 0.984177
    ford 13108  535.050811 345.635490 0.987468
  toyota  3775  564.412680 339.965707 0.992024
 hyundai  2724  570.561065 362.710890 0.990842
   skoda  3507  591.453614 404.982711 0.990690
      vw  8479  686.241571 447.794275 0.992020
     bmw  6029 1019.104211 634.184072 0.991913
    audi  5971 1020.306011 637.106042 0.992483
mercedes  9541 1149.001100 698.037248 0.988372

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1143.391435  780.680350 0.896993
    ford 3282 1347.582089  931.183258 0.918878
 hyundai  683 1439.731060  928.386067 0.942983
   skoda  875 1564.294389 1067.217619 0.935391
  toyota  941 1571.925232  947.383192 0.936841
      vw 2125 1889.320722 1226.463762 0.942763
    audi 1489 2630.209902 1669.746477 0.942193
     bmw 1513 2670.874361 1694.002100 0.945343
mercedes 2381 2898.125343 1847.452824 0.919963

      Brand     N         RMSE          MAE        R²
1      opel  1906  1143.391435   780.680350  0.896993
2      ford  3282  1347.582089   931.183258  0.918878
5   hyundai   683  1439.731060   928.386067  0.942983
7     skoda   875  1564.294389  1067.217619  0.935391
3    toyota   941  1571.925232   947.383192  0.936841
0        vw  2125  1889.320722  1226.463762  0.942763
6      audi  1489  2630.209902  1669.746477  0.942193
8       bmw  1513  2670.874361  1694.002100  0.945343
4  mercedes  2381  2898.125343  1847.452824  0.919963

### Neural Network

In [ ]:
from sklearn.neural_network import MLPRegressor

mlp_deep = MLPRegressor(
    hidden_layer_sizes=(256, 128, 64),  
    activation='relu',
    solver='adam',
    alpha=0.0001,  
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=2000,
    batch_size=256,
    random_state=69,
    early_stopping=True,
    n_iter_no_change=30,  
    validation_fraction=0.15,
    verbose=True
)

mlp_trainer = BrandModelTrainer(mlp_deep)


mlp_trainer.fit(X_train_filter, y_train)


mlp_trainer.evaluate_train(X_train_filter, y_train)
mlp_trainer.evaluate(X_val_filter, y_val)


mlp_trainer.evaluate_train_by_brand(X_train_filter, y_train)
mlp_trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

Iteration 1, loss = 60074429.15314120
Validation score: -8.812077
Iteration 2, loss = 59153427.26676983
Validation score: -8.429295
Iteration 3, loss = 54038065.92276022
Validation score: -6.897440
Iteration 4, loss = 38504717.10375964
Validation score: -3.973099
Iteration 5, loss = 16150524.08295236
Validation score: -1.474015
Iteration 6, loss = 5774947.23333462
Validation score: -0.430285
Iteration 7, loss = 3898101.21302131
Validation score: 0.003783
Iteration 8, loss = 3113215.03595616
Validation score: 0.137238
Iteration 9, loss = 2652479.89972620
Validation score: 0.221500
Iteration 10, loss = 2354027.43999203
Validation score: 0.290069
Iteration 11, loss = 2146626.74663658
Validation score: 0.349042
Iteration 12, loss = 1999515.69672397
Validation score: 0.393220
Iteration 13, loss = 1892011.74866987
Validation score: 0.442029
Iteration 14, loss = 1816187.10595373
Validation score: 0.465819
Iteration 15, loss = 1751985.64477006
Validation score: 0.482954
Iteration 16, loss = 1708235.84678329
Validation score: 0.499220
Iteration 17, loss = 1673936.22538976
Validation score: 0.508246
Iteration 18, loss = 1648355.80747340
Validation score: 0.531357
Iteration 19, loss = 1628122.41294175
Validation score: 0.528997
Iteration 20, loss = 1617043.14901606
Validation score: 0.551390
Iteration 21, loss = 1598557.22469747
Validation score: 0.555413
Iteration 22, loss = 1587393.92502867
Validation score: 0.548803
Iteration 23, loss = 1579967.38636132
Validation score: 0.554319
Iteration 24, loss = 1571865.23629600
Validation score: 0.560589
Iteration 25, loss = 1563782.18693905
Validation score: 0.557229
Iteration 26, loss = 1557403.66088512
Validation score: 0.579870
Iteration 27, loss = 1554549.26638171
Validation score: 0.569204
Iteration 28, loss = 1549345.05422825
Validation score: 0.571654
Iteration 29, loss = 1543247.82397602
Validation score: 0.581876
Iteration 30, loss = 1544100.56103076
Validation score: 0.578023
Iteration 31, loss = 1534327.25219837
Validation score: 0.569164
Iteration 32, loss = 1530985.98375643
Validation score: 0.574365
Iteration 33, loss = 1525995.92142627
Validation score: 0.581192
Iteration 34, loss = 1521580.95717540
Validation score: 0.590790
Iteration 35, loss = 1514903.69770893
Validation score: 0.581522
Iteration 36, loss = 1511403.87294857
Validation score: 0.571888
Iteration 37, loss = 1506830.30619242
Validation score: 0.591335
Iteration 38, loss = 1500526.87708110
Validation score: 0.589391
Iteration 39, loss = 1497935.73172305
Validation score: 0.587830
Iteration 40, loss = 1489853.82220379
Validation score: 0.574545
Iteration 41, loss = 1490671.83765124
Validation score: 0.592796
Iteration 42, loss = 1478866.54865248
Validation score: 0.591140
Iteration 43, loss = 1474176.65243224
Validation score: 0.593009
Iteration 44, loss = 1467819.58789499
Validation score: 0.594237
Iteration 45, loss = 1460887.17272951
Validation score: 0.585908
Iteration 46, loss = 1456210.56530735
Validation score: 0.599839
Iteration 47, loss = 1453011.59011229
Validation score: 0.598843
Iteration 48, loss = 1447787.96298510
Validation score: 0.593516
Iteration 49, loss = 1438638.57606612
Validation score: 0.598419
Iteration 50, loss = 1428045.37886971
Validation score: 0.594142
Iteration 51, loss = 1420317.65593580
Validation score: 0.596932
Iteration 52, loss = 1415416.84286862
Validation score: 0.603287
Iteration 53, loss = 1406848.41956149
Validation score: 0.603534
Iteration 54, loss = 1397392.67215533
Validation score: 0.618363
Iteration 55, loss = 1389203.77748155
Validation score: 0.609345
Iteration 56, loss = 1379347.53820242
Validation score: 0.624528
Iteration 57, loss = 1371391.79862310
Validation score: 0.620131
Iteration 58, loss = 1358556.95984347
Validation score: 0.626183
Iteration 59, loss = 1347494.21080180
Validation score: 0.631514
Iteration 60, loss = 1336556.94144341
Validation score: 0.637580
Iteration 61, loss = 1326888.80037940
Validation score: 0.641269
Iteration 62, loss = 1320111.37322728
Validation score: 0.643219
Iteration 63, loss = 1309456.91163537
Validation score: 0.644984
Iteration 64, loss = 1294321.71938428
Validation score: 0.644294
Iteration 65, loss = 1280946.00514660
Validation score: 0.671213
Iteration 66, loss = 1269264.95303268
Validation score: 0.663233
Iteration 67, loss = 1254035.91311499
Validation score: 0.669036
Iteration 68, loss = 1240529.62728898
Validation score: 0.663509
Iteration 69, loss = 1231274.88306714
Validation score: 0.666222
Iteration 70, loss = 1221682.48008143
Validation score: 0.678521
Iteration 71, loss = 1205662.31583552
Validation score: 0.692847
Iteration 72, loss = 1196115.09010791
Validation score: 0.696659
Iteration 73, loss = 1181899.45983120
Validation score: 0.701038
Iteration 74, loss = 1167747.01815881
Validation score: 0.696616
Iteration 75, loss = 1153849.78997761
Validation score: 0.707069
Iteration 76, loss = 1142858.42845265
Validation score: 0.716801
Iteration 77, loss = 1132781.19093289
Validation score: 0.719914
Iteration 78, loss = 1119784.06528389
Validation score: 0.724028
Iteration 79, loss = 1107859.61299060
Validation score: 0.732262
Iteration 80, loss = 1102735.48122482
Validation score: 0.746853
Iteration 81, loss = 1087407.03071031
Validation score: 0.749106
Iteration 82, loss = 1079066.57049300
Validation score: 0.754142
Iteration 83, loss = 1072457.29467821
Validation score: 0.754941
Iteration 84, loss = 1058479.35299532
Validation score: 0.758091
Iteration 85, loss = 1054272.61765518
Validation score: 0.770794
Iteration 86, loss = 1043235.12146771
Validation score: 0.768952
Iteration 87, loss = 1035966.02149364
Validation score: 0.774136
Iteration 88, loss = 1029994.87590653
Validation score: 0.776348
Iteration 89, loss = 1024187.93516284
Validation score: 0.783662
Iteration 90, loss = 1017805.22216193
Validation score: 0.789263
Iteration 91, loss = 1010875.45123824
Validation score: 0.789573
Iteration 92, loss = 1004432.01787789
Validation score: 0.793160
Iteration 93, loss = 998033.45900594
Validation score: 0.793743
Iteration 94, loss = 999925.57945414
Validation score: 0.795982
Iteration 95, loss = 993550.25171451
Validation score: 0.801478
Iteration 96, loss = 985545.25209478
Validation score: 0.798547
Iteration 97, loss = 980055.08394046
Validation score: 0.809254
Iteration 98, loss = 975782.14969927
Validation score: 0.803487
Iteration 99, loss = 970558.50950960
Validation score: 0.812330
Iteration 100, loss = 970414.85298950
Validation score: 0.814030
Iteration 101, loss = 965394.24648993
Validation score: 0.817884
Iteration 102, loss = 957689.20726765
Validation score: 0.814104
Iteration 103, loss = 957333.24720309
Validation score: 0.814711
Iteration 104, loss = 957705.07461372
Validation score: 0.819282
Iteration 105, loss = 948175.41495774
Validation score: 0.821420
Iteration 106, loss = 943027.21170746
Validation score: 0.817092
Iteration 107, loss = 941338.84871071
Validation score: 0.819897
Iteration 108, loss = 938722.00563515
Validation score: 0.820318
Iteration 109, loss = 937099.43471795
Validation score: 0.826870
Iteration 110, loss = 931248.13413792
Validation score: 0.823076
Iteration 111, loss = 928498.17106682
Validation score: 0.829009
Iteration 112, loss = 927810.03771175
Validation score: 0.820516
Iteration 113, loss = 923961.56313174
Validation score: 0.829850
Iteration 114, loss = 917870.55111327
Validation score: 0.831510
Iteration 115, loss = 919734.74132167
Validation score: 0.828486
Iteration 116, loss = 911596.48699047
Validation score: 0.832093
Iteration 117, loss = 908382.85579005
Validation score: 0.832207
Iteration 118, loss = 906740.20134419
Validation score: 0.833395
Iteration 119, loss = 906229.78079843
Validation score: 0.836003
Iteration 120, loss = 903015.26920647
Validation score: 0.835362
Iteration 121, loss = 898473.57053293
Validation score: 0.837411
Iteration 122, loss = 891837.27292450
Validation score: 0.829399
Iteration 123, loss = 892768.35308019
Validation score: 0.835499
Iteration 124, loss = 893724.71436930
Validation score: 0.838980
Iteration 125, loss = 891464.80019573
Validation score: 0.837954
Iteration 126, loss = 886249.59808483
Validation score: 0.837671
Iteration 127, loss = 878979.90509465
Validation score: 0.844509
Iteration 128, loss = 881416.66354599
Validation score: 0.846132
Iteration 129, loss = 877489.46907821
Validation score: 0.843020
Iteration 130, loss = 879004.55817575
Validation score: 0.841994
Iteration 131, loss = 871106.41003725
Validation score: 0.845026
Iteration 132, loss = 871132.53357950
Validation score: 0.844828
Iteration 133, loss = 866466.51227541
Validation score: 0.842791
Iteration 134, loss = 863078.49885890
Validation score: 0.853169
Iteration 135, loss = 861629.69707321
Validation score: 0.838490
Iteration 136, loss = 865765.31787667
Validation score: 0.852581
Iteration 137, loss = 859862.94340314
Validation score: 0.845234
Iteration 138, loss = 853501.21270677
Validation score: 0.851108
Iteration 139, loss = 850656.19136114
Validation score: 0.849654
Iteration 140, loss = 852054.51799812
Validation score: 0.850247
Iteration 141, loss = 848400.05154851
Validation score: 0.849673
Iteration 142, loss = 845022.20926812
Validation score: 0.853072
Iteration 143, loss = 842685.56362699
Validation score: 0.849049
Iteration 144, loss = 841936.36519368
Validation score: 0.852309
Iteration 145, loss = 838271.89030609
Validation score: 0.854976
Iteration 146, loss = 837374.95665164
Validation score: 0.854612
Iteration 147, loss = 838830.01191330
Validation score: 0.851830
Iteration 148, loss = 839044.71731763
Validation score: 0.853690
Iteration 149, loss = 836916.40085182
Validation score: 0.856137
Iteration 150, loss = 831464.30627341
Validation score: 0.856868
Iteration 151, loss = 828144.64117519
Validation score: 0.854115
Iteration 152, loss = 827277.10766242
Validation score: 0.851619
Iteration 153, loss = 831796.04222077
Validation score: 0.855967
Iteration 154, loss = 822169.60877750
Validation score: 0.858126
Iteration 155, loss = 817031.69882156
Validation score: 0.855076
Iteration 156, loss = 819157.07221998
Validation score: 0.857315
Iteration 157, loss = 814630.06201732
Validation score: 0.857194
Iteration 158, loss = 809146.43450883
Validation score: 0.861780
Iteration 159, loss = 809464.45352565
Validation score: 0.861516
Iteration 160, loss = 807885.09488524
Validation score: 0.861801
Iteration 161, loss = 804256.41051222
Validation score: 0.863192
Iteration 162, loss = 805990.13255798
Validation score: 0.858393
Iteration 163, loss = 801240.10788776
Validation score: 0.863941
Iteration 164, loss = 805097.39903983
Validation score: 0.860348
Iteration 165, loss = 802531.87940837
Validation score: 0.862431
Iteration 166, loss = 796450.84025856
Validation score: 0.863927
Iteration 167, loss = 793991.48912194
Validation score: 0.866870
Iteration 168, loss = 795048.26460848
Validation score: 0.865015
Iteration 169, loss = 796666.31059115
Validation score: 0.865894
Iteration 170, loss = 790016.60055369
Validation score: 0.861117
Iteration 171, loss = 792727.13576690
Validation score: 0.867541
Iteration 172, loss = 785424.66514100
Validation score: 0.866967
Iteration 173, loss = 784675.61742061
Validation score: 0.867268
Iteration 174, loss = 778599.68190570
Validation score: 0.867288
Iteration 175, loss = 779938.71454875
Validation score: 0.869312
Iteration 176, loss = 775411.11812810
Validation score: 0.869330
Iteration 177, loss = 774647.22698886
Validation score: 0.869115
Iteration 178, loss = 769709.39026578
Validation score: 0.868741
Iteration 179, loss = 770928.82270044
Validation score: 0.869584
Iteration 180, loss = 769108.62594651
Validation score: 0.870819
Iteration 181, loss = 767704.60402969
Validation score: 0.870980
Iteration 182, loss = 764279.49178304
Validation score: 0.870997
Iteration 183, loss = 759407.21429622
Validation score: 0.871277
Iteration 184, loss = 761719.82121375
Validation score: 0.870973
Iteration 185, loss = 761377.06373317
Validation score: 0.872056
Iteration 186, loss = 759430.17858023
Validation score: 0.867533
Iteration 187, loss = 760039.36737269
Validation score: 0.869775
Iteration 188, loss = 759558.73167227
Validation score: 0.872279
Iteration 189, loss = 754569.15750317
Validation score: 0.870565
Iteration 190, loss = 763754.31894466
Validation score: 0.871598
Iteration 191, loss = 754296.95469092
Validation score: 0.870820
Iteration 192, loss = 752061.05394361
Validation score: 0.868091
Iteration 193, loss = 747520.21483847
Validation score: 0.872198
Iteration 194, loss = 749474.37208882
Validation score: 0.870900
Iteration 195, loss = 766764.83776648
Validation score: 0.871080
Iteration 196, loss = 744534.98983505
Validation score: 0.870786
Iteration 197, loss = 745790.97039081
Validation score: 0.871794
Iteration 198, loss = 739872.90459917
Validation score: 0.872907
Iteration 199, loss = 740728.63481389
Validation score: 0.870339
Iteration 200, loss = 742101.31745647
Validation score: 0.871525
Iteration 201, loss = 738591.85231046
Validation score: 0.871278
Iteration 202, loss = 736751.52792578
Validation score: 0.871426
Iteration 203, loss = 739816.12399900
Validation score: 0.871176
Iteration 204, loss = 735128.78892616
Validation score: 0.868473
Iteration 205, loss = 734339.64743367
Validation score: 0.870855
Iteration 206, loss = 730303.75054446
Validation score: 0.872423
Iteration 207, loss = 730473.65865920
Validation score: 0.872488
Iteration 208, loss = 730115.65412008
Validation score: 0.870571
Iteration 209, loss = 727104.22447784
Validation score: 0.869368
Iteration 210, loss = 726536.41077629
Validation score: 0.870823
Iteration 211, loss = 730812.42069334
Validation score: 0.870309
Iteration 212, loss = 740913.57590075
Validation score: 0.870948
Iteration 213, loss = 720560.86472158
Validation score: 0.871884
Iteration 214, loss = 721658.99305518
Validation score: 0.866517
Iteration 215, loss = 730274.59175284
Validation score: 0.867852
Iteration 216, loss = 723845.91741987
Validation score: 0.872286
Iteration 217, loss = 725360.45745316
Validation score: 0.873087
Iteration 218, loss = 728326.40790171
Validation score: 0.871222
Iteration 219, loss = 716572.28733314
Validation score: 0.867896
Iteration 220, loss = 721964.87600122
Validation score: 0.871209
Iteration 221, loss = 714586.07298135
Validation score: 0.871466
Iteration 222, loss = 715535.87446564
Validation score: 0.868689
Iteration 223, loss = 714118.37996619
Validation score: 0.870321
Iteration 224, loss = 714220.12164688
Validation score: 0.869858
Iteration 225, loss = 712760.16272148
Validation score: 0.872581
Iteration 226, loss = 712048.83034220
Validation score: 0.871338
Iteration 227, loss = 711971.65831187
Validation score: 0.869810
Iteration 228, loss = 707732.02620217
Validation score: 0.871494
Iteration 229, loss = 707036.75613823
Validation score: 0.868666
Iteration 230, loss = 708875.82107873
Validation score: 0.870474
Iteration 231, loss = 707187.59290071
Validation score: 0.870613
Iteration 232, loss = 707880.47318851
Validation score: 0.869479
Iteration 233, loss = 704528.78003343
Validation score: 0.871732
Iteration 234, loss = 702310.83160191
Validation score: 0.871753
Iteration 235, loss = 705484.15626424
Validation score: 0.871457
Iteration 236, loss = 700536.36483097
Validation score: 0.870059
Iteration 237, loss = 699370.52302361
Validation score: 0.869582
Iteration 238, loss = 702134.44908207
Validation score: 0.872661
Iteration 239, loss = 698908.36373974
Validation score: 0.870864
Iteration 240, loss = 695262.55027034
Validation score: 0.871656
Iteration 241, loss = 699013.07489218
Validation score: 0.870246
Iteration 242, loss = 696708.47179680
Validation score: 0.872931
Iteration 243, loss = 696439.62684053
Validation score: 0.869291
Iteration 244, loss = 694631.95741363
Validation score: 0.871676
Iteration 245, loss = 693925.63751304
Validation score: 0.870839
Iteration 246, loss = 694905.63590138
Validation score: 0.871999
Iteration 247, loss = 694255.54272973
Validation score: 0.869035
Iteration 248, loss = 696838.00174766
Validation score: 0.871277
Validation score did not improve more than tol=0.000100 for 30 consecutive epochs. Stopping.
  ✓ opel done.
Iteration 1, loss = 97061401.91249341
Validation score: -3.664306
Iteration 2, loss = 96954823.30297382
Validation score: -3.654969
Iteration 3, loss = 96609390.49545933
Validation score: -3.626800
Iteration 4, loss = 95655140.77794327
Validation score: -3.553708
Iteration 5, loss = 93337727.98447196
Validation score: -3.389559
Iteration 6, loss = 88516446.07571189
Validation score: -3.068916
Iteration 7, loss = 79755296.98161741
Validation score: -2.524008
Iteration 8, loss = 65734807.94981998
Validation score: -1.731637
Iteration 9, loss = 46940639.56392781
Validation score: -0.767700
Iteration 10, loss = 26561261.21433806
Validation score: 0.105098
Iteration 11, loss = 11799766.88173585
Validation score: 0.577001
Iteration 12, loss = 6097645.02118013
Validation score: 0.694134
Iteration 13, loss = 4735047.85194021
Validation score: 0.751509
Iteration 14, loss = 3946653.34981599
Validation score: 0.783133
Iteration 15, loss = 3581606.58503941
Validation score: 0.793561
Iteration 16, loss = 3406688.63330704
Validation score: 0.797152
Iteration 17, loss = 3290549.63354514
Validation score: 0.800658
Iteration 18, loss = 3200058.80072569
Validation score: 0.801646
Iteration 19, loss = 3124091.53543814
Validation score: 0.802514
Iteration 20, loss = 3061206.74044825
Validation score: 0.802907
Iteration 21, loss = 3001156.39618569
Validation score: 0.803711
Iteration 22, loss = 2942079.14379786
Validation score: 0.807089
Iteration 23, loss = 2894280.77469798
Validation score: 0.807949
Iteration 24, loss = 2843379.36577798
Validation score: 0.807073
Iteration 25, loss = 2809102.36467376
Validation score: 0.813579
Iteration 26, loss = 2757238.32781338
Validation score: 0.814948
Iteration 27, loss = 2723795.02959894
Validation score: 0.816244
Iteration 28, loss = 2692402.95237759
Validation score: 0.814071
Iteration 29, loss = 2651871.58644443
Validation score: 0.815206
Iteration 30, loss = 2630815.98192735
Validation score: 0.819160
Iteration 31, loss = 2595828.86654959
Validation score: 0.818325
Iteration 32, loss = 2573342.21628251
Validation score: 0.820551
Iteration 33, loss = 2547096.81675414
Validation score: 0.821594
Iteration 34, loss = 2526593.43601789
Validation score: 0.822224
Iteration 35, loss = 2504394.18126095
Validation score: 0.823551
Iteration 36, loss = 2486477.91168294
Validation score: 0.822967
Iteration 37, loss = 2466592.84217598
Validation score: 0.825227
Iteration 38, loss = 2449668.78642667
Validation score: 0.825763
Iteration 39, loss = 2430812.51840508
Validation score: 0.826019
Iteration 40, loss = 2416550.79252474
Validation score: 0.826972
Iteration 41, loss = 2400371.67466992
Validation score: 0.828302
Iteration 42, loss = 2387785.53190340
Validation score: 0.829819
Iteration 43, loss = 2374783.06565897
Validation score: 0.829277
Iteration 44, loss = 2366526.19647236
Validation score: 0.833766
Iteration 45, loss = 2347178.09962807
Validation score: 0.834401
Iteration 46, loss = 2333990.19434170
Validation score: 0.834894
Iteration 47, loss = 2324900.16848672
Validation score: 0.834880
Iteration 48, loss = 2312025.77357677
Validation score: 0.836787
Iteration 49, loss = 2301426.43155351
Validation score: 0.837808
Iteration 50, loss = 2290687.12523400
Validation score: 0.837500
Iteration 51, loss = 2283625.24930551
Validation score: 0.840877
Iteration 52, loss = 2273617.23044466
Validation score: 0.840062
Iteration 53, loss = 2264429.16123792
Validation score: 0.842951
Iteration 54, loss = 2255798.03196777
Validation score: 0.842935
Iteration 55, loss = 2244410.49265669
Validation score: 0.842884
Iteration 56, loss = 2241449.12106532
Validation score: 0.844309
Iteration 57, loss = 2228973.55200813
Validation score: 0.844434

      Brand     N         RMSE          MAE        R²
1      opel  1906  1265.193099   884.901378  0.873878
2      ford  3282  1463.474109  1025.101353  0.904325
5   hyundai   683  1468.102410   997.308031  0.940713
3    toyota   941  1550.406242   972.589193  0.938559
7     skoda   875  1704.502860  1213.497803  0.923290
0        vw  2125  2234.134239  1452.120753  0.919964
6      audi  1489  2920.003752  1962.489014  0.928753
4  mercedes  2381  3319.253478  2221.531215  0.895013
8       bmw  1513  3362.738278  2268.145322  0.913358

### Results

Performance on the full dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3383.27 | 2156.67 | 0.8723 |
| Tree | 2784.00 | 1663.58 | 0.9135 |
| KNR|2623.89 |1599.60 |0.9232 |
|RF | 2032.89 |1258.34 |0.9539 |
|NN | 2319.24 |1466.96 |0.9400 |



Performance on the reduced dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3501.39 | 2241.68 | 0.8632 |
| Tree       | 2759.39 | 1650.79 | 0.9150 |
| KNR               | 2624.75 | 1598.18 | 0.9231 |
| RF                | **2036.38** | **1254.22** | **0.9537** |
| NN                | 2337.17.41 | 1476.69 | 0.9391 |

In [ ]:
raise SystemExit("Stop before training the models")

SystemExit: Stop before training the models

C:\Users\liber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

## Feature Selection - Wrapper Method

In [ ]:
num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()

print(num_cols)

['mileage', 'tax', 'mpg', 'engineSize', 'previousOwners', 'stated_no_damage', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']

In [ ]:
def rfe(X_train, X_val, y_train, y_val, num_cols, step=1, n_estimators=100, random_state=69):
    
    valid_num_cols = [col for col in num_cols if col in X_train.columns]
    if len(valid_num_cols) == 0:
        raise ValueError("No valid numeric columns found in X_train.")
    print(f"Using {len(valid_num_cols)} numeric columns for RFE:\n{valid_num_cols}")
    
    X_train_num = X_train[valid_num_cols]
    X_val_num = X_val[valid_num_cols]
    nof_list = np.arange(1, X_train_num.shape[1]+1)
    
    best_mae = float('inf')
    nof = 0
    train_mae_list = []
    val_mae_list = []
    features_to_select = None
    
    for n in nof_list:
        model = RandomForestRegressor(n_estimators=n_estimators, random_state=random_state, n_jobs=-1)
        rfe = RFE(estimator=model, n_features_to_select=n, step=step)
        X_train_rfe = rfe.fit_transform(X_train_num, y_train)
        X_val_rfe = rfe.transform(X_val_num)
        
        model.fit(X_train_rfe, y_train)
        
        train_pred = model.predict(X_train_rfe)
        val_pred = model.predict(X_val_rfe)
        train_mae = mean_absolute_error(y_train, train_pred)
        val_mae = mean_absolute_error(y_val, val_pred)
        
        train_mae_list.append(train_mae)
        val_mae_list.append(val_mae)
        
        if val_mae < best_mae:
            best_mae = val_mae
            nof = n
            features_to_select = pd.Series(rfe.support_, index=X_train_num.columns)
    
    selected_features = features_to_select[features_to_select].index.tolist()
    
    print(f"\nOptimum number of features: {nof}")
    print(f"Best validation MAE: {best_mae:.4f}")
    print("Selected features:")
    print(selected_features)
    
    return nof, best_mae, selected_features, train_mae_list, val_mae_list

In [ ]:
nof, best_score, selected_rfe_features, train_scores, val_scores = rfe(
    X_train, X_val, y_train, y_val, num_cols
)

Using 11 numeric columns for RFE:
['mileage', 'tax', 'mpg', 'engineSize', 'previousOwners', 'stated_no_damage', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']

Optimum number of features: 9
Best validation MAE: 1323.6319
Selected features:
['mileage', 'tax', 'mpg', 'engineSize', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']

In [ ]:
X_train_rfed = X_train[["mileage", "tax", "mpg", "engineSize", "age", "efficiency_ratio", "mileage_per_year", "age_mileage",
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_train_rfed

,mileage,tax,mpg,engineSize,age,efficiency_ratio,mileage_per_year,age_mileage,Brand,transmission,model_mean_price,fuelType
0,16326,125,51.4,1.4,3,34.266667,4081.500000,0.48978,opel,manual,10496.007929,petrol
1,12510,145,56.5,1.0,2,51.363636,4170.000000,0.25020,toyota,manual,8029.315503,petrol
2,6999,144,58.2,1.0,1,52.909091,3499.500000,0.06999,ford,manual,13441.487966,petrol
3,28465,160,43.5,2.0,3,20.714286,7116.250000,0.85395,mercedes,manual,30801.319510,petrol
4,9221,145,33.6,2.0,1,16.000000,4610.500000,0.09221,vw,semi-auto,34233.178082,electric
...,...,...,...,...,...,...,...,...,...,...,...,...
60773,21131,145,67.3,2.1,1,30.590909,10565.500000,0.21131,mercedes,semi-auto,20327.302521,diesel
60774,4722,145,50.4,1.6,1,29.647059,2361.000000,0.04722,vw,manual,22619.961912,diesel
60775,24755,0,76.3,1.6,5,44.882353,4125.833333,1.23775,audi,manual,14343.507937,diesel
60776,42000,125,57.6,2.0,5,27.428571,7000.000000,2.10000,bmw,manual,15717.953402,diesel
60777,27553,30,62.8,1.6,3,36.941176,6888.250000,0.82659,toyota,manual,12768.027027,diesel

In [ ]:
X_val_rfed = X_val[["mileage", "tax", "mpg", "engineSize", "age", "efficiency_ratio", "mileage_per_year", "age_mileage",
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_val_rfed

,mileage,tax,mpg,engineSize,age,efficiency_ratio,mileage_per_year,age_mileage,Brand,transmission,model_mean_price,fuelType
0,5000,145,48.7,2.0,1,23.190476,2500.000000,0.05000,vw,automatic,17101.053465,diesel
1,10,145,43.5,1.4,1,29.000000,5.000000,0.00010,opel,manual,8348.382147,petrol
2,46000,125,51.4,1.0,4,46.727273,9200.000000,1.84000,ford,semi-auto,13441.487966,petrol
3,24219,20,60.1,1.2,3,46.230769,6054.750000,0.72657,vw,manual,11435.947368,petrol
4,20251,145,46.3,1.8,4,24.368421,4050.200000,0.81004,toyota,automatic,10373.418919,petrol
...,...,...,...,...,...,...,...,...,...,...,...,...
15190,33154,30,54.3,1.2,6,41.769231,4736.285714,1.98924,ford,manual,10245.037681,petrol
15191,19000,20,60.1,1.0,4,54.636364,3800.000000,0.76000,vw,manual,11435.947368,petrol
15192,3971,145,45.6,1.5,1,28.500000,1985.500000,0.03971,vw,manual,16722.731829,petrol
15193,56603,0,83.1,1.4,4,55.400000,11320.600000,2.26412,vw,manual,11435.947368,diesel
15194,24545,145,43.5,1.4,3,29.000000,6136.250000,0.73635,opel,semi-auto,12511.510798,petrol

In [ ]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train_rfed, y_train)


rf_trainer.evaluate_train(X_train_rfed, y_train)
rf_trainer.evaluate(X_val_rfed, y_val)

rf_trainer.evaluate_train_by_brand(X_train_rfed, y_train)
rf_trainer.evaluate_by_brand(X_val_rfed, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 791.34
  MAE:  473.66
  R²:   0.9932

Validation Set Performance (Overall):
  RMSE: 2033.05
  MAE:  1256.58
  R²:   0.9539

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7644  463.914285 309.235998 0.982848
    ford 13108  535.870395 345.862177 0.987429
  toyota  3775  561.716833 338.077681 0.992100
 hyundai  2724  577.270768 367.348817 0.990626
   skoda  3507  602.826087 409.353137 0.990329
      vw  8479  708.249640 454.007482 0.991500
    audi  5971 1037.789691 645.645367 0.992224
     bmw  6029 1039.159002 641.595021 0.991591
mercedes  9541 1125.371000 692.305729 0.988845

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1151.895521  786.584062 0.895455
    ford 3282 1354.041743  935.275800 0.918098
 hyundai  683 1438.914752  944.670402 0.943047
   skoda  875 1554.184116 1073.572999 0.936224
  toyota  941 1560.618769  952.116895 0.937747
      vw 2125 1904.666983 1228.593323 0.941829
    audi 1489 2602.379454 1662.530539 0.943410
     bmw 1513 2680.604426 1713.106259 0.944944
mercedes 2381 2881.876592 1833.798991 0.920858

      Brand     N         RMSE          MAE        R²
1      opel  1906  1151.895521   786.584062  0.895455
2      ford  3282  1354.041743   935.275800  0.918098
5   hyundai   683  1438.914752   944.670402  0.943047
7     skoda   875  1554.184116  1073.572999  0.936224
3    toyota   941  1560.618769   952.116895  0.937747
0        vw  2125  1904.666983  1228.593323  0.941829
6      audi  1489  2602.379454  1662.530539  0.943410
8       bmw  1513  2680.604426  1713.106259  0.944944
4  mercedes  2381  2881.876592  1833.798991  0.920858

Final Results

Performance on the full dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3383.27 | 2156.67 | 0.8723 |
| Tree | 2784.00 | 1663.58 | 0.9135 |
| KNR|2623.89 |1599.60 |0.9232 |
|RF | 2032.89 |1258.34 |0.9539 |
|NN | 2319.24 |1466.96 |0.9400 |



Performance on the reduced dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3501.39 | 2241.68 | 0.8632 |
| Tree       | 2759.39 | 1650.79 | 0.9150 |
| KNR               | 2624.75 | 1598.18 | 0.9231 |
| RF                | **2036.38** | **1254.22** | **0.9537** |
| NN                | 2337.17.41 | 1476.69 | 0.9391 |


Random Forest on the rfed dataset

|*Model*| *RMSE*| *MAE* | *R²*|
|----|----|----|----|
|RF| 2033.05| 1256.58 | 0.9539|

## Hyperparam tuning

In [ ]:
class HoldoutRandomSearch:
    def __init__(self, trainer_class, param_space, n_iter=20, optimize_metric='mae'):
        self.trainer_class = trainer_class
        self.param_space = param_space
        self.n_iter = n_iter
        self.optimize_metric = optimize_metric.lower()
        self.results = []
        self.best_params = None
        self.best_score = None
        self.best_trainer = None
        self.brand_best_configs = {}
        
    def sample_params(self):
        if isinstance(self.param_space, list):
            return random.choice(self.param_space)
        else:
            return {k: random.choice(v) for k, v in self.param_space.items()}
    
    def _get_param_summary(self, params):
        summary = {}
        
        if 'n_estimators' in params:
            summary['n_estimators'] = params['n_estimators']
        if 'max_depth' in params:
            summary['max_depth'] = params['max_depth']
        if 'max_features' in params:
            summary['max_features'] = params['max_features']
            
        if 'hidden_layer_sizes' in params:
            summary['hidden_layers'] = str(params['hidden_layer_sizes'])
        if 'alpha' in params:
            summary['alpha'] = params['alpha']
        if 'learning_rate_init' in params:
            summary['lr'] = params['learning_rate_init']
        if 'activation' in params:
            summary['activation'] = params['activation']
            
        return summary
    
    def run(self, X_train, y_train, X_val, y_val):
        metric_name = self.optimize_metric.upper()
        print(f"Running random search ({self.n_iter} iterations)...")
        print(f"Optimizing for: {metric_name}\n")
        
        start_time = time.time()
        brands = X_train["Brand"].unique()

        for brand in brands:
            self.brand_best_configs[brand] = {
                'score': float('inf'),
                'params': None,
                'config_num': None,
                'all_metrics': {}
            }
        
        for i in range(self.n_iter):
            iter_start = time.time()
            params = self.sample_params()
            
            print(f"\n{'='*70}")
            print(f"[{i+1}/{self.n_iter}] Testing params:")
            print(params)
            print('='*70)
            

            estimator = self.trainer_class.estimator.__class__(**params)
            trainer = BrandModelTrainer(estimator)
            trainer.fit(X_train, y_train)

            metrics = trainer.evaluate(X_val, y_val)
            rmse = metrics["RMSE"]
            mae = metrics["MAE"]
            r2 = metrics["R²"]
            
            current_score = mae if self.optimize_metric == 'mae' else rmse
            
            brand_results = {}
            for brand in brands:
                mask = X_val["Brand"] == brand
                y_true_brand = y_val[mask]
                y_pred_brand = trainer.predict(X_val[mask])
                
                brand_rmse = np.sqrt(mean_squared_error(y_true_brand, y_pred_brand))
                brand_mae = mean_absolute_error(y_true_brand, y_pred_brand)
                brand_r2 = r2_score(y_true_brand, y_pred_brand)
                
                brand_score = brand_mae if self.optimize_metric == 'mae' else brand_rmse
                
                brand_results[brand] = {
                    'score': brand_score,
                    'rmse': brand_rmse,
                    'mae': brand_mae,
                    'r2': brand_r2
                }
                
                if brand_score < self.brand_best_configs[brand]['score']:
                    self.brand_best_configs[brand]['score'] = brand_score
                    self.brand_best_configs[brand]['params'] = params.copy()
                    self.brand_best_configs[brand]['config_num'] = i + 1
                    self.brand_best_configs[brand]['all_metrics'] = {
                        'rmse': brand_rmse,
                        'mae': brand_mae,
                        'r2': brand_r2
                    }
            
            self.results.append({
                "config_num": i + 1,
                "params": params,
                "rmse": rmse,
                "mae": mae,
                "r2": r2,
                "score": current_score,
                "brand_results": brand_results
            })

            if self.best_score is None or current_score < self.best_score:
                self.best_score = current_score
                self.best_params = params
                self.best_trainer = trainer
                print(f"New best overall model ({metric_name}: {current_score:.2f})")
           

            elapsed_total = time.time() - start_time
            avg_per_iter = elapsed_total / (i + 1)
            eta = avg_per_iter * (self.n_iter - (i + 1))
            
            print(f"\nProgress: {i+1}/{self.n_iter} | Elapsed: {elapsed_total:.1f}s | ETA: ~{eta:.1f}s")
        
        print(f"SEARCH COMPLETED - FINAL RESULTS (Optimized for {metric_name})")
        
        print(f"\n Best general model:")
        print(f"  Best {metric_name}: {self.best_score:.2f}")
        
        best_result = [r for r in self.results if r['score'] == self.best_score][0]
        print(f"  RMSE: {best_result['rmse']:.2f}")
        print(f"  MAE:  {best_result['mae']:.2f}")
        print(f"  R²:   {best_result['r2']:.4f}")
        print(f"  Params: {self.best_params}")
   
        print(f"Best configuration per brand (by {metric_name})")

        
        brand_summary = []
        for brand in sorted(brands):
            config = self.brand_best_configs[brand]
            
            summary = {
                'Brand': brand,
                f'Best_{metric_name}': config['score'],
                'RMSE': config['all_metrics']['rmse'],
                'MAE': config['all_metrics']['mae'],
                'R²': config['all_metrics']['r2'],
                'Config_Num': config['config_num']
            }
            
            param_summary = self._get_param_summary(config['params'])
            summary.update(param_summary)
            
            brand_summary.append(summary)
            
            print(f"\n{brand.upper()}:")
            print(f"  Best {metric_name}: {config['score']:.2f}")
            print(f"  RMSE: {config['all_metrics']['rmse']:.2f}")
            print(f"  MAE:  {config['all_metrics']['mae']:.2f}")
            print(f"  R²:   {config['all_metrics']['r2']:.4f}")
            print(f"  Found at iteration: {config['config_num']}")
            print(f"  Best params:")
            for k, v in list(config['params'].items())[:5]:
                if k not in ['random_state', 'n_jobs', 'shuffle', 'verbose', 'warm_start']:
                    print(f"    {k}: {v}")
        
        df_summary = pd.DataFrame(brand_summary).sort_values(f'Best_{metric_name}')
  
        print(df_summary.to_string(index=False))
        
        results_df = pd.DataFrame([
            {
                'Config': r['config_num'],
                metric_name: r['score'],
                'RMSE': r['rmse'],
                'MAE': r['mae'],
                'R²': r['r2']
            }
            for r in self.results
        ]).sort_values(metric_name)
        
        print(f"ALL CONFIGURATIONS (sorted by {metric_name}):")
        print(results_df.head(10).to_string(index=False))
        
        return self.best_trainer, self.best_params, self.best_score

### Random Forest

In [ ]:
base_estimator = RandomForestRegressor(random_state=69, n_jobs=-1)
trainer = BrandModelTrainer(base_estimator)

param_space_rf = {
    "n_estimators": [400, 800, 1200],
    "max_depth": [None, 15, 25, 35],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [0.3, 0.5, 0.7, 1.0],
    "min_impurity_decrease": [0.0, 1e-4, 1e-3, 1e-2],
    "max_samples": [0.5, 0.7, 0.9, None],
    "criterion": ["squared_error", "friedman_mse"],
    "bootstrap": [True],
    "random_state": [69],
    "n_jobs": [-1]
}

search = HoldoutRandomSearch(
    trainer_class=trainer,
    param_space=param_space_rf,
    n_iter=60
)


best_trainer, best_params, best_rmse = search.run(X_train_filter, y_train, X_val_filter, y_val)

Running random search (60 iterations)...
Optimizing for: MAE


======================================================================
[1/60] Testing params:
{'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.0001, 'max_samples': 0.9, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2010.32
  MAE:  1245.43
  R²:   0.9549
New best overall model (MAE: 1245.43)

Progress: 1/60 | Elapsed: 84.7s | ETA: ~4996.7s

======================================================================
[2/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 1.0, 'min_impurity_decrease': 0.001, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2089.98
  MAE:  1266.69
  R²:   0.9513

Progress: 2/60 | Elapsed: 190.5s | ETA: ~5525.7s

======================================================================
[3/60] Testing params:
{'n_estimators': 400, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.7, 'min_impurity_decrease': 0.01, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2060.10
  MAE:  1257.78
  R²:   0.9526

Progress: 3/60 | Elapsed: 232.2s | ETA: ~4412.4s

======================================================================
[4/60] Testing params:
{'n_estimators': 400, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.7, 'min_impurity_decrease': 0.0, 'max_samples': 0.9, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2062.24
  MAE:  1257.46
  R²:   0.9525

Progress: 4/60 | Elapsed: 269.9s | ETA: ~3778.5s

======================================================================
[5/60] Testing params:
{'n_estimators': 1200, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2037.26
  MAE:  1253.80
  R²:   0.9537

Progress: 5/60 | Elapsed: 369.2s | ETA: ~4061.1s

======================================================================
[6/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'min_impurity_decrease': 0.0001, 'max_samples': None, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1956.11
  MAE:  1219.53
  R²:   0.9573
New best overall model (MAE: 1219.53)

Progress: 6/60 | Elapsed: 438.6s | ETA: ~3947.5s

======================================================================
[7/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.0, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2196.31
  MAE:  1307.09
  R²:   0.9462

Progress: 7/60 | Elapsed: 516.7s | ETA: ~3911.8s

======================================================================
[8/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 1.0, 'min_impurity_decrease': 0.0001, 'max_samples': 0.5, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2047.28
  MAE:  1253.09
  R²:   0.9532

Progress: 8/60 | Elapsed: 633.0s | ETA: ~4114.8s

======================================================================
[9/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.0001, 'max_samples': 0.5, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2196.32
  MAE:  1307.09
  R²:   0.9462

Progress: 9/60 | Elapsed: 719.8s | ETA: ~4079.0s

======================================================================
[10/60] Testing params:
{'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.001, 'max_samples': 0.7, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2173.93
  MAE:  1293.43
  R²:   0.9473

Progress: 10/60 | Elapsed: 813.7s | ETA: ~4068.4s

======================================================================
[11/60] Testing params:
{'n_estimators': 1200, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.7, 'min_impurity_decrease': 0.0001, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2149.22
  MAE:  1294.60
  R²:   0.9485

Progress: 11/60 | Elapsed: 891.1s | ETA: ~3969.5s

======================================================================
[12/60] Testing params:
{'n_estimators': 800, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2030.13
  MAE:  1247.29
  R²:   0.9540

Progress: 12/60 | Elapsed: 953.2s | ETA: ~3813.0s

======================================================================
[13/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2006.46
  MAE:  1248.43
  R²:   0.9551

Progress: 13/60 | Elapsed: 985.4s | ETA: ~3562.7s

======================================================================
[14/60] Testing params:
{'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2081.26
  MAE:  1282.49
  R²:   0.9517

Progress: 14/60 | Elapsed: 1042.1s | ETA: ~3424.0s

======================================================================
[15/60] Testing params:
{'n_estimators': 800, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'min_impurity_decrease': 0.0, 'max_samples': 0.9, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1973.44
  MAE:  1220.90
  R²:   0.9565

Progress: 15/60 | Elapsed: 1111.7s | ETA: ~3335.1s

======================================================================
[16/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2032.75
  MAE:  1259.43
  R²:   0.9539

Progress: 16/60 | Elapsed: 1174.7s | ETA: ~3230.6s

======================================================================
[17/60] Testing params:
{'n_estimators': 800, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 1.0, 'min_impurity_decrease': 0.0, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2146.70
  MAE:  1285.88
  R²:   0.9486

Progress: 17/60 | Elapsed: 1234.3s | ETA: ~3122.0s

======================================================================
[18/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.7, 'min_impurity_decrease': 0.0, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2005.18
  MAE:  1233.73
  R²:   0.9551

Progress: 18/60 | Elapsed: 1270.3s | ETA: ~2964.1s

======================================================================
[19/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2125.79
  MAE:  1278.16
  R²:   0.9496

Progress: 19/60 | Elapsed: 1378.6s | ETA: ~2974.9s

======================================================================
[20/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.7, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2072.73
  MAE:  1267.26
  R²:   0.9521

Progress: 20/60 | Elapsed: 1412.4s | ETA: ~2824.8s

======================================================================
[21/60] Testing params:
{'n_estimators': 800, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.0001, 'max_samples': 0.7, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2080.71
  MAE:  1287.46
  R²:   0.9517

Progress: 21/60 | Elapsed: 1465.6s | ETA: ~2721.8s

======================================================================
[22/60] Testing params:
{'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1974.65
  MAE:  1232.44
  R²:   0.9565

Progress: 22/60 | Elapsed: 1615.0s | ETA: ~2789.5s

======================================================================
[23/60] Testing params:
{'n_estimators': 1200, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.7, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2079.17
  MAE:  1269.84
  R²:   0.9518

Progress: 23/60 | Elapsed: 1709.6s | ETA: ~2750.2s

======================================================================
[24/60] Testing params:
{'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.7, 'min_impurity_decrease': 0.01, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1978.78
  MAE:  1225.37
  R²:   0.9563

Progress: 24/60 | Elapsed: 1806.2s | ETA: ~2709.3s

======================================================================
[25/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.7, 'min_impurity_decrease': 0.001, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1990.74
  MAE:  1229.02
  R²:   0.9558

Progress: 25/60 | Elapsed: 1881.7s | ETA: ~2634.4s

======================================================================
[26/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 1.0, 'min_impurity_decrease': 0.0001, 'max_samples': None, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2052.95
  MAE:  1252.95
  R²:   0.9530

Progress: 26/60 | Elapsed: 1963.3s | ETA: ~2567.4s

======================================================================
[27/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2042.87
  MAE:  1251.67
  R²:   0.9534

Progress: 27/60 | Elapsed: 2027.7s | ETA: ~2478.3s

======================================================================
[28/60] Testing params:
{'n_estimators': 1200, 'max_depth': 35, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.5, 'min_impurity_decrease': 0.0001, 'max_samples': 0.7, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}

In [ ]:
best_trainer.evaluate_by_brand(X_val_filter, y_val)

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1086.769229  748.110206 0.906943
    ford 3282 1277.274084  901.254733 0.927122
 hyundai  683 1368.252148  890.840175 0.948504
  toyota  941 1378.231055  858.386788 0.951447
   skoda  875 1494.197535 1037.671806 0.941052
      vw 2125 1875.588743 1188.962644 0.943592
     bmw 1513 2457.630204 1624.097258 0.953722
    audi 1489 2543.390249 1621.939526 0.945946
mercedes 2381 2793.058290 1790.165923 0.925661

      Brand     N         RMSE          MAE        R²
1      opel  1906  1086.769229   748.110206  0.906943
2      ford  3282  1277.274084   901.254733  0.927122
5   hyundai   683  1368.252148   890.840175  0.948504
3    toyota   941  1378.231055   858.386788  0.951447
7     skoda   875  1494.197535  1037.671806  0.941052
0        vw  2125  1875.588743  1188.962644  0.943592
8       bmw  1513  2457.630204  1624.097258  0.953722
6      audi  1489  2543.390249  1621.939526  0.945946
4  mercedes  2381  2793.058290  1790.165923  0.925661

In [ ]:
raise SystemExit("Stop before training the models")

## Predictions

In [44]:
best_params_per_brand = {
    'opel': {
        'n_estimators': 1200,
        'max_depth': 15,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': 0.7,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'toyota': {
        'n_estimators': 800,
        'max_depth': 25,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.3,
        'min_impurity_decrease': 0.01,
        'max_samples': None,
        'criterion': 'friedman_mse',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'ford': {
        'n_estimators': 1200,
        'max_depth': 15,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': 0.7,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'hyundai': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'skoda': {
        'n_estimators': 1200,
        'max_depth': 15,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': 0.7,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'vw': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'bmw': {
        'n_estimators': 400,
        'max_depth': 35,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'audi': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'mercedes': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    }
}

In [49]:
X_full_train = pd.concat([X_train_filter, X_val_filter], axis=0)
y_full_train = pd.concat([y_train, y_val], axis=0)

numeric_cols = ['mileage', 'tax', 'mpg', 'engineSize', 'age', 
                 'efficiency_ratio', 
                'model_mean_price']

categorical_cols = ['Brand', 'transmission', 'fuelType']

In [50]:
models = {}
scalers = {}
brand_encoders = {}


brands = X_full_train['Brand'].unique()

for brand in brands:
    brand_lower = brand.lower()
    print(f"\n Training model for {brand.upper()}")
    
    mask_train = X_full_train['Brand'] == brand
    X_brand_train = X_full_train[mask_train].copy()
    y_brand_train = y_full_train[mask_train].copy()
    
    X_numeric = X_brand_train[numeric_cols].copy()
    
    scaler = RobustScaler()
    X_numeric_scaled = scaler.fit_transform(X_numeric)
    X_numeric_scaled = pd.DataFrame(
        X_numeric_scaled, 
        columns=numeric_cols,
        index=X_brand_train.index
    )

    scalers[brand] = scaler

    X_brand_encoded = X_numeric_scaled.copy()
    
    for col in ['transmission', 'fuelType']:
        dummies = pd.get_dummies(X_brand_train[col], prefix=col, drop_first=True)
        X_brand_encoded = pd.concat([X_brand_encoded, dummies], axis=1)
    

    brand_encoders[brand] = {
        'columns': X_brand_encoded.columns.tolist(),
        'numeric_cols': numeric_cols
    }
    
    if brand_lower in best_params_per_brand:
        params = best_params_per_brand[brand_lower]
    else:
        params = {
            'n_estimators': 1200,
            'max_depth': None,
            'min_samples_split': 5,
            'min_samples_leaf': 1,
            'max_features': 0.5,
            'random_state': 69,
            'n_jobs': -1
        }
    
    model = RandomForestRegressor(**params)
    model.fit(X_brand_encoded, y_brand_train)
  
    models[brand] = model
    
    print(f" {brand.upper()} model trained")

 Training model for OPEL
 OPEL model trained

 Training model for AUDI
 AUDI model trained

 Training model for MERCEDES
 MERCEDES model trained

 Training model for FORD
 FORD model trained

 Training model for BMW
 BMW model trained

 Training model for TOYOTA
 TOYOTA model trained

 Training model for HYUNDAI
 HYUNDAI model trained

 Training model for VW
 VW model trained

 Training model for SKODA
 SKODA model trained

In [54]:
test_processed.head()

,year,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,Brand,transmission,model,fuelType
carID,,,,,,,,,,,
89856,2015,30700,205,41.5,1.6,3,1.0,hyundai,automatic,i30,petrol
106581,2017,48191,150,38.2,2.0,2,1.0,vw,semi-auto,tiguan,petrol
80886,2016,36792,125,51.4,1.5,2,1.0,bmw,automatic,2 series,petrol
100174,2019,5533,145,44.1,1.2,1,1.0,opel,manual,grandland x,petrol
81376,2019,9058,150,51.4,2.0,4,1.0,bmw,semi-auto,1 series,diesel

In [55]:
X_test = minimal_features(test_processed)
X_test

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,Brand,transmission,model,fuelType,age,mileage_per_year,efficiency_ratio,age_mileage
carID,,,,,,,,,,,,,,
89856,30700,205,41.5,1.6,3,1.0,hyundai,automatic,i30,petrol,5,5116.666667,24.411765,1.53500
106581,48191,150,38.2,2.0,2,1.0,vw,semi-auto,tiguan,petrol,3,12047.750000,18.190476,1.44573
80886,36792,125,51.4,1.5,2,1.0,bmw,automatic,2 series,petrol,4,7358.400000,32.125000,1.47168
100174,5533,145,44.1,1.2,1,1.0,opel,manual,grandland x,petrol,1,2766.500000,33.923077,0.05533
81376,9058,150,51.4,2.0,4,1.0,bmw,semi-auto,1 series,diesel,1,4529.000000,24.476190,0.09058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105775,27575,145,46.3,1.4,1,1.0,vw,manual,tiguan,petrol,3,6893.750000,30.866667,0.82725
81363,1980,145,34.0,2.0,3,1.0,bmw,automatic,x2,petrol,0,1980.000000,16.190476,0.00000
76833,8297,145,38.2,2.0,4,1.0,audi,semi-auto,q5,diesel,1,4148.500000,18.190476,0.08297
91768,50755,145,28.5,1.3,1,1.0,mercedes,manual,a class,petrol,1,25377.500000,20.357143,0.50755
99627,11071,30,58.0,1.3,4,1.0,toyota,automatic,yaris,petrol,3,2767.750000,41.428571,0.33213

In [58]:
X_test['model_mean_price'] = X_test['model'].map(model_mean_price)

In [61]:
X_train_filter.head()

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model_mean_price,fuelType
0,11899,124,51.4,1.4,2,1.0,4,34.266667,opel,manual,10488.218094,petrol
1,18500,145,48.7,1.4,4,1.0,2,32.466667,audi,semi-auto,22860.502532,petrol
2,10658,145,46.3,1.5,2,1.0,1,28.937500,mercedes,semi-auto,23609.185947,petrol
3,1500,145,43.5,0.0,4,1.0,0,435.000000,audi,manual,22522.319540,petrol
4,18495,98,64.1,2.1,4,1.0,3,29.136364,mercedes,automatic,23609.185947,diesel

In [62]:
X_test = X_test.drop(columns=["model", "mileage_per_year", "age_mileage"])
X_test.head()

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,Brand,transmission,fuelType,age,efficiency_ratio,model_mean_price
carID,,,,,,,,,,,,
89856,30700,205,41.5,1.6,3,1.0,hyundai,automatic,petrol,5,24.411765,11848.081505
106581,48191,150,38.2,2.0,2,1.0,vw,semi-auto,petrol,3,18.190476,21509.106996
80886,36792,125,51.4,1.5,2,1.0,bmw,automatic,petrol,4,32.125000,19665.944282
100174,5533,145,44.1,1.2,1,1.0,opel,manual,petrol,1,33.923077,17217.228906
81376,9058,150,51.4,2.0,4,1.0,bmw,semi-auto,diesel,1,24.476190,15836.032550

In [63]:
predictions = np.zeros(len(X_test))

for brand in X_test['Brand'].unique():
    print(f"\n Predicting for {brand.upper()}...")

    mask_test = X_test['Brand'] == brand
    X_brand_test = X_test[mask_test].copy()
    
    X_numeric_test = X_brand_test[numeric_cols].copy()
    
    scaler = scalers[brand]
    X_numeric_test_scaled = scaler.transform(X_numeric_test)
    X_numeric_test_scaled = pd.DataFrame(
        X_numeric_test_scaled,
        columns=numeric_cols,
        index=X_brand_test.index
    )
    
    X_brand_test_encoded = X_numeric_test_scaled.copy()
    
    for col in ['transmission', 'fuelType']:
        dummies = pd.get_dummies(X_brand_test[col], prefix=col, drop_first=True)
        X_brand_test_encoded = pd.concat([X_brand_test_encoded, dummies], axis=1)

    expected_cols = brand_encoders[brand]['columns']

    for col in expected_cols:
        if col not in X_brand_test_encoded.columns:
            X_brand_test_encoded[col] = 0
    
    X_brand_test_encoded = X_brand_test_encoded[expected_cols]
    
    model = models[brand]
    brand_predictions = model.predict(X_brand_test_encoded)

    predictions[mask_test] = brand_predictions

 Predicting for HYUNDAI...

 Predicting for VW...

 Predicting for BMW...

 Predicting for OPEL...

 Predicting for FORD...

 Predicting for MERCEDES...

 Predicting for SKODA...

 Predicting for TOYOTA...

 Predicting for AUDI...

In [64]:
if X_test.index.name == 'carID' or 'carID' in X_test.index.names:
    car_ids = X_test.index
else:
    car_ids = X_test.index

submission = pd.DataFrame({
    'carID': car_ids,
    'price': predictions
})

submission = submission.sort_values('carID')


submission['price'] = submission['price'].round(2)

output_filename = 'submission.csv'
submission.to_csv(output_filename, index=False)