# Project

In [48]:
import pandas as pd
from thefuzz import process
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# For imputation
from sklearn.experimental import enable_iterative_imputer  # noqa
from sklearn.impute import IterativeImputer

from scipy import stats
from sklearn.feature_selection import VarianceThreshold, RFE
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

import numpy as np
from sklearn.base import BaseEstimator, clone
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from typing import Dict

from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.neighbors import KNeighborsRegressor

from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor

import random
from copy import deepcopy
import time

In [49]:
train_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/train.csv")

In [50]:
train_df.set_index("carID")

,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,,
69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,NaN,11.417268,2.0,63.0,4.000000,0.0
53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,145.0,47.900000,1.5,50.0,1.000000,0.0
6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,145.0,40.900000,1.5,56.0,4.000000,0.0
29021,Ford,FIESTA,2018.0,12500,anual,9102.0,Petrol,145.0,65.700000,1.0,50.0,-2.340306,0.0
10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,145.0,42.800000,1.5,97.0,3.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37194,Mercedes,C Class,2015.0,13498,Manual,14480.0,etrol,125.0,53.300000,2.0,78.0,0.000000,0.0
6265,Audi,Q3,2013.0,12495,Semi-Auto,52134.0,Diesel,200.0,47.900000,2.0,38.0,2.000000,0.0
54886,Toyota,Aygo,2017.0,8399,Automatic,11304.0,Petrol,145.0,67.000000,1.0,57.0,3.000000,0.0
860,Audi,Q3,2015.0,12990,Manual,69072.0,iesel,125.0,60.100000,2.0,74.0,2.000000,0.0
15795,Ford,Fiesta,2018.0,10495,Manual,16709.0,Petro,145.0,64.200000,1.1,38.0,1.000000,0.0

## Data cleaning

In [51]:
# TODO: Move the functions to a separate file

In [52]:
# String cleaning and Small numbers changes

def simple_processing(df):
    """
    Apply string cleaning, brand/model corrections, and fuzzy matching.
    These operations don"t require fitting on training data.
    """

    df = df.copy()
    # ============================================================================
    # SECTION 1: REFERENCE DATA SETUP
    # ============================================================================
    
    # Reference list of correct model names
    models = ["golf", "veloste", "caddy", "yaris", "q2", "fiesta", "2 series", "3 series", "a3", "octavia", 
              "passat", "focus", "insignia", "a class", "q3", "fabia", "ka+", "glc class", "i30", "c class", 
              "polo", "e class", "q5", "up", "c-hr", "mokka x", "corsa", "astra", "tt", "5 series", "aygo", 
              "4 series", "slk", "viva", "t-roc", "ecosport", "tucson", "x-class", "cl class", "ix20", "i20", 
              "rapid", "a1", "auris", "sharan", "adam", "x3", "a8", "gls class", "b-max", "a4", "kona", "i10", 
              "mokka", "s-max", "x2", "crossland x", "tiguan", "a5", "gle class", "zafira", "ioniq", "a6", 
              "mondeo", "yeti outdoor", "x1", "scala", "s class", "1 series", "kamiq", "kuga", "tourneo connect", 
              "q7", "gla class", "arteon", "sl class", "santa fe", "grandland x", "i800", "rav4", "touran", 
              "citigo", "roomster", "prius", "corolla", "b class", "kodiaq", "v class", "caddy maxi life", 
              "superb", "getz", "combo life", "beetle", "galaxy", "m3", "gtc", "x4", "ka", "ix35", 
              "grand tourneo connect", "m4", "tourneo custom", "z4", "x5", "meriva", "rs6", "verso", "touareg", 
              "shuttle", "cls class", "c-max", "puma", "cla class", "i40", "tiguan allspace", "6 series", 
              "caravelle", "karoq", "i3", "grand c-max", "t-cross", "a7", "golf sv", "agila", "gt86", "yeti", 
              "california", "land cruiser", "edge", "x6", "caddy life", "8 series", "fusion", "gl class", 
              "scirocco", "z3", "proace verso", "hilux", "amarok", "cc", "7 series", "avensis", "eos", "m class", 
              "grandland", "zafira tourer", "rs5", "r8", "mustang", "antara", "q8", "camry", "clk", "rs3", 
              "jetta", "kadjar", "sq5", "rs4", "supra", "i8", "x7", "sq7", "g class", "s3", "crossland", 
              "tigra", "escort", "glb class", "vivaro", "verso-s", "m5", "s4", "iq", "a2", "caddy maxi", 
              "streetka", "cascada", "accent", "s8", "rs", "golf s", "ranger", "vectra", "ampera", "fox", 
              "urban cruiser", "m2", "clc class", "m6", "s5", "terracan", "200", "220", "230", "NaN"]
    
    # Get unique short model names (2 characters) for separate handling
    short_models = [models[i] for i in range(len(models)) if len(models[i]) == 2]
    short_models = list(set(short_models))
    
    transmission_types = ["semi-auto", "manual", "automatic", "unkown", "NaN", "other"]
    fuel_types = ["petrol", "diesel", "hybrid", "electric", "other", "NaN"]
    
    # Brand name corrections mapping
    brand_mapping = {
        "vw": "vw",
        "v": "vw",
        "w": "vw",
        
        "toyota": "toyota",
        "toyot": "toyota",
        "oyota": "toyota",
        
        "audi": "audi",
        "aud": "audi",
        "udi": "audi",
        "ud": "audi",
        
        "ford": "ford",
        "for": "ford",
        "ord": "ford",
        "or": "ford",
        
        "bmw": "bmw",
        "bm": "bmw",
        "mw": "bmw",
        
        "skoda": "skoda",
        "skod": "skoda",
        "koda": "skoda",
        "kod": "skoda",
        
        "opel": "opel",
        "ope": "opel",
        "pel": "opel",
        "pe": "opel",
        
        "mercedes": "mercedes",
        "mercede": "mercedes",
        "ercedes": "mercedes",
        "ercede": "mercedes",
        
        "hyundai": "hyundai",
        "hyunda": "hyundai",
        "yundai": "hyundai",
        "yunda": "hyundai"
    }
    
    # ============================================================================
    # SECTION 2: INITIAL CLEANING (NO FITTING REQUIRED) -> no risk of data leakage
    # ============================================================================
        
    # Convert brand names to lowercase and removes all beginning and trailing whitespace (e.g. space) from the column
    df["Brand"] = df["Brand"].str.lower().str.strip()
    df["model"] = df["model"].str.lower().str.strip()
    df["transmission"] = df["transmission"].str.lower().str.strip()
    df["fuelType"] = df["fuelType"].str.lower().str.strip()
    
    # Replace NaN with string NaN to avoid errors in the fuzzy algorithm (cant match NaNs)
    df[["model", "transmission", "fuelType"]] = df[["model", "transmission", "fuelType"]].fillna("NaN")
    
    # 1.1 Fixing brands
    df["Brand"] = df["Brand"].map(brand_mapping)
    
    # 1.2 Fixing models
    # Similarity matching for Models, Transmission and fuel columns (Fuzzy Match)
    # Source for process.extractOne (fuzzy): https://github.com/seatgeek/thefuzz
    
    # VECTORIZED APPROACH: Only perform fuzzy matching once per unique value instead of per row
    
    # Models - handle different lengths separately
    unique_models = df["model"].unique()
    model_lookup = {}
    for val in unique_models:
        if pd.isna(val) or val == "NaN":
            model_lookup[val] = "NaN"
        elif len(val) > 2:  # Only perform fuzzy matching for models that have a name longer than 2 letters -> fuzzy will become fuzzy (unreliable) if names are to short
            model_lookup[val] = process.extractOne(val, models)[0]  # [0] because we get the name and score as a return -> score used for debugging
        elif len(val) == 2:  # Use the short names list for comparisons if the model names are 2 letters
            model_lookup[val] = process.extractOne(val, short_models)[0]
        else:  # We can define models with only one letter
            model_lookup[val] = "NaN"
    df["model"] = df["model"].map(model_lookup)
    
    # Transmission
    unique_trans = df["transmission"].unique()
    trans_lookup = {val: process.extractOne(val, transmission_types)[0] for val in unique_trans}
    df["transmission"] = df["transmission"].map(trans_lookup)
    
    # FuelType
    unique_fuel = df["fuelType"].unique()
    fuel_lookup = {val: process.extractOne(val, fuel_types)[0] for val in unique_fuel}
    df["fuelType"] = df["fuelType"].map(fuel_lookup)
    
    # Convert the str NaN values back to pd.NA for easier further processing and readability
    df["model"] = df["model"].replace("NaN", pd.NA)
    df["transmission"] = df["transmission"].replace(["unkown", "NaN", "other"], pd.NA)
    df["fuelType"] = df["fuelType"].replace(["other", "NaN"], pd.NA)
    
    #df["Brand"] = df["Brand"].fillna(df["Brand_mode"])  # rename new column
    #df.drop("Brand_mode", axis=1, inplace=True)  # remove the old brand column
    
    ################################################################################
    # Simple Number Cleaning
    ################################################################################

    # Cleaning numeric columns
    df["year"] = df["year"].round(0)
    
    # Create the new column
    df["stated_no_damage"] = ~df["hasDamage"].astype(bool)
    df = df.drop(["hasDamage"], axis=1)

    # Round year to integer (no fractional years)
    df["year"] = df["year"].round()
    
    # Mileage: take absolute value and round
    # Some imputation might produce small negative values
    df["mileage"] = abs(df["mileage"].round())
    
    # Tax: take absolute value and round
    df["tax"] = abs(df["tax"].round())
    
    # MPG: round to 1 decimal place 
    df["mpg"] = abs(df["mpg"].round(1))
    
    # Engine size: round to 1 decimal place
    df["engineSize"] = abs(df["engineSize"].round(1))
    
    # Paint quality correction (domain-specific business logic)
    # Assumption based on data exploration:
    # - Values < 4 likely had decimal point in wrong place (e.g., 3.5 -> 35%)
    # - Values > 100 likely have erroneous leading 1 (e.g., 185 -> 85%)
    def fix_paint_quality(x):
        if x < 4:
            return x * 10
        elif x > 100:
            return x - 100
        else:
            return x
    
    df["paintQuality%"] = df["paintQuality%"].apply(fix_paint_quality).round()
    
    # Previous owners: take absolute value and round to integer
    df["previousOwners"] = abs(df["previousOwners"].round())
    
    return df

In [53]:
def mode_imputation(df):
    """
    Get the most frequent brand for each model -> returns df with model and brand
    """
    brand_models = df.groupby("model_transformed")["Brand_transformed"].agg(lambda x: x.mode()[0] if len(x.mode()) > 0 else pd.NA)
    df = pd.merge(df, brand_models, on="model_transformed", how="left", suffixes=("", "_mode"))  # add the model and brand df to our main df (onyl add the brand columns, join on model)
    
    df["Brand_transformed"] = df["Brand_transformed"].fillna(df["Brand_transformed_mode"])  # rename new column
    df.drop("Brand_transformed_mode", axis=1, inplace=True)  # remove the old brand column
    

    return df

In [54]:
# Categorical featue Encoding
def fit_transform_encoding(df):
    """
    Fit label encoders for categorical columns on training data.
    """
    
    encoders = {
        "Brand": LabelEncoder(),
        "model": LabelEncoder(),
        "transmission": LabelEncoder(),
        "fuelType": LabelEncoder()
    }
    
    # Fit each encoder on the corresponding column
    """encoders["brand"].fit(df["Brand"])
    encoders["model"].fit(df["model"])
    encoders["transmission"].fit(df["transmission"])
    encoders["fuelType"].fit(df["fuelType"])"""

    columns = ["Brand", "model", "transmission", "fuelType"]

    # Code adapted from: https://stackoverflow.com/questions/36808434/label-encoder-encoding-missing-values

    for column in columns:
        # Get non-null string values
        mask = df[column].notna() & (df[column].apply(type) == str)
        
        # Fit encoder on unique non-null values
        fit_by = df.loc[mask, column].unique()
        encoders[column].fit(fit_by)
        
        # Transform only non-null values (vectorized)
        new_col_name = column + "_transformed"
        df[new_col_name] = pd.NA  # Initialize with NA
        df.loc[mask, new_col_name] = encoders[column].transform(df.loc[mask, column])
        
        # Convert to nullable integer
        df[new_col_name] = df[new_col_name].astype("Int64")

    df = df.drop(columns, axis=1)
    return df, encoders

In [55]:
# Train imputer on train

def fit_imputer(df, fast=True): 
    # Select estimator based on speed/accuracy tradeoff
    if fast:
        # Use default BayesianRidge (fast, ~1 second)
        estimator = None
    else:
        # Use Random Forest for better accuracy with complex relationships (~2 minutes)
        estimator = RandomForestRegressor(
            n_estimators=20,      # Limited trees for speed
            max_depth=10,         # Prevent overfitting
            random_state=12       # Reproducibility
        )

    # TODO: for later
    # Test if we perform better if we use numerical and categorical imputers separately
    
    # Initialize imputer
    imputer = IterativeImputer(
        estimator=estimator,
        max_iter=10,                    # Number of imputation rounds
        random_state=12,                # For reproducibility
        initial_strategy="mean"         # Initial fill before iterative process
    )
    
    # TODO: Test other categorical imputers like: missForest, datawig
    """imputer = IterativeImputer(
        estimator=RandomForestClassifier(),
        max_iter=10,                    # Number of imputation rounds
        random_state=12,                # For reproducibility
        initial_strategy="most_frequent"         # Initial fill before iterative process
        )"""

    # FIT on training data
    # CRITICAL: We fit on data that still has missing values!
    # The imputer learns patterns of missingness and relationships

    imputer.fit(df)
    
    return imputer

In [56]:
def apply_imputer(df, imputer):
    """
        Apply the pretrained imputer to the dataframe
    """

    imputed_values = imputer.transform(df)

    df[df.columns] = imputed_values

    # TODO: rounding is not the best approach as the imputers prediction are continues thus 1.2 doesnt mean the value is closer to 1 than 2
    # However, rounding is the quickest way to fix this for now
    df[["mpg", "engineSize"]] = abs(df[["mpg", "engineSize"]]).round(1)
    try: 
        df[["year", "price", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]] = abs(df[["year", "price", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]]).round(0).astype(int)
    except KeyError: # will raise keyError if we run it on testing data as it has no price column
        df[["year", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]] = abs(df[["year", "tax", "mileage", "paintQuality%", "previousOwners", "Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"]]).round(0).astype(int)
    
    return df

In [57]:
def decode(df, encoders):
    # Iterative imputer produces ~20-30 values that are outside of the range of the encoder
    # The simplest fix is to clip does values back into the range of the encoder
 

    df["Brand_transformed"] = df["Brand_transformed"].clip(lower=0, upper=encoders["Brand"].classes_.shape[0]-1).astype(int)
    df["Brand"] = encoders["Brand"].inverse_transform(df["Brand_transformed"])

    df["transmission_transformed"] = df["transmission_transformed"].clip(lower=0, upper=encoders["transmission"].classes_.shape[0]-1).astype(int)
    df["transmission"] = encoders["transmission"].inverse_transform(df["transmission_transformed"])
        
    # Use clip with the information of the fitted encoder, .classes_.shape gives us the dimension of the labels the encoder uses [0] is the rows - 1 because we start clipping at 0
    df["model_transformed"] = df["model_transformed"].clip(lower=0, upper=encoders["model"].classes_.shape[0]-1).astype(int)
    df["model"] = encoders["model"].inverse_transform(df["model_transformed"])
    
    df["fuelType_transformed"] = df["fuelType_transformed"].clip(lower=0, upper=encoders["fuelType"].classes_.shape[0]-1).astype(int)
    df["fuelType"] = encoders["fuelType"].inverse_transform(df["fuelType_transformed"])
    

    df.drop(columns=["Brand_transformed", "model_transformed", "transmission_transformed", "fuelType_transformed"], inplace=True)

    return df

### Workflow for Train and Validation Sets

#### Encoding

In [58]:
# Fix typos and small numeric cleanup
df = simple_processing(train_df)
# Encode cateogrical columns and replace the str with int columns. Return fitted encoders for decoding at the end

df_encoded, encoders = fit_transform_encoding(df)

#### Creating the stratification column

In [59]:
# Create Categorical price column with 0 < 1 < 2 for the price
df_encoded["price_cat"] = pd.qcut(df_encoded["price"], 3, labels=False)

# Combine the 10 unique brand values (1-9 & NA) with the 3 unique price category values (0-2)
stratify_col = df_encoded["Brand_transformed"].astype(str) + "_" + df_encoded["price_cat"].astype(str)

#### Imputation and decoding

In [60]:
# Train validation split
train_split, validation_split = train_test_split(df_encoded, test_size=0.2, random_state=42, stratify=stratify_col)
# train_split, validation_split = train_test_split(df_encoded, test_size=0.2, random_state=42)

train_split = mode_imputation(train_split)
validation_split = mode_imputation(validation_split)

# Train imputer on train (data leakage risk thus only train on train_split)
imputer = fit_imputer(train_split)

# Apply trained imputer to both datasplits
imputed_train = apply_imputer(train_split, imputer)
imputer_test = apply_imputer(validation_split, imputer)

# Decode encoded columns using the fitted encoders
train_processed = decode(imputed_train, encoders)
validation_processed = decode(imputer_test, encoders)

### Workflow for Seperated Testing Dataset

In [61]:
test_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/test.csv")

In [62]:
test_df.set_index("carID")

,Brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,
89856,Hyundai,I30,2022.878006,Automatic,30700.000000,petrol,205.0,41.5,1.6,61.0,3.0,0.0
106581,VW,Tiguan,2017.000000,Semi-Auto,-48190.655673,Petrol,150.0,38.2,2.0,60.0,2.0,0.0
80886,BMW,2 Series,2016.000000,Automatic,36792.000000,Petrol,125.0,51.4,1.5,94.0,2.0,0.0
100174,Opel,Grandland X,2019.000000,Manual,5533.000000,Petrol,145.0,44.1,1.2,77.0,1.0,0.0
81376,BMW,1 Series,2019.000000,Semi-Auto,9058.000000,Diesel,150.0,51.4,2.0,45.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
105775,VW,Tiguan,2017.000000,Manual,27575.000000,Petrol,145.0,46.3,1.4,94.0,1.0,0.0
81363,BMW,X2,2020.000000,Automatic,1980.000000,Petrol,145.0,34.0,2.0,39.0,3.0,0.0
76833,Audi,Q5,2019.000000,Semi-Auto,8297.000000,Diesel,145.0,38.2,2.0,88.0,4.0,0.0
91768,Mercedes,A Class,2019.000000,Manual,-50755.210230,Petrol,145.0,28.5,1.3,81.0,1.0,0.0
99627,Toyota,Yaris,2017.000000,Automatic,11071.000000,Petrol,30.0,58.0,1.3,98.0,4.0,0.0

In [63]:
test = simple_processing(test_df)
test_df_encoded, test_encoders = fit_transform_encoding(test)


df_encoded_no_price = df_encoded.drop(["price", "price_cat"], axis=1)
test_imputers = fit_imputer(df_encoded_no_price) # we use the full encoded training dataframe to train the imputers

# Apply trained imputer to both datasplits
test_df_imputed = apply_imputer(test_df_encoded, test_imputers)

test_processed = decode(test_df_imputed, test_encoders)

In [125]:
train_val_models = set(pd.concat([train_processed, validation_processed])["model"].unique())
test_models = set(test_processed["model"].unique())

missing_models = train_val_models - test_models

In [126]:
list(missing_models)

['streetka',
 '200',
 'urban cruiser',
 'getz',
 '230',
 '220',
 'a2',
 'kadjar',
 'escort',
 'caddy maxi',
 'accent',
 'ranger',
 'verso-s']

## Feature Engineering

In [64]:
train_processed = train_processed.set_index("carID")
validation_processed = validation_processed.set_index("carID")
train_processed.index = train_processed.index.astype(int)
validation_processed.index = validation_processed.index.astype(int)

In [65]:
X_train = train_processed.drop(columns=['price'])
y_train = train_processed['price']
X_val = validation_processed.drop(columns=['price'])
y_val = validation_processed['price']

In [66]:
def minimal_features(df):
    df = df.copy()
    df['age'] = 2024 - df['year']
    df = df.drop(columns=["year"])
    df['mileage_per_year'] = df['mileage'] / (df['age'] + 1)
    df['efficiency_ratio'] = df['mpg'] / (df['engineSize'] + 0.1)
    df['age_mileage'] = df['age'] * df['mileage'] / 100000
    df['condition_score'] = (df['paintQuality%']/100) * 0.5 + df['stated_no_damage'].astype(int) * 0.5

    return df

In [67]:
X_train = minimal_features(X_train)
X_val = minimal_features(X_val)

In [68]:
X_train = X_train.drop(columns=["price_cat"])
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60778 entries, 44735 to 59767
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           60778 non-null  int32
 1   tax               60778 non-null  int32
 2   mpg               60778 non-null  float64
 3   engineSize        60778 non-null  float64
 4   paintQuality%     60778 non-null  int32
 5   previousOwners    60778 non-null  int32
 6   stated_no_damage  60778 non-null  float64
 7   Brand             60778 non-null  object
 8   transmission      60778 non-null  object
 9   model             60778 non-null  object
 10  fuelType          60778 non-null  object
 11  age               60778 non-null  int32
 12  mileage_per_year  60778 non-null  float64
 13  efficiency_ratio  60778 non-null  float64
 14  age_mileage       60778 non-null  float64
 15  condition_score   60778 non-null  float64
dtypes: float64(7), int32(5), object(4)
memory usage: 6.5+ MB

In [69]:
X_val = X_val.drop(columns=["price_cat"])
X_val.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15195 entries, 10742 to 43030
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           15195 non-null  int32
 1   tax               15195 non-null  int32
 2   mpg               15195 non-null  float64
 3   engineSize        15195 non-null  float64
 4   paintQuality%     15195 non-null  int32
 5   previousOwners    15195 non-null  int32
 6   stated_no_damage  15195 non-null  float64
 7   Brand             15195 non-null  object
 8   transmission      15195 non-null  object
 9   model             15195 non-null  object
 10  fuelType          15195 non-null  object
 11  age               15195 non-null  int32
 12  mileage_per_year  15195 non-null  float64
 13  efficiency_ratio  15195 non-null  float64
 14  age_mileage       15195 non-null  float64
 15  condition_score   15195 non-null  float64
dtypes: float64(7), int32(5), object(4)
memory usage: 1.6+ MB

In [70]:
y_train

carID
44735    33569
44774    27699
36653    24400
22889     6391
62059    11386
         ...
71271     9798
7862     16750
33501     7900
68727    29100
59767     9999
Name: price, Length: 60778, dtype: int32

In [71]:
y_val

carID
10742    23975
33830    12991
2417      3990
4544     27990
73794    14578
         ...
8206     11850
71796    27490
72896     3999
23839    17495
43030    29062
Name: price, Length: 15195, dtype: int32

## Test of the models on the full dataset

In [72]:
class BrandModelTrainer:
    def __init__(self, estimator):
        self.estimator = estimator
        self.brand_models = {}
        self.feature_cols = None

    def fit(self, X_train, y_train):
        self.feature_cols = [c for c in X_train.columns if c != "Brand"]
        print(f"Training models for {len(X_train['Brand'].unique())} brands...\n")

        for brand in X_train["Brand"].unique():
            mask = X_train["Brand"] == brand
            Xb = X_train.loc[mask, self.feature_cols]
            yb = y_train[mask]

            numeric_cols = Xb.select_dtypes(include=["int64", "int32" ,"float64"]).columns.tolist()
            categorical_cols = Xb.select_dtypes(include=["object", "category"]).columns.tolist()

            preprocessor = ColumnTransformer([
                ("num", RobustScaler(), numeric_cols),
                ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
            ])

            model = Pipeline([
                ("preprocess", preprocessor),
                ("estimator", clone(self.estimator))
            ])

            model.fit(Xb, yb)
            self.brand_models[brand] = model
            print(f"  ✓ {brand} done.")

        return self

    def predict(self, X):
        preds = np.zeros(len(X))
        for brand, model in self.brand_models.items():
            mask = X["Brand"] == brand
            if mask.sum() == 0:
                continue
            Xb = X.loc[mask, self.feature_cols]
            preds[mask] = model.predict(Xb)
        return preds

    def evaluate_train(self, X_train, y_train):
        y_pred = self.predict(X_train)
        rmse = np.sqrt(mean_squared_error(y_train, y_pred))
        mae = mean_absolute_error(y_train, y_pred)
        r2 = r2_score(y_train, y_pred)
        print("\nTraining Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    def evaluate(self, X_val, y_val):
        y_pred = self.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, y_pred))
        mae = mean_absolute_error(y_val, y_pred)
        r2 = r2_score(y_val, y_pred)
        print("\nValidation Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    def evaluate_by_brand(self, X, y, split_name="Validation"):
        y_pred = self.predict(X)
        results = []
        for brand in X["Brand"].unique():
            mask = X["Brand"] == brand
            y_true_b = y[mask]
            y_pred_b = y_pred[mask]
            rmse = np.sqrt(mean_squared_error(y_true_b, y_pred_b))
            mae = mean_absolute_error(y_true_b, y_pred_b)
            r2 = r2_score(y_true_b, y_pred_b)
            results.append({"Brand": brand, "N": len(y_true_b), "RMSE": rmse, "MAE": mae, "R²": r2})
        df = pd.DataFrame(results).sort_values("RMSE")
        print(f"\n{split_name} Performance per Brand:")
        print(df.to_string(index=False))
        return df

    def evaluate_train_by_brand(self, X_train, y_train):
        return self.evaluate_by_brand(X_train, y_train, split_name="Training")
    
    def save_predictions(self, X, path):
        preds = self.predict(X)
        df = pd.DataFrame({
            "CarID": X["CarID"].values,
            "price": preds
        })
        df.to_csv(path, index=False)
        print(f"File salvato in: {path}")
        return df

In [73]:
raise SystemExit("Stop before training the models")

SystemExit: Stop before training the models

C:\Users\liber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

### Linear Regression

In [74]:
LR = LinearRegression()
trainer = BrandModelTrainer(LR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 3380.85
  MAE:  2014.80
  R²:   0.8789

Validation Set Performance (Overall):
  RMSE: 3488.30
  MAE:  2061.42
  R²:   0.8737

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7633 1553.487221 1075.327688 0.809318
  toyota  3770 1907.315967 1178.019716 0.905757
    ford 13120 2030.106966 1412.417309 0.821233
   skoda  3504 2071.581305 1475.058073 0.884629
 hyundai  2728 2125.775692 1494.385483 0.872634
      vw  8488 2851.656086 1992.541466 0.862518
    audi  5979 4164.132833 2710.427594 0.872121
     bmw  6032 4263.054881 2737.450213 0.864427
mercedes  9524 5601.268326 3401.902605 0.746194

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1556.566420 1100.204792 0.811613
    ford 3272 2007.789638 1408.503335 0.818991
 hyundai  676 2109.611642 1498.986787 0.874111
  toyota  948 2326.030448 1257.583011 0.888588
      vw 2118 2988.753071 2085.102039 0.856886
   skoda  882 3058.561033 1542.063744 0.796293
     bmw 1514 4064.865621 2714.628644 0.860412
    audi 1489 4238.717697 2701.409287 0.870185
mercedes 2384 5792.752645 3564.143687 0.745079

      Brand     N         RMSE          MAE        R²
7      opel  1912  1556.566420  1100.204792  0.811613
4      ford  3272  2007.789638  1408.503335  0.818991
1   hyundai   676  2109.611642  1498.986787  0.874111
6    toyota   948  2326.030448  1257.583011  0.888588
3        vw  2118  2988.753071  2085.102039  0.856886
8     skoda   882  3058.561033  1542.063744  0.796293
0       bmw  1514  4064.865621  2714.628644  0.860412
2      audi  1489  4238.717697  2701.409287  0.870185
5  mercedes  2384  5792.752645  3564.143687  0.745079

### ElasticNet

In [75]:
Elastic = ElasticNet()
trainer = BrandModelTrainer(Elastic)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)        # Performance VALID

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 4877.07
  MAE:  3004.49
  R²:   0.7481

Validation Set Performance (Overall):
  RMSE: 4956.03
  MAE:  3039.99
  R²:   0.7450

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7633 2276.768085 1705.542112 0.590426
    ford 13120 2773.118187 1993.085741 0.666430
 hyundai  2728 3400.891063 2460.719099 0.674010
   skoda  3504 3416.761384 2451.956322 0.686149
  toyota  3770 3564.493160 2388.972686 0.670846
      vw  8488 4444.784957 3052.834859 0.665996
    audi  5979 6342.491208 3783.407764 0.703333
mercedes  9524 6744.941632 4307.569557 0.631969
     bmw  6032 7544.506573 4902.116314 0.575388

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 2236.901130 1694.842772 0.610948
    ford 3272 2667.850122 1969.886276 0.680414
 hyundai  676 3355.629894 2387.951904 0.681484
   skoda  882 4209.466075 2651.006135 0.614143
  toyota  948 4372.783516 2564.539942 0.606253
      vw 2118 4591.360191 3184.666880 0.662258
    audi 1489 6287.644806 3761.883497 0.714352
     bmw 1514 6980.504921 4669.488881 0.588349
mercedes 2384 7145.177273 4491.147713 0.612152

      Brand     N         RMSE          MAE        R²
7      opel  1912  2236.901130  1694.842772  0.610948
4      ford  3272  2667.850122  1969.886276  0.680414
1   hyundai   676  3355.629894  2387.951904  0.681484
8     skoda   882  4209.466075  2651.006135  0.614143
6    toyota   948  4372.783516  2564.539942  0.606253
3        vw  2118  4591.360191  3184.666880  0.662258
2      audi  1489  6287.644806  3761.883497  0.714352
0       bmw  1514  6980.504921  4669.488881  0.588349
5  mercedes  2384  7145.177273  4491.147713  0.612152

### KNR

In [77]:
KNR = KNeighborsRegressor()
trainer = BrandModelTrainer(KNR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 2320.16
  MAE:  1345.63
  R²:   0.9430

Validation Set Performance (Overall):
  RMSE: 3004.83
  MAE:  1691.97
  R²:   0.9063

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7633 1118.723446  759.469593 0.901113
    ford 13120 1381.416863  908.169055 0.917225
  toyota  3770 1386.423964  860.994271 0.950204
   skoda  3504 1536.559687 1098.264326 0.936526
 hyundai  2728 1552.258830 1006.690762 0.932088
      vw  8488 1978.751757 1327.420570 0.933804
    audi  5979 2916.518209 1908.458404 0.937269
     bmw  6032 3430.589480 2042.193733 0.912205
mercedes  9524 3481.102444 2019.716758 0.901969

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1274.143190  883.549372 0.873773
    ford 3272 1692.398602 1120.063570 0.871391
 hyundai  676 1751.783234 1207.137574 0.913195
  toyota  948 2183.386741 1163.818354 0.901834
      vw 2118 2521.333122 1690.080925 0.898150
   skoda  882 3076.105669 1479.626531 0.793949
    audi 1489 3900.317141 2375.428610 0.890086
     bmw 1514 4080.868240 2518.895905 0.859311
mercedes 2384 4508.164805 2600.956711 0.845604

      Brand     N         RMSE          MAE        R²
7      opel  1912  1274.143190   883.549372  0.873773
4      ford  3272  1692.398602  1120.063570  0.871391
1   hyundai   676  1751.783234  1207.137574  0.913195
6    toyota   948  2183.386741  1163.818354  0.901834
3        vw  2118  2521.333122  1690.080925  0.898150
8     skoda   882  3076.105669  1479.626531  0.793949
2      audi  1489  3900.317141  2375.428610  0.890086
0       bmw  1514  4080.868240  2518.895905  0.859311
5  mercedes  2384  4508.164805  2600.956711  0.845604

### Random Forest

In [78]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train, y_train)


rf_trainer.evaluate_train(X_train, y_train)
rf_trainer.evaluate(X_val, y_val)

rf_trainer.evaluate_train_by_brand(X_train, y_train)
rf_trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 828.36
  MAE:  472.72
  R²:   0.9927

Validation Set Performance (Overall):
  RMSE: 2233.99
  MAE:  1286.08
  R²:   0.9482

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7633  446.549880 295.556575 0.984244
    ford 13120  524.178664 338.974203 0.988082
 hyundai  2728  555.835528 352.943321 0.991292
  toyota  3770  579.052927 347.716891 0.991314
   skoda  3504  588.728238 405.752300 0.990682
      vw  8488  739.931366 460.947176 0.990744
    audi  5979 1027.835403 646.914747 0.992209
mercedes  9524 1181.202633 686.011663 0.988713
     bmw  6032 1221.793276 666.110857 0.988864

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1141.155866  783.097798 0.898748
    ford 3272 1427.626564  919.831189 0.908485
  toyota  948 1551.581965  891.329684 0.950426
 hyundai  676 1575.881109 1008.623580 0.929753
      vw 2118 2014.058237 1282.536838 0.935010
   skoda  882 2739.298041 1129.830351 0.836600
     bmw 1514 2785.243281 1750.372695 0.934464
    audi 1489 2982.593525 1753.850161 0.935725
mercedes 2384 3073.058973 1901.756418 0.928257

      Brand     N         RMSE          MAE        R²
7      opel  1912  1141.155866   783.097798  0.898748
4      ford  3272  1427.626564   919.831189  0.908485
6    toyota   948  1551.581965   891.329684  0.950426
1   hyundai   676  1575.881109  1008.623580  0.929753
3        vw  2118  2014.058237  1282.536838  0.935010
8     skoda   882  2739.298041  1129.830351  0.836600
0       bmw  1514  2785.243281  1750.372695  0.934464
2      audi  1489  2982.593525  1753.850161  0.935725
5  mercedes  2384  3073.058973  1901.756418  0.928257

### Neural Network

In [79]:
from sklearn.neural_network import MLPRegressor

mlp_deep = MLPRegressor(
    hidden_layer_sizes=(256, 128, 64),  
    activation='relu',
    solver='adam',
    alpha=0.0001,  
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=2000,
    batch_size=256,
    random_state=42,
    early_stopping=True,
    n_iter_no_change=30,  
    validation_fraction=0.15,
    verbose=True
)

mlp_trainer = BrandModelTrainer(mlp_deep)


mlp_trainer.fit(X_train, y_train)


mlp_trainer.evaluate_train(X_train, y_train)
mlp_trainer.evaluate(X_val, y_val)


mlp_trainer.evaluate_train_by_brand(X_train, y_train)
mlp_trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

Iteration 1, loss = 364771944.06513423
Validation score: -5.895844
Iteration 2, loss = 359762314.87924159
Validation score: -5.636126
Iteration 3, loss = 325595247.23774594
Validation score: -4.341845
Iteration 4, loss = 216729778.86876193
Validation score: -1.521373
Iteration 5, loss = 78330282.92392096
Validation score: 0.261328
Iteration 6, loss = 32374601.21564107
Validation score: 0.545695
Iteration 7, loss = 24345913.69186404
Validation score: 0.630332
Iteration 8, loss = 21518155.24057179
Validation score: 0.668546
Iteration 9, loss = 19897585.37890808
Validation score: 0.691826
Iteration 10, loss = 18702125.67444406
Validation score: 0.704042
Iteration 11, loss = 17915964.00727439
Validation score: 0.710169
Iteration 12, loss = 17244805.12727088
Validation score: 0.721765
Iteration 13, loss = 16706856.43732269
Validation score: 0.727891
Iteration 14, loss = 16239235.19005160
Validation score: 0.734724
Iteration 15, loss = 15903477.01230653
Validation score: 0.737542
Iteration 16, loss = 15513898.33049703
Validation score: 0.745016
Iteration 17, loss = 15188962.19660851
Validation score: 0.749372
Iteration 18, loss = 14935317.94471378
Validation score: 0.754787
Iteration 19, loss = 14646721.68981934
Validation score: 0.756795
Iteration 20, loss = 14423977.63429103
Validation score: 0.768414
Iteration 21, loss = 14188739.40576598
Validation score: 0.769203
Iteration 22, loss = 13997698.32104946
Validation score: 0.772761
Iteration 23, loss = 13824325.39572462
Validation score: 0.778628
Iteration 24, loss = 13677940.69158315
Validation score: 0.781130
Iteration 25, loss = 13464105.33700930
Validation score: 0.787572
Iteration 26, loss = 13342038.51947815
Validation score: 0.787411
Iteration 27, loss = 13231316.66656803
Validation score: 0.792433
Iteration 28, loss = 13092604.93994768
Validation score: 0.791694
Iteration 29, loss = 12956745.92736087
Validation score: 0.798737
Iteration 30, loss = 12807518.29515442
Validation score: 0.803523
Iteration 31, loss = 12698879.81506475
Validation score: 0.803335
Iteration 32, loss = 12543641.50966088
Validation score: 0.808570
Iteration 33, loss = 12460036.46754902
Validation score: 0.811052
Iteration 34, loss = 12341877.46268792
Validation score: 0.814362
Iteration 35, loss = 12225442.26395170
Validation score: 0.815117
Iteration 36, loss = 12104690.91480733
Validation score: 0.816800
Iteration 37, loss = 12015510.59684771
Validation score: 0.818059
Iteration 38, loss = 11894916.37065255
Validation score: 0.820122
Iteration 39, loss = 11796156.84595662
Validation score: 0.821657
Iteration 40, loss = 11691705.19542034
Validation score: 0.823312
Iteration 41, loss = 11593133.81203779
Validation score: 0.826409
Iteration 42, loss = 11496874.80507129
Validation score: 0.827057
Iteration 43, loss = 11422824.03242728
Validation score: 0.832553
Iteration 44, loss = 11306153.39512496
Validation score: 0.831154
Iteration 45, loss = 11197522.88559322
Validation score: 0.829796
Iteration 46, loss = 11127313.00373104
Validation score: 0.830049
Iteration 47, loss = 11047034.15857295
Validation score: 0.836365
Iteration 48, loss = 10938872.69850219
Validation score: 0.834925
Iteration 49, loss = 10846946.23498235
Validation score: 0.838897
Iteration 50, loss = 10782868.89263600
Validation score: 0.837679
Iteration 51, loss = 10689414.37260727
Validation score: 0.840606
Iteration 52, loss = 10635623.72778253
Validation score: 0.839233
Iteration 53, loss = 10599177.01464061
Validation score: 0.840270
Iteration 54, loss = 10489143.68562604
Validation score: 0.843680
Iteration 55, loss = 10444548.11475046
Validation score: 0.846336
Iteration 56, loss = 10350313.27880475
Validation score: 0.843561
Iteration 57, loss = 10290011.29860266
Validation score: 0.843226
Iteration 58, loss = 10232172.26128358
Validation score: 0.845302
Iteration 59, loss = 10167908.91515982
Validation score: 0.848084
Iteration 60, loss = 10131893.12039497
Validation score: 0.847488
Iteration 61, loss = 10090860.49555597
Validation score: 0.848053
Iteration 62, loss = 10006169.43468171
Validation score: 0.848649
Iteration 63, loss = 9950212.67093368
Validation score: 0.850462
Iteration 64, loss = 9951560.89373102
Validation score: 0.851729
Iteration 65, loss = 9851131.22193460
Validation score: 0.846741
Iteration 66, loss = 9760541.26173106
Validation score: 0.850507
Iteration 67, loss = 9714131.49927922
Validation score: 0.852554
Iteration 68, loss = 9687768.80806265
Validation score: 0.851390
Iteration 69, loss = 9595340.67040555
Validation score: 0.850546
Iteration 70, loss = 9571372.47098543
Validation score: 0.853060
Iteration 71, loss = 9515770.92547017
Validation score: 0.850361
Iteration 72, loss = 9462579.50001293
Validation score: 0.855266
Iteration 73, loss = 9402108.01124577
Validation score: 0.852524
Iteration 74, loss = 9356592.83385549
Validation score: 0.855707
Iteration 75, loss = 9352286.45866329
Validation score: 0.852428
Iteration 76, loss = 9250065.43212936
Validation score: 0.852156
Iteration 77, loss = 9195232.49727343
Validation score: 0.856769
Iteration 78, loss = 9188892.99247676
Validation score: 0.854890
Iteration 79, loss = 9093393.77570418
Validation score: 0.854709
Iteration 80, loss = 9026041.74698597
Validation score: 0.852684
Iteration 81, loss = 9000850.25554181
Validation score: 0.855973
Iteration 82, loss = 8995336.19399430
Validation score: 0.852240
Iteration 83, loss = 8903894.02439941
Validation score: 0.857158
Iteration 84, loss = 8834315.26711974
Validation score: 0.856772
Iteration 85, loss = 8842747.22576334
Validation score: 0.859042
Iteration 86, loss = 8766438.52837030
Validation score: 0.859533
Iteration 87, loss = 8751412.20783854
Validation score: 0.859906
Iteration 88, loss = 8651877.01090111
Validation score: 0.859327
Iteration 89, loss = 8588579.18434141
Validation score: 0.861744
Iteration 90, loss = 8598254.02121885
Validation score: 0.859481
Iteration 91, loss = 8511777.99530522
Validation score: 0.860756
Iteration 92, loss = 8496242.93848797
Validation score: 0.854820
Iteration 93, loss = 8443860.25839981
Validation score: 0.861402
Iteration 94, loss = 8379587.17187452
Validation score: 0.861276
Iteration 95, loss = 8327656.32918204
Validation score: 0.861995
Iteration 96, loss = 8268127.64419456
Validation score: 0.863469
Iteration 97, loss = 8273454.41656309
Validation score: 0.862460
Iteration 98, loss = 8216689.29139777
Validation score: 0.861597
Iteration 99, loss = 8155583.27116482
Validation score: 0.860145
Iteration 100, loss = 8093290.75494925
Validation score: 0.865325
Iteration 101, loss = 8081430.81082978
Validation score: 0.863374
Iteration 102, loss = 8031633.22989353
Validation score: 0.861623
Iteration 103, loss = 7990768.44810882
Validation score: 0.866666
Iteration 104, loss = 7966527.14726572
Validation score: 0.865466
Iteration 105, loss = 7923790.00226470
Validation score: 0.865963
Iteration 106, loss = 7865291.85174553
Validation score: 0.863813
Iteration 107, loss = 7948043.49709161
Validation score: 0.863620
Iteration 108, loss = 7836778.94377325
Validation score: 0.862773
Iteration 109, loss = 7756880.93369616
Validation score: 0.864071
Iteration 110, loss = 7734944.20294964
Validation score: 0.861620
Iteration 111, loss = 7698888.22305255
Validation score: 0.864814
Iteration 112, loss = 7634392.05731843
Validation score: 0.863160
Iteration 113, loss = 7610628.85777530
Validation score: 0.866217
Iteration 114, loss = 7550230.29599351
Validation score: 0.865261
Iteration 115, loss = 7564875.07051471
Validation score: 0.867090
Iteration 116, loss = 7499606.30030516
Validation score: 0.864994
Iteration 117, loss = 7475018.63050110
Validation score: 0.865551
Iteration 118, loss = 7431401.60734697
Validation score: 0.865661
Iteration 119, loss = 7409546.86384534
Validation score: 0.861393
Iteration 120, loss = 7337972.34504231
Validation score: 0.867900
Iteration 121, loss = 7352801.50055854
Validation score: 0.867023
Iteration 122, loss = 7258728.84520849
Validation score: 0.869030
Iteration 123, loss = 7226627.98335313
Validation score: 0.868740
Iteration 124, loss = 7206127.44873929
Validation score: 0.868638
Iteration 125, loss = 7169980.54401963
Validation score: 0.865568
Iteration 126, loss = 7158983.94571719
Validation score: 0.870821
Iteration 127, loss = 7100568.06193188
Validation score: 0.869421
Iteration 128, loss = 7081772.64149214
Validation score: 0.870162
Iteration 129, loss = 7003794.60157857
Validation score: 0.861961
Iteration 130, loss = 7033416.39884377
Validation score: 0.869913
Iteration 131, loss = 6996358.41978317
Validation score: 0.865580
Iteration 132, loss = 6996549.50396970
Validation score: 0.869312
Iteration 133, loss = 6916691.03022003
Validation score: 0.870216
Iteration 134, loss = 6901624.78428356
Validation score: 0.871474
Iteration 135, loss = 6881429.50183107
Validation score: 0.872624
Iteration 136, loss = 6865296.97325328
Validation score: 0.872088
Iteration 137, loss = 6828790.37891871
Validation score: 0.871487
Iteration 138, loss = 6795733.80774361
Validation score: 0.870401
Iteration 139, loss = 6728533.55462511
Validation score: 0.871080
Iteration 140, loss = 6712555.67257881
Validation score: 0.871825
Iteration 141, loss = 6663998.16985141
Validation score: 0.862722
Iteration 142, loss = 6738944.17239857
Validation score: 0.870295
Iteration 143, loss = 6730916.18707510
Validation score: 0.866376
Iteration 144, loss = 6647846.39757610
Validation score: 0.863999
Iteration 145, loss = 6614619.93515304
Validation score: 0.860050
Iteration 146, loss = 6585883.08279203
Validation score: 0.871146
Iteration 147, loss = 6504672.29024669
Validation score: 0.872462
Iteration 148, loss = 6504400.08227247
Validation score: 0.872064
Iteration 149, loss = 6494017.44410633
Validation score: 0.871763
Iteration 150, loss = 6429220.03990389
Validation score: 0.871576
Iteration 151, loss = 6421226.25562614
Validation score: 0.874764
Iteration 152, loss = 6407180.53990029
Validation score: 0.869649
Iteration 153, loss = 6378138.57900207
Validation score: 0.875224
Iteration 154, loss = 6398000.65649914
Validation score: 0.872208
Iteration 155, loss = 6339414.19274521
Validation score: 0.872353
Iteration 156, loss = 6344102.33455454
Validation score: 0.869702
Iteration 157, loss = 6269796.96303989
Validation score: 0.873996
Iteration 158, loss = 6290021.60490759
Validation score: 0.872911
Iteration 159, loss = 6214767.35218490
Validation score: 0.874415
Iteration 160, loss = 6190894.04616479
Validation score: 0.873878
Iteration 161, loss = 6190092.16806777
Validation score: 0.874944
Iteration 162, loss = 6215157.04242580
Validation score: 0.871665
Iteration 163, loss = 6169081.66146435
Validation score: 0.872585
Iteration 164, loss = 6115546.57488650
Validation score: 0.872261
Iteration 165, loss = 6134419.12201195
Validation score: 0.876725
Iteration 166, loss = 6092444.64308113
Validation score: 0.876528
Iteration 167, loss = 6066711.37590011
Validation score: 0.878366
Iteration 168, loss = 6041474.88944988
Validation score: 0.872391
Iteration 169, loss = 5999068.69815099
Validation score: 0.872083
Iteration 170, loss = 5976067.58065660
Validation score: 0.878246
Iteration 171, loss = 6035856.80477837
Validation score: 0.876116
Iteration 172, loss = 5972505.98097420
Validation score: 0.876855
Iteration 173, loss = 5931739.09018329
Validation score: 0.874219
Iteration 174, loss = 5987048.48212206
Validation score: 0.874259
Iteration 175, loss = 5906104.92025774
Validation score: 0.876678
Iteration 176, loss = 5937030.90445807
Validation score: 0.875617
Iteration 177, loss = 5843424.88179855
Validation score: 0.874522
Iteration 178, loss = 5850576.68844601
Validation score: 0.879220
Iteration 179, loss = 5832104.45681160
Validation score: 0.879213
Iteration 180, loss = 5784154.44077886
Validation score: 0.875650
Iteration 181, loss = 5782849.11180643
Validation score: 0.878330
Iteration 182, loss = 5784238.73042931
Validation score: 0.874981
Iteration 183, loss = 5756501.77010179
Validation score: 0.877620
Iteration 184, loss = 5732343.34071440
Validation score: 0.878767
Iteration 185, loss = 5727599.20260840
Validation score: 0.877502
Iteration 186, loss = 5709989.51950070
Validation score: 0.876934
Iteration 187, loss = 5689057.23416433
Validation score: 0.875999
Iteration 188, loss = 5689898.51547397
Validation score: 0.876604
Iteration 189, loss = 5650604.58868100
Validation score: 0.878547
Iteration 190, loss = 5627298.93336114
Validation score: 0.875620
Iteration 191, loss = 5612782.17347223
Validation score: 0.872805
Iteration 192, loss = 5583944.10200108
Validation score: 0.877895
Iteration 193, loss = 5595969.33426620
Validation score: 0.878482
Iteration 194, loss = 5572286.76049608
Validation score: 0.877707
Iteration 195, loss = 5526290.99663565
Validation score: 0.877090
Iteration 196, loss = 5545429.00654397
Validation score: 0.879475
Iteration 197, loss = 5586778.33199769
Validation score: 0.880209
Iteration 198, loss = 5496617.74860478
Validation score: 0.879118
Iteration 199, loss = 5486850.01346007
Validation score: 0.880276
Iteration 200, loss = 5470276.20212800
Validation score: 0.872176
Iteration 201, loss = 5514064.82942851
Validation score: 0.874417
Iteration 202, loss = 5469703.57218892
Validation score: 0.875940
Iteration 203, loss = 5450491.45509348
Validation score: 0.877319
Iteration 204, loss = 5462101.24084342
Validation score: 0.876480
Iteration 205, loss = 5423257.14608905
Validation score: 0.877583
Iteration 206, loss = 5521365.18721746
Validation score: 0.875569
Iteration 207, loss = 5391553.24876167
Validation score: 0.881856
Iteration 208, loss = 5377251.82737577
Validation score: 0.881254
Iteration 209, loss = 5351065.00034527
Validation score: 0.877414
Iteration 210, loss = 5383414.59609282
Validation score: 0.881143
Iteration 211, loss = 5388404.20989280
Validation score: 0.880832
Iteration 212, loss = 5324035.25204728
Validation score: 0.868832
Iteration 213, loss = 5420713.59445523
Validation score: 0.877047
Iteration 214, loss = 5300868.46527870
Validation score: 0.877025
Iteration 215, loss = 5280655.54220065
Validation score: 0.876560
Iteration 216, loss = 5306906.75457712
Validation score: 0.877322
Iteration 217, loss = 5254575.12203614
Validation score: 0.875033
Iteration 218, loss = 5286538.38836362
Validation score: 0.880073
Iteration 219, loss = 5231984.64361896
Validation score: 0.881189
Iteration 220, loss = 5208176.03056091
Validation score: 0.877629
Iteration 221, loss = 5239974.94773759
Validation score: 0.877898
Iteration 222, loss = 5248424.32117730
Validation score: 0.878516
Iteration 223, loss = 5177540.48810821
Validation score: 0.878547
Iteration 224, loss = 5189528.29961827
Validation score: 0.878263
Iteration 225, loss = 5137988.00913551
Validation score: 0.877433
Iteration 226, loss = 5178180.76474123
Validation score: 0.879406
Iteration 227, loss = 5149612.02057196
Validation score: 0.879070
Iteration 228, loss = 5142145.08421163
Validation score: 0.878056
Iteration 229, loss = 5121413.14929162
Validation score: 0.877839
Iteration 230, loss = 5095188.33790364
Validation score: 0.879573
Iteration 231, loss = 5093556.36768700
Validation score: 0.880553
Iteration 232, loss = 5083609.88396450
Validation score: 0.876967
Iteration 233, loss = 5089960.63164259
Validation score: 0.881707
Iteration 234, loss = 5061734.15564640
Validation score: 0.881094
Iteration 235, loss = 5043960.49764031
Validation score: 0.874578
Iteration 236, loss = 5071944.11290214
Validation score: 0.876736
Iteration 237, loss = 5012818.65397223
Validation score: 0.881133
Iteration 238, loss = 5025727.78769825
Validation score: 0.879928
Validation score did not improve more than tol=0.000100 for 30 consecutive epochs. Stopping.
  ✓ mercedes done.
Iteration 1, loss = 90459582.78189930
Validation score: -6.786438
Iteration 2, loss = 82683996.95966417
Validation score: -4.941340
Iteration 3, loss = 39360337.56499252
Validation score: 0.105046
Iteration 4, loss = 5423202.70942580
Validation score: 0.660739
Iteration 5, loss = 3511309.41463121
Validation score: 0.724316
Iteration 6, loss = 2967771.43511600
Validation score: 0.756864
Iteration 7, loss = 2652376.62996866
Validation score: 0.774907
Iteration 8, loss = 2453513.96015460
Validation score: 0.787418
Iteration 9, loss = 2309278.61869008
Validation score: 0.796391
Iteration 10, loss = 2201428.34973489
Validation score: 0.803321
Iteration 11, loss = 2111295.82757132
Validation score: 0.809088
Iteration 12, loss = 2039446.15404754
Validation score: 0.813494
Iteration 13, loss = 1979318.77092115
Validation score: 0.817649
Iteration 14, loss = 1928575.15534375
Validation score: 0.820712
Iteration 15, loss = 1884732.04915705
Validation score: 0.823451
Iteration 16, loss = 1849097.57162205
Validation score: 0.825600
Iteration 17, loss = 1816457.11394461
Validation score: 0.827482
Iteration 18, loss = 1787114.69594487
Validation score: 0.829029
Iteration 19, loss = 1759578.20693646
Validation score: 0.831115
Iteration 20, loss = 1738656.40779893
Validation score: 0.832112
Iteration 21, loss = 1719239.34758493
Validation score: 0.832790
Iteration 22, loss = 1703077.35971014
Validation score: 0.834177
Iteration 23, loss = 1682724.22473158
Validation score: 0.834935
Iteration 24, loss = 1668507.24451016
Validation score: 0.835765
Iteration 25, loss = 1655714.04919046
Validation score: 0.836513
Iteration 26, loss = 1641848.63700677
Validation score: 0.837458
Iteration 27, loss = 1628988.15566464
Validation score: 0.838401
Iteration 28, loss = 1616744.58333090
Validation score: 0.838853
Iteration 29, loss = 1606651.23703262
Validation score: 0.839793
Iteration 30, loss = 1591432.50598179
Validation score: 0.840455
Iteration 31, loss = 1584454.80852700
Validation score: 0.841121
Iteration 32, loss = 1576100.59718875
Validation score: 0.841816
Iteration 33, loss = 1560763.54663623
Validation score: 0.843108
Iteration 34, loss = 1552355.13897186
Validation score: 0.843630
Iteration 35, loss = 1542439.37985526
Validation score: 0.844376
Iteration 36, loss = 1532380.76147146
Validation score: 0.845051
Iteration 37, loss = 1523339.75712040
Validation score: 0.845632
Iteration 38, loss = 1512771.75890607
Validation score: 0.846626
Iteration 39, loss = 1502783.50463192
Validation score: 0.847629
Iteration 40, loss = 1492328.01696181
Validation score: 0.848318
Iteration 41, loss = 1481931.75248099
Validation score: 0.849048
Iteration 42, loss = 1473209.14058727
Validation score: 0.849927
Iteration 43, loss = 1463835.29273938
Validation score: 0.850330
Iteration 44, loss = 1451189.64393058
Validation score: 0.851469
Iteration 45, loss = 1446533.36900292
Validation score: 0.851940
Iteration 46, loss = 1438719.80249161
Validation score: 0.853388
Iteration 47, loss = 1425690.65349076
Validation score: 0.854376
Iteration 48, loss = 1414751.92552168
Validation score: 0.855455
Iteration 49, loss = 1406701.22459154
Validation score: 0.855743
Iteration 50, loss = 1403317.36311113
Validation score: 0.855702
Iteration 51, loss = 1389249.65122678
Validation score: 0.857817
Iteration 52, loss = 1381447.90533462
Validation score: 0.858176
Iteration 53, loss = 1372406.18522362
Validation score: 0.857882
Iteration 54, loss = 1366491.09566479
Validation score: 0.860231
Iteration 55, loss = 1359698.03548555
Validation score: 0.860270
Iteration 56, loss = 1349514.13797353
Validation score: 0.861251
Iteration 57, loss = 1343131.80050894
Validation score: 0.862584
Iteration 58, loss = 1340664.27810196
Validation score: 0.859637
Iteration 59, loss = 1330495.91100077
Validation score: 0.862774
Iteration 60, loss = 1324639.21550816
Validation score: 0.864135
Iteration 61, loss = 1310598.87646275
Validation score: 0.863580
Iteration 62, loss = 1309146.97780926
Validation score: 0.865096
Iteration 63, loss = 1311650.48423410
Validation score: 0.865593
Iteration 64, loss = 1294525.43490061
Validation score: 0.866270

      Brand     N         RMSE          MAE        R²
7      opel  1912  1126.031498   781.354543  0.901414
4      ford  3272  1537.055512  1035.234848  0.893918
1   hyundai   676  1618.566354  1098.226810  0.925896
6    toyota   948  1805.556131   989.849916  0.932869
3        vw  2118  2055.793181  1352.922704  0.932289
8     skoda   882  2791.922977  1221.496772  0.830262
0       bmw  1514  3036.292605  1942.782433  0.922117
2      audi  1489  3334.061488  2004.198121  0.919684
5  mercedes  2384  3518.602942  2299.999134  0.905946

| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3488.30 | 2061.42 | 0.8737 |
| ElasticNet | 4956.03 | 3039.99 | 0.7450 |
| KNR|3004.83 |1691.97 |0.9063 |
|RF | 2233.99 |1286.08 |0.9482 |
|NN | 2445.42 |1442.16 |0.9379 |

## Feature selection - Filter Methods

In [113]:
df = X_train.join(y_train)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60778 entries, 44735 to 59767
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           60778 non-null  int32
 1   tax               60778 non-null  int32
 2   mpg               60778 non-null  float64
 3   engineSize        60778 non-null  float64
 4   paintQuality%     60778 non-null  int32
 5   previousOwners    60778 non-null  int32
 6   stated_no_damage  60778 non-null  float64
 7   Brand             60778 non-null  object
 8   transmission      60778 non-null  object
 9   model             60778 non-null  object
 10  fuelType          60778 non-null  object
 11  age               60778 non-null  int32
 12  mileage_per_year  60778 non-null  float64
 13  efficiency_ratio  60778 non-null  float64
 14  age_mileage       60778 non-null  float64
 15  condition_score   60778 non-null  float64
 16  price             60778 non-null  int32
dtypes: float64(7), int32(6), object(4)
memory usage: 8.2+ MB

In [115]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
y = df['price']

numerical_cols = df.select_dtypes(include=['int64', "int32",'float64']).columns

# Drop 'carID' and 'price'
num_cols = [col for col in numerical_cols 
            if "_transformed" not in col and col not in ['price', 'carID']]

print(num_cols)
print(categorical_cols)

['mileage', 'tax', 'mpg', 'engineSize', 'paintQuality%', 'previousOwners', 'stated_no_damage', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'condition_score']
['Brand', 'transmission', 'model', 'fuelType']

In [116]:
df

,mileage,tax,mpg,engineSize,paintQuality%,previousOwners,stated_no_damage,Brand,transmission,model,fuelType,age,mileage_per_year,efficiency_ratio,age_mileage,condition_score,price
carID,,,,,,,,,,,,,,,,,
44735,1000,145,35.8,2.0,86,2,1.0,mercedes,semi-auto,a class,petrol,4,200.000000,17.047619,0.04000,0.930,33569
44774,5012,116,59.2,1.6,51,3,1.0,mercedes,semi-auto,c class,diesel,5,835.333333,34.823529,0.25060,0.755,27699
36653,10000,146,52.0,1.5,74,3,1.0,mercedes,automatic,c class,petrol,5,1666.666667,32.500000,0.50000,0.870,24400
22889,110000,20,67.3,2.0,61,1,1.0,ford,manual,mondeo,diesel,9,11000.000000,32.047619,9.90000,0.805,6391
62059,17113,145,47.1,1.4,89,4,1.0,opel,manual,mokka x,petrol,6,2444.714286,31.400000,1.02678,0.945,11386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71271,15773,20,58.9,1.0,90,2,0.0,vw,manual,polo,petrol,7,1971.625000,53.545455,1.10411,0.450,9798
7862,27563,160,46.3,2.0,60,3,1.0,bmw,semi-auto,5 series,petrol,9,2756.300000,22.047619,2.48067,0.800,16750
33501,10164,145,60.1,1.0,40,2,1.0,hyundai,manual,i10,petrol,6,1452.000000,54.636364,0.60984,0.700,7900
68727,12400,145,34.5,2.0,53,4,1.0,vw,manual,t-roc,petrol,5,2066.666667,16.428571,0.62000,0.765,29100
59767,3588,140,43.5,1.4,92,1,1.0,opel,manual,corsa,petrol,1,1794.000000,29.000000,0.03588,0.960,9999

In [117]:
#FILTER METHOD


#ANOVA FUNCTION

def anova_for_categorical(df, y, categorical_cols):
    # Align indices between df and y
    common_idx = df.index.intersection(y.index)
    df_aligned = df.loc[common_idx]
    y_aligned = y.loc[common_idx]
    
    f_scores, p_values = [], []
    for col in df_aligned.columns:
        if col in categorical_cols:
            groups = [y_aligned[df_aligned[col] == cat] for cat in df_aligned[col].dropna().unique()]
            if len(groups) > 1 and all(len(g) > 1 for g in groups):
                f_stat, p_val = stats.f_oneway(*groups)
            else:
                f_stat, p_val = 0.0, 1.0
        else:
            if df_aligned[col].nunique() > 1:
                # Remove NaN values for correlation calculation
                valid_idx = df_aligned[col].notna() & y_aligned.notna()
                if valid_idx.sum() > 1:
                    corr = np.corrcoef(df_aligned.loc[valid_idx, col], y_aligned[valid_idx])[0, 1]
                    f_stat = corr**2 * valid_idx.sum()
                    p_val = 0.0
                else:
                    f_stat, p_val = 0.0, 1.0
            else:
                f_stat, p_val = 0.0, 1.0
        f_scores.append(f_stat)
        p_values.append(p_val)
    
    return np.array(f_scores), np.array(p_values)


def filter_method_selection(X_train, y_train, categorical_cols, num_cols,
                            top_k=None,
                            var_threshold=0.01,
                            corr_threshold=0.85):
    
    print("FILTER METHOD (Variance + Spearman Correlation + ANOVA)")
    
    # Ensure indices match
    common_idx = X_train.index.intersection(y_train.index)
    X_train = X_train.loc[common_idx]
    y_train = y_train.loc[common_idx]
    
    # Filter numerical columns that exist in X_train
    num_cols_in_X = [col for col in num_cols if col in X_train.columns]
    
    # Variance Threshold
    if num_cols_in_X:
        vt_selector = VarianceThreshold(threshold=var_threshold)
        X_num_vt = pd.DataFrame(
            vt_selector.fit_transform(X_train[num_cols_in_X]),
            columns=np.array(num_cols_in_X)[vt_selector.get_support()],
            index=X_train.index
        )
        print(f"Removed {len(num_cols_in_X) - X_num_vt.shape[1]} low-variance numeric features.")
    else:
        X_num_vt = pd.DataFrame(index=X_train.index)
    
    # Spearman Correlation
    if not X_num_vt.empty and X_num_vt.shape[1] > 1:
        corr_matrix = X_num_vt.corr(method='spearman').abs()
        upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
        to_drop = [col for col in upper.columns if any(upper[col] > corr_threshold)]
        X_num_corr = X_num_vt.drop(columns=to_drop)
        print(f"Removed {len(to_drop)} correlated numeric features (Spearman |corr| > {corr_threshold}).")
    else:
        X_num_corr = X_num_vt
    
    # Filter categorical columns that exist in X_train
    categorical_cols_in_X = [col for col in categorical_cols if col in X_train.columns]
    
    # Combine numeric + categorical
    X_filtered = pd.concat([X_num_corr, X_train[categorical_cols_in_X]], axis=1)
    
    # ANOVA F-test
    f_scores, f_pvalues = anova_for_categorical(X_filtered, y_train, categorical_cols_in_X)
    f_norm = (f_scores - f_scores.min()) / (f_scores.max() - f_scores.min() + 1e-10)
    
    results_df = pd.DataFrame({
        'feature': X_filtered.columns,
        'ANOVA_F': f_scores,
        'ANOVA_p_value': f_pvalues,
        'ANOVA_norm': f_norm,
        'type': ['categorical' if c in categorical_cols_in_X else 'numerical' for c in X_filtered.columns]
    }).sort_values('ANOVA_norm', ascending=False)
    
    if top_k is None:
        selected_features = X_filtered.columns.tolist()
    else:
        selected_features = X_filtered.columns[np.argsort(f_norm)[-top_k:]].tolist()
    
    print(f"\nFilter method selected {len(selected_features)} features")
    
    return selected_features, X_filtered[selected_features], results_df

In [118]:
y = df["price"]

df = df.drop(columns=["price"])

In [119]:

#X_train = df[num_cols]
#y_train = df['price']

# Filter method (Variance + Spearman + ANOVA)
# Define categorical and numerical columns first (if not already defined)
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
num_cols = df.select_dtypes(include=['int64',"int32", 'float64']).columns.tolist()

# Filter method with all required parameters
selected_filter, X_train_filtered, filter_df = filter_method_selection(
    df, 
    y,
    categorical_cols=categorical_cols,  # Add this
    num_cols=num_cols,                  # Add this
    top_k=None, 
    var_threshold=0.01, 
    corr_threshold=0.85
)

# Print features selected
print("\nFeatures selected by Filter Method:")
for f in selected_filter:
    print(f)

# Display feature importance scores
print("\nTop 10 Features by ANOVA Score:")
print(filter_df.head(10))

FILTER METHOD (Variance + Spearman Correlation + ANOVA)
Removed 0 low-variance numeric features.
Removed 3 correlated numeric features (Spearman |corr| > 0.85).

Filter method selected 13 features

Features selected by Filter Method:
mileage
tax
mpg
engineSize
paintQuality%
previousOwners
stated_no_damage
age
efficiency_ratio
Brand
transmission
model
fuelType

Top 10 Features by ANOVA Score:
             feature       ANOVA_F  ANOVA_p_value  ANOVA_norm         type
3         engineSize  23128.081112            0.0    1.000000    numerical
7                age  13914.885189            0.0    0.601645    numerical
10      transmission  12694.800173            0.0    0.548891  categorical
0            mileage  10456.747359            0.0    0.452123    numerical
1                tax   6204.904680            0.0    0.268284    numerical
2                mpg   5267.455866            0.0    0.227752    numerical
9              Brand   3113.772851            0.0    0.134632  categorical
12          fuelType    997.607619            0.0    0.043134  categorical
8   efficiency_ratio    523.211349            0.0    0.022622    numerical
4      paintQuality%      1.384565            0.0    0.000060    numerical

In [120]:
raise SystemExit("Stop before training the models")

SystemExit: Stop before training the models

C:\Users\liber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

## Test models on reduced DF

In [88]:
X_train_filter = X_train[["mileage", "tax", "mpg", "engineSize", "paintQuality%", "previousOwners", "stated_no_damage", "age", "efficiency_ratio",
                            "Brand", "transmission", "model", "fuelType"]]
X_train_filter

,mileage,tax,mpg,engineSize,paintQuality%,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model,fuelType
carID,,,,,,,,,,,,,
44735,1000,145,35.8,2.0,86,2,1.0,4,17.047619,mercedes,semi-auto,a class,petrol
44774,5012,116,59.2,1.6,51,3,1.0,5,34.823529,mercedes,semi-auto,c class,diesel
36653,10000,146,52.0,1.5,74,3,1.0,5,32.500000,mercedes,automatic,c class,petrol
22889,110000,20,67.3,2.0,61,1,1.0,9,32.047619,ford,manual,mondeo,diesel
62059,17113,145,47.1,1.4,89,4,1.0,6,31.400000,opel,manual,mokka x,petrol
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71271,15773,20,58.9,1.0,90,2,0.0,7,53.545455,vw,manual,polo,petrol
7862,27563,160,46.3,2.0,60,3,1.0,9,22.047619,bmw,semi-auto,5 series,petrol
33501,10164,145,60.1,1.0,40,2,1.0,6,54.636364,hyundai,manual,i10,petrol
68727,12400,145,34.5,2.0,53,4,1.0,5,16.428571,vw,manual,t-roc,petrol
59767,3588,140,43.5,1.4,92,1,1.0,1,29.000000,opel,manual,corsa,petrol

In [89]:
X_val_filter = X_val[["mileage", "tax", "mpg", "engineSize", "paintQuality%", "previousOwners", "stated_no_damage", "age", "efficiency_ratio",
                            "Brand", "transmission", "model", "fuelType"]]
X_val_filter

,mileage,tax,mpg,engineSize,paintQuality%,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model,fuelType
carID,,,,,,,,,,,,,
10742,10,145,60.1,2.0,46,2,1.0,5,28.619048,bmw,manual,2 series,diesel
33830,26671,145,44.8,1.6,40,1,1.0,7,26.352941,hyundai,manual,tucson,petrol
2417,148000,305,35.8,3.0,82,0,1.0,16,11.548387,audi,manual,a4,diesel
4544,6541,145,47.9,2.0,59,2,1.0,5,22.809524,audi,semi-auto,a4,diesel
73794,31190,145,58.9,1.0,73,0,1.0,6,53.545455,vw,manual,golf sv,petrol
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8206,32285,150,68.9,2.0,98,4,1.0,7,32.809524,bmw,manual,1 series,diesel
71796,3252,145,32.8,2.0,71,3,1.0,5,15.619048,vw,semi-auto,golf,petrol
72896,67039,145,48.7,1.8,40,2,1.0,15,25.631579,vw,manual,polo,petrol
23839,9080,145,49.6,1.0,43,0,1.0,5,45.090909,ford,manual,focus,petrol
43030,26500,145,56.5,2.1,40,0,1.0,6,25.681818,mercedes,semi-auto,glc class,diesel

In [90]:
LR = LinearRegression()
trainer = BrandModelTrainer(LR)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 3505.92
  MAE:  2119.84
  R²:   0.8698

Validation Set Performance (Overall):
  RMSE: 3611.32
  MAE:  2167.81
  R²:   0.8646

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7633 1587.460508 1099.919342 0.800886
  toyota  3770 1922.071099 1183.028084 0.904293
    ford 13120 2122.843582 1512.673343 0.804527
   skoda  3504 2134.574421 1516.083684 0.877506
 hyundai  2728 2197.747433 1538.439900 0.863864
      vw  8488 2916.108755 2037.931265 0.856233
    audi  5979 4338.783014 2817.498954 0.861169
     bmw  6032 4530.372664 3018.630939 0.846892
mercedes  9524 5770.013105 3598.940739 0.730672

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1601.653529 1125.376930 0.800542
    ford 3272 2072.927484 1503.594797 0.807055
 hyundai  676 2290.049307 1582.255137 0.851655
  toyota  948 2334.180053 1263.668663 0.887806
      vw 2118 3016.630278 2114.531143 0.854204
   skoda  882 3127.743839 1604.868756 0.786973
    audi 1489 4301.443655 2780.241433 0.866315
     bmw 1514 4330.239245 2984.125322 0.841591
mercedes 2384 6028.838676 3795.743667 0.723877

      Brand     N         RMSE          MAE        R²
7      opel  1912  1601.653529  1125.376930  0.800542
4      ford  3272  2072.927484  1503.594797  0.807055
1   hyundai   676  2290.049307  1582.255137  0.851655
6    toyota   948  2334.180053  1263.668663  0.887806
3        vw  2118  3016.630278  2114.531143  0.854204
8     skoda   882  3127.743839  1604.868756  0.786973
2      audi  1489  4301.443655  2780.241433  0.866315
0       bmw  1514  4330.239245  2984.125322  0.841591
5  mercedes  2384  6028.838676  3795.743667  0.723877

In [91]:
Elastic = ElasticNet()
trainer = BrandModelTrainer(Elastic)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)        # Performance VALID

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 4942.71
  MAE:  3033.19
  R²:   0.7413

Validation Set Performance (Overall):
  RMSE: 5009.89
  MAE:  3070.02
  R²:   0.7395

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7633 2307.406147 1726.696222 0.579329
    ford 13120 2790.398116 2006.953052 0.662260
   skoda  3504 3427.075818 2452.132851 0.684252
 hyundai  2728 3444.723415 2475.356616 0.665553
  toyota  3770 3588.944737 2384.883692 0.666315
      vw  8488 4495.913785 3090.974731 0.658267
    audi  5979 6456.733053 3834.177629 0.692550
mercedes  9524 6832.184248 4353.053290 0.622386
     bmw  6032 7666.728779 4954.377269 0.561519

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 2280.690821 1729.146369 0.595566
    ford 3272 2693.744091 1993.583232 0.674181
 hyundai  676 3424.031652 2401.232847 0.668366
   skoda  882 4229.256080 2659.747942 0.610507
  toyota  948 4367.256157 2547.810722 0.607248
      vw 2118 4671.112170 3249.607287 0.650423
    audi 1489 6371.030489 3801.402761 0.706726
     bmw 1514 7072.751441 4724.489407 0.577397
mercedes 2384 7198.090578 4504.861671 0.606387

      Brand     N         RMSE          MAE        R²
7      opel  1912  2280.690821  1729.146369  0.595566
4      ford  3272  2693.744091  1993.583232  0.674181
1   hyundai   676  3424.031652  2401.232847  0.668366
8     skoda   882  4229.256080  2659.747942  0.610507
6    toyota   948  4367.256157  2547.810722  0.607248
3        vw  2118  4671.112170  3249.607287  0.650423
2      audi  1489  6371.030489  3801.402761  0.706726
0       bmw  1514  7072.751441  4724.489407  0.577397
5  mercedes  2384  7198.090578  4504.861671  0.606387

In [92]:
KNR = KNeighborsRegressor()
trainer = BrandModelTrainer(KNR)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 2331.86
  MAE:  1341.70
  R²:   0.9424

Validation Set Performance (Overall):
  RMSE: 2990.28
  MAE:  1691.12
  R²:   0.9072

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7633 1110.463353  748.398533 0.902568
  toyota  3770 1332.202473  832.235968 0.954023
    ford 13120 1356.013314  883.019497 0.920241
   skoda  3504 1494.834582 1071.983048 0.939927
 hyundai  2728 1526.767346 1001.357405 0.934300
      vw  8488 1928.038340 1318.974741 0.937153
    audi  5979 2979.969927 1935.642014 0.934510
     bmw  6032 3438.592051 2052.168170 0.911795
mercedes  9524 3551.069890 2044.892566 0.897989

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1313.098665  909.123640 0.865937
    ford 3272 1633.083094 1082.981357 0.880249
 hyundai  676 1865.842886 1275.730769 0.901523
  toyota  948 1938.332689 1095.546624 0.922633
      vw 2118 2447.721156 1661.948253 0.904010
   skoda  882 3010.026979 1401.473016 0.802706
    audi 1489 3950.739859 2409.848892 0.887225
     bmw 1514 4118.586179 2566.181242 0.856698
mercedes 2384 4502.466256 2636.039681 0.845995

      Brand     N         RMSE          MAE        R²
7      opel  1912  1313.098665   909.123640  0.865937
4      ford  3272  1633.083094  1082.981357  0.880249
1   hyundai   676  1865.842886  1275.730769  0.901523
6    toyota   948  1938.332689  1095.546624  0.922633
3        vw  2118  2447.721156  1661.948253  0.904010
8     skoda   882  3010.026979  1401.473016  0.802706
2      audi  1489  3950.739859  2409.848892  0.887225
0       bmw  1514  4118.586179  2566.181242  0.856698
5  mercedes  2384  4502.466256  2636.039681  0.845995

In [93]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train_filter, y_train)


rf_trainer.evaluate_train(X_train_filter, y_train)
rf_trainer.evaluate(X_val_filter, y_val)

rf_trainer.evaluate_train_by_brand(X_train_filter, y_train)
rf_trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Training Set Performance (Overall):
  RMSE: 825.28
  MAE:  471.41
  R²:   0.9928

Validation Set Performance (Overall):
  RMSE: 2199.79
  MAE:  1275.63
  R²:   0.9498

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7633  446.553515 296.280294 0.984244
    ford 13120  521.334117 337.928879 0.988211
 hyundai  2728  556.679215 354.290044 0.991266
  toyota  3770  580.918446 347.435915 0.991258
   skoda  3504  599.534590 407.890890 0.990337
      vw  8488  729.062862 459.621713 0.991014
    audi  5979 1024.328063 643.965190 0.992262
mercedes  9524 1179.741378 683.904246 0.988741
     bmw  6032 1213.975644 660.730448 0.989006

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1138.584807  782.090724 0.899204
    ford 3272 1409.114654  914.551974 0.910843
 hyundai  676 1564.568370 1012.588565 0.930758
  toyota  948 1578.062076  907.960496 0.948720
      vw 2118 1973.198928 1265.436747 0.937620
   skoda  882 2739.936003 1116.640091 0.836524
     bmw 1514 2786.715586 1744.709122 0.934394
    audi 1489 2927.764329 1748.242962 0.938066
mercedes 2384 2978.509295 1862.620331 0.932604

      Brand     N         RMSE          MAE        R²
7      opel  1912  1138.584807   782.090724  0.899204
4      ford  3272  1409.114654   914.551974  0.910843
1   hyundai   676  1564.568370  1012.588565  0.930758
6    toyota   948  1578.062076   907.960496  0.948720
3        vw  2118  1973.198928  1265.436747  0.937620
8     skoda   882  2739.936003  1116.640091  0.836524
0       bmw  1514  2786.715586  1744.709122  0.934394
2      audi  1489  2927.764329  1748.242962  0.938066
5  mercedes  2384  2978.509295  1862.620331  0.932604

In [94]:
from sklearn.neural_network import MLPRegressor

mlp_deep = MLPRegressor(
    hidden_layer_sizes=(256, 128, 64),  
    activation='relu',
    solver='adam',
    alpha=0.0001,  
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=2000,
    batch_size=256,
    random_state=42,
    early_stopping=True,
    n_iter_no_change=30,  
    validation_fraction=0.15,
    verbose=True
)

mlp_trainer = BrandModelTrainer(mlp_deep)


mlp_trainer.fit(X_train_filter, y_train)


mlp_trainer.evaluate_train(X_train_filter, y_train)
mlp_trainer.evaluate(X_val_filter, y_val)


mlp_trainer.evaluate_train_by_brand(X_train_filter, y_train)
mlp_trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

Iteration 1, loss = 363484396.04617161
Validation score: -5.687736
Iteration 2, loss = 359248626.43689102
Validation score: -5.477660
Iteration 3, loss = 332130181.63105667
Validation score: -4.460717
Iteration 4, loss = 242595327.75663561
Validation score: -2.046251
Iteration 5, loss = 107113782.12193915
Validation score: -0.028550
Iteration 6, loss = 42734994.25602884
Validation score: 0.384009
Iteration 7, loss = 28949559.18862030
Validation score: 0.547595
Iteration 8, loss = 23465120.67177410
Validation score: 0.616564
Iteration 9, loss = 20964133.03023534
Validation score: 0.652100
Iteration 10, loss = 19534923.15288718
Validation score: 0.680525
Iteration 11, loss = 18629790.00127812
Validation score: 0.695709
Iteration 12, loss = 18034208.93990591
Validation score: 0.704869
Iteration 13, loss = 17473906.81268818
Validation score: 0.716191
Iteration 14, loss = 17052548.27323876
Validation score: 0.723869
Iteration 15, loss = 16697131.00582343
Validation score: 0.730025
Iteration 16, loss = 16372203.02812150
Validation score: 0.738186
Iteration 17, loss = 16100357.24402754
Validation score: 0.743148
Iteration 18, loss = 15816086.56762852
Validation score: 0.748878
Iteration 19, loss = 15601286.96450387
Validation score: 0.751346
Iteration 20, loss = 15387374.12932323
Validation score: 0.756245
Iteration 21, loss = 15155861.77587547
Validation score: 0.762558
Iteration 22, loss = 14960001.85354026
Validation score: 0.767098
Iteration 23, loss = 14774504.29068746
Validation score: 0.767798
Iteration 24, loss = 14630495.02361048
Validation score: 0.771654
Iteration 25, loss = 14487343.55859199
Validation score: 0.777463
Iteration 26, loss = 14439545.79168580
Validation score: 0.776042
Iteration 27, loss = 14279648.91516002
Validation score: 0.779124
Iteration 28, loss = 14119058.39642966
Validation score: 0.782165
Iteration 29, loss = 14034412.66530119
Validation score: 0.783112
Iteration 30, loss = 13891717.88951120
Validation score: 0.783378
Iteration 31, loss = 13822406.90392208
Validation score: 0.788028
Iteration 32, loss = 13691622.87704061
Validation score: 0.787104
Iteration 33, loss = 13576522.26131647
Validation score: 0.791032
Iteration 34, loss = 13539414.77294745
Validation score: 0.793258
Iteration 35, loss = 13421714.88892775
Validation score: 0.793506
Iteration 36, loss = 13336520.76195525
Validation score: 0.794000
Iteration 37, loss = 13260877.39948767
Validation score: 0.794142
Iteration 38, loss = 13167497.41724539
Validation score: 0.793211
Iteration 39, loss = 13100808.71903537
Validation score: 0.798390
Iteration 40, loss = 12999558.93039019
Validation score: 0.795545
Iteration 41, loss = 12914048.65852134
Validation score: 0.796291
Iteration 42, loss = 12840372.63514241
Validation score: 0.799676
Iteration 43, loss = 12774076.43053796
Validation score: 0.800997
Iteration 44, loss = 12774566.92428084
Validation score: 0.800994
Iteration 45, loss = 12597929.97567761
Validation score: 0.799271
Iteration 46, loss = 12509913.34882192
Validation score: 0.800414
Iteration 47, loss = 12452208.33373248
Validation score: 0.804594
Iteration 48, loss = 12353051.70171775
Validation score: 0.803026
Iteration 49, loss = 12280128.63213062
Validation score: 0.802622
Iteration 50, loss = 12201380.83644030
Validation score: 0.807624
Iteration 51, loss = 12112522.39400412
Validation score: 0.807275
Iteration 52, loss = 12009521.52881902
Validation score: 0.802952
Iteration 53, loss = 11900691.48148790
Validation score: 0.808619
Iteration 54, loss = 11840044.37183299
Validation score: 0.810350
Iteration 55, loss = 11768664.68748213
Validation score: 0.810596
Iteration 56, loss = 11710313.87452877
Validation score: 0.809391
Iteration 57, loss = 11630833.53983483
Validation score: 0.806363
Iteration 58, loss = 11571348.72055247
Validation score: 0.807806
Iteration 59, loss = 11463342.05704601
Validation score: 0.812985
Iteration 60, loss = 11456859.05905085
Validation score: 0.813672
Iteration 61, loss = 11324744.08627113
Validation score: 0.813453
Iteration 62, loss = 11221718.82053358
Validation score: 0.812600
Iteration 63, loss = 11164617.43291594
Validation score: 0.815480
Iteration 64, loss = 11079012.81855808
Validation score: 0.814872
Iteration 65, loss = 11017879.80355847
Validation score: 0.817279
Iteration 66, loss = 10998970.50518315
Validation score: 0.815330
Iteration 67, loss = 10901828.62648166
Validation score: 0.819311
Iteration 68, loss = 10836226.74922939
Validation score: 0.817320
Iteration 69, loss = 10832831.33512723
Validation score: 0.818569
Iteration 70, loss = 10718382.33570472
Validation score: 0.817089
Iteration 71, loss = 10694501.57744469
Validation score: 0.821906
Iteration 72, loss = 10613091.70641277
Validation score: 0.820636
Iteration 73, loss = 10579033.93218198
Validation score: 0.819303
Iteration 74, loss = 10484838.45254427
Validation score: 0.821496
Iteration 75, loss = 10480357.33742949
Validation score: 0.820019
Iteration 76, loss = 10446708.93279288
Validation score: 0.811296
Iteration 77, loss = 10459533.30969918
Validation score: 0.818618
Iteration 78, loss = 10334488.79606966
Validation score: 0.820799
Iteration 79, loss = 10269989.00631916
Validation score: 0.823053
Iteration 80, loss = 10210274.86321254
Validation score: 0.819884
Iteration 81, loss = 10155532.64380845
Validation score: 0.825547
Iteration 82, loss = 10128701.65745489
Validation score: 0.824553
Iteration 83, loss = 10081118.24145591
Validation score: 0.823794
Iteration 84, loss = 10036532.95711540
Validation score: 0.825473
Iteration 85, loss = 9944077.74159833
Validation score: 0.826354
Iteration 86, loss = 9893089.91817567
Validation score: 0.827543
Iteration 87, loss = 9831338.82266491
Validation score: 0.825526
Iteration 88, loss = 9781977.01606240
Validation score: 0.821034
Iteration 89, loss = 9754094.16037405
Validation score: 0.829625
Iteration 90, loss = 9725224.16110985
Validation score: 0.827729
Iteration 91, loss = 9616791.97628827
Validation score: 0.827961
Iteration 92, loss = 9612072.08868661
Validation score: 0.831251
Iteration 93, loss = 9514390.15489545
Validation score: 0.826526
Iteration 94, loss = 9488473.28316218
Validation score: 0.828095
Iteration 95, loss = 9481094.12773163
Validation score: 0.832025
Iteration 96, loss = 9460071.49858998
Validation score: 0.829011
Iteration 97, loss = 9364954.47349133
Validation score: 0.832938
Iteration 98, loss = 9378866.29240352
Validation score: 0.830195
Iteration 99, loss = 9315081.96935294
Validation score: 0.833603
Iteration 100, loss = 9321732.79262882
Validation score: 0.822915
Iteration 101, loss = 9296954.91403314
Validation score: 0.825714
Iteration 102, loss = 9188802.74659971
Validation score: 0.829557
Iteration 103, loss = 9128870.45924378
Validation score: 0.832914
Iteration 104, loss = 9130615.90863232
Validation score: 0.832486
Iteration 105, loss = 9125897.26724385
Validation score: 0.834604
Iteration 106, loss = 9073470.52985626
Validation score: 0.834179
Iteration 107, loss = 9053458.78722392
Validation score: 0.834180
Iteration 108, loss = 8956112.11397816
Validation score: 0.833781
Iteration 109, loss = 8889699.46387126
Validation score: 0.833249
Iteration 110, loss = 8911139.50357324
Validation score: 0.834910
Iteration 111, loss = 8838332.71991001
Validation score: 0.836781
Iteration 112, loss = 8844328.16019068
Validation score: 0.837665
Iteration 113, loss = 8735655.76155668
Validation score: 0.831980
Iteration 114, loss = 8700088.49532442
Validation score: 0.834249
Iteration 115, loss = 8683507.24455963
Validation score: 0.835759
Iteration 116, loss = 8615084.46427324
Validation score: 0.836579
Iteration 117, loss = 8625450.83015902
Validation score: 0.837509
Iteration 118, loss = 8533464.92850577
Validation score: 0.827003
Iteration 119, loss = 8572272.70050739
Validation score: 0.832488
Iteration 120, loss = 8473021.16515031
Validation score: 0.835147
Iteration 121, loss = 8413826.59715357
Validation score: 0.833367
Iteration 122, loss = 8393020.10647949
Validation score: 0.833858
Iteration 123, loss = 8325206.78270679
Validation score: 0.835482
Iteration 124, loss = 8264391.62347268
Validation score: 0.838673
Iteration 125, loss = 8233118.01844465
Validation score: 0.838904
Iteration 126, loss = 8218565.32110407
Validation score: 0.836853
Iteration 127, loss = 8186333.12332143
Validation score: 0.837664
Iteration 128, loss = 8117461.45805383
Validation score: 0.835295
Iteration 129, loss = 8055200.93731592
Validation score: 0.839969
Iteration 130, loss = 8091750.55358498
Validation score: 0.840437
Iteration 131, loss = 8067872.23961762
Validation score: 0.838096
Iteration 132, loss = 7982420.36883853
Validation score: 0.831965
Iteration 133, loss = 7959629.29158810
Validation score: 0.836843
Iteration 134, loss = 8073018.90092558
Validation score: 0.835698
Iteration 135, loss = 7857920.98971390
Validation score: 0.839960
Iteration 136, loss = 7837718.89151244
Validation score: 0.835796
Iteration 137, loss = 7823863.49021810
Validation score: 0.837451
Iteration 138, loss = 7775269.38203943
Validation score: 0.842607
Iteration 139, loss = 7805109.90257231
Validation score: 0.841860
Iteration 140, loss = 7795725.56539260
Validation score: 0.841621
Iteration 141, loss = 7775892.71242641
Validation score: 0.841092
Iteration 142, loss = 7661104.86046391
Validation score: 0.841699
Iteration 143, loss = 7584660.40349269
Validation score: 0.840759
Iteration 144, loss = 7587553.95764084
Validation score: 0.838583
Iteration 145, loss = 7550201.16876946
Validation score: 0.834995
Iteration 146, loss = 7490075.66402672
Validation score: 0.841981
Iteration 147, loss = 7506489.11160678
Validation score: 0.841082
Iteration 148, loss = 7438906.17517481
Validation score: 0.843623
Iteration 149, loss = 7450833.77944445
Validation score: 0.840991
Iteration 150, loss = 7384728.61588001
Validation score: 0.841795
Iteration 151, loss = 7355326.80546739
Validation score: 0.843673
Iteration 152, loss = 7377317.20129578
Validation score: 0.843586
Iteration 153, loss = 7326860.89215115
Validation score: 0.842813
Iteration 154, loss = 7259344.38672231
Validation score: 0.842997
Iteration 155, loss = 7341623.81294721
Validation score: 0.837624
Iteration 156, loss = 7301997.02512930
Validation score: 0.836122
Iteration 157, loss = 7259600.84791970
Validation score: 0.844172
Iteration 158, loss = 7222799.32394692
Validation score: 0.842348
Iteration 159, loss = 7115319.93380797
Validation score: 0.841652
Iteration 160, loss = 7117643.74755534
Validation score: 0.841970
Iteration 161, loss = 7135975.20315815
Validation score: 0.843366
Iteration 162, loss = 7028384.45003959
Validation score: 0.841138
Iteration 163, loss = 7026365.37132186
Validation score: 0.843453
Iteration 164, loss = 6971186.20984636
Validation score: 0.843152
Iteration 165, loss = 7007809.52024726
Validation score: 0.844055
Iteration 166, loss = 6913011.73617556
Validation score: 0.841865
Iteration 167, loss = 6895842.49988848
Validation score: 0.841524
Iteration 168, loss = 6904678.66790485
Validation score: 0.842244
Iteration 169, loss = 6839117.16616028
Validation score: 0.844905
Iteration 170, loss = 6852851.89130050
Validation score: 0.844185
Iteration 171, loss = 6805212.14760454
Validation score: 0.842340
Iteration 172, loss = 6789056.20566608
Validation score: 0.843504
Iteration 173, loss = 6730471.71275430
Validation score: 0.843240
Iteration 174, loss = 6755417.87586858
Validation score: 0.845952
Iteration 175, loss = 6696770.95251283
Validation score: 0.841428
Iteration 176, loss = 6727388.01895982
Validation score: 0.839983
Iteration 177, loss = 6678024.23883528
Validation score: 0.840324
Iteration 178, loss = 6598461.19879192
Validation score: 0.846122
Iteration 179, loss = 6603733.81973592
Validation score: 0.842468
Iteration 180, loss = 6593706.49081542
Validation score: 0.845851
Iteration 181, loss = 6589133.11883154
Validation score: 0.846338
Iteration 182, loss = 6611239.05127671
Validation score: 0.845347
Iteration 183, loss = 6510317.32292788
Validation score: 0.846171
Iteration 184, loss = 6509241.58594318
Validation score: 0.844274
Iteration 185, loss = 6468236.08213099
Validation score: 0.842857
Iteration 186, loss = 6445325.86008318
Validation score: 0.843694
Iteration 187, loss = 6470391.15091767
Validation score: 0.846046
Iteration 188, loss = 6516055.58708381
Validation score: 0.843264
Iteration 189, loss = 6389184.76512574
Validation score: 0.846188
Iteration 190, loss = 6361104.47362944
Validation score: 0.845823
Iteration 191, loss = 6341696.53136560
Validation score: 0.841659
Iteration 192, loss = 6341439.85671002
Validation score: 0.846074
Iteration 193, loss = 6304548.95025590
Validation score: 0.847602
Iteration 194, loss = 6298884.09025467
Validation score: 0.846461
Iteration 195, loss = 6273981.11051925
Validation score: 0.845311
Iteration 196, loss = 6285290.92522016
Validation score: 0.847081
Iteration 197, loss = 6272503.94940596
Validation score: 0.845066
Iteration 198, loss = 6230909.30107946
Validation score: 0.846974
Iteration 199, loss = 6180777.26410575
Validation score: 0.844182
Iteration 200, loss = 6151991.98674017
Validation score: 0.847320
Iteration 201, loss = 6149134.58265594
Validation score: 0.846181
Iteration 202, loss = 6132153.91882299
Validation score: 0.843173
Iteration 203, loss = 6127964.43760493
Validation score: 0.846346
Iteration 204, loss = 6078171.01315818
Validation score: 0.846837
Iteration 205, loss = 6046182.57116463
Validation score: 0.848168
Iteration 206, loss = 6071676.16068507
Validation score: 0.845352
Iteration 207, loss = 6066891.90385038
Validation score: 0.846748
Iteration 208, loss = 6050499.31276165
Validation score: 0.843256
Iteration 209, loss = 6024194.66054957
Validation score: 0.846969
Iteration 210, loss = 5969899.18341726
Validation score: 0.847888
Iteration 211, loss = 5996336.51776462
Validation score: 0.847085
Iteration 212, loss = 5937558.73299762
Validation score: 0.848039
Iteration 213, loss = 5937365.09301095
Validation score: 0.847081
Iteration 214, loss = 5914019.96222466
Validation score: 0.848578
Iteration 215, loss = 5946112.47810808
Validation score: 0.848278
Iteration 216, loss = 5869308.20213573
Validation score: 0.847834
Iteration 217, loss = 5864978.97893058
Validation score: 0.848587
Iteration 218, loss = 5838065.25114901
Validation score: 0.849088
Iteration 219, loss = 5954894.23073668
Validation score: 0.849007
Iteration 220, loss = 5869603.65426934
Validation score: 0.849007
Iteration 221, loss = 5801289.20817633
Validation score: 0.848550
Iteration 222, loss = 5751286.47327793
Validation score: 0.848834
Iteration 223, loss = 5742652.38910750
Validation score: 0.848561
Iteration 224, loss = 5725449.29728938
Validation score: 0.847206
Iteration 225, loss = 5780142.45813882
Validation score: 0.841868
Iteration 226, loss = 5834868.61284549
Validation score: 0.848673
Iteration 227, loss = 5671100.39149137
Validation score: 0.848096
Iteration 228, loss = 5690176.36496302
Validation score: 0.849427
Iteration 229, loss = 5647341.07276555
Validation score: 0.847386
Iteration 230, loss = 5658170.07824034
Validation score: 0.850585
Iteration 231, loss = 5590843.44707567
Validation score: 0.847471
Iteration 232, loss = 5605103.77900182
Validation score: 0.847909
Iteration 233, loss = 5608287.02027226
Validation score: 0.848866
Iteration 234, loss = 5590446.37315735
Validation score: 0.845564
Iteration 235, loss = 5657678.47126354
Validation score: 0.842119
Iteration 236, loss = 5560720.63011357
Validation score: 0.846890
Iteration 237, loss = 5565299.93513868
Validation score: 0.850466
Iteration 238, loss = 5532931.54666608
Validation score: 0.847993
Iteration 239, loss = 5486493.71604359
Validation score: 0.846890
Iteration 240, loss = 5512203.73946710
Validation score: 0.845623
Iteration 241, loss = 5440318.74147700
Validation score: 0.850889
Iteration 242, loss = 5462077.54223346
Validation score: 0.850793
Iteration 243, loss = 5497691.42611910
Validation score: 0.850957
Iteration 244, loss = 5467730.67224969
Validation score: 0.851214
Iteration 245, loss = 5404820.11169187
Validation score: 0.850517
Iteration 246, loss = 5403301.69896546
Validation score: 0.847684
Iteration 247, loss = 5367756.55098841
Validation score: 0.851015
Iteration 248, loss = 5354614.25751060
Validation score: 0.847604
Iteration 249, loss = 5385984.98606939
Validation score: 0.850003
Iteration 250, loss = 5342164.98047749
Validation score: 0.849070
Iteration 251, loss = 5337885.02330358
Validation score: 0.845261
Iteration 252, loss = 5281324.36590551
Validation score: 0.850677
Iteration 253, loss = 5292417.19180703
Validation score: 0.852946
Iteration 254, loss = 5332022.88946415
Validation score: 0.851304
Iteration 255, loss = 5303247.17722671
Validation score: 0.850328
Iteration 256, loss = 5325422.09944612
Validation score: 0.849237
Iteration 257, loss = 5280815.78357603
Validation score: 0.848237
Iteration 258, loss = 5279973.95389928
Validation score: 0.849900
Iteration 259, loss = 5211042.08093756
Validation score: 0.850762
Iteration 260, loss = 5205795.06463621
Validation score: 0.850167
Iteration 261, loss = 5184909.69737802
Validation score: 0.850748
Iteration 262, loss = 5182324.12128589
Validation score: 0.851747
Iteration 263, loss = 5144908.33302491
Validation score: 0.846495
Iteration 264, loss = 5162532.54374215
Validation score: 0.850956
Iteration 265, loss = 5148008.65050896
Validation score: 0.851445
Iteration 266, loss = 5111831.69583124
Validation score: 0.849882
Iteration 267, loss = 5101689.40411123
Validation score: 0.850375
Iteration 268, loss = 5097863.63587342
Validation score: 0.850031
Iteration 269, loss = 5102736.45366782
Validation score: 0.850114
Iteration 270, loss = 5101189.71348711
Validation score: 0.847557
Iteration 271, loss = 5047840.44051472
Validation score: 0.839961
Iteration 272, loss = 5102435.02646137
Validation score: 0.850921
Iteration 273, loss = 5046148.41734828
Validation score: 0.851450
Iteration 274, loss = 5037792.54249179
Validation score: 0.849953
Iteration 275, loss = 5064316.25456820
Validation score: 0.849151
Iteration 276, loss = 5018658.69988172
Validation score: 0.850851
Iteration 277, loss = 4967500.68068207
Validation score: 0.851319
Iteration 278, loss = 5046055.61560260
Validation score: 0.850633
Iteration 279, loss = 4976008.80797446
Validation score: 0.852935
Iteration 280, loss = 4926055.82419320
Validation score: 0.849099
Iteration 281, loss = 4922732.45823440
Validation score: 0.848508
Iteration 282, loss = 4948679.87729670
Validation score: 0.850530
Iteration 283, loss = 4945316.61699793
Validation score: 0.848642
Iteration 284, loss = 4927506.46697937
Validation score: 0.846413
Validation score did not improve more than tol=0.000100 for 30 consecutive epochs. Stopping.
  ✓ mercedes done.
Iteration 1, loss = 90854588.38389087
Validation score: -6.847352
Iteration 2, loss = 83164715.26877514
Validation score: -4.987828
Iteration 3, loss = 39432381.96648427
Validation score: 0.158203
Iteration 4, loss = 5363395.53488712
Validation score: 0.667735
Iteration 5, loss = 3384812.01626531
Validation score: 0.726589
Iteration 6, loss = 2917678.37515272
Validation score: 0.756163
Iteration 7, loss = 2658408.37987367
Validation score: 0.776149
Iteration 8, loss = 2492053.67203407
Validation score: 0.789339
Iteration 9, loss = 2367982.36881707
Validation score: 0.798796
Iteration 10, loss = 2275882.11065194
Validation score: 0.806543
Iteration 11, loss = 2200201.20994695
Validation score: 0.812363
Iteration 12, loss = 2136849.35414256
Validation score: 0.816786
Iteration 13, loss = 2086502.74547517
Validation score: 0.821358
Iteration 14, loss = 2041941.38346615
Validation score: 0.824741
Iteration 15, loss = 2002223.98423776
Validation score: 0.827441
Iteration 16, loss = 1968777.50262862
Validation score: 0.829646
Iteration 17, loss = 1942215.14203017
Validation score: 0.832001

      Brand     N         RMSE          MAE        R²
7      opel  1912  1186.500705   800.923160  0.890541
4      ford  3272  1539.916948  1031.839193  0.893522
1   hyundai   676  1655.840881  1103.776241  0.922443
6    toyota   948  1882.418828  1031.582812  0.927032
3        vw  2118  2093.184574  1387.211827  0.929803
8     skoda   882  2803.950805  1219.084165  0.828796
0       bmw  1514  3168.423637  2047.445679  0.915191
2      audi  1489  3337.461660  2003.108940  0.919520
5  mercedes  2384  3541.420207  2315.413045  0.904723

Performance on the full dataset

| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3488.30 | 2061.42 | 0.8737 |
| ElasticNet | 4956.03 | 3039.99 | 0.7450 |
| KNR|3004.83 |1691.97 |0.9063 |
|RF | 2233.99 |1286.08 |0.9482 |
|NN | 2445.42 |1442.16 |0.9379 |

Performance on the reduced dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3611.32 | 2167.81 | 0.8646 |
| ElasticNet        | 5009.89 | 3070.02 | 0.7395 |
| KNR               | 2990.28 | 1691.12 | 0.9072 |
| RF                | **2199.79** | **1275.63** | **0.9498** |
| NN                | 2481.41 | 1464.13 | 0.9361 |

In [95]:
raise SystemExit("Stop before training the models")

SystemExit: Stop before training the models

C:\Users\liber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

## Feature Selection - Wrapper Method

In [ ]:
#WRAPPER METHOD

def rfe(train_processed, validation_processed, num_cols, step=1, n_estimators=100, random_state=42):
    
    # Filter numeric columns to those that actually exist in train_processed
    valid_num_cols = [col for col in num_cols if col in train_processed.columns]
    if len(valid_num_cols) == 0:
        raise ValueError("No valid numeric columns found in train_processed.")

    print(f"Using {len(valid_num_cols)} numeric columns for RFE:\n{valid_num_cols}")

    # Prepare numeric features and targets
    X_train_num = train_processed[valid_num_cols]
    y_train = train_processed['price']

    X_val_num = validation_processed[valid_num_cols]
    y_val = validation_processed['price']

    nof_list = np.arange(1, X_train_num.shape[1]+1)
    high_score = 0
    nof = 0
    train_score_list = []
    val_score_list = []
    features_to_select = None

    for n in nof_list:
        model = RandomForestRegressor(n_estimators=n_estimators, random_state=random_state, n_jobs=-1)
        rfe = RFE(estimator=model, n_features_to_select=n, step=step)
        X_train_rfe = rfe.fit_transform(X_train_num, y_train)
        X_val_rfe = rfe.transform(X_val_num)
        model.fit(X_train_rfe, y_train)

        train_score = model.score(X_train_rfe, y_train)
        val_score = model.score(X_val_rfe, y_val)
        train_score_list.append(train_score)
        val_score_list.append(val_score)

        if val_score > high_score:
            high_score = val_score
            nof = n
            features_to_select = pd.Series(rfe.support_, index=X_train_num.columns)

    selected_features = features_to_select[features_to_select].index.tolist()
    
    print
    print(f"\nOptimum number of features: {nof}")
    print(f"Best validation score: {high_score:.4f}")
    print("Selected features:")
    print(selected_features)

    return nof, high_score, selected_features, train_score_list, val_score_list

In [ ]:

# RFE (Random Forest) using your workflow variables
nof, best_score, selected_rfe_features, train_scores, val_scores = rfe(
    train_processed, validation_processed, num_cols
)

Using 7 numeric columns for RFE:
['mileage', 'tax', 'mpg', 'engineSize', 'paintQuality%', 'previousOwners', 'stated_no_damage']

Optimum number of features: 5
Best validation score: 0.8478
Selected features:
['mileage', 'tax', 'mpg', 'engineSize', 'paintQuality%']

## Hyperparam tuning

In [99]:
class HoldoutRandomSearch:
    def __init__(self, trainer_class, param_space, n_iter=20, optimize_metric='mae'):
        self.trainer_class = trainer_class
        self.param_space = param_space
        self.n_iter = n_iter
        self.optimize_metric = optimize_metric.lower()
        self.results = []
        self.best_params = None
        self.best_score = None
        self.best_trainer = None
        self.brand_best_configs = {}
        
    def sample_params(self):
        if isinstance(self.param_space, list):
            return random.choice(self.param_space)
        else:
            return {k: random.choice(v) for k, v in self.param_space.items()}
    
    def _get_param_summary(self, params):
        summary = {}
        
        if 'n_estimators' in params:
            summary['n_estimators'] = params['n_estimators']
        if 'max_depth' in params:
            summary['max_depth'] = params['max_depth']
        if 'max_features' in params:
            summary['max_features'] = params['max_features']
            
        if 'hidden_layer_sizes' in params:
            summary['hidden_layers'] = str(params['hidden_layer_sizes'])
        if 'alpha' in params:
            summary['alpha'] = params['alpha']
        if 'learning_rate_init' in params:
            summary['lr'] = params['learning_rate_init']
        if 'activation' in params:
            summary['activation'] = params['activation']
            
        return summary
    
    def run(self, X_train, y_train, X_val, y_val):
        metric_name = self.optimize_metric.upper()
        print(f"Running random search ({self.n_iter} iterations)...")
        print(f"Optimizing for: {metric_name}\n")
        
        start_time = time.time()
        brands = X_train["Brand"].unique()

        for brand in brands:
            self.brand_best_configs[brand] = {
                'score': float('inf'),
                'params': None,
                'config_num': None,
                'all_metrics': {}
            }
        
        for i in range(self.n_iter):
            iter_start = time.time()
            params = self.sample_params()
            
            print(f"\n{'='*70}")
            print(f"[{i+1}/{self.n_iter}] Testing params:")
            print(params)
            print('='*70)
            

            estimator = self.trainer_class.estimator.__class__(**params)
            trainer = BrandModelTrainer(estimator)
            trainer.fit(X_train, y_train)

            metrics = trainer.evaluate(X_val, y_val)
            rmse = metrics["RMSE"]
            mae = metrics["MAE"]
            r2 = metrics["R²"]
            
            current_score = mae if self.optimize_metric == 'mae' else rmse
            
            brand_results = {}
            for brand in brands:
                mask = X_val["Brand"] == brand
                y_true_brand = y_val[mask]
                y_pred_brand = trainer.predict(X_val[mask])
                
                brand_rmse = np.sqrt(mean_squared_error(y_true_brand, y_pred_brand))
                brand_mae = mean_absolute_error(y_true_brand, y_pred_brand)
                brand_r2 = r2_score(y_true_brand, y_pred_brand)
                
                brand_score = brand_mae if self.optimize_metric == 'mae' else brand_rmse
                
                brand_results[brand] = {
                    'score': brand_score,
                    'rmse': brand_rmse,
                    'mae': brand_mae,
                    'r2': brand_r2
                }
                
                if brand_score < self.brand_best_configs[brand]['score']:
                    self.brand_best_configs[brand]['score'] = brand_score
                    self.brand_best_configs[brand]['params'] = params.copy()
                    self.brand_best_configs[brand]['config_num'] = i + 1
                    self.brand_best_configs[brand]['all_metrics'] = {
                        'rmse': brand_rmse,
                        'mae': brand_mae,
                        'r2': brand_r2
                    }
            
            self.results.append({
                "config_num": i + 1,
                "params": params,
                "rmse": rmse,
                "mae": mae,
                "r2": r2,
                "score": current_score,
                "brand_results": brand_results
            })

            if self.best_score is None or current_score < self.best_score:
                self.best_score = current_score
                self.best_params = params
                self.best_trainer = trainer
                print(f"New best overall model ({metric_name}: {current_score:.2f})")
           

            elapsed_total = time.time() - start_time
            avg_per_iter = elapsed_total / (i + 1)
            eta = avg_per_iter * (self.n_iter - (i + 1))
            
            print(f"\nProgress: {i+1}/{self.n_iter} | Elapsed: {elapsed_total:.1f}s | ETA: ~{eta:.1f}s")
        
        print(f"SEARCH COMPLETED - FINAL RESULTS (Optimized for {metric_name})")
        
        print(f"\n Best general model:")
        print(f"  Best {metric_name}: {self.best_score:.2f}")
        
        best_result = [r for r in self.results if r['score'] == self.best_score][0]
        print(f"  RMSE: {best_result['rmse']:.2f}")
        print(f"  MAE:  {best_result['mae']:.2f}")
        print(f"  R²:   {best_result['r2']:.4f}")
        print(f"  Params: {self.best_params}")
   
        print(f"Best configuration per brand (by {metric_name})")

        
        brand_summary = []
        for brand in sorted(brands):
            config = self.brand_best_configs[brand]
            
            summary = {
                'Brand': brand,
                f'Best_{metric_name}': config['score'],
                'RMSE': config['all_metrics']['rmse'],
                'MAE': config['all_metrics']['mae'],
                'R²': config['all_metrics']['r2'],
                'Config_Num': config['config_num']
            }
            
            param_summary = self._get_param_summary(config['params'])
            summary.update(param_summary)
            
            brand_summary.append(summary)
            
            print(f"\n{brand.upper()}:")
            print(f"  Best {metric_name}: {config['score']:.2f}")
            print(f"  RMSE: {config['all_metrics']['rmse']:.2f}")
            print(f"  MAE:  {config['all_metrics']['mae']:.2f}")
            print(f"  R²:   {config['all_metrics']['r2']:.4f}")
            print(f"  Found at iteration: {config['config_num']}")
            print(f"  Best params:")
            for k, v in list(config['params'].items())[:5]:
                if k not in ['random_state', 'n_jobs', 'shuffle', 'verbose', 'warm_start']:
                    print(f"    {k}: {v}")
        
        df_summary = pd.DataFrame(brand_summary).sort_values(f'Best_{metric_name}')
  
        print(df_summary.to_string(index=False))
        
        results_df = pd.DataFrame([
            {
                'Config': r['config_num'],
                metric_name: r['score'],
                'RMSE': r['rmse'],
                'MAE': r['mae'],
                'R²': r['r2']
            }
            for r in self.results
        ]).sort_values(metric_name)
        
        print(f"ALL CONFIGURATIONS (sorted by {metric_name}):")
        print(results_df.head(10).to_string(index=False))
        
        return self.best_trainer, self.best_params, self.best_score

### Random Forest

In [103]:
base_estimator = RandomForestRegressor(random_state=69, n_jobs=-1)
trainer = BrandModelTrainer(base_estimator)

param_space_rf = {
    "n_estimators": [400, 600, 1000, 1200],
    "max_depth": [None, 10, 20, 40, 50, 60],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [0.6, 0.8, 0.9],
    "min_impurity_decrease": [0.0, 0.5, 1, 5],
    "max_samples": [0.85, 0.9, None],
    "ccp_alpha": [0.0], 
    "random_state": [69],
    "n_jobs": [-1]
}

search = HoldoutRandomSearch(
    trainer_class=trainer,
    param_space=param_space_rf,
    n_iter=10
)


best_trainer, best_params, best_rmse = search.run(X_train_filter, y_train, X_val_filter, y_val)

Running random search (10 iterations)...
Optimizing for: MAE


======================================================================
[1/10] Testing params:
{'n_estimators': 1200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.9, 'min_impurity_decrease': 0.0, 'max_samples': 0.9, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2304.25
  MAE:  1374.08
  R²:   0.9449
New best overall model (MAE: 1374.08)

Progress: 1/10 | Elapsed: 151.0s | ETA: ~1358.9s

======================================================================
[2/10] Testing params:
{'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.9, 'min_impurity_decrease': 5, 'max_samples': 0.9, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2172.23
  MAE:  1259.17
  R²:   0.9510
New best overall model (MAE: 1259.17)

Progress: 2/10 | Elapsed: 677.4s | ETA: ~2709.5s

======================================================================
[3/10] Testing params:
{'n_estimators': 1200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.9, 'min_impurity_decrease': 1, 'max_samples': None, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2448.32
  MAE:  1396.93
  R²:   0.9378

Progress: 3/10 | Elapsed: 867.4s | ETA: ~2024.0s

======================================================================
[4/10] Testing params:
{'n_estimators': 600, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.6, 'min_impurity_decrease': 0.0, 'max_samples': 0.85, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2375.76
  MAE:  1314.33
  R²:   0.9414

Progress: 4/10 | Elapsed: 1058.8s | ETA: ~1588.2s

======================================================================
[5/10] Testing params:
{'n_estimators': 1000, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.9, 'min_impurity_decrease': 5, 'max_samples': 0.9, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2386.03
  MAE:  1322.68
  R²:   0.9409

Progress: 5/10 | Elapsed: 1225.3s | ETA: ~1225.3s

======================================================================
[6/10] Testing params:
{'n_estimators': 1200, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.9, 'min_impurity_decrease': 0.5, 'max_samples': None, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2321.12
  MAE:  1381.94
  R²:   0.9441

Progress: 6/10 | Elapsed: 1380.1s | ETA: ~920.0s

======================================================================
[7/10] Testing params:
{'n_estimators': 1200, 'max_depth': 60, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.8, 'min_impurity_decrease': 0.0, 'max_samples': 0.85, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2194.75
  MAE:  1265.47
  R²:   0.9500

Progress: 7/10 | Elapsed: 1600.3s | ETA: ~685.8s

======================================================================
[8/10] Testing params:
{'n_estimators': 600, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.9, 'min_impurity_decrease': 1, 'max_samples': 0.85, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2385.18
  MAE:  1322.94
  R²:   0.9409

Progress: 8/10 | Elapsed: 1721.5s | ETA: ~430.4s

======================================================================
[9/10] Testing params:
{'n_estimators': 1000, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.6, 'min_impurity_decrease': 5, 'max_samples': None, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2342.58
  MAE:  1299.70
  R²:   0.9430

Progress: 9/10 | Elapsed: 1875.2s | ETA: ~208.4s

======================================================================
[10/10] Testing params:
{'n_estimators': 400, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.9, 'min_impurity_decrease': 0.5, 'max_samples': None, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2200.70
  MAE:  1268.95
  R²:   0.9497

Progress: 10/10 | Elapsed: 1965.9s | ETA: ~0.0s
SEARCH COMPLETED - FINAL RESULTS (Optimized for MAE)

 Best general model:
  Best MAE: 1259.17
  RMSE: 2172.23
  MAE:  1259.17
  R²:   0.9510
  Params: {'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.9, 'min_impurity_decrease': 5, 'max_samples': 0.9, 'ccp_alpha': 0.0, 'random_state': 69, 'n_jobs': -1}
Best configuration per brand (by MAE)

AUDI:
  Best MAE: 1735.41
  RMSE: 2889.57
  MAE:  1735.41
  R²:   0.9397
  Found at iteration: 2
  Best params:
    n_estimators: 1200
    max_depth: None
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: 0.9

BMW:
  Best MAE: 1722.28
  RMSE: 2759.00
  MAE:  1722.28
  R²:   0.9357
  Found at iteration: 2
  Best params:
    n_estimators: 1200
    max_depth: None
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: 0.9

FORD:
  Best MAE: 895.32
  RMSE: 1369.65
  MAE:  895.32
  R²:   0.9158
  Found at iteration: 7
  Best params:
    n_estimators: 1200
    max_depth: 60
    min_samples_split: 10
    min_samples_leaf: 1
    max_features: 0.8

HYUNDAI:
  Best MAE: 985.48
  RMSE: 1489.63
  MAE:  985.48
  R²:   0.9372
  Found at iteration: 9
  Best params:
    n_estimators: 1000
    max_depth: 40
    min_samples_split: 2
    min_samples_leaf: 4
    max_features: 0.6

MERCEDES:
  Best MAE: 1847.52
  RMSE: 2942.96
  MAE:  1847.52
  R²:   0.9342
  Found at iteration: 2
  Best params:
    n_estimators: 1200
    max_depth: None
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: 0.9

OPEL:
  Best MAE: 754.00
  RMSE: 1095.45
  MAE:  754.00
  R²:   0.9067
  Found at iteration: 7
  Best params:
    n_estimators: 1200
    max_depth: 60
    min_samples_split: 10
    min_samples_leaf: 1
    max_features: 0.8

SKODA:
  Best MAE: 1084.07
  RMSE: 2705.98
  MAE:  1084.07
  R²:   0.8406
  Found at iteration: 7
  Best params:
    n_estimators: 1200
    max_depth: 60
    min_samples_split: 10
    min_samples_leaf: 1
    max_features: 0.8

TOYOTA:
  Best MAE: 899.11
  RMSE: 1568.56
  MAE:  899.11
  R²:   0.9493
  Found at iteration: 2
  Best params:
    n_estimators: 1200
    max_depth: None
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: 0.9

VW:
  Best MAE: 1242.39
  RMSE: 1947.86
  MAE:  1242.39
  R²:   0.9392
  Found at iteration: 2
  Best params:
    n_estimators: 1200
    max_depth: None
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: 0.9
   Brand    Best_MAE        RMSE         MAE       R²  Config_Num  n_estimators  max_depth  max_features
    opel  753.997912 1095.446847  753.997912 0.906697           7          1200       60.0           0.8
    ford  895.324115 1369.650622  895.324115 0.915767           7          1200       60.0           0.8
  toyota  899.105577 1568.562553  899.105577 0.949335           2          1200        NaN           0.9
 hyundai  985.481520 1489.634517  985.481520 0.937231           9          1000       40.0           0.6
   skoda 1084.074317 2705.984436 1084.074317 0.840551           7          1200       60.0           0.8
      vw 1242.387070 1947.857993 1242.387070 0.939212           2          1200        NaN           0.9
     bmw 1722.280598 2759.002995 1722.280598 0.935693           2          1200        NaN           0.9
    audi 1735.413536 2889.571404 1735.413536 0.939672           2          1200        NaN           0.9
mercedes 1847.519375 2942.959370 1847.519375 0.934203           2          1200        NaN           0.9
ALL CONFIGURATIONS (sorted by MAE):
 Config         MAE        RMSE       R²
      2 1259.173421 2172.228366 0.951018
      7 1265.466633 2194.753886 0.949997
     10 1268.949967 2200.704336 0.949725
      9 1299.704663 2342.575021 0.943034
      4 1314.331356 2375.762999 0.941409
      5 1322.682056 2386.028673 0.940901
      8 1322.944180 2385.177976 0.940943
      1 1374.079372 2304.250268 0.944883
      6 1381.938033 2321.119391 0.944073
      3 1396.934051 2448.316435 0.937775

In [104]:
best_trainer.evaluate_by_brand(X_val, y_val)

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1111.904671  766.004723 0.903872
    ford 3272 1386.288222  903.570179 0.913708
 hyundai  676 1514.489790  987.232646 0.935119
  toyota  948 1568.562553  899.105577 0.949335
      vw 2118 1947.857993 1242.387070 0.939212
   skoda  882 2719.428060 1094.002885 0.838962
     bmw 1514 2759.002995 1722.280598 0.935693
    audi 1489 2889.571404 1735.413536 0.939672
mercedes 2384 2942.959370 1847.519375 0.934203

      Brand     N         RMSE          MAE        R²
7      opel  1912  1111.904671   766.004723  0.903872
4      ford  3272  1386.288222   903.570179  0.913708
1   hyundai   676  1514.489790   987.232646  0.935119
6    toyota   948  1568.562553   899.105577  0.949335
3        vw  2118  1947.857993  1242.387070  0.939212
8     skoda   882  2719.428060  1094.002885  0.838962
0       bmw  1514  2759.002995  1722.280598  0.935693
2      audi  1489  2889.571404  1735.413536  0.939672
5  mercedes  2384  2942.959370  1847.519375  0.934203

In [ ]:
configs = [

    {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 2, 
     'min_samples_leaf': 1, 'max_features': 0.85, 'random_state': 69, 'n_jobs': -1},
    
  
    {'n_estimators': 800, 'max_depth': 40, 'min_samples_split': 2, 
     'min_samples_leaf': 1, 'max_features': 0.8, 'random_state': 69, 'n_jobs': -1},
    
    
    {'n_estimators': 600, 'max_depth': 50, 'min_samples_split': 2, 
     'min_samples_leaf': 1, 'max_features': 0.8, 'random_state': 69, 'n_jobs': -1},
    
  
    {'n_estimators': 400, 'max_depth': 45, 'min_samples_split': 2, 
     'min_samples_leaf': 1, 'max_features': 0.9, 'random_state': 69, 'n_jobs': -1},
    

    {'n_estimators': 1000, 'max_depth': 35, 'min_samples_split': 3, 
     'min_samples_leaf': 2, 'max_features': 0.8, 'random_state': 69, 'n_jobs': -1},
    
 
    {'n_estimators': 700, 'max_depth': 40, 'min_samples_split': 3, 
     'min_samples_leaf': 1, 'max_features': 0.85, 'random_state': 69, 'n_jobs': -1},
    

    {'n_estimators': 500, 'max_depth': 60, 'min_samples_split': 2, 
     'min_samples_leaf': 1, 'max_features': 0.75, 'random_state': 69, 'n_jobs': -1},
    

    {'n_estimators': 600, 'max_depth': 40, 'min_samples_split': 5, 
     'min_samples_leaf': 1, 'max_features': 0.7, 'random_state': 69, 'n_jobs': -1},
    

    {'n_estimators': 1200, 'max_depth': 40, 'min_samples_split': 2, 
     'min_samples_leaf': 1, 'max_features': 0.8, 'random_state': 69, 'n_jobs': -1},
    

    {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 2, 
     'min_samples_leaf': 1, 'max_features': 0.8, 'random_state': 69, 'n_jobs': -1},

    {
        #'criterion': 'absolute_error',
        'n_estimators': 600,
        'max_depth': 40,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.7,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    
    {
        #'criterion': 'absolute_error',
        'n_estimators': 800,
        'max_depth': 40,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.7,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    
    {
       # 'criterion': 'absolute_error',
        'n_estimators': 600,
        'max_depth': 40,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.7,
        'min_impurity_decrease': 0.0,
        'max_samples': 0.85,  
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    
    {
        #'criterion': 'absolute_error',
        'n_estimators': 600,
        'max_depth': 40,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.7,
        'min_impurity_decrease': 1.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    
    {
        #'criterion': 'absolute_error',
        'n_estimators': 600,
        'max_depth': 40,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.8,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    
    {
       # 'criterion': 'absolute_error',
        'n_estimators': 600,
        'max_depth': 50,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.7,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    
    {
        #'criterion': 'absolute_error',
        'n_estimators': 700,
        'max_depth': 40,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.75,
        'min_impurity_decrease': 0.5,
        'max_samples': 0.9,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    

    {
        #'criterion': 'absolute_error',
        'n_estimators': 600,
        'max_depth': 40,
        'min_samples_split': 5,
        'min_samples_leaf': 2,
        'max_features': 0.7,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },

    {
        #'criterion': 'absolute_error',
        'n_estimators': 600,
        'max_depth': 45,
        'min_samples_split': 3,
        'min_samples_leaf': 1,
        'max_features': 0.7,
        'min_impurity_decrease': 5.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    },
    
    {
        #'criterion': 'absolute_error',
        'n_estimators': 1000,
        'max_depth': 45,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.8,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'ccp_alpha': 0.0,
        'random_state': 69,
        'n_jobs': -1
    }
]


best_rmse = float('inf')
best_params = None
best_trainer = None
all_results = []


for i, params in enumerate(configs, 1):
    print(f"\n{'='*70}")
    print(f"[{i}/10] Testing Configuration {i}")
    print(f"{'='*70}")
    print(f"Parameters:")
    for k, v in params.items():
        if k not in ['random_state', 'n_jobs']:
            print(f"  {k}: {v}")
    

    rf = RandomForestRegressor(**params)
    trainer = BrandModelTrainer(estimator=rf)
    

    trainer.fit(X_train_filter, y_train)
    

    val_metrics = trainer.evaluate(X_val_filter, y_val)

    result = {
        'config_num': i,
        'params': params.copy(),
        'rmse': val_metrics['RMSE'],
        'mae': val_metrics['MAE'],
        'r2': val_metrics['R²']
    }
    all_results.append(result)
    

    if val_metrics['RMSE'] < best_rmse:
        best_rmse = val_metrics['RMSE']
        best_params = params
        best_trainer = trainer
        print(" NEW BEST MODEL")



results_df = pd.DataFrame([
    {
        'Config': r['config_num'],
        'RMSE': r['rmse'],
        'MAE': r['mae'],
        'R²': r['r2'],
        'n_estimators': r['params']['n_estimators'],
        'max_depth': r['params']['max_depth'],
        'max_features': r['params']['max_features']
    }
    for r in all_results
]).sort_values('RMSE')

print("\nAll Results (sorted by RMSE):")
print(results_df.to_string(index=False))


print(f"Configuration: #{results_df.iloc[0]['Config']}")
print(f"RMSE: {best_rmse:.2f}")
print(f"\nBest Parameters:")
for k, v in best_params.items():
    if k not in ['random_state', 'n_jobs']:
        print(f"  {k}: {v}")


print(f"\n{'='*70}")
print("BEST MODEL - DETAILED EVALUATION")
print(f"{'='*70}")
best_trainer.evaluate_by_brand(X_val_filter, y_val, split_name="Validation")

======================================================================
[1/10] Testing Configuration 1
======================================================================
Parameters:
  n_estimators: 500
  max_depth: 40
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.85
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2189.30
  MAE:  1272.13
  R²:   0.9502
 NEW BEST MODEL

======================================================================
[2/10] Testing Configuration 2
======================================================================
Parameters:
  n_estimators: 800
  max_depth: 40
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.8
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2181.40
  MAE:  1268.27
  R²:   0.9506
 NEW BEST MODEL

======================================================================
[3/10] Testing Configuration 3
======================================================================
Parameters:
  n_estimators: 600
  max_depth: 50
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.8
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2181.29
  MAE:  1268.57
  R²:   0.9506
 NEW BEST MODEL

======================================================================
[4/10] Testing Configuration 4
======================================================================
Parameters:
  n_estimators: 400
  max_depth: 45
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.9
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2193.41
  MAE:  1274.86
  R²:   0.9501

======================================================================
[5/10] Testing Configuration 5
======================================================================
Parameters:
  n_estimators: 1000
  max_depth: 35
  min_samples_split: 3
  min_samples_leaf: 2
  max_features: 0.8
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2240.55
  MAE:  1281.37
  R²:   0.9479

======================================================================
[6/10] Testing Configuration 6
======================================================================
Parameters:
  n_estimators: 700
  max_depth: 40
  min_samples_split: 3
  min_samples_leaf: 1
  max_features: 0.85
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2194.89
  MAE:  1270.48
  R²:   0.9500

======================================================================
[7/10] Testing Configuration 7
======================================================================
Parameters:
  n_estimators: 500
  max_depth: 60
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.75
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2179.87
  MAE:  1267.11
  R²:   0.9507
 NEW BEST MODEL

======================================================================
[8/10] Testing Configuration 8
======================================================================
Parameters:
  n_estimators: 600
  max_depth: 40
  min_samples_split: 5
  min_samples_leaf: 1
  max_features: 0.7
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2175.07
  MAE:  1262.30
  R²:   0.9509
 NEW BEST MODEL

======================================================================
[9/10] Testing Configuration 9
======================================================================
Parameters:
  n_estimators: 1200
  max_depth: 40
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.8
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2180.52
  MAE:  1267.34
  R²:   0.9506

======================================================================
[10/10] Testing Configuration 10
======================================================================
Parameters:
  n_estimators: 600
  max_depth: None
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.8
Training models for 9 brands...

  ✓ mercedes done.
  ✓ ford done.
  ✓ opel done.
  ✓ skoda done.
  ✓ audi done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ bmw done.

Validation Set Performance (Overall):
  RMSE: 2181.29
  MAE:  1268.57
  R²:   0.9506

All Results (sorted by RMSE):
 Config        RMSE         MAE       R²  n_estimators  max_depth  max_features
      8 2175.070279 1262.301507 0.950890           600       40.0          0.70
      7 2179.865265 1267.109817 0.950673           500       60.0          0.75
      9 2180.518477 1267.336752 0.950643          1200       40.0          0.80
      3 2181.285548 1268.568038 0.950609           600       50.0          0.80
     10 2181.285548 1268.568038 0.950609           600        NaN          0.80
      2 2181.400708 1268.274128 0.950603           800       40.0          0.80
      1 2189.303119 1272.125307 0.950245           500       40.0          0.85
      4 2193.409654 1274.856130 0.950058           400       45.0          0.90
      6 2194.885861 1270.483796 0.949991           700       40.0          0.85
      5 2240.552409 1281.371370 0.947888          1000       35.0          0.80
Configuration: #8.0
RMSE: 2175.07

Best Parameters:
  n_estimators: 600
  max_depth: 40
  min_samples_split: 5
  min_samples_leaf: 1
  max_features: 0.7

======================================================================
BEST MODEL - DETAILED EVALUATION
======================================================================

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1912 1100.085079  759.352091 0.905905
    ford 3272 1382.574221  901.469981 0.914170
 hyundai  676 1465.116593  968.086540 0.939281
  toyota  948 1606.752309  912.695746 0.946838
      vw 2118 1930.362238 1238.666120 0.940299
   skoda  882 2712.636379 1085.090500 0.839766
     bmw 1514 2721.503842 1716.882855 0.937429
    audi 1489 2931.014349 1772.308270 0.937929
mercedes 2384 2970.204540 1862.687096 0.932979

      Brand     N         RMSE          MAE        R²
7      opel  1912  1100.085079   759.352091  0.905905
4      ford  3272  1382.574221   901.469981  0.914170
1   hyundai   676  1465.116593   968.086540  0.939281
6    toyota   948  1606.752309   912.695746  0.946838
3        vw  2118  1930.362238  1238.666120  0.940299
8     skoda   882  2712.636379  1085.090500  0.839766
0       bmw  1514  2721.503842  1716.882855  0.937429
2      audi  1489  2931.014349  1772.308270  0.937929
5  mercedes  2384  2970.204540  1862.687096  0.932979

In [ ]:
raise SystemExit("Stop before training the models")

## Predictions

In [ ]:
rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=20,
    min_samples_split=4,
    min_samples_leaf=2,
    max_features="sqrt",
    n_jobs=-1,
    random_state=42
)

trainer = BrandModelTrainer(estimator=rf)

trainer.fit(X_train, y_train)
trainer.evaluate(X_val, y_val)
trainer.evaluate_by_brand(X_val, y_val)

trainer.save_predictions(X_val, "predictions.csv")