#TODO

- prova multipli nn su 27 modelli
- function documentation
- import all the functions
- hyperparam refined
- train full df
- predictions

# Project

In [3]:
import pandas as pd
#from thefuzz import process
#from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# For imputation
#from sklearn.experimental import enable_iterative_imputer  # noqa
#from sklearn.impute import IterativeImputer

from scipy import stats
from sklearn.feature_selection import VarianceThreshold, RFE
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier #, ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor

import numpy as np
from sklearn.base import BaseEstimator, clone
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from typing import Dict

from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.neighbors import KNeighborsRegressor

from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor

import random
from copy import deepcopy
import time

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.cluster import DBSCAN

In [ ]:
import sys
import os

# Add the current directory to sys.path so we can import from Functions
if os.getcwd() not in sys.path:
    sys.path.append(os.getcwd())

# Import Preprocessing functions
from Functions.preprocessing import (
    simple_processing, 
    remove_price_outliers, 
    fit_transform_encoding, 
    decode, 
    minimal_features
)

# Import Imputation functions
from Functions.imputation import (
    mode_imputation, 
    fit_imputer, 
    apply_imputer, 
    fit_price_imputer, 
    apply_price_imputer
)

In [6]:
train_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/train.csv")

In [7]:
train_df = train_df.set_index("carID")
train_df = train_df.drop(columns=["paintQuality%"])

In [9]:
#train_df.head()

### Making sure that the model prices are not typos

In [ ]:
"""
#df_cleaned = simple_processing(train_df)
#df_cleaned = df_cleaned[df_cleaned["model"].notna()]
#df_price_model = df_cleaned[["Brand","model", "price"]].copy()

# Get the list of unique models
models = df_price_model['model'].unique()

# Loop through each model and create a boxplot
#for model in models:
sns.catplot(data=df_price_model, y='price', col='model', kind='box', col_wrap=4, height=3, sharey=False)
plt.show()"""

"# Get the list of unique models\nmodels = df_price_model['model'].unique()\n\n# Loop through each model and create a boxplot\n#for model in models:\nsns.catplot(data=df_price_model, y='price', col='model', kind='box', col_wrap=4, height=3, sharey=False)\nplt.show()"

## Data cleaning

## Workflow for Train and Validation Sets

TODO: Explanation

#### Encoding

In [10]:
# Fix typos and small numeric cleanup
df = simple_processing(train_df)

# Remove extreme price outliers
df = remove_price_outliers(df)

# Encode cateogrical columns and replace the str with int columns. Return fitted encoders for decoding at the end
df_encoded, encoders = fit_transform_encoding(df)

#### Creating the stratification column

In [11]:
# Create Categorical price column with 0 < 1 < 2 for the price
df_encoded["price_cat"] = pd.qcut(df_encoded["price"], 3, labels=False)

# Combine the 10 unique brand values (1-9 & NA) with the 3 unique price category values (0-2)
stratify_col = df_encoded["Brand_transformed"].astype(str) + "_" + df_encoded["price_cat"].astype(str)

#### Imputation and decoding

In [12]:
# Train validation split
train_split, validation_split = train_test_split(df_encoded, test_size=0.2, random_state=69, stratify=stratify_col)
# train_split, validation_split = train_test_split(df_encoded, test_size=0.2, random_state=42)

# Drop price_cat column from both splits as it would introduce data leakage
train_split = train_split.drop("price_cat", axis=1)
validation_split = validation_split.drop("price_cat", axis=1)

train_split = mode_imputation(train_split)
validation_split = mode_imputation(validation_split)

# Train imputer on train (data leakage risk thus only train on train_split)
imputer = fit_imputer(train_split)

# Apply trained imputer to both datasplits
imputed_train = apply_imputer(train_split, imputer)
imputed_validation = apply_imputer(validation_split, imputer)

# Impute the missing price values created by removing extrem outliers
# In our step to remove extrem price outliers we introduced missing values in the price column. However, in our normal imputer, which we also use for imputing the test 
# Dataset we can not fix these values as this would cause the imputer to not work on the test subset, with no price feature. 
# Thus we create a seperate price imputer to fix the missing values in the testing and validation sets. This imputer is trained on train and applied to validation
# Fit price imputer
price_imputer = fit_price_imputer(imputed_train)
# Apply price imputer
imputed_train = apply_price_imputer(imputed_train, price_imputer)
imputed_validation = apply_price_imputer(imputed_validation, price_imputer)

# Decode encoded columns using the fitted encoders
train_processed = decode(imputed_train, encoders)
validation_processed = decode(imputed_validation, encoders)

c:\Users\morit\anaconda3\envs\DataMining\Lib\site-packages\sklearn\impute\_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

## Workflow for Cleaning Testing Dataset

We use all the information available from the training data sets (train and validation splits) to fit imputers and preprocess the testing dataset. This should create a scenario as close to real world deployment as possible, where we use our existing data to process new data entries.

In [13]:
test_df = pd.read_csv("https://raw.githubusercontent.com/LiberoBiagi/ML_Nova_IMS_25-26/refs/heads/main/data/test.csv")

In [14]:
test_df = test_df.set_index("carID")
test_df = test_df.drop(columns=["paintQuality%"])

### Simple pre Imputation processing of Test data

In [20]:
test = simple_processing(test_df)

test_df_encoded, test_encoders = fit_transform_encoding(test)

### Fit the full testing imputer

In [18]:
# Preprocess the full training dataframe from scratch
df = simple_processing(train_df)
df = remove_price_outliers(df)
df_encoded, encoders = fit_transform_encoding(df)
train_df_mode_imputed = mode_imputation(df_encoded)

# Train a full imputer on the all available training data
full_training_imputer = fit_imputer(train_df_mode_imputed)

c:\Users\morit\anaconda3\envs\DataMining\Lib\site-packages\sklearn\impute\_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

### Apply the full imputer to the testing data

In [23]:
#df_encoded_no_price = test_df_imputed.drop(["price", "price_cat"], axis=1)

# Apply imputer trained on testing data
test_df_imputed = apply_imputer(test_df_encoded, full_training_imputer)

test_processed = decode(test_df_imputed, test_encoders)

# MARCEL PART

In [24]:
train_val_models = set(pd.concat([train_processed, validation_processed])["model"].unique())
test_models = set(test_processed["model"].unique())

missing_models = train_val_models - test_models

In [25]:
list(missing_models)

['s8',
 'streetka',
 'getz',
 'ranger',
 '200',
 'accent',
 'caddy maxi',
 '230',
 'escort',
 'urban cruiser',
 'verso-s',
 '220',
 'kadjar',
 'a2']

## Feature Engineering

In [26]:
train_processed.index = train_processed.index.astype(int)
validation_processed.index = validation_processed.index.astype(int)

In [27]:
X_train = train_processed
X_val = validation_processed

In [28]:
def minimal_features(df):
    df = df.copy()
    df['age'] = 2020 - df['year']
    df = df.drop(columns=["year"])
    df['mileage_per_year'] = df['mileage'] / (df['age'] + 1)
    df['efficiency_ratio'] = df['mpg'] / (df['engineSize'] + 0.1)
    df['age_mileage'] = df['age'] * df['mileage'] / 100000

    return df

In [29]:
X_train = minimal_features(X_train)
X_val = minimal_features(X_val)

In [30]:
model_mean_price = X_train.groupby('model')['price'].mean() 
X_train['model_mean_price'] = X_train['model'].map(model_mean_price) 
X_val['model_mean_price'] = X_val['model'].map(model_mean_price)

In [31]:
X_train = X_train.drop(columns=["model"])
X_val = X_val.drop(columns=["model"])

In [32]:
y_train = X_train['price']
y_val = X_val['price']

In [33]:
X_train = X_train.drop(columns=['price'])

X_val = X_val.drop(columns=['price'])

In [34]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60778 entries, 0 to 60777
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           60778 non-null  int64
 1   tax               60778 non-null  int64
 2   mpg               60778 non-null  float64
 3   engineSize        60778 non-null  float64
 4   previousOwners    60778 non-null  int64
 5   stated_no_damage  60778 non-null  float64
 6   Brand             60778 non-null  object
 7   transmission      60778 non-null  object
 8   fuelType          60778 non-null  object
 9   age               60778 non-null  int64
 10  mileage_per_year  60778 non-null  float64
 11  efficiency_ratio  60778 non-null  float64
 12  age_mileage       60778 non-null  float64
 13  model_mean_price  60778 non-null  float64
dtypes: float64(7), int64(4), object(3)
memory usage: 6.5+ MB

In [35]:
X_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15195 entries, 0 to 15194
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           15195 non-null  int64
 1   tax               15195 non-null  int64
 2   mpg               15195 non-null  float64
 3   engineSize        15195 non-null  float64
 4   previousOwners    15195 non-null  int64
 5   stated_no_damage  15195 non-null  float64
 6   Brand             15195 non-null  object
 7   transmission      15195 non-null  object
 8   fuelType          15195 non-null  object
 9   age               15195 non-null  int64
 10  mileage_per_year  15195 non-null  float64
 11  efficiency_ratio  15195 non-null  float64
 12  age_mileage       15195 non-null  float64
 13  model_mean_price  15195 non-null  float64
dtypes: float64(7), int64(4), object(3)
memory usage: 1.6+ MB

In [36]:
y_train.info()

<class 'pandas.core.series.Series'>
RangeIndex: 60778 entries, 0 to 60777
Series name: price
Non-Null Count  Dtype
--------------  -----
60778 non-null  float64
dtypes: float64(1)
memory usage: 475.0 KB

In [37]:
y_val.info()

<class 'pandas.core.series.Series'>
RangeIndex: 15195 entries, 0 to 15194
Series name: price
Non-Null Count  Dtype
--------------  -----
15195 non-null  float64
dtypes: float64(1)
memory usage: 118.8 KB

## Test of the models on the full dataset

In [38]:
class BrandModelTrainer:
    def __init__(self, estimator):
        self.estimator = estimator
        self.brand_models = {}
        self.feature_cols = None

    def fit(self, X_train, y_train):
        self.feature_cols = [c for c in X_train.columns if c != "Brand"]
        print(f"Training models for {len(X_train['Brand'].unique())} brands...\n")

        for brand in X_train["Brand"].unique():
            mask = X_train["Brand"] == brand
            Xb = X_train.loc[mask, self.feature_cols]
            yb = y_train[mask]

            numeric_cols = Xb.select_dtypes(include=["int64", "int32" ,"float64"]).columns.tolist()
            categorical_cols = Xb.select_dtypes(include=["object", "category"]).columns.tolist()

            preprocessor = ColumnTransformer([
                ("num", RobustScaler(), numeric_cols),
                ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
            ])

            model = Pipeline([
                ("preprocess", preprocessor),
                ("estimator", clone(self.estimator))
            ])

            model.fit(Xb, yb)
            self.brand_models[brand] = model
            print(f"  ✓ {brand} done.")

        return self

    def predict(self, X):
        preds = np.zeros(len(X))
        for brand, model in self.brand_models.items():
            mask = X["Brand"] == brand
            if mask.sum() == 0:
                continue
            Xb = X.loc[mask, self.feature_cols]
            preds[mask] = model.predict(Xb)
        return preds

    def evaluate_train(self, X_train, y_train):
        y_pred = self.predict(X_train)
        rmse = np.sqrt(mean_squared_error(y_train, y_pred))
        mae = mean_absolute_error(y_train, y_pred)
        r2 = r2_score(y_train, y_pred)
        print("\nTraining Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    def evaluate(self, X_val, y_val):
        y_pred = self.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, y_pred))
        mae = mean_absolute_error(y_val, y_pred)
        r2 = r2_score(y_val, y_pred)
        print("\nValidation Set Performance (Overall):")
        print(f"  RMSE: {rmse:.2f}")
        print(f"  MAE:  {mae:.2f}")
        print(f"  R²:   {r2:.4f}")
        return {"RMSE": rmse, "MAE": mae, "R²": r2}

    def evaluate_by_brand(self, X, y, split_name="Validation"):
        y_pred = self.predict(X)
        results = []
        for brand in X["Brand"].unique():
            mask = X["Brand"] == brand
            y_true_b = y[mask]
            y_pred_b = y_pred[mask]
            rmse = np.sqrt(mean_squared_error(y_true_b, y_pred_b))
            mae = mean_absolute_error(y_true_b, y_pred_b)
            r2 = r2_score(y_true_b, y_pred_b)
            results.append({"Brand": brand, "N": len(y_true_b), "RMSE": rmse, "MAE": mae, "R²": r2})
        df = pd.DataFrame(results).sort_values("RMSE")
        print(f"\n{split_name} Performance per Brand:")
        print(df.to_string(index=False))
        return df

    def evaluate_train_by_brand(self, X_train, y_train):
        return self.evaluate_by_brand(X_train, y_train, split_name="Training")
    
    def save_predictions(self, X, path):
        preds = self.predict(X)
        df = pd.DataFrame({
            "CarID": X["CarID"].values,
            "price": preds
        })
        df.to_csv(path, index=False)
        print(f"File salvato in: {path}")
        return df

In [41]:
#raise SystemExit("Stop before training the models")

### Linear Regression

In [42]:
LR = LinearRegression()
trainer = BrandModelTrainer(LR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 3451.10
  MAE:  2146.54
  R²:   0.8706

Validation Set Performance (Overall):
  RMSE: 3378.60
  MAE:  2146.61
  R²:   0.8741

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7640 1820.940267 1258.038406 0.739457
    ford 13110 2115.475577 1486.041527 0.802222
   skoda  3504 2160.162219 1501.938959 0.875942
 hyundai  2724 2423.738071 1651.687723 0.838554
  toyota  3776 2424.533705 1488.493680 0.846946
      vw  8479 3164.500884 2106.312660 0.831688
    audi  5971 4468.931440 2912.149730 0.853660
     bmw  6037 4555.101513 3095.915974 0.839049
mercedes  9537 5179.988218 3360.414584 0.760750

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1893.012996 1299.110166 0.717565
   skoda  881 2240.480606 1535.947815 0.868385
 hyundai  687 2243.184900 1621.896771 0.853502
    ford 3278 2246.715780 1490.218126 0.777431
  toyota  940 2768.807529 1582.394431 0.830498
      vw 2125 3083.038407 2135.915540 0.842650
    audi 1490 4272.881130 2859.099780 0.857222
     bmw 1505 4456.642789 3027.288735 0.845313
mercedes 2382 4921.308969 3335.661848 0.778288

      Brand     N         RMSE          MAE        R²
7      opel  1907  1893.012996  1299.110166  0.717565
8     skoda   881  2240.480606  1535.947815  0.868385
5   hyundai   687  2243.184900  1621.896771  0.853502
1      ford  3278  2246.715780  1490.218126  0.777431
3    toyota   940  2768.807529  1582.394431  0.830498
0        vw  2125  3083.038407  2135.915540  0.842650
6      audi  1490  4272.881130  2859.099780  0.857222
2       bmw  1505  4456.642789  3027.288735  0.845313
4  mercedes  2382  4921.308969  3335.661848  0.778288

### Decision Tree

In [43]:
Tree = DecisionTreeRegressor(criterion="absolute_error")
trainer = BrandModelTrainer(Tree)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)        # Performance VALID

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 104.41
  MAE:  5.77
  R²:   0.9999

Validation Set Performance (Overall):
  RMSE: 2717.14
  MAE:  1627.71
  R²:   0.9186

Training Performance per Brand:
   Brand     N       RMSE       MAE       R²
  toyota  3776  36.498308  1.571769 0.999965
    ford 13110  59.143592  3.164760 0.999845
      vw  8479  71.144767  4.987027 0.999915
   skoda  3504  81.232575  3.905251 0.999825
    audi  5971  91.272020  4.119578 0.999939
    opel  7640 115.867908 10.034293 0.998945
 hyundai  2724 122.123981  7.596549 0.999590
     bmw  6037 124.888708  3.789631 0.999879
mercedes  9537 164.661451 10.760931 0.999758

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1534.792612 1030.244288 0.814343
 hyundai  687 1732.147224 1182.071665 0.912648
  toyota  940 1869.821695 1186.005952 0.922698
    ford 3278 1882.128912 1152.855623 0.843805
   skoda  881 2021.426015 1365.042160 0.892863
      vw 2125 2552.563894 1607.347802 0.892140
    audi 1490 3481.589306 2234.856538 0.905207
mercedes 2382 3679.842512 2356.913161 0.876039
     bmw 1505 3906.644091 2325.608900 0.881137

      Brand     N         RMSE          MAE        R²
7      opel  1907  1534.792612  1030.244288  0.814343
5   hyundai   687  1732.147224  1182.071665  0.912648
3    toyota   940  1869.821695  1186.005952  0.922698
1      ford  3278  1882.128912  1152.855623  0.843805
8     skoda   881  2021.426015  1365.042160  0.892863
0        vw  2125  2552.563894  1607.347802  0.892140
6      audi  1490  3481.589306  2234.856538  0.905207
4  mercedes  2382  3679.842512  2356.913161  0.876039
2       bmw  1505  3906.644091  2325.608900  0.881137

### KNR

In [44]:
KNR = KNeighborsRegressor()
trainer = BrandModelTrainer(KNR)

# fit
trainer.fit(X_train, y_train)

# performance overall
trainer.evaluate_train(X_train, y_train)
trainer.evaluate(X_val, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train, y_train)
trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 2087.10
  MAE:  1278.17
  R²:   0.9527

Validation Set Performance (Overall):
  RMSE: 2602.17
  MAE:  1607.67
  R²:   0.9253

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7640 1053.369568  709.972862 0.912814
    ford 13110 1257.785857  861.041191 0.930084
  toyota  3776 1356.807409  860.440746 0.952068
 hyundai  2724 1581.592342 1002.412886 0.931254
   skoda  3504 1586.397607 1136.117614 0.933092
      vw  8479 1942.281431 1310.870678 0.936594
mercedes  9537 2831.116625 1838.563952 0.928532
    audi  5971 2906.105145 1816.370438 0.938116
     bmw  6037 2993.330574 1907.752829 0.930497

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1413.309166  945.040416 0.842571
    ford 3278 1654.822606 1062.651280 0.879254
 hyundai  687 1681.360294 1156.872522 0.917696
   skoda  881 1823.152122 1344.157726 0.912850
  toyota  940 1991.106210 1135.496156 0.912345
      vw 2125 2347.034894 1639.854301 0.908810
    audi 1490 3325.835116 2230.596571 0.913499
     bmw 1505 3602.446882 2343.213821 0.898927
mercedes 2382 3766.317872 2418.907461 0.870144

      Brand     N         RMSE          MAE        R²
7      opel  1907  1413.309166   945.040416  0.842571
1      ford  3278  1654.822606  1062.651280  0.879254
5   hyundai   687  1681.360294  1156.872522  0.917696
8     skoda   881  1823.152122  1344.157726  0.912850
3    toyota   940  1991.106210  1135.496156  0.912345
0        vw  2125  2347.034894  1639.854301  0.908810
6      audi  1490  3325.835116  2230.596571  0.913499
2       bmw  1505  3602.446882  2343.213821  0.898927
4  mercedes  2382  3766.317872  2418.907461  0.870144

### Random Forest

In [45]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train, y_train)


rf_trainer.evaluate_train(X_train, y_train)
rf_trainer.evaluate(X_val, y_val)

rf_trainer.evaluate_train_by_brand(X_train, y_train)
rf_trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 778.75
  MAE:  468.95
  R²:   0.9934

Validation Set Performance (Overall):
  RMSE: 2027.75
  MAE:  1254.55
  R²:   0.9547

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7640  467.466688 300.273072 0.982829
    ford 13110  507.914036 343.069032 0.988599
  toyota  3776  548.127567 334.022290 0.992177
 hyundai  2724  610.205448 371.660006 0.989767
   skoda  3504  624.784356 410.416263 0.989622
      vw  8479  716.999618 455.181956 0.991359
    audi  5971 1010.132487 628.499576 0.992523
     bmw  6037 1051.525778 641.963074 0.991423
mercedes  9537 1081.936465 682.631900 0.989562

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1261.061787  826.756821 0.874662
 hyundai  687 1265.098545  892.610998 0.953404
  toyota  940 1393.624389  927.351962 0.957058
   skoda  881 1434.187029 1015.580090 0.946070
    ford 3278 1438.352141  915.406146 0.908778
      vw 2125 1864.178800 1221.533862 0.942471
    audi 1490 2562.367951 1682.489444 0.948654
     bmw 1505 2606.440047 1674.686016 0.947090
mercedes 2382 2936.111831 1881.960610 0.921083

      Brand     N         RMSE          MAE        R²
7      opel  1907  1261.061787   826.756821  0.874662
5   hyundai   687  1265.098545   892.610998  0.953404
3    toyota   940  1393.624389   927.351962  0.957058
8     skoda   881  1434.187029  1015.580090  0.946070
1      ford  3278  1438.352141   915.406146  0.908778
0        vw  2125  1864.178800  1221.533862  0.942471
6      audi  1490  2562.367951  1682.489444  0.948654
2       bmw  1505  2606.440047  1674.686016  0.947090
4  mercedes  2382  2936.111831  1881.960610  0.921083

### Neural Network

In [46]:
from sklearn.neural_network import MLPRegressor

mlp_deep = MLPRegressor(
    hidden_layer_sizes=(256, 128, 64),  
    activation='relu',
    solver='adam',
    alpha=0.0001,  
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=2000,
    batch_size=256,
    random_state=69,
    early_stopping=True,
    n_iter_no_change=30,  
    validation_fraction=0.15,
    verbose=True
)

mlp_trainer = BrandModelTrainer(mlp_deep)


mlp_trainer.fit(X_train, y_train)


mlp_trainer.evaluate_train(X_train, y_train)
mlp_trainer.evaluate(X_val, y_val)


mlp_trainer.evaluate_train_by_brand(X_train, y_train)
mlp_trainer.evaluate_by_brand(X_val, y_val)

Training models for 9 brands...

Iteration 1, loss = 60111864.13044062
Validation score: -7.709747
Iteration 2, loss = 59282110.35702281
Validation score: -7.419917
Iteration 3, loss = 54952942.34602675
Validation score: -6.231930
Iteration 4, loss = 42148467.32360731
Validation score: -3.543174
Iteration 5, loss = 21787892.62978505
Validation score: -0.725817
Iteration 6, loss = 8364469.90237840
Validation score: 0.275050
Iteration 7, loss = 5086909.91066059
Validation score: 0.428377
Iteration 8, loss = 4129072.72753506
Validation score: 0.501465
Iteration 9, loss = 3456362.85398503
Validation score: 0.565016
Iteration 10, loss = 3055046.94756908
Validation score: 0.602447
Iteration 11, loss = 2754357.85856672
Validation score: 0.631723
Iteration 12, loss = 2493046.44782003
Validation score: 0.654691
Iteration 13, loss = 2297959.17005230
Validation score: 0.672515
Iteration 14, loss = 2142533.92213469
Validation score: 0.684756
Iteration 15, loss = 2023008.35796549
Validation score: 0.695291
Iteration 16, loss = 1924636.21670683
Validation score: 0.700712
Iteration 17, loss = 1851187.22290499
Validation score: 0.707095
Iteration 18, loss = 1790669.10029678
Validation score: 0.709515
Iteration 19, loss = 1741256.11508387
Validation score: 0.713901
Iteration 20, loss = 1703447.07777402
Validation score: 0.715439
Iteration 21, loss = 1669608.01720006
Validation score: 0.716696
Iteration 22, loss = 1645985.59417582
Validation score: 0.717691
Iteration 23, loss = 1622304.87893961
Validation score: 0.718518
Iteration 24, loss = 1604571.50901463
Validation score: 0.719939
Iteration 25, loss = 1587964.94774073
Validation score: 0.719769
Iteration 26, loss = 1578753.76146928
Validation score: 0.719311
Iteration 27, loss = 1570065.27826693
Validation score: 0.720182
Iteration 28, loss = 1557229.66780792
Validation score: 0.721174
Iteration 29, loss = 1547507.81127079
Validation score: 0.722439
Iteration 30, loss = 1539178.71402314
Validation score: 0.722197
Iteration 31, loss = 1531570.74147548
Validation score: 0.722693
Iteration 32, loss = 1524991.49759113
Validation score: 0.723144
Iteration 33, loss = 1519400.00197579
Validation score: 0.722900
Iteration 34, loss = 1513748.36227817
Validation score: 0.723717
Iteration 35, loss = 1507988.54096734
Validation score: 0.722410
Iteration 36, loss = 1505160.10212484
Validation score: 0.724409
Iteration 37, loss = 1500442.54283790
Validation score: 0.722740
Iteration 38, loss = 1499101.09770413
Validation score: 0.725116
Iteration 39, loss = 1490249.51330700
Validation score: 0.724449
Iteration 40, loss = 1487557.90778533
Validation score: 0.725700
Iteration 41, loss = 1483201.55790362
Validation score: 0.726121
Iteration 42, loss = 1481325.24314376
Validation score: 0.722636
Iteration 43, loss = 1477430.89239437
Validation score: 0.726233
Iteration 44, loss = 1474893.07334525
Validation score: 0.726696
Iteration 45, loss = 1467637.11741924
Validation score: 0.725786
Iteration 46, loss = 1467772.13249628
Validation score: 0.726183
Iteration 47, loss = 1462293.27156191
Validation score: 0.728654
Iteration 48, loss = 1458215.53048860
Validation score: 0.727054
Iteration 49, loss = 1456414.44154379
Validation score: 0.726550
Iteration 50, loss = 1453150.50760802
Validation score: 0.728795
Iteration 51, loss = 1449207.18507902
Validation score: 0.730197
Iteration 52, loss = 1444697.28285509
Validation score: 0.729681
Iteration 53, loss = 1440577.43132414
Validation score: 0.728851
Iteration 54, loss = 1436176.02087024
Validation score: 0.729621
Iteration 55, loss = 1432826.24164884
Validation score: 0.732275
Iteration 56, loss = 1426878.79913732
Validation score: 0.730443
Iteration 57, loss = 1421778.23916469
Validation score: 0.731422
Iteration 58, loss = 1419389.28764439
Validation score: 0.733117
Iteration 59, loss = 1413514.68472674
Validation score: 0.732030
Iteration 60, loss = 1403712.82077088
Validation score: 0.733635
Iteration 61, loss = 1398677.68236748
Validation score: 0.736153
Iteration 62, loss = 1392341.29550828
Validation score: 0.734754
Iteration 63, loss = 1385342.50351427
Validation score: 0.737705
Iteration 64, loss = 1376437.88875767
Validation score: 0.737969
Iteration 65, loss = 1368605.34119218
Validation score: 0.739336
Iteration 66, loss = 1363601.21770776
Validation score: 0.737584
Iteration 67, loss = 1359051.07965870
Validation score: 0.735886
Iteration 68, loss = 1346201.95464815
Validation score: 0.741853
Iteration 69, loss = 1334163.67098954
Validation score: 0.742540
Iteration 70, loss = 1328914.08184629
Validation score: 0.741494
Iteration 71, loss = 1313933.32231412
Validation score: 0.745552
Iteration 72, loss = 1301428.61136900
Validation score: 0.744182
Iteration 73, loss = 1292838.30564866
Validation score: 0.747993
Iteration 74, loss = 1286155.83993193
Validation score: 0.749141
Iteration 75, loss = 1270247.53865257
Validation score: 0.751048
Iteration 76, loss = 1261858.07732756
Validation score: 0.752184
Iteration 77, loss = 1243430.50609963
Validation score: 0.753345
Iteration 78, loss = 1228659.05673112
Validation score: 0.753533
Iteration 79, loss = 1217894.87530295
Validation score: 0.757022
Iteration 80, loss = 1206882.96592249
Validation score: 0.757362
Iteration 81, loss = 1188981.53245221
Validation score: 0.759559
Iteration 82, loss = 1175341.10523833
Validation score: 0.759750
Iteration 83, loss = 1160693.60268049
Validation score: 0.761938
Iteration 84, loss = 1147949.72147664
Validation score: 0.762135
Iteration 85, loss = 1137948.80074721
Validation score: 0.763103
Iteration 86, loss = 1122322.03852650
Validation score: 0.766289
Iteration 87, loss = 1112767.68902426
Validation score: 0.767060
Iteration 88, loss = 1097507.60985777
Validation score: 0.767600
Iteration 89, loss = 1082479.28032652
Validation score: 0.769936
Iteration 90, loss = 1069638.13366088
Validation score: 0.769886
Iteration 91, loss = 1057469.57123737
Validation score: 0.771941
Iteration 92, loss = 1049603.78675152
Validation score: 0.769466
Iteration 93, loss = 1031229.10274762
Validation score: 0.774157
Iteration 94, loss = 1022447.55220309
Validation score: 0.776311
Iteration 95, loss = 1013856.92513233
Validation score: 0.776052
Iteration 96, loss = 1001715.20193456
Validation score: 0.777950
Iteration 97, loss = 993356.16194444
Validation score: 0.778833
Iteration 98, loss = 982664.91024628
Validation score: 0.778280
Iteration 99, loss = 976968.23220722
Validation score: 0.779794
Iteration 100, loss = 973083.44145533
Validation score: 0.778865
Iteration 101, loss = 962513.47055322
Validation score: 0.780946
Iteration 102, loss = 954664.50526256
Validation score: 0.781468
Iteration 103, loss = 947908.65805502
Validation score: 0.780171
Iteration 104, loss = 942345.06661948
Validation score: 0.781491
Iteration 105, loss = 936483.39846419
Validation score: 0.782218
Iteration 106, loss = 932287.55676379
Validation score: 0.780520
Iteration 107, loss = 926124.96623842
Validation score: 0.781201
Iteration 108, loss = 924810.50086343
Validation score: 0.783099
Iteration 109, loss = 915814.52786824
Validation score: 0.783547
Iteration 110, loss = 913228.66321273
Validation score: 0.785186
Iteration 111, loss = 908441.85293943
Validation score: 0.784258
Iteration 112, loss = 905242.66734711
Validation score: 0.783744
Iteration 113, loss = 901054.75132113
Validation score: 0.785645
Iteration 114, loss = 895188.60613810
Validation score: 0.785871
Iteration 115, loss = 891918.75987153
Validation score: 0.783671
Iteration 116, loss = 888804.28339100
Validation score: 0.785331
Iteration 117, loss = 882430.18259196
Validation score: 0.786113
Iteration 118, loss = 879923.22180013
Validation score: 0.785731
Iteration 119, loss = 875706.73746874
Validation score: 0.786223
Iteration 120, loss = 873374.98145115
Validation score: 0.784658
Iteration 121, loss = 873728.73626284
Validation score: 0.786994
Iteration 122, loss = 865946.33714822
Validation score: 0.787823
Iteration 123, loss = 860821.38741757
Validation score: 0.789084
Iteration 124, loss = 857624.54226438
Validation score: 0.789043
Iteration 125, loss = 852214.47576026
Validation score: 0.790265
Iteration 126, loss = 854252.31741567
Validation score: 0.790788
Iteration 127, loss = 848517.24408183
Validation score: 0.790072
Iteration 128, loss = 840873.88852443
Validation score: 0.790833
Iteration 129, loss = 839085.67586246
Validation score: 0.792130
Iteration 130, loss = 837393.78130530
Validation score: 0.791938
Iteration 131, loss = 835664.04044933
Validation score: 0.790959
Iteration 132, loss = 831579.32207575
Validation score: 0.792701
Iteration 133, loss = 830119.35232644
Validation score: 0.792448
Iteration 134, loss = 827331.88741869
Validation score: 0.790624
Iteration 135, loss = 822611.22214783
Validation score: 0.792377
Iteration 136, loss = 816455.92364955
Validation score: 0.792600
Iteration 137, loss = 817214.41323122
Validation score: 0.793578
Iteration 138, loss = 812310.37184304
Validation score: 0.792813
Iteration 139, loss = 809087.48283631
Validation score: 0.794333
Iteration 140, loss = 807243.57083423
Validation score: 0.793192
Iteration 141, loss = 807468.74305719
Validation score: 0.795834
Iteration 142, loss = 805192.05652863
Validation score: 0.795750
Iteration 143, loss = 801505.16681214
Validation score: 0.795264
Iteration 144, loss = 795704.26834747
Validation score: 0.796671
Iteration 145, loss = 799029.83646836
Validation score: 0.797297
Iteration 146, loss = 791915.33285346
Validation score: 0.795895
Iteration 147, loss = 789402.77648637
Validation score: 0.797110
Iteration 148, loss = 786694.44575822
Validation score: 0.795521
Iteration 149, loss = 787849.24128608
Validation score: 0.796933
Iteration 150, loss = 785435.22525333
Validation score: 0.795514
Iteration 151, loss = 787882.34136970
Validation score: 0.797722
Iteration 152, loss = 794399.68671638
Validation score: 0.798129
Iteration 153, loss = 785346.38740069
Validation score: 0.797412
Iteration 154, loss = 785243.04850457
Validation score: 0.799370
Iteration 155, loss = 776479.07668630
Validation score: 0.796204
Iteration 156, loss = 772530.43439605
Validation score: 0.799369
Iteration 157, loss = 769645.21993992
Validation score: 0.800033
Iteration 158, loss = 766952.73910045
Validation score: 0.798928
Iteration 159, loss = 765567.74854037
Validation score: 0.800591
Iteration 160, loss = 762985.64130581
Validation score: 0.796692
Iteration 161, loss = 763414.13907733
Validation score: 0.800152
Iteration 162, loss = 765168.74902397
Validation score: 0.800397
Iteration 163, loss = 761172.07667582
Validation score: 0.799304
Iteration 164, loss = 756260.54594315
Validation score: 0.799757
Iteration 165, loss = 756404.20364377
Validation score: 0.801914
Iteration 166, loss = 752952.57774634
Validation score: 0.800268
Iteration 167, loss = 751799.16882988
Validation score: 0.802133
Iteration 168, loss = 752115.46796266
Validation score: 0.799089
Iteration 169, loss = 750071.66857635
Validation score: 0.801829
Iteration 170, loss = 746271.63942072
Validation score: 0.799181
Iteration 171, loss = 745911.86930688
Validation score: 0.799336
Iteration 172, loss = 749688.74600075
Validation score: 0.802401
Iteration 173, loss = 744688.40584671
Validation score: 0.800187
Iteration 174, loss = 745649.45700220
Validation score: 0.801155
Iteration 175, loss = 741518.95866591
Validation score: 0.801293
Iteration 176, loss = 739848.50104323
Validation score: 0.801840
Iteration 177, loss = 737235.55150896
Validation score: 0.801966
Iteration 178, loss = 735647.28414848
Validation score: 0.800535
Iteration 179, loss = 731581.15819630
Validation score: 0.803089
Iteration 180, loss = 729739.77917648
Validation score: 0.803845
Iteration 181, loss = 729639.45126541
Validation score: 0.802735
Iteration 182, loss = 728877.25704124
Validation score: 0.802225
Iteration 183, loss = 731423.11116043
Validation score: 0.804111
Iteration 184, loss = 736669.43831637
Validation score: 0.801899
Iteration 185, loss = 724149.48123164
Validation score: 0.804720
Iteration 186, loss = 721344.66527720
Validation score: 0.801994
Iteration 187, loss = 723157.79243504
Validation score: 0.804481
Iteration 188, loss = 722809.55376502
Validation score: 0.803355
Iteration 189, loss = 720188.70554146
Validation score: 0.803697
Iteration 190, loss = 720893.10347229
Validation score: 0.800624
Iteration 191, loss = 717618.98877132
Validation score: 0.804239
Iteration 192, loss = 715938.93305333
Validation score: 0.804878
Iteration 193, loss = 715673.20631025
Validation score: 0.802650
Iteration 194, loss = 718516.75034661
Validation score: 0.805632
Iteration 195, loss = 717351.36476100
Validation score: 0.803526
Iteration 196, loss = 715974.46492333
Validation score: 0.805402
Iteration 197, loss = 715510.44656668
Validation score: 0.802995
Iteration 198, loss = 706367.85356134
Validation score: 0.805231
Iteration 199, loss = 714558.42780682
Validation score: 0.805711
Iteration 200, loss = 704413.27758312
Validation score: 0.806226
Iteration 201, loss = 704351.67618377
Validation score: 0.806410
Iteration 202, loss = 704457.88816517
Validation score: 0.805448
Iteration 203, loss = 704335.43585610
Validation score: 0.804566
Iteration 204, loss = 703845.48359558
Validation score: 0.802571
Iteration 205, loss = 709260.97908012
Validation score: 0.804592
Iteration 206, loss = 700499.36462184
Validation score: 0.807036
Iteration 207, loss = 699080.54756911
Validation score: 0.806524
Iteration 208, loss = 701000.00786583
Validation score: 0.807184
Iteration 209, loss = 710042.74417058
Validation score: 0.808033
Iteration 210, loss = 705122.42481908
Validation score: 0.801806
Iteration 211, loss = 700251.35809938
Validation score: 0.806958
Iteration 212, loss = 694632.07392632
Validation score: 0.808582
Iteration 213, loss = 695712.39115815
Validation score: 0.806821
Iteration 214, loss = 690405.83245603
Validation score: 0.808513
Iteration 215, loss = 689196.98364997
Validation score: 0.807915
Iteration 216, loss = 688698.42245159
Validation score: 0.808768
Iteration 217, loss = 689364.01999094
Validation score: 0.807293
Iteration 218, loss = 687050.68441299
Validation score: 0.808809
Iteration 219, loss = 685495.93946211
Validation score: 0.804876
Iteration 220, loss = 688145.95327094
Validation score: 0.808906
Iteration 221, loss = 683811.70642816
Validation score: 0.808155
Iteration 222, loss = 680222.49686633
Validation score: 0.808650
Iteration 223, loss = 682265.31494143
Validation score: 0.810054
Iteration 224, loss = 678796.63822276
Validation score: 0.809475
Iteration 225, loss = 676123.88205919
Validation score: 0.810620
Iteration 226, loss = 682089.83474630
Validation score: 0.804411
Iteration 227, loss = 688419.95711694
Validation score: 0.809241
Iteration 228, loss = 673464.68693189
Validation score: 0.809052
Iteration 229, loss = 671913.21071011
Validation score: 0.809941
Iteration 230, loss = 673746.72250288
Validation score: 0.809843
Iteration 231, loss = 670139.66407588
Validation score: 0.808598
Iteration 232, loss = 670957.91334967
Validation score: 0.810036
Iteration 233, loss = 667593.10274608
Validation score: 0.810441
Iteration 234, loss = 669057.42713334
Validation score: 0.810004
Iteration 235, loss = 670455.66155519
Validation score: 0.811277
Iteration 236, loss = 667141.59903775
Validation score: 0.807295
Iteration 237, loss = 666292.00726403
Validation score: 0.811723
Iteration 238, loss = 658858.29200582
Validation score: 0.811937
Iteration 239, loss = 660015.90679351
Validation score: 0.809515
Iteration 240, loss = 658783.49712125
Validation score: 0.811777
Iteration 241, loss = 657578.62612414
Validation score: 0.810936
Iteration 242, loss = 658537.62409471
Validation score: 0.811775
Iteration 243, loss = 654705.85576360
Validation score: 0.811404
Iteration 244, loss = 653361.74067714
Validation score: 0.812637
Iteration 245, loss = 656178.11888468
Validation score: 0.812439
Iteration 246, loss = 652276.34443724
Validation score: 0.810171
Iteration 247, loss = 655298.00119867
Validation score: 0.814194
Iteration 248, loss = 662662.53515780
Validation score: 0.812177
Iteration 249, loss = 650117.55732488
Validation score: 0.813121
Iteration 250, loss = 658694.99377166
Validation score: 0.813952
Iteration 251, loss = 649349.68842052
Validation score: 0.810659
Iteration 252, loss = 644566.29974066
Validation score: 0.811363
Iteration 253, loss = 644793.47079430
Validation score: 0.811423
Iteration 254, loss = 645217.79788559
Validation score: 0.814050
Iteration 255, loss = 641818.62056777
Validation score: 0.813867
Iteration 256, loss = 642181.22778435
Validation score: 0.813861
Iteration 257, loss = 641359.78092460
Validation score: 0.814899
Iteration 258, loss = 639651.92837204
Validation score: 0.812111
Iteration 259, loss = 638506.94942343
Validation score: 0.814345
Iteration 260, loss = 636125.74452622
Validation score: 0.813433
Iteration 261, loss = 635698.11733334
Validation score: 0.812663
Iteration 262, loss = 634667.91926187
Validation score: 0.814846
Iteration 263, loss = 637108.58238154
Validation score: 0.814064
Iteration 264, loss = 632108.71543246
Validation score: 0.815330
Iteration 265, loss = 633301.57064843
Validation score: 0.814415
Iteration 266, loss = 628955.09980167
Validation score: 0.815603
Iteration 267, loss = 629871.13778377
Validation score: 0.813347
Iteration 268, loss = 628837.48800392
Validation score: 0.813126
Iteration 269, loss = 627421.02168353
Validation score: 0.816250
Iteration 270, loss = 630573.09504454
Validation score: 0.813581
Iteration 271, loss = 638817.01625627
Validation score: 0.816288
Iteration 272, loss = 628487.24917277
Validation score: 0.814589
Iteration 273, loss = 623442.64854881
Validation score: 0.816096
Iteration 274, loss = 623825.39702875
Validation score: 0.813329
Iteration 275, loss = 619444.30552312
Validation score: 0.812683
Iteration 276, loss = 619509.54962275
Validation score: 0.814691
Iteration 277, loss = 630584.80397237
Validation score: 0.813845
Iteration 278, loss = 623303.80329354
Validation score: 0.816105
Iteration 279, loss = 621012.01279566
Validation score: 0.817128
Iteration 280, loss = 624703.32296359
Validation score: 0.816849
Iteration 281, loss = 616686.17987205
Validation score: 0.815830
Iteration 282, loss = 614163.41137101
Validation score: 0.817281
Iteration 283, loss = 615203.12675335
Validation score: 0.816191
Iteration 284, loss = 615330.38900656
Validation score: 0.817852
Iteration 285, loss = 611309.40034416
Validation score: 0.817202
Iteration 286, loss = 607778.33208780
Validation score: 0.817676
Iteration 287, loss = 608344.58946730
Validation score: 0.816549
Iteration 288, loss = 613404.42007729
Validation score: 0.814362
Iteration 289, loss = 608888.68158954
Validation score: 0.817869
Iteration 290, loss = 604214.33640418
Validation score: 0.816385
Iteration 291, loss = 607365.77725305
Validation score: 0.813157
Iteration 292, loss = 607296.19713662
Validation score: 0.817210
Iteration 293, loss = 605968.34377470
Validation score: 0.814629
Iteration 294, loss = 603478.70431976
Validation score: 0.816930
Iteration 295, loss = 603676.37343527
Validation score: 0.818748
Iteration 296, loss = 601234.79517437
Validation score: 0.817942
Iteration 297, loss = 606359.11176335
Validation score: 0.817997
Iteration 298, loss = 609454.93371184
Validation score: 0.818841
Iteration 299, loss = 616244.75229664
Validation score: 0.814261
Iteration 300, loss = 607084.13367661
Validation score: 0.820067
Iteration 301, loss = 609856.54151906
Validation score: 0.818093
Iteration 302, loss = 599681.74873393
Validation score: 0.819205
Iteration 303, loss = 593164.03401686
Validation score: 0.819639
Iteration 304, loss = 592316.55499218
Validation score: 0.817782
Iteration 305, loss = 593674.72713923
Validation score: 0.818740
Iteration 306, loss = 592885.92195517
Validation score: 0.815333
Iteration 307, loss = 592905.46291285
Validation score: 0.815599

      Brand     N         RMSE          MAE        R²
7      opel  1907  1294.647665   872.751475  0.867896
5   hyundai   687  1512.684519  1070.760884  0.933381
1      ford  3278  1571.041086  1023.167182  0.891171
8     skoda   881  1680.440120  1195.354945  0.925960
3    toyota   940  1775.131177  1048.794443  0.930329
0        vw  2125  2241.242017  1485.990807  0.916846
6      audi  1490  2987.781788  2023.078248  0.930190
2       bmw  1505  3047.281032  2044.076017  0.927679
4  mercedes  2382  3428.452434  2274.602822  0.892397

### Performance

| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3383.27 | 2156.67 | 0.8723 |
| Tree | 2784.00 | 1663.58 | 0.9135 |
| KNR|2623.89 |1599.60 |0.9232 |
|RF | 2032.89 |1258.34 |0.9539 |
|NN | 2319.24 |1466.96 |0.9400 |

## Feature selection - Filter Methods

In [47]:
df = X_train.join(y_train)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60778 entries, 0 to 60777
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mileage           60778 non-null  int64
 1   tax               60778 non-null  int64
 2   mpg               60778 non-null  float64
 3   engineSize        60778 non-null  float64
 4   previousOwners    60778 non-null  int64
 5   stated_no_damage  60778 non-null  float64
 6   Brand             60778 non-null  object
 7   transmission      60778 non-null  object
 8   fuelType          60778 non-null  object
 9   age               60778 non-null  int64
 10  mileage_per_year  60778 non-null  float64
 11  efficiency_ratio  60778 non-null  float64
 12  age_mileage       60778 non-null  float64
 13  model_mean_price  60778 non-null  float64
 14  price             60778 non-null  float64
dtypes: float64(8), int64(4), object(3)
memory usage: 7.0+ MB

In [49]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
y = df['price']

numerical_cols = df.select_dtypes(include=['int64', "int32",'float64']).columns

# Drop 'carID' and 'price'
num_cols = [col for col in numerical_cols 
            if "_transformed" not in col and col not in ['price', 'carID']]

print(num_cols)
print(categorical_cols)

['mileage', 'tax', 'mpg', 'engineSize', 'previousOwners', 'stated_no_damage', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']
['Brand', 'transmission', 'fuelType']

In [50]:
#FILTER METHOD


#ANOVA FUNCTION

def anova_for_categorical(df, y, categorical_cols):
    # Align indices between df and y
    common_idx = df.index.intersection(y.index)
    df_aligned = df.loc[common_idx]
    y_aligned = y.loc[common_idx]
    
    f_scores, p_values = [], []
    for col in df_aligned.columns:
        if col in categorical_cols:
            groups = [y_aligned[df_aligned[col] == cat] for cat in df_aligned[col].dropna().unique()]
            if len(groups) > 1 and all(len(g) > 1 for g in groups):
                f_stat, p_val = stats.f_oneway(*groups)
            else:
                f_stat, p_val = 0.0, 1.0
        else:
            if df_aligned[col].nunique() > 1:
                # Remove NaN values for correlation calculation
                valid_idx = df_aligned[col].notna() & y_aligned.notna()
                if valid_idx.sum() > 1:
                    corr = np.corrcoef(df_aligned.loc[valid_idx, col], y_aligned[valid_idx])[0, 1]
                    f_stat = corr**2 * valid_idx.sum()
                    p_val = 0.0
                else:
                    f_stat, p_val = 0.0, 1.0
            else:
                f_stat, p_val = 0.0, 1.0
        f_scores.append(f_stat)
        p_values.append(p_val)
    
    return np.array(f_scores), np.array(p_values)


def filter_method_selection(X_train, y_train, categorical_cols, num_cols,
                            top_k=None,
                            var_threshold=0.01,
                            corr_threshold=0.85):
    
    print("FILTER METHOD (Variance + Spearman Correlation + ANOVA)")
    
    # Ensure indices match
    common_idx = X_train.index.intersection(y_train.index)
    X_train = X_train.loc[common_idx]
    y_train = y_train.loc[common_idx]
    
    # Filter numerical columns that exist in X_train
    num_cols_in_X = [col for col in num_cols if col in X_train.columns]
    
    # Variance Threshold
    if num_cols_in_X:
        vt_selector = VarianceThreshold(threshold=var_threshold)
        X_num_vt = pd.DataFrame(
            vt_selector.fit_transform(X_train[num_cols_in_X]),
            columns=np.array(num_cols_in_X)[vt_selector.get_support()],
            index=X_train.index
        )
        print(f"Removed {len(num_cols_in_X) - X_num_vt.shape[1]} low-variance numeric features.")
    else:
        X_num_vt = pd.DataFrame(index=X_train.index)
    
    # Spearman Correlation
    if not X_num_vt.empty and X_num_vt.shape[1] > 1:
        corr_matrix = X_num_vt.corr(method='spearman').abs()
        upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
        to_drop = [col for col in upper.columns if any(upper[col] > corr_threshold)]
        X_num_corr = X_num_vt.drop(columns=to_drop)
        print(f"Removed {len(to_drop)} correlated numeric features (Spearman |corr| > {corr_threshold}).")
    else:
        X_num_corr = X_num_vt
    
    # Filter categorical columns that exist in X_train
    categorical_cols_in_X = [col for col in categorical_cols if col in X_train.columns]
    
    # Combine numeric + categorical
    X_filtered = pd.concat([X_num_corr, X_train[categorical_cols_in_X]], axis=1)
    
    # ANOVA F-test
    f_scores, f_pvalues = anova_for_categorical(X_filtered, y_train, categorical_cols_in_X)
    f_norm = (f_scores - f_scores.min()) / (f_scores.max() - f_scores.min() + 1e-10)
    
    results_df = pd.DataFrame({
        'feature': X_filtered.columns,
        'ANOVA_F': f_scores,
        'ANOVA_p_value': f_pvalues,
        'ANOVA_norm': f_norm,
        'type': ['categorical' if c in categorical_cols_in_X else 'numerical' for c in X_filtered.columns]
    }).sort_values('ANOVA_norm', ascending=False)
    
    if top_k is None:
        selected_features = X_filtered.columns.tolist()
    else:
        selected_features = X_filtered.columns[np.argsort(f_norm)[-top_k:]].tolist()
    
    print(f"\nFilter method selected {len(selected_features)} features")
    
    return selected_features, X_filtered[selected_features], results_df

In [51]:
y = df["price"]

df = df.drop(columns=["price"])

In [52]:

#X_train = df[num_cols]
#y_train = df['price']

# Filter method (Variance + Spearman + ANOVA)
# Define categorical and numerical columns first (if not already defined)
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
num_cols = df.select_dtypes(include=['int64',"int32", 'float64']).columns.tolist()

# Filter method with all required parameters
selected_filter, X_train_filtered, filter_df = filter_method_selection(
    df, 
    y,
    categorical_cols=categorical_cols,  # Add this
    num_cols=num_cols,                  # Add this
    top_k=None, 
    var_threshold=0.01, 
    corr_threshold=0.85
)

# Print features selected
print("\nFeatures selected by Filter Method:")
for f in selected_filter:
    print(f)

# Display feature importance scores
print("\nTop 10 Features by ANOVA Score:")
print(filter_df.head(10))

FILTER METHOD (Variance + Spearman Correlation + ANOVA)
Removed 0 low-variance numeric features.
Removed 2 correlated numeric features (Spearman |corr| > 0.85).

Filter method selected 12 features

Features selected by Filter Method:
mileage
tax
mpg
engineSize
previousOwners
stated_no_damage
age
efficiency_ratio
model_mean_price
Brand
transmission
fuelType

Top 10 Features by ANOVA Score:
             feature       ANOVA_F  ANOVA_p_value  ANOVA_norm         type
8   model_mean_price  34547.008697            0.0    1.000000    numerical
3         engineSize  22794.859457            0.0    0.659821    numerical
6                age  14620.501980            0.0    0.423206    numerical
10      transmission  13281.732054            0.0    0.384454  categorical
0            mileage  10577.242575            0.0    0.306169    numerical
1                tax   5798.312998            0.0    0.167838    numerical
2                mpg   5375.501179            0.0    0.155600    numerical
9              Brand   3199.622457            0.0    0.092616  categorical
11          fuelType   1049.389687            0.0    0.030376  categorical
7   efficiency_ratio    588.407258            0.0    0.017032    numerical

In [53]:
#raise SystemExit("Stop before training the models")

## Test models on reduced DF

In [54]:
X_train_filter = X_train[["mileage", "tax", "mpg", "engineSize", "previousOwners", "stated_no_damage", "age", "efficiency_ratio", 
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_train_filter

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model_mean_price,fuelType
0,11899,126,51.4,1.4,2,1.0,4,34.266667,opel,manual,10503.556408,petrol
1,18500,145,48.9,1.4,4,1.0,2,32.600000,audi,semi-auto,22908.439241,petrol
2,10658,145,46.3,1.5,2,1.0,1,28.937500,mercedes,semi-auto,23606.673383,petrol
3,1500,145,43.5,0.0,4,1.0,0,435.000000,audi,manual,22661.237986,petrol
4,18495,100,64.0,2.1,4,1.0,3,29.090909,mercedes,automatic,23606.673383,diesel
...,...,...,...,...,...,...,...,...,...,...,...,...
60773,14867,150,55.4,1.4,3,1.0,2,36.933333,opel,manual,8321.809541,petrol
60774,20100,145,52.3,1.2,3,1.0,2,40.230769,toyota,manual,12412.360202,petrol
60775,10498,145,68.9,1.0,0,1.0,2,62.636364,toyota,manual,8070.361947,petrol
60776,17502,145,40.4,2.0,4,1.0,3,19.238095,audi,semi-auto,30342.439331,petrol
60777,16734,145,54.3,1.4,1,1.0,2,36.200000,opel,manual,8321.809541,petrol

In [55]:
X_val_filter = X_val[["mileage", "tax", "mpg", "engineSize", "previousOwners", "stated_no_damage", "age", "efficiency_ratio", 
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_val_filter

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model_mean_price,fuelType
0,14774,145,53.3,2.0,0,1.0,1,25.380952,vw,manual,16879.259184,diesel
1,16375,150,47.9,1.6,4,1.0,4,28.176471,ford,manual,10246.530606,petrol
2,32746,265,37.2,3.0,3,0.0,4,12.000000,bmw,semi-auto,19699.821797,petrol
3,10164,145,68.9,1.5,3,1.0,1,43.062500,bmw,automatic,15827.569495,diesel
4,11407,145,80.7,1.5,2,1.0,1,50.437500,ford,manual,13395.112459,diesel
...,...,...,...,...,...,...,...,...,...,...,...,...
15190,10766,20,51.4,1.4,2,1.0,1,34.266667,opel,manual,10503.556408,petrol
15191,5000,145,48.7,2.0,1,1.0,0,23.190476,vw,semi-auto,16879.259184,diesel
15192,28056,145,60.1,2.0,0,1.0,3,28.619048,ford,manual,15778.868664,diesel
15193,25169,145,56.5,1.0,4,1.0,2,51.363636,ford,manual,10246.530606,petrol
15194,23389,145,58.9,1.5,2,0.0,3,36.812500,toyota,manual,10491.719221,petrol

### Linear Regression

In [56]:
LR = LinearRegression()
trainer = BrandModelTrainer(LR)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 3573.81
  MAE:  2222.15
  R²:   0.8613

Validation Set Performance (Overall):
  RMSE: 3519.67
  MAE:  2235.12
  R²:   0.8634

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7640 1853.243137 1263.525248 0.730132
   skoda  3504 2185.729272 1507.377371 0.872988
    ford 13110 2221.794471 1588.261416 0.781843
  toyota  3776 2442.888906 1483.777615 0.844619
 hyundai  2724 2537.793064 1708.739414 0.823002
      vw  8479 3209.605225 2119.217054 0.826856
    audi  5971 4622.986455 2990.908133 0.843397
     bmw  6037 4847.060828 3308.061684 0.817756
mercedes  9537 5337.510529 3485.881963 0.745978

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1950.044591 1321.161729 0.700290
   skoda  881 2249.534191 1530.980556 0.867319
 hyundai  687 2282.681098 1611.756547 0.848298
    ford 3278 2336.042981 1583.077034 0.759381
  toyota  940 2813.057197 1597.891923 0.825037
      vw 2125 3147.797050 2168.685325 0.835971
    audi 1490 4415.497094 2951.564753 0.847531
     bmw 1505 4801.691577 3303.615640 0.820433
mercedes 2382 5135.215991 3491.835771 0.758596

      Brand     N         RMSE          MAE        R²
7      opel  1907  1950.044591  1321.161729  0.700290
8     skoda   881  2249.534191  1530.980556  0.867319
5   hyundai   687  2282.681098  1611.756547  0.848298
1      ford  3278  2336.042981  1583.077034  0.759381
3    toyota   940  2813.057197  1597.891923  0.825037
0        vw  2125  3147.797050  2168.685325  0.835971
6      audi  1490  4415.497094  2951.564753  0.847531
2       bmw  1505  4801.691577  3303.615640  0.820433
4  mercedes  2382  5135.215991  3491.835771  0.758596

### Single tree

In [57]:
Tree = DecisionTreeRegressor(criterion="absolute_error")
trainer = BrandModelTrainer(Tree)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)        # Performance VALID

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 104.41
  MAE:  5.77
  R²:   0.9999

Validation Set Performance (Overall):
  RMSE: 2854.93
  MAE:  1655.03
  R²:   0.9101

Training Performance per Brand:
   Brand     N       RMSE       MAE       R²
  toyota  3776  36.498308  1.571769 0.999965
    ford 13110  59.143592  3.164760 0.999845
      vw  8479  71.144767  4.987027 0.999915
   skoda  3504  81.232575  3.905251 0.999825
    audi  5971  91.272020  4.119578 0.999939
    opel  7640 115.867908 10.034293 0.998945
 hyundai  2724 122.123981  7.596549 0.999590
     bmw  6037 124.888708  3.789631 0.999879
mercedes  9537 164.661451 10.760931 0.999758

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1606.384364 1041.118099 0.796619
    ford 3278 1897.636311 1187.793212 0.841221
   skoda  881 1916.737540 1297.177888 0.903673
 hyundai  687 2034.726270 1226.984328 0.879465
  toyota  940 2120.916044 1224.776553 0.900543
      vw 2125 3130.114979 1702.693199 0.837808
    audi 1490 3394.728552 2153.917612 0.909878
     bmw 1505 3521.283126 2267.880902 0.903430
mercedes 2382 4106.184337 2473.310167 0.845651

      Brand     N         RMSE          MAE        R²
7      opel  1907  1606.384364  1041.118099  0.796619
1      ford  3278  1897.636311  1187.793212  0.841221
8     skoda   881  1916.737540  1297.177888  0.903673
5   hyundai   687  2034.726270  1226.984328  0.879465
3    toyota   940  2120.916044  1224.776553  0.900543
0        vw  2125  3130.114979  1702.693199  0.837808
6      audi  1490  3394.728552  2153.917612  0.909878
2       bmw  1505  3521.283126  2267.880902  0.903430
4  mercedes  2382  4106.184337  2473.310167  0.845651

In [58]:
KNR = KNeighborsRegressor()
trainer = BrandModelTrainer(KNR)

# fit
trainer.fit(X_train_filter, y_train)

# performance overall
trainer.evaluate_train(X_train_filter, y_train)
trainer.evaluate(X_val_filter, y_val)

# performance per brand
trainer.evaluate_train_by_brand(X_train_filter, y_train)
trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 2106.90
  MAE:  1279.35
  R²:   0.9518

Validation Set Performance (Overall):
  RMSE: 2653.18
  MAE:  1617.00
  R²:   0.9224

Training Performance per Brand:
   Brand     N        RMSE         MAE       R²
    opel  7640 1053.694252  709.095485 0.912760
    ford 13110 1251.262280  850.643022 0.930808
  toyota  3776 1295.274172  827.372689 0.956317
   skoda  3504 1560.093244 1116.381197 0.935293
 hyundai  2724 1620.480566  996.822500 0.927832
      vw  8479 1877.588841 1263.898586 0.940748
    audi  5971 2901.822295 1837.330792 0.938298
mercedes  9537 2924.337715 1879.424958 0.923748
     bmw  6037 3073.882105 1958.675710 0.926706

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1445.251685  958.619872 0.835374
    ford 3278 1624.221228 1047.505393 0.883679
  toyota  940 1743.326649 1085.874875 0.932803
 hyundai  687 1762.972849 1202.259160 0.909512
   skoda  881 1786.394014 1321.542894 0.916329
      vw 2125 2353.584548 1599.852623 0.908300
    audi 1490 3448.410768 2288.695058 0.907005
     bmw 1505 3746.992595 2422.754153 0.890654
mercedes 2382 3882.664379 2452.357828 0.861997

      Brand     N         RMSE          MAE        R²
7      opel  1907  1445.251685   958.619872  0.835374
1      ford  3278  1624.221228  1047.505393  0.883679
3    toyota   940  1743.326649  1085.874875  0.932803
5   hyundai   687  1762.972849  1202.259160  0.909512
8     skoda   881  1786.394014  1321.542894  0.916329
0        vw  2125  2353.584548  1599.852623  0.908300
6      audi  1490  3448.410768  2288.695058  0.907005
2       bmw  1505  3746.992595  2422.754153  0.890654
4  mercedes  2382  3882.664379  2452.357828  0.861997

In [59]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train_filter, y_train)


rf_trainer.evaluate_train(X_train_filter, y_train)
rf_trainer.evaluate(X_val_filter, y_val)

rf_trainer.evaluate_train_by_brand(X_train_filter, y_train)
rf_trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ audi done.
  ✓ mercedes done.
  ✓ ford done.
  ✓ bmw done.
  ✓ toyota done.
  ✓ hyundai done.
  ✓ vw done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 788.13
  MAE:  469.51
  R²:   0.9933

Validation Set Performance (Overall):
  RMSE: 2027.59
  MAE:  1256.56
  R²:   0.9547

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7640  467.382275 298.537130 0.982835
    ford 13110  508.887901 344.593448 0.988555
  toyota  3776  564.494504 337.391921 0.991703
 hyundai  2724  602.582997 367.218501 0.990021
   skoda  3504  631.736410 410.235779 0.989390
      vw  8479  706.981063 453.792085 0.991599
    audi  5971 1014.231488 627.762153 0.992462
     bmw  6037 1041.720655 638.596788 0.991582
mercedes  9537 1129.458861 689.349146 0.988625

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1907 1239.971469  818.720845 0.878819
 hyundai  687 1286.891712  884.574004 0.951785
  toyota  940 1382.206957  916.673530 0.957759
    ford 3278 1446.357182  922.507889 0.907760
   skoda  881 1456.285159 1026.730184 0.944395
      vw 2125 1867.099239 1222.317564 0.942291
    audi 1490 2540.261094 1669.125358 0.949536
     bmw 1505 2606.699005 1683.205149 0.947080
mercedes 2382 2942.758312 1896.157208 0.920725

      Brand     N         RMSE          MAE        R²
7      opel  1907  1239.971469   818.720845  0.878819
5   hyundai   687  1286.891712   884.574004  0.951785
3    toyota   940  1382.206957   916.673530  0.957759
1      ford  3278  1446.357182   922.507889  0.907760
8     skoda   881  1456.285159  1026.730184  0.944395
0        vw  2125  1867.099239  1222.317564  0.942291
6      audi  1490  2540.261094  1669.125358  0.949536
2       bmw  1505  2606.699005  1683.205149  0.947080
4  mercedes  2382  2942.758312  1896.157208  0.920725

### Neural Network

In [ ]:
from sklearn.neural_network import MLPRegressor

mlp_deep = MLPRegressor(
    hidden_layer_sizes=(256, 128, 64),  
    activation='relu',
    solver='adam',
    alpha=0.0001,  
    learning_rate_init=0.001,
    learning_rate='adaptive',
    max_iter=2000,
    batch_size=256,
    random_state=69,
    early_stopping=True,
    n_iter_no_change=30,  
    validation_fraction=0.15,
    verbose=True
)

mlp_trainer = BrandModelTrainer(mlp_deep)


mlp_trainer.fit(X_train_filter, y_train)


mlp_trainer.evaluate_train(X_train_filter, y_train)
mlp_trainer.evaluate(X_val_filter, y_val)


mlp_trainer.evaluate_train_by_brand(X_train_filter, y_train)
mlp_trainer.evaluate_by_brand(X_val_filter, y_val)

Training models for 9 brands...

Iteration 1, loss = 60223741.91105462
Validation score: -8.499781
Iteration 2, loss = 59305243.73648416
Validation score: -8.141860
Iteration 3, loss = 54311011.70361839
Validation score: -6.604598
Iteration 4, loss = 39077679.26747093
Validation score: -3.119478
Iteration 5, loss = 17349704.22868298
Validation score: -0.286623
Iteration 6, loss = 6842669.32004735
Validation score: 0.253421
Iteration 7, loss = 4574541.98373487
Validation score: 0.416557
Iteration 8, loss = 3643442.89648826
Validation score: 0.512893
Iteration 9, loss = 3102487.21743364
Validation score: 0.576590
Iteration 10, loss = 2738243.97477274
Validation score: 0.621080
Iteration 11, loss = 2430380.28119225
Validation score: 0.654328
Iteration 12, loss = 2228989.22444136
Validation score: 0.679126
Iteration 13, loss = 2072881.88185177
Validation score: 0.695507
Iteration 14, loss = 1960234.96096304
Validation score: 0.708916
Iteration 15, loss = 1877569.67398978
Validation score: 0.717944
Iteration 16, loss = 1817079.70812771
Validation score: 0.724473
Iteration 17, loss = 1770989.97629491
Validation score: 0.731251
Iteration 18, loss = 1735025.92761256
Validation score: 0.735220
Iteration 19, loss = 1705743.14376878
Validation score: 0.736931
Iteration 20, loss = 1688397.06231048
Validation score: 0.737672
Iteration 21, loss = 1669041.38927560
Validation score: 0.742939
Iteration 22, loss = 1651635.30033688
Validation score: 0.744374
Iteration 23, loss = 1636298.05051177
Validation score: 0.745666
Iteration 24, loss = 1626804.51054261
Validation score: 0.746311
Iteration 25, loss = 1616326.87946847
Validation score: 0.747652
Iteration 26, loss = 1608564.39160115
Validation score: 0.749362
Iteration 27, loss = 1600043.76506420
Validation score: 0.750765
Iteration 28, loss = 1594347.60856022
Validation score: 0.750203
Iteration 29, loss = 1589852.68954896
Validation score: 0.751865
Iteration 30, loss = 1580512.68491771
Validation score: 0.752653
Iteration 31, loss = 1576301.41971303
Validation score: 0.753293
Iteration 32, loss = 1571731.95193232
Validation score: 0.754651
Iteration 33, loss = 1569768.75691801
Validation score: 0.754490
Iteration 34, loss = 1560373.22803290
Validation score: 0.754931
Iteration 35, loss = 1556124.55509133
Validation score: 0.756344
Iteration 36, loss = 1549370.48237628
Validation score: 0.756963
Iteration 37, loss = 1545802.86234525
Validation score: 0.758436
Iteration 38, loss = 1541019.84603286
Validation score: 0.758617
Iteration 39, loss = 1536839.46594946
Validation score: 0.759544
Iteration 40, loss = 1532347.50858173
Validation score: 0.758673
Iteration 41, loss = 1528539.15515084
Validation score: 0.760578
Iteration 42, loss = 1523166.50452241
Validation score: 0.760413
Iteration 43, loss = 1518751.01496685
Validation score: 0.761716
Iteration 44, loss = 1517482.88434466
Validation score: 0.762169
Iteration 45, loss = 1509616.44409729
Validation score: 0.761522
Iteration 46, loss = 1506565.53284268
Validation score: 0.763295
Iteration 47, loss = 1499645.70154846
Validation score: 0.764514
Iteration 48, loss = 1495610.99606201
Validation score: 0.765590
Iteration 49, loss = 1492520.80119180
Validation score: 0.765787
Iteration 50, loss = 1486574.19379635
Validation score: 0.767277
Iteration 51, loss = 1481470.35353953
Validation score: 0.766939
Iteration 52, loss = 1475492.61560844
Validation score: 0.767349
Iteration 53, loss = 1477088.89737888
Validation score: 0.766929
Iteration 54, loss = 1465953.41843165
Validation score: 0.769760
Iteration 55, loss = 1462877.63417801
Validation score: 0.770169
Iteration 56, loss = 1458890.55521846
Validation score: 0.771774
Iteration 57, loss = 1449458.30762082
Validation score: 0.772071
Iteration 58, loss = 1444076.46447256
Validation score: 0.773092
Iteration 59, loss = 1439015.85271257
Validation score: 0.773656
Iteration 60, loss = 1435810.48098216
Validation score: 0.774763
Iteration 61, loss = 1428226.26429144
Validation score: 0.775768
Iteration 62, loss = 1420937.97898358
Validation score: 0.776823
Iteration 63, loss = 1414873.72058519
Validation score: 0.777427
Iteration 64, loss = 1406727.88268059
Validation score: 0.777229
Iteration 65, loss = 1400231.68795473
Validation score: 0.779142
Iteration 66, loss = 1391644.98276663
Validation score: 0.780015
Iteration 67, loss = 1385891.91742972
Validation score: 0.779259
Iteration 68, loss = 1381188.76773205
Validation score: 0.782272
Iteration 69, loss = 1370244.61827059
Validation score: 0.783882
Iteration 70, loss = 1362100.62354212
Validation score: 0.785014
Iteration 71, loss = 1350855.30770573
Validation score: 0.780487
Iteration 72, loss = 1350161.35513211
Validation score: 0.786742
Iteration 73, loss = 1334195.33486896
Validation score: 0.788301
Iteration 74, loss = 1321444.85651485
Validation score: 0.790330
Iteration 75, loss = 1312170.60348870
Validation score: 0.792934
Iteration 76, loss = 1296629.75586163
Validation score: 0.794768
Iteration 77, loss = 1283460.36872446
Validation score: 0.796964
Iteration 78, loss = 1268979.35004638
Validation score: 0.798953
Iteration 79, loss = 1256153.54220731
Validation score: 0.800985
Iteration 80, loss = 1242071.20473597
Validation score: 0.803397
Iteration 81, loss = 1223233.26786169
Validation score: 0.806254
Iteration 82, loss = 1213222.87526611
Validation score: 0.808574
Iteration 83, loss = 1192524.76770815
Validation score: 0.810533
Iteration 84, loss = 1176530.42366825
Validation score: 0.814109
Iteration 85, loss = 1160248.52001971
Validation score: 0.810274
Iteration 86, loss = 1145646.75393451
Validation score: 0.817925
Iteration 87, loss = 1128630.31558334
Validation score: 0.821565
Iteration 88, loss = 1110385.27152870
Validation score: 0.823506
Iteration 89, loss = 1097404.32518768
Validation score: 0.826392
Iteration 90, loss = 1080270.07616085
Validation score: 0.828725
Iteration 91, loss = 1071259.23036606
Validation score: 0.827165
Iteration 92, loss = 1062725.56778277
Validation score: 0.832209
Iteration 93, loss = 1047567.21775719
Validation score: 0.834066
Iteration 94, loss = 1038028.41662683
Validation score: 0.834719
Iteration 95, loss = 1025801.86531114
Validation score: 0.835867
Iteration 96, loss = 1020706.51029140
Validation score: 0.837565
Iteration 97, loss = 1006651.75303678
Validation score: 0.838932
Iteration 98, loss = 1000887.19981762
Validation score: 0.837537
Iteration 99, loss = 997994.40997695
Validation score: 0.841534
Iteration 100, loss = 989885.73502587
Validation score: 0.841694
Iteration 101, loss = 985592.22031823
Validation score: 0.842852
Iteration 102, loss = 976088.42531432
Validation score: 0.844004
Iteration 103, loss = 971009.09821829
Validation score: 0.843518
Iteration 104, loss = 968473.34753665
Validation score: 0.844354
Iteration 105, loss = 960529.23575018
Validation score: 0.846532
Iteration 106, loss = 955525.11766415
Validation score: 0.846382
Iteration 107, loss = 950240.89889348
Validation score: 0.847829
Iteration 108, loss = 948231.24972322
Validation score: 0.843914
Iteration 109, loss = 950024.26708856
Validation score: 0.847210
Iteration 110, loss = 939221.81590405
Validation score: 0.849048
Iteration 111, loss = 932292.12946564
Validation score: 0.849308
Iteration 112, loss = 929452.41743566
Validation score: 0.849198
Iteration 113, loss = 926689.40868981
Validation score: 0.850970
Iteration 114, loss = 924110.65375662
Validation score: 0.850605
Iteration 115, loss = 918867.15653286
Validation score: 0.851675
Iteration 116, loss = 914872.13987660
Validation score: 0.851278
Iteration 117, loss = 915657.72671321
Validation score: 0.849181
Iteration 118, loss = 929726.38262276
Validation score: 0.850749
Iteration 119, loss = 908103.60957919
Validation score: 0.851296
Iteration 120, loss = 905681.83523709
Validation score: 0.853138
Iteration 121, loss = 901406.45789358
Validation score: 0.853769
Iteration 122, loss = 902447.50549998
Validation score: 0.853878
Iteration 123, loss = 896887.51884009
Validation score: 0.854856
Iteration 124, loss = 896961.95039836
Validation score: 0.854335
Iteration 125, loss = 893519.75197665
Validation score: 0.855631
Iteration 126, loss = 887808.06084843
Validation score: 0.854848
Iteration 127, loss = 887534.09185292
Validation score: 0.852461
Iteration 128, loss = 887889.49594864
Validation score: 0.855823
Iteration 129, loss = 881799.72180701
Validation score: 0.855845
Iteration 130, loss = 881977.99378048
Validation score: 0.855144
Iteration 131, loss = 886575.99019413
Validation score: 0.856970
Iteration 132, loss = 876481.12913528
Validation score: 0.856392
Iteration 133, loss = 874674.77201545
Validation score: 0.856675
Iteration 134, loss = 874601.30226341
Validation score: 0.857470
Iteration 135, loss = 870803.64369032
Validation score: 0.857415
Iteration 136, loss = 866235.01653097
Validation score: 0.857657
Iteration 137, loss = 867396.55610074
Validation score: 0.857727
Iteration 138, loss = 863682.39225462
Validation score: 0.858308
Iteration 139, loss = 860560.18485941
Validation score: 0.858283
Iteration 140, loss = 860339.95436522
Validation score: 0.858163
Iteration 141, loss = 856528.62999952
Validation score: 0.858606
Iteration 142, loss = 859115.02104881
Validation score: 0.857697
Iteration 143, loss = 851919.04967082
Validation score: 0.859522
Iteration 144, loss = 852726.47757673
Validation score: 0.858077
Iteration 145, loss = 849340.28203471
Validation score: 0.859673
Iteration 146, loss = 855321.81626530
Validation score: 0.859653
Iteration 147, loss = 846783.08997198
Validation score: 0.860743
Iteration 148, loss = 847397.83367820
Validation score: 0.860695
Iteration 149, loss = 842603.12002486
Validation score: 0.860213
Iteration 150, loss = 838880.90764772
Validation score: 0.861397
Iteration 151, loss = 838120.38839069
Validation score: 0.860449
Iteration 152, loss = 839350.49613705
Validation score: 0.861837
Iteration 153, loss = 839637.92949879
Validation score: 0.861431
Iteration 154, loss = 834148.28842459
Validation score: 0.861624
Iteration 155, loss = 841178.54516977
Validation score: 0.860755
Iteration 156, loss = 839156.51030643
Validation score: 0.859272
Iteration 157, loss = 839209.90483993
Validation score: 0.862199
Iteration 158, loss = 828809.72380516
Validation score: 0.861794
Iteration 159, loss = 825404.34220268
Validation score: 0.862904
Iteration 160, loss = 826507.01579940
Validation score: 0.861581
Iteration 161, loss = 824250.98690099
Validation score: 0.862574
Iteration 162, loss = 821974.86661673
Validation score: 0.863343
Iteration 163, loss = 825599.24322425
Validation score: 0.863040
Iteration 164, loss = 820057.91977500
Validation score: 0.862983
Iteration 165, loss = 813517.55409882
Validation score: 0.863539
Iteration 166, loss = 817931.99813497
Validation score: 0.863675
Iteration 167, loss = 815403.97320859
Validation score: 0.864503
Iteration 168, loss = 812831.78513939
Validation score: 0.864237
Iteration 169, loss = 811199.49697806
Validation score: 0.864650
Iteration 170, loss = 812428.31082155
Validation score: 0.864335
Iteration 171, loss = 814682.62147437
Validation score: 0.863984
Iteration 172, loss = 807984.71172208
Validation score: 0.865257
Iteration 173, loss = 805816.86248036
Validation score: 0.864902
Iteration 174, loss = 803200.42379757
Validation score: 0.864769
Iteration 175, loss = 803155.50152776
Validation score: 0.864342
Iteration 176, loss = 799987.87016435
Validation score: 0.865300
Iteration 177, loss = 797677.02959411
Validation score: 0.866350
Iteration 178, loss = 797561.68883060
Validation score: 0.864810
Iteration 179, loss = 795339.26832633
Validation score: 0.865712
Iteration 180, loss = 792888.34154696
Validation score: 0.865025
Iteration 181, loss = 796013.71386297
Validation score: 0.866081
Iteration 182, loss = 798574.04859724
Validation score: 0.866332
Iteration 183, loss = 788449.05862421
Validation score: 0.865705
Iteration 184, loss = 787931.73966536
Validation score: 0.866874
Iteration 185, loss = 784576.89263211
Validation score: 0.867824
Iteration 186, loss = 784384.06706419
Validation score: 0.867215
Iteration 187, loss = 780015.48849847
Validation score: 0.867201
Iteration 188, loss = 782911.22140740
Validation score: 0.868379
Iteration 189, loss = 777134.85728848
Validation score: 0.869114
Iteration 190, loss = 776858.32271958
Validation score: 0.868856
Iteration 191, loss = 773775.19665138
Validation score: 0.869516
Iteration 192, loss = 776977.34920102
Validation score: 0.868081
Iteration 193, loss = 773010.89919958
Validation score: 0.868080
Iteration 194, loss = 775094.82156215
Validation score: 0.867030
Iteration 195, loss = 769219.00006623
Validation score: 0.869765
Iteration 196, loss = 770325.19410322
Validation score: 0.870880
Iteration 197, loss = 765073.50444513
Validation score: 0.870606
Iteration 198, loss = 770209.76564639
Validation score: 0.869582
Iteration 199, loss = 764648.28355233
Validation score: 0.869465
Iteration 200, loss = 760256.42858480
Validation score: 0.869576
Iteration 201, loss = 760368.27173361
Validation score: 0.872169
Iteration 202, loss = 759040.17614264
Validation score: 0.870704
Iteration 203, loss = 753632.76908724
Validation score: 0.871563
Iteration 204, loss = 757166.23266900
Validation score: 0.870886
Iteration 205, loss = 753091.52184193
Validation score: 0.872665
Iteration 206, loss = 748618.67784679
Validation score: 0.870365
Iteration 207, loss = 750558.79871097
Validation score: 0.872137
Iteration 208, loss = 745796.96543497
Validation score: 0.872522
Iteration 209, loss = 742757.94036864
Validation score: 0.871156
Iteration 210, loss = 745774.00126883
Validation score: 0.869471
Iteration 211, loss = 743565.04304586
Validation score: 0.873130
Iteration 212, loss = 740587.92933955
Validation score: 0.872859
Iteration 213, loss = 740306.19795278
Validation score: 0.874470
Iteration 214, loss = 739552.98042349
Validation score: 0.873429
Iteration 215, loss = 740444.58873092
Validation score: 0.874097
Iteration 216, loss = 737703.20327737
Validation score: 0.872312
Iteration 217, loss = 737213.27746380
Validation score: 0.873082
Iteration 218, loss = 738355.87364819
Validation score: 0.874069
Iteration 219, loss = 731186.68877970
Validation score: 0.873914
Iteration 220, loss = 728062.72562372
Validation score: 0.873455
Iteration 221, loss = 725850.76201042
Validation score: 0.874789
Iteration 222, loss = 726214.69779627
Validation score: 0.873661
Iteration 223, loss = 724609.95897491
Validation score: 0.874931
Iteration 224, loss = 722900.96346189
Validation score: 0.874611
Iteration 225, loss = 722872.05107286
Validation score: 0.874247
Iteration 226, loss = 733657.69482610
Validation score: 0.874035
Iteration 227, loss = 728699.43228991
Validation score: 0.874301
Iteration 228, loss = 719361.69638531
Validation score: 0.875605
Iteration 229, loss = 720360.19332113
Validation score: 0.874521
Iteration 230, loss = 717968.91524511
Validation score: 0.874698
Iteration 231, loss = 717262.95290832
Validation score: 0.875560
Iteration 232, loss = 720419.53721353
Validation score: 0.875025
Iteration 233, loss = 715421.73477707
Validation score: 0.874641
Iteration 234, loss = 718858.08246831
Validation score: 0.873497
Iteration 235, loss = 719242.28559970
Validation score: 0.874356
Iteration 236, loss = 716085.30810431
Validation score: 0.875952
Iteration 237, loss = 715445.46188578
Validation score: 0.877807
Iteration 238, loss = 708861.28797705
Validation score: 0.874588
Iteration 239, loss = 715301.70627388
Validation score: 0.876867
Iteration 240, loss = 712322.78654408
Validation score: 0.874836
Iteration 241, loss = 712447.85078480
Validation score: 0.875460
Iteration 242, loss = 702771.78822953
Validation score: 0.877084
Iteration 243, loss = 704964.27938138
Validation score: 0.877469
Iteration 244, loss = 703336.05410707
Validation score: 0.876158
Iteration 245, loss = 701534.73823050
Validation score: 0.876940
Iteration 246, loss = 702628.39840132
Validation score: 0.876320
Iteration 247, loss = 702784.31459746
Validation score: 0.878300
Iteration 248, loss = 699380.59963005
Validation score: 0.876134
Iteration 249, loss = 701148.76075861
Validation score: 0.878003
Iteration 250, loss = 696965.31674406
Validation score: 0.878311
Iteration 251, loss = 695840.68216466
Validation score: 0.879069
Iteration 252, loss = 695893.32417453
Validation score: 0.877352
Iteration 253, loss = 697921.31886738
Validation score: 0.878515
Iteration 254, loss = 693757.50687884
Validation score: 0.878202
Iteration 255, loss = 691216.31707164
Validation score: 0.877703
Iteration 256, loss = 692713.58301628
Validation score: 0.878403
Iteration 257, loss = 690954.58562283
Validation score: 0.878094
Iteration 258, loss = 691648.71958429
Validation score: 0.872604
Iteration 259, loss = 713024.34637689
Validation score: 0.874505
Iteration 260, loss = 700141.26448727
Validation score: 0.877893
Iteration 261, loss = 690589.72513408
Validation score: 0.879992
Iteration 262, loss = 688327.73819117
Validation score: 0.878271
Iteration 263, loss = 694249.57704028
Validation score: 0.878643
Iteration 264, loss = 695292.01197870
Validation score: 0.878367
Iteration 265, loss = 688493.77464751
Validation score: 0.880148
Iteration 266, loss = 696544.23735215
Validation score: 0.877294
Iteration 267, loss = 694389.02527651
Validation score: 0.879582
Iteration 268, loss = 691816.80006480
Validation score: 0.875393
Iteration 269, loss = 685496.07924992
Validation score: 0.877043
Iteration 270, loss = 691849.06128935
Validation score: 0.878724
Iteration 271, loss = 684311.81774560
Validation score: 0.881080
Iteration 272, loss = 686482.01553312
Validation score: 0.877209
Iteration 273, loss = 685542.19360835
Validation score: 0.878131
Iteration 274, loss = 684352.29959592
Validation score: 0.879600
Iteration 275, loss = 679671.25441174
Validation score: 0.880881
Iteration 276, loss = 675391.81621292
Validation score: 0.880363
Iteration 277, loss = 672746.55201594
Validation score: 0.878634
Iteration 278, loss = 678117.34925565
Validation score: 0.880893
Iteration 279, loss = 671192.46066215
Validation score: 0.882216
Iteration 280, loss = 670599.62209944
Validation score: 0.880362
Iteration 281, loss = 680904.55276813
Validation score: 0.880469
Iteration 282, loss = 672359.95621687
Validation score: 0.879648
Iteration 283, loss = 669567.40392796
Validation score: 0.882768
Iteration 284, loss = 672128.70526040
Validation score: 0.881069
Iteration 285, loss = 671492.51734598
Validation score: 0.882075
Iteration 286, loss = 673706.04587078
Validation score: 0.880688
Iteration 287, loss = 714287.89709176
Validation score: 0.873260
Iteration 288, loss = 684710.51935171
Validation score: 0.881245
Iteration 289, loss = 678085.20406748
Validation score: 0.882841
Iteration 290, loss = 670558.07869702
Validation score: 0.880603
Iteration 291, loss = 672866.83773170
Validation score: 0.881897
Iteration 292, loss = 662917.07082493
Validation score: 0.881322
Iteration 293, loss = 661434.69971012
Validation score: 0.880989
Iteration 294, loss = 670151.46965702
Validation score: 0.882634
Iteration 295, loss = 663633.32783965
Validation score: 0.881352
Iteration 296, loss = 662626.66181661
Validation score: 0.882614
Iteration 297, loss = 663061.89443569
Validation score: 0.883122
Iteration 298, loss = 658790.06889247
Validation score: 0.882650
Iteration 299, loss = 661873.45513951
Validation score: 0.883189
Iteration 300, loss = 664942.53169677
Validation score: 0.879298
Iteration 301, loss = 666914.10882360
Validation score: 0.881843
Iteration 302, loss = 663793.42797592
Validation score: 0.878060
Iteration 303, loss = 660398.58699195
Validation score: 0.883141
Iteration 304, loss = 657744.69187442
Validation score: 0.882633
Iteration 305, loss = 657079.21847097
Validation score: 0.882527
Iteration 306, loss = 651459.12175757
Validation score: 0.881429
Iteration 307, loss = 654779.29309598
Validation score: 0.880486

c:\Users\morit\anaconda3\envs\DataMining\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:788: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")

  ✓ vw done.
Iteration 1, loss = 120998905.52754487
Validation score: -5.229427
Iteration 2, loss = 120880361.83692554
Validation score: -5.218358
Iteration 3, loss = 120517438.54874848
Validation score: -5.186479
Iteration 4, loss = 119550014.55574410
Validation score: -5.106757
Iteration 5, loss = 117285603.36957321
Validation score: -4.933171
Iteration 6, loss = 112701052.97455740
Validation score: -4.601372
Iteration 7, loss = 104499460.94121246
Validation score: -4.041990
Iteration 8, loss = 91414734.78050460
Validation score: -3.222218
Iteration 9, loss = 73513067.36346826
Validation score: -2.205951
Iteration 10, loss = 53201145.03586544
Validation score: -1.178995
Iteration 11, loss = 34034232.89337071
Validation score: -0.311240

### Results

Performance on the full dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3383.27 | 2156.67 | 0.8723 |
| Tree | 2784.00 | 1663.58 | 0.9135 |
| KNR|2623.89 |1599.60 |0.9232 |
|RF | 2032.89 |1258.34 |0.9539 |
|NN | 2319.24 |1466.96 |0.9400 |



Performance on the reduced dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3501.39 | 2241.68 | 0.8632 |
| Tree       | 2759.39 | 1650.79 | 0.9150 |
| KNR               | 2624.75 | 1598.18 | 0.9231 |
| RF                | **2036.38** | **1254.22** | **0.9537** |
| NN                | 2337.17.41 | 1476.69 | 0.9391 |

In [ ]:
#raise SystemExit("Stop before training the models")

SystemExit: Stop before training the models

C:\Users\liber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

## Feature Selection - Wrapper Method

In [ ]:
num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()

print(num_cols)

['mileage', 'tax', 'mpg', 'engineSize', 'previousOwners', 'stated_no_damage', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']

In [ ]:
def rfe(X_train, X_val, y_train, y_val, num_cols, step=1, n_estimators=100, random_state=69):
    
    valid_num_cols = [col for col in num_cols if col in X_train.columns]
    if len(valid_num_cols) == 0:
        raise ValueError("No valid numeric columns found in X_train.")
    print(f"Using {len(valid_num_cols)} numeric columns for RFE:\n{valid_num_cols}")
    
    X_train_num = X_train[valid_num_cols]
    X_val_num = X_val[valid_num_cols]
    nof_list = np.arange(1, X_train_num.shape[1]+1)
    
    best_mae = float('inf')
    nof = 0
    train_mae_list = []
    val_mae_list = []
    features_to_select = None
    
    for n in nof_list:
        model = RandomForestRegressor(n_estimators=n_estimators, random_state=random_state, n_jobs=-1)
        rfe = RFE(estimator=model, n_features_to_select=n, step=step)
        X_train_rfe = rfe.fit_transform(X_train_num, y_train)
        X_val_rfe = rfe.transform(X_val_num)
        
        model.fit(X_train_rfe, y_train)
        
        train_pred = model.predict(X_train_rfe)
        val_pred = model.predict(X_val_rfe)
        train_mae = mean_absolute_error(y_train, train_pred)
        val_mae = mean_absolute_error(y_val, val_pred)
        
        train_mae_list.append(train_mae)
        val_mae_list.append(val_mae)
        
        if val_mae < best_mae:
            best_mae = val_mae
            nof = n
            features_to_select = pd.Series(rfe.support_, index=X_train_num.columns)
    
    selected_features = features_to_select[features_to_select].index.tolist()
    
    print(f"\nOptimum number of features: {nof}")
    print(f"Best validation MAE: {best_mae:.4f}")
    print("Selected features:")
    print(selected_features)
    
    return nof, best_mae, selected_features, train_mae_list, val_mae_list

In [ ]:
nof, best_score, selected_rfe_features, train_scores, val_scores = rfe(
    X_train, X_val, y_train, y_val, num_cols
)

Using 11 numeric columns for RFE:
['mileage', 'tax', 'mpg', 'engineSize', 'previousOwners', 'stated_no_damage', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']

Optimum number of features: 9
Best validation MAE: 1323.6319
Selected features:
['mileage', 'tax', 'mpg', 'engineSize', 'age', 'mileage_per_year', 'efficiency_ratio', 'age_mileage', 'model_mean_price']

In [ ]:
X_train_rfed = X_train[["mileage", "tax", "mpg", "engineSize", "age", "efficiency_ratio", "mileage_per_year", "age_mileage",
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_train_rfed

,mileage,tax,mpg,engineSize,age,efficiency_ratio,mileage_per_year,age_mileage,Brand,transmission,model_mean_price,fuelType
0,16326,125,51.4,1.4,3,34.266667,4081.500000,0.48978,opel,manual,10496.007929,petrol
1,12510,145,56.5,1.0,2,51.363636,4170.000000,0.25020,toyota,manual,8029.315503,petrol
2,6999,144,58.2,1.0,1,52.909091,3499.500000,0.06999,ford,manual,13441.487966,petrol
3,28465,160,43.5,2.0,3,20.714286,7116.250000,0.85395,mercedes,manual,30801.319510,petrol
4,9221,145,33.6,2.0,1,16.000000,4610.500000,0.09221,vw,semi-auto,34233.178082,electric
...,...,...,...,...,...,...,...,...,...,...,...,...
60773,21131,145,67.3,2.1,1,30.590909,10565.500000,0.21131,mercedes,semi-auto,20327.302521,diesel
60774,4722,145,50.4,1.6,1,29.647059,2361.000000,0.04722,vw,manual,22619.961912,diesel
60775,24755,0,76.3,1.6,5,44.882353,4125.833333,1.23775,audi,manual,14343.507937,diesel
60776,42000,125,57.6,2.0,5,27.428571,7000.000000,2.10000,bmw,manual,15717.953402,diesel
60777,27553,30,62.8,1.6,3,36.941176,6888.250000,0.82659,toyota,manual,12768.027027,diesel

In [ ]:
X_val_rfed = X_val[["mileage", "tax", "mpg", "engineSize", "age", "efficiency_ratio", "mileage_per_year", "age_mileage",
                          "Brand", "transmission", "model_mean_price", "fuelType"]]
X_val_rfed

,mileage,tax,mpg,engineSize,age,efficiency_ratio,mileage_per_year,age_mileage,Brand,transmission,model_mean_price,fuelType
0,5000,145,48.7,2.0,1,23.190476,2500.000000,0.05000,vw,automatic,17101.053465,diesel
1,10,145,43.5,1.4,1,29.000000,5.000000,0.00010,opel,manual,8348.382147,petrol
2,46000,125,51.4,1.0,4,46.727273,9200.000000,1.84000,ford,semi-auto,13441.487966,petrol
3,24219,20,60.1,1.2,3,46.230769,6054.750000,0.72657,vw,manual,11435.947368,petrol
4,20251,145,46.3,1.8,4,24.368421,4050.200000,0.81004,toyota,automatic,10373.418919,petrol
...,...,...,...,...,...,...,...,...,...,...,...,...
15190,33154,30,54.3,1.2,6,41.769231,4736.285714,1.98924,ford,manual,10245.037681,petrol
15191,19000,20,60.1,1.0,4,54.636364,3800.000000,0.76000,vw,manual,11435.947368,petrol
15192,3971,145,45.6,1.5,1,28.500000,1985.500000,0.03971,vw,manual,16722.731829,petrol
15193,56603,0,83.1,1.4,4,55.400000,11320.600000,2.26412,vw,manual,11435.947368,diesel
15194,24545,145,43.5,1.4,3,29.000000,6136.250000,0.73635,opel,semi-auto,12511.510798,petrol

In [ ]:
RF = RandomForestRegressor(random_state=69)
rf_trainer = BrandModelTrainer(RF)


rf_trainer.fit(X_train_rfed, y_train)


rf_trainer.evaluate_train(X_train_rfed, y_train)
rf_trainer.evaluate(X_val_rfed, y_val)

rf_trainer.evaluate_train_by_brand(X_train_rfed, y_train)
rf_trainer.evaluate_by_brand(X_val_rfed, y_val)

Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Training Set Performance (Overall):
  RMSE: 791.34
  MAE:  473.66
  R²:   0.9932

Validation Set Performance (Overall):
  RMSE: 2033.05
  MAE:  1256.58
  R²:   0.9539

Training Performance per Brand:
   Brand     N        RMSE        MAE       R²
    opel  7644  463.914285 309.235998 0.982848
    ford 13108  535.870395 345.862177 0.987429
  toyota  3775  561.716833 338.077681 0.992100
 hyundai  2724  577.270768 367.348817 0.990626
   skoda  3507  602.826087 409.353137 0.990329
      vw  8479  708.249640 454.007482 0.991500
    audi  5971 1037.789691 645.645367 0.992224
     bmw  6029 1039.159002 641.595021 0.991591
mercedes  9541 1125.371000 692.305729 0.988845

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1151.895521  786.584062 0.895455
    ford 3282 1354.041743  935.275800 0.918098
 hyundai  683 1438.914752  944.670402 0.943047
   skoda  875 1554.184116 1073.572999 0.936224
  toyota  941 1560.618769  952.116895 0.937747
      vw 2125 1904.666983 1228.593323 0.941829
    audi 1489 2602.379454 1662.530539 0.943410
     bmw 1513 2680.604426 1713.106259 0.944944
mercedes 2381 2881.876592 1833.798991 0.920858

      Brand     N         RMSE          MAE        R²
1      opel  1906  1151.895521   786.584062  0.895455
2      ford  3282  1354.041743   935.275800  0.918098
5   hyundai   683  1438.914752   944.670402  0.943047
7     skoda   875  1554.184116  1073.572999  0.936224
3    toyota   941  1560.618769   952.116895  0.937747
0        vw  2125  1904.666983  1228.593323  0.941829
6      audi  1489  2602.379454  1662.530539  0.943410
8       bmw  1513  2680.604426  1713.106259  0.944944
4  mercedes  2381  2881.876592  1833.798991  0.920858

Final Results

Performance on the full dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3383.27 | 2156.67 | 0.8723 |
| Tree | 2784.00 | 1663.58 | 0.9135 |
| KNR|2623.89 |1599.60 |0.9232 |
|RF | 2032.89 |1258.34 |0.9539 |
|NN | 2319.24 |1466.96 |0.9400 |



Performance on the reduced dataset
| *Model* | *RMSE* | *MAE* | *R²* |
|---------|--------|--------|------|
| Linear Regression | 3501.39 | 2241.68 | 0.8632 |
| Tree       | 2759.39 | 1650.79 | 0.9150 |
| KNR               | 2624.75 | 1598.18 | 0.9231 |
| RF                | **2036.38** | **1254.22** | **0.9537** |
| NN                | 2337.17.41 | 1476.69 | 0.9391 |


Random Forest on the rfed dataset

|*Model*| *RMSE*| *MAE* | *R²*|
|----|----|----|----|
|RF| 2033.05| 1256.58 | 0.9539|

## Hyperparam tuning

In [ ]:
class HoldoutRandomSearch:
    def __init__(self, trainer_class, param_space, n_iter=20, optimize_metric='mae'):
        self.trainer_class = trainer_class
        self.param_space = param_space
        self.n_iter = n_iter
        self.optimize_metric = optimize_metric.lower()
        self.results = []
        self.best_params = None
        self.best_score = None
        self.best_trainer = None
        self.brand_best_configs = {}
        
    def sample_params(self):
        if isinstance(self.param_space, list):
            return random.choice(self.param_space)
        else:
            return {k: random.choice(v) for k, v in self.param_space.items()}
    
    def _get_param_summary(self, params):
        summary = {}
        
        if 'n_estimators' in params:
            summary['n_estimators'] = params['n_estimators']
        if 'max_depth' in params:
            summary['max_depth'] = params['max_depth']
        if 'max_features' in params:
            summary['max_features'] = params['max_features']
            
        if 'hidden_layer_sizes' in params:
            summary['hidden_layers'] = str(params['hidden_layer_sizes'])
        if 'alpha' in params:
            summary['alpha'] = params['alpha']
        if 'learning_rate_init' in params:
            summary['lr'] = params['learning_rate_init']
        if 'activation' in params:
            summary['activation'] = params['activation']
            
        return summary
    
    def run(self, X_train, y_train, X_val, y_val):
        metric_name = self.optimize_metric.upper()
        print(f"Running random search ({self.n_iter} iterations)...")
        print(f"Optimizing for: {metric_name}\n")
        
        start_time = time.time()
        brands = X_train["Brand"].unique()

        for brand in brands:
            self.brand_best_configs[brand] = {
                'score': float('inf'),
                'params': None,
                'config_num': None,
                'all_metrics': {}
            }
        
        for i in range(self.n_iter):
            iter_start = time.time()
            params = self.sample_params()
            
            print(f"\n{'='*70}")
            print(f"[{i+1}/{self.n_iter}] Testing params:")
            print(params)
            print('='*70)
            

            estimator = self.trainer_class.estimator.__class__(**params)
            trainer = BrandModelTrainer(estimator)
            trainer.fit(X_train, y_train)

            metrics = trainer.evaluate(X_val, y_val)
            rmse = metrics["RMSE"]
            mae = metrics["MAE"]
            r2 = metrics["R²"]
            
            current_score = mae if self.optimize_metric == 'mae' else rmse
            
            brand_results = {}
            for brand in brands:
                mask = X_val["Brand"] == brand
                y_true_brand = y_val[mask]
                y_pred_brand = trainer.predict(X_val[mask])
                
                brand_rmse = np.sqrt(mean_squared_error(y_true_brand, y_pred_brand))
                brand_mae = mean_absolute_error(y_true_brand, y_pred_brand)
                brand_r2 = r2_score(y_true_brand, y_pred_brand)
                
                brand_score = brand_mae if self.optimize_metric == 'mae' else brand_rmse
                
                brand_results[brand] = {
                    'score': brand_score,
                    'rmse': brand_rmse,
                    'mae': brand_mae,
                    'r2': brand_r2
                }
                
                if brand_score < self.brand_best_configs[brand]['score']:
                    self.brand_best_configs[brand]['score'] = brand_score
                    self.brand_best_configs[brand]['params'] = params.copy()
                    self.brand_best_configs[brand]['config_num'] = i + 1
                    self.brand_best_configs[brand]['all_metrics'] = {
                        'rmse': brand_rmse,
                        'mae': brand_mae,
                        'r2': brand_r2
                    }
            
            self.results.append({
                "config_num": i + 1,
                "params": params,
                "rmse": rmse,
                "mae": mae,
                "r2": r2,
                "score": current_score,
                "brand_results": brand_results
            })

            if self.best_score is None or current_score < self.best_score:
                self.best_score = current_score
                self.best_params = params
                self.best_trainer = trainer
                print(f"New best overall model ({metric_name}: {current_score:.2f})")
           

            elapsed_total = time.time() - start_time
            avg_per_iter = elapsed_total / (i + 1)
            eta = avg_per_iter * (self.n_iter - (i + 1))
            
            print(f"\nProgress: {i+1}/{self.n_iter} | Elapsed: {elapsed_total:.1f}s | ETA: ~{eta:.1f}s")
        
        print(f"SEARCH COMPLETED - FINAL RESULTS (Optimized for {metric_name})")
        
        print(f"\n Best general model:")
        print(f"  Best {metric_name}: {self.best_score:.2f}")
        
        best_result = [r for r in self.results if r['score'] == self.best_score][0]
        print(f"  RMSE: {best_result['rmse']:.2f}")
        print(f"  MAE:  {best_result['mae']:.2f}")
        print(f"  R²:   {best_result['r2']:.4f}")
        print(f"  Params: {self.best_params}")
   
        print(f"Best configuration per brand (by {metric_name})")

        
        brand_summary = []
        for brand in sorted(brands):
            config = self.brand_best_configs[brand]
            
            summary = {
                'Brand': brand,
                f'Best_{metric_name}': config['score'],
                'RMSE': config['all_metrics']['rmse'],
                'MAE': config['all_metrics']['mae'],
                'R²': config['all_metrics']['r2'],
                'Config_Num': config['config_num']
            }
            
            param_summary = self._get_param_summary(config['params'])
            summary.update(param_summary)
            
            brand_summary.append(summary)
            
            print(f"\n{brand.upper()}:")
            print(f"  Best {metric_name}: {config['score']:.2f}")
            print(f"  RMSE: {config['all_metrics']['rmse']:.2f}")
            print(f"  MAE:  {config['all_metrics']['mae']:.2f}")
            print(f"  R²:   {config['all_metrics']['r2']:.4f}")
            print(f"  Found at iteration: {config['config_num']}")
            print(f"  Best params:")
            for k, v in list(config['params'].items())[:5]:
                if k not in ['random_state', 'n_jobs', 'shuffle', 'verbose', 'warm_start']:
                    print(f"    {k}: {v}")
        
        df_summary = pd.DataFrame(brand_summary).sort_values(f'Best_{metric_name}')
  
        print(df_summary.to_string(index=False))
        
        results_df = pd.DataFrame([
            {
                'Config': r['config_num'],
                metric_name: r['score'],
                'RMSE': r['rmse'],
                'MAE': r['mae'],
                'R²': r['r2']
            }
            for r in self.results
        ]).sort_values(metric_name)
        
        print(f"ALL CONFIGURATIONS (sorted by {metric_name}):")
        print(results_df.head(10).to_string(index=False))
        
        return self.best_trainer, self.best_params, self.best_score

### Random Forest

In [ ]:
base_estimator = RandomForestRegressor(random_state=69, n_jobs=-1)
trainer = BrandModelTrainer(base_estimator)

param_space_rf = {
    "n_estimators": [400, 800, 1200],
    "max_depth": [None, 15, 25, 35],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [0.3, 0.5, 0.7, 1.0],
    "min_impurity_decrease": [0.0, 1e-4, 1e-3, 1e-2],
    "max_samples": [0.5, 0.7, 0.9, None],
    "criterion": ["squared_error", "friedman_mse"],
    "bootstrap": [True],
    "random_state": [69],
    "n_jobs": [-1]
}

search = HoldoutRandomSearch(
    trainer_class=trainer,
    param_space=param_space_rf,
    n_iter=60
)


best_trainer, best_params, best_rmse = search.run(X_train_filter, y_train, X_val_filter, y_val)

Running random search (60 iterations)...
Optimizing for: MAE


======================================================================
[1/60] Testing params:
{'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.0001, 'max_samples': 0.9, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2010.32
  MAE:  1245.43
  R²:   0.9549
New best overall model (MAE: 1245.43)

Progress: 1/60 | Elapsed: 84.7s | ETA: ~4996.7s

======================================================================
[2/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 1.0, 'min_impurity_decrease': 0.001, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2089.98
  MAE:  1266.69
  R²:   0.9513

Progress: 2/60 | Elapsed: 190.5s | ETA: ~5525.7s

======================================================================
[3/60] Testing params:
{'n_estimators': 400, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.7, 'min_impurity_decrease': 0.01, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2060.10
  MAE:  1257.78
  R²:   0.9526

Progress: 3/60 | Elapsed: 232.2s | ETA: ~4412.4s

======================================================================
[4/60] Testing params:
{'n_estimators': 400, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.7, 'min_impurity_decrease': 0.0, 'max_samples': 0.9, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2062.24
  MAE:  1257.46
  R²:   0.9525

Progress: 4/60 | Elapsed: 269.9s | ETA: ~3778.5s

======================================================================
[5/60] Testing params:
{'n_estimators': 1200, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2037.26
  MAE:  1253.80
  R²:   0.9537

Progress: 5/60 | Elapsed: 369.2s | ETA: ~4061.1s

======================================================================
[6/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'min_impurity_decrease': 0.0001, 'max_samples': None, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1956.11
  MAE:  1219.53
  R²:   0.9573
New best overall model (MAE: 1219.53)

Progress: 6/60 | Elapsed: 438.6s | ETA: ~3947.5s

======================================================================
[7/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.0, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2196.31
  MAE:  1307.09
  R²:   0.9462

Progress: 7/60 | Elapsed: 516.7s | ETA: ~3911.8s

======================================================================
[8/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 1.0, 'min_impurity_decrease': 0.0001, 'max_samples': 0.5, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2047.28
  MAE:  1253.09
  R²:   0.9532

Progress: 8/60 | Elapsed: 633.0s | ETA: ~4114.8s

======================================================================
[9/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.0001, 'max_samples': 0.5, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2196.32
  MAE:  1307.09
  R²:   0.9462

Progress: 9/60 | Elapsed: 719.8s | ETA: ~4079.0s

======================================================================
[10/60] Testing params:
{'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.001, 'max_samples': 0.7, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2173.93
  MAE:  1293.43
  R²:   0.9473

Progress: 10/60 | Elapsed: 813.7s | ETA: ~4068.4s

======================================================================
[11/60] Testing params:
{'n_estimators': 1200, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.7, 'min_impurity_decrease': 0.0001, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2149.22
  MAE:  1294.60
  R²:   0.9485

Progress: 11/60 | Elapsed: 891.1s | ETA: ~3969.5s

======================================================================
[12/60] Testing params:
{'n_estimators': 800, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2030.13
  MAE:  1247.29
  R²:   0.9540

Progress: 12/60 | Elapsed: 953.2s | ETA: ~3813.0s

======================================================================
[13/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2006.46
  MAE:  1248.43
  R²:   0.9551

Progress: 13/60 | Elapsed: 985.4s | ETA: ~3562.7s

======================================================================
[14/60] Testing params:
{'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2081.26
  MAE:  1282.49
  R²:   0.9517

Progress: 14/60 | Elapsed: 1042.1s | ETA: ~3424.0s

======================================================================
[15/60] Testing params:
{'n_estimators': 800, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'min_impurity_decrease': 0.0, 'max_samples': 0.9, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1973.44
  MAE:  1220.90
  R²:   0.9565

Progress: 15/60 | Elapsed: 1111.7s | ETA: ~3335.1s

======================================================================
[16/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2032.75
  MAE:  1259.43
  R²:   0.9539

Progress: 16/60 | Elapsed: 1174.7s | ETA: ~3230.6s

======================================================================
[17/60] Testing params:
{'n_estimators': 800, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 1.0, 'min_impurity_decrease': 0.0, 'max_samples': 0.5, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2146.70
  MAE:  1285.88
  R²:   0.9486

Progress: 17/60 | Elapsed: 1234.3s | ETA: ~3122.0s

======================================================================
[18/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.7, 'min_impurity_decrease': 0.0, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2005.18
  MAE:  1233.73
  R²:   0.9551

Progress: 18/60 | Elapsed: 1270.3s | ETA: ~2964.1s

======================================================================
[19/60] Testing params:
{'n_estimators': 1200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 1.0, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2125.79
  MAE:  1278.16
  R²:   0.9496

Progress: 19/60 | Elapsed: 1378.6s | ETA: ~2974.9s

======================================================================
[20/60] Testing params:
{'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.7, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2072.73
  MAE:  1267.26
  R²:   0.9521

Progress: 20/60 | Elapsed: 1412.4s | ETA: ~2824.8s

======================================================================
[21/60] Testing params:
{'n_estimators': 800, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.3, 'min_impurity_decrease': 0.0001, 'max_samples': 0.7, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2080.71
  MAE:  1287.46
  R²:   0.9517

Progress: 21/60 | Elapsed: 1465.6s | ETA: ~2721.8s

======================================================================
[22/60] Testing params:
{'n_estimators': 1200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.3, 'min_impurity_decrease': 0.01, 'max_samples': None, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1974.65
  MAE:  1232.44
  R²:   0.9565

Progress: 22/60 | Elapsed: 1615.0s | ETA: ~2789.5s

======================================================================
[23/60] Testing params:
{'n_estimators': 1200, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.7, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2079.17
  MAE:  1269.84
  R²:   0.9518

Progress: 23/60 | Elapsed: 1709.6s | ETA: ~2750.2s

======================================================================
[24/60] Testing params:
{'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.7, 'min_impurity_decrease': 0.01, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1978.78
  MAE:  1225.37
  R²:   0.9563

Progress: 24/60 | Elapsed: 1806.2s | ETA: ~2709.3s

======================================================================
[25/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.7, 'min_impurity_decrease': 0.001, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 1990.74
  MAE:  1229.02
  R²:   0.9558

Progress: 25/60 | Elapsed: 1881.7s | ETA: ~2634.4s

======================================================================
[26/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 1.0, 'min_impurity_decrease': 0.0001, 'max_samples': None, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2052.95
  MAE:  1252.95
  R²:   0.9530

Progress: 26/60 | Elapsed: 1963.3s | ETA: ~2567.4s

======================================================================
[27/60] Testing params:
{'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'min_impurity_decrease': 0.001, 'max_samples': 0.9, 'criterion': 'squared_error', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}
======================================================================
Training models for 9 brands...

  ✓ opel done.
  ✓ toyota done.
  ✓ ford done.
  ✓ mercedes done.
  ✓ vw done.
  ✓ bmw done.
  ✓ audi done.
  ✓ hyundai done.
  ✓ skoda done.

Validation Set Performance (Overall):
  RMSE: 2042.87
  MAE:  1251.67
  R²:   0.9534

Progress: 27/60 | Elapsed: 2027.7s | ETA: ~2478.3s

======================================================================
[28/60] Testing params:
{'n_estimators': 1200, 'max_depth': 35, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.5, 'min_impurity_decrease': 0.0001, 'max_samples': 0.7, 'criterion': 'friedman_mse', 'bootstrap': True, 'random_state': 69, 'n_jobs': -1}

In [ ]:
best_trainer.evaluate_by_brand(X_val_filter, y_val)

Validation Performance per Brand:
   Brand    N        RMSE         MAE       R²
    opel 1906 1086.769229  748.110206 0.906943
    ford 3282 1277.274084  901.254733 0.927122
 hyundai  683 1368.252148  890.840175 0.948504
  toyota  941 1378.231055  858.386788 0.951447
   skoda  875 1494.197535 1037.671806 0.941052
      vw 2125 1875.588743 1188.962644 0.943592
     bmw 1513 2457.630204 1624.097258 0.953722
    audi 1489 2543.390249 1621.939526 0.945946
mercedes 2381 2793.058290 1790.165923 0.925661

      Brand     N         RMSE          MAE        R²
1      opel  1906  1086.769229   748.110206  0.906943
2      ford  3282  1277.274084   901.254733  0.927122
5   hyundai   683  1368.252148   890.840175  0.948504
3    toyota   941  1378.231055   858.386788  0.951447
7     skoda   875  1494.197535  1037.671806  0.941052
0        vw  2125  1875.588743  1188.962644  0.943592
8       bmw  1513  2457.630204  1624.097258  0.953722
6      audi  1489  2543.390249  1621.939526  0.945946
4  mercedes  2381  2793.058290  1790.165923  0.925661

In [ ]:
#raise SystemExit("Stop before training the models")

## Predictions

In [ ]:
best_params_per_brand = {
    'opel': {
        'n_estimators': 1200,
        'max_depth': 15,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': 0.7,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'toyota': {
        'n_estimators': 800,
        'max_depth': 25,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.3,
        'min_impurity_decrease': 0.01,
        'max_samples': None,
        'criterion': 'friedman_mse',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'ford': {
        'n_estimators': 1200,
        'max_depth': 15,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': 0.7,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'hyundai': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'skoda': {
        'n_estimators': 1200,
        'max_depth': 15,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': 0.7,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'vw': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'bmw': {
        'n_estimators': 400,
        'max_depth': 35,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'audi': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    },
    'mercedes': {
        'n_estimators': 1200,
        'max_depth': None,
        'min_samples_split': 5,
        'min_samples_leaf': 1,
        'max_features': 0.5,
        'min_impurity_decrease': 0.0,
        'max_samples': None,
        'criterion': 'squared_error',
        'bootstrap': True,
        'random_state': 69,
        'n_jobs': -1
    }
}

In [ ]:
X_full_train = pd.concat([X_train_filter, X_val_filter], axis=0)
y_full_train = pd.concat([y_train, y_val], axis=0)

numeric_cols = ['mileage', 'tax', 'mpg', 'engineSize', 'age', 
                 'efficiency_ratio', 
                'model_mean_price']

categorical_cols = ['Brand', 'transmission', 'fuelType']

In [ ]:
models = {}
scalers = {}
brand_encoders = {}


brands = X_full_train['Brand'].unique()

for brand in brands:
    brand_lower = brand.lower()
    print(f"\n Training model for {brand.upper()}")
    
    mask_train = X_full_train['Brand'] == brand
    X_brand_train = X_full_train[mask_train].copy()
    y_brand_train = y_full_train[mask_train].copy()
    
    X_numeric = X_brand_train[numeric_cols].copy()
    
    scaler = RobustScaler()
    X_numeric_scaled = scaler.fit_transform(X_numeric)
    X_numeric_scaled = pd.DataFrame(
        X_numeric_scaled, 
        columns=numeric_cols,
        index=X_brand_train.index
    )

    scalers[brand] = scaler

    X_brand_encoded = X_numeric_scaled.copy()
    
    for col in ['transmission', 'fuelType']:
        dummies = pd.get_dummies(X_brand_train[col], prefix=col, drop_first=True)
        X_brand_encoded = pd.concat([X_brand_encoded, dummies], axis=1)
    

    brand_encoders[brand] = {
        'columns': X_brand_encoded.columns.tolist(),
        'numeric_cols': numeric_cols
    }
    
    if brand_lower in best_params_per_brand:
        params = best_params_per_brand[brand_lower]
    else:
        params = {
            'n_estimators': 1200,
            'max_depth': None,
            'min_samples_split': 5,
            'min_samples_leaf': 1,
            'max_features': 0.5,
            'random_state': 69,
            'n_jobs': -1
        }
    
    model = RandomForestRegressor(**params)
    model.fit(X_brand_encoded, y_brand_train)
  
    models[brand] = model
    
    print(f" {brand.upper()} model trained")

 Training model for OPEL
 OPEL model trained

 Training model for AUDI
 AUDI model trained

 Training model for MERCEDES
 MERCEDES model trained

 Training model for FORD
 FORD model trained

 Training model for BMW
 BMW model trained

 Training model for TOYOTA
 TOYOTA model trained

 Training model for HYUNDAI
 HYUNDAI model trained

 Training model for VW
 VW model trained

 Training model for SKODA
 SKODA model trained

In [ ]:
test_processed.head()

,year,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,Brand,transmission,model,fuelType
carID,,,,,,,,,,,
89856,2015,30700,205,41.5,1.6,3,1.0,hyundai,automatic,i30,petrol
106581,2017,48191,150,38.2,2.0,2,1.0,vw,semi-auto,tiguan,petrol
80886,2016,36792,125,51.4,1.5,2,1.0,bmw,automatic,2 series,petrol
100174,2019,5533,145,44.1,1.2,1,1.0,opel,manual,grandland x,petrol
81376,2019,9058,150,51.4,2.0,4,1.0,bmw,semi-auto,1 series,diesel

In [ ]:
X_test = minimal_features(test_processed)
X_test

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,Brand,transmission,model,fuelType,age,mileage_per_year,efficiency_ratio,age_mileage
carID,,,,,,,,,,,,,,
89856,30700,205,41.5,1.6,3,1.0,hyundai,automatic,i30,petrol,5,5116.666667,24.411765,1.53500
106581,48191,150,38.2,2.0,2,1.0,vw,semi-auto,tiguan,petrol,3,12047.750000,18.190476,1.44573
80886,36792,125,51.4,1.5,2,1.0,bmw,automatic,2 series,petrol,4,7358.400000,32.125000,1.47168
100174,5533,145,44.1,1.2,1,1.0,opel,manual,grandland x,petrol,1,2766.500000,33.923077,0.05533
81376,9058,150,51.4,2.0,4,1.0,bmw,semi-auto,1 series,diesel,1,4529.000000,24.476190,0.09058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105775,27575,145,46.3,1.4,1,1.0,vw,manual,tiguan,petrol,3,6893.750000,30.866667,0.82725
81363,1980,145,34.0,2.0,3,1.0,bmw,automatic,x2,petrol,0,1980.000000,16.190476,0.00000
76833,8297,145,38.2,2.0,4,1.0,audi,semi-auto,q5,diesel,1,4148.500000,18.190476,0.08297
91768,50755,145,28.5,1.3,1,1.0,mercedes,manual,a class,petrol,1,25377.500000,20.357143,0.50755
99627,11071,30,58.0,1.3,4,1.0,toyota,automatic,yaris,petrol,3,2767.750000,41.428571,0.33213

In [ ]:
X_test['model_mean_price'] = X_test['model'].map(model_mean_price)

In [ ]:
X_train_filter.head()

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,age,efficiency_ratio,Brand,transmission,model_mean_price,fuelType
0,11899,124,51.4,1.4,2,1.0,4,34.266667,opel,manual,10488.218094,petrol
1,18500,145,48.7,1.4,4,1.0,2,32.466667,audi,semi-auto,22860.502532,petrol
2,10658,145,46.3,1.5,2,1.0,1,28.937500,mercedes,semi-auto,23609.185947,petrol
3,1500,145,43.5,0.0,4,1.0,0,435.000000,audi,manual,22522.319540,petrol
4,18495,98,64.1,2.1,4,1.0,3,29.136364,mercedes,automatic,23609.185947,diesel

In [ ]:
X_test = X_test.drop(columns=["model", "mileage_per_year", "age_mileage"])
X_test.head()

,mileage,tax,mpg,engineSize,previousOwners,stated_no_damage,Brand,transmission,fuelType,age,efficiency_ratio,model_mean_price
carID,,,,,,,,,,,,
89856,30700,205,41.5,1.6,3,1.0,hyundai,automatic,petrol,5,24.411765,11848.081505
106581,48191,150,38.2,2.0,2,1.0,vw,semi-auto,petrol,3,18.190476,21509.106996
80886,36792,125,51.4,1.5,2,1.0,bmw,automatic,petrol,4,32.125000,19665.944282
100174,5533,145,44.1,1.2,1,1.0,opel,manual,petrol,1,33.923077,17217.228906
81376,9058,150,51.4,2.0,4,1.0,bmw,semi-auto,diesel,1,24.476190,15836.032550

In [ ]:
predictions = np.zeros(len(X_test))

for brand in X_test['Brand'].unique():
    print(f"\n Predicting for {brand.upper()}...")

    mask_test = X_test['Brand'] == brand
    X_brand_test = X_test[mask_test].copy()
    
    X_numeric_test = X_brand_test[numeric_cols].copy()
    
    scaler = scalers[brand]
    X_numeric_test_scaled = scaler.transform(X_numeric_test)
    X_numeric_test_scaled = pd.DataFrame(
        X_numeric_test_scaled,
        columns=numeric_cols,
        index=X_brand_test.index
    )
    
    X_brand_test_encoded = X_numeric_test_scaled.copy()
    
    for col in ['transmission', 'fuelType']:
        dummies = pd.get_dummies(X_brand_test[col], prefix=col, drop_first=True)
        X_brand_test_encoded = pd.concat([X_brand_test_encoded, dummies], axis=1)

    expected_cols = brand_encoders[brand]['columns']

    for col in expected_cols:
        if col not in X_brand_test_encoded.columns:
            X_brand_test_encoded[col] = 0
    
    X_brand_test_encoded = X_brand_test_encoded[expected_cols]
    
    model = models[brand]
    brand_predictions = model.predict(X_brand_test_encoded)

    predictions[mask_test] = brand_predictions

 Predicting for HYUNDAI...

 Predicting for VW...

 Predicting for BMW...

 Predicting for OPEL...

 Predicting for FORD...

 Predicting for MERCEDES...

 Predicting for SKODA...

 Predicting for TOYOTA...

 Predicting for AUDI...

In [ ]:
if X_test.index.name == 'carID' or 'carID' in X_test.index.names:
    car_ids = X_test.index
else:
    car_ids = X_test.index

submission = pd.DataFrame({
    'carID': car_ids,
    'price': predictions
})

submission = submission.sort_values('carID')


submission['price'] = submission['price'].round(2)

output_filename = 'submission.csv'
submission.to_csv(output_filename, index=False)